src/firejail/netfilter.c

In netfilter.c, the memset call on line 70 is before the check for null pointer, so it could cause a null pointer dereference crash. The statement has been moved to after the null pointer check.

Fix potential null pointer dereference in netfilter

---

.gitignore

If you build firejail and then type `git status`, it shows all the built files as untracked. I've created a `.gitignore` file so that `git status` is clean even after a build. This also allows you to use `git add --all` when you create new files, rather than having to add each file individually.

Create a .gitignore file for firejail

---

src/man/firejail-profile.txt

Here is a new pull request for the manpage typos. I had to regenerate the patch and the pull request as it had the wrong email address, sorry for any confusion!

Fix typos in firejail-profile manpage

---

src/firejail/arg-checking.txt
src/firejail/firejail.h
src/firejail/fs_home.c
src/firejail/main.c
src/firejail/profile.c
src/firejail/sandbox.c
src/firejail/usage.c
src/man/firejail-profile.txt
src/man/firejail.txt

This implements the enhancement in issue #15 - the `--private-home` option is another way of specifying `--private.keep`. The `--private.keep` option still works, but the documentation now only lists the `--private-home` option.

Implement the --private-home option

---

etc/disable-common.inc

The payload I saw for it also searched for these specific directories as well. Two notes:
* Is the ```+``` in ```${HOME}.config/psi+``` going to be an issue?
* I couldn't actually find what ```.tconn``` is for.

A bit more for CVE-2015-4495

---

src/firejail/fs.c

Firejail wasn't handling relative symlinks correctly (like when a symlink is `../file`) and also wasn't handling multiple symlinks correctly (it could only handle one link, not a link to a link). This commit fixes that by calling the `realpath` function to do all the hard work for us.

Call realpath to resolve symlinks correctly in disable_file

---

src/firejail/firejail.h
src/firejail/fs_dev.c
src/firejail/fs_var.c
src/firejail/util.c

Removed the `get_link` function in util.c and replace all calls to it with the `realpath` standard library function. This makes firejail handle all symlinks correctly.

Replace get_link with realpath

---

src/firejail/fs.c
src/firejail/profile.c
todo

The `~` character is now supported in the `--blacklist` option and in profile includes for specifying the home directory of the current user.

Support ~ in blacklist and profile includes

---

src/firejail/profile.c
todo

Filenames with spaces can now be blacklisted on the command line:
`firejail "--blacklist=My Documents"`
...or in a profile file:
`blacklist My Documents`

Support filenames with spaces in the blacklist option

---

Makefile.in

Copied the new location for the bash completion files into the `Makefile.in` file, so that they get included in the `make install` command.

Fix the 'make install' command for new bash completion location

---

src/firejail/Makefile.in
src/firejail/fs.c
src/firejail/main.c
src/firejail/netfilter.c
src/firejail/profile.c
src/firejail/sandbox.c
src/firejail/seccomp.c
src/firejail/util.c
src/firemon/Makefile.in
src/firemon/firemon.c
src/firemon/netstats.c
src/firemon/top.c
src/ftee/Makefile.in
src/lib/Makefile.in
src/lib/libnetlink.c
src/lib/pid.c
src/libtrace/Makefile.in

Firejail now compiles with the `-W -Wall -Werror` option in `CFLAGS`. This option enables all warnings and turns them into errors, i.e. the compile stops if there are any warnings. I've removed all existing warnings so the code is now clean, and this means that in future the code will remain clean (as it's now impossible to introduce new warnings without breaking the build).

Compile with -W -Wall -Werror

---

src/firejail/sandbox.c

Without this patch, firejail handles arguments differently in `--shell=none` mode. For example, this is a normal command:
```
$ firejail --debug /bin/echo 1 2 3
...
Starting /bin/echo 1 2 3 
execvp argument 0: /bin/bash
execvp argument 1: -c
execvp argument 2: /bin/echo 1 2 3 
Child process initialized
1 2 3
```
But when you execute it with `--shell=none`, it drops the first argument, and only "2 3" is printed:
```
firejail --debug --shell=none /bin/echo 1 2 3
...
execvp argument 0: /bin/echo
execvp argument 1: 1
execvp argument 2: 2
execvp argument 3: 3
Child process initialized
2 3
```
This patch makes the `--shell=none` command work the same as a normal command:
```
firejail --debug --shell=none /bin/echo 1 2 3
...
execvp argument 0: /bin/echo
execvp argument 1: 1
execvp argument 2: 2 …
```

Fix arguments passed to child process during execvp in --shell=none mode

---

src/lib/Makefile.in
src/libtrace/Makefile.in

Putting `--enable-fatal-warnings` in the `./configure` command is a great idea, thank you for that! As it means we can easily turn it on and off, I've made a patch to make it available in all the Makefiles.

Support --enable-fatal-warnings in all Makefiles

---

src/firejail/firejail.h
src/firejail/fs.c
src/firejail/fs_home.c
src/firejail/profile.c
src/firejail/util.c

Implemented a new function called `expand_home` in util.c, in order to help with issue #40 . The following now work, that didn't before:
`firejail --private-home=~/dir/file`
`firejail --private-home=${HOME}/dir/file`
As a nice side-effect, the following now also works (previously `--private` only supported `~` for homedir):
`firejail --private=${HOME}/dir`
Hopefully I haven't broken anything else but please give it a test!

Implement the expand_home util function

---

src/firejail/usage.c

The `--env` commit introduced a typo, this patch reverts it back to normal

Fix typo in usage.c

---

etc/disable-history.inc
src/firejail/fs.c

* Plug a memory leak.
* Remove the short-circuit.  (This breaks when someone uses [] or ?
patterns without using *.  I figure it's best to use the principle of
least surprise and just let the system glob() implementation do what
it does.)
* Stop sorting results.
I've also replaced a lot of disable-history.inc with a glob pattern.
Now it catches files like .sqlite_history and whatever the user runs
under rlwrap.

Rewrite globbing code to fix various minor issues

---

src/firejail/caps.c
src/firejail/fs.c

In some places the code compares the first n characters of a string and
then assumes a valid string starts from the n+2th character.  I didn't
find any places where this wasn't justifiable, but I think it's better
to stick to safer patterns, especially in SUID code.

Clean up some fragile uses of strncmp.

---

Makefile.in

The default in autotools is not to strip executables when doing make install, but only when doing make install-strip. Not doing that confuses a lot of automated build systems like source based package managers or tools that build packages automatically. It would be very nice if you could pull this.

added install-strip, make install now without strip.

---

src/firejail/errno.c
src/firejail/firejail.h
src/firejail/main.c
src/firejail/sandbox.c
src/firejail/seccomp.c
src/firejail/syscall.c
src/man/firejail.txt
src/tools/extract_errnos.sh

No tests yet. Tried to get the existing tests running without much success :(
Would users like to mix errno and black/white -lists? i currently only need errno filter and default allow.
Tried to keep same code style, hope it is ok.

Add seccomp errno filter support

---

etc/spotify.profile

This PR proposes a firejail profile for Spotify.
Since Spotify, when used for streaming, only requires access to a very small group of folders (config, local and cache for itself), I created the profile based around a whitelist. 
Finally, it allows access to the per-user pulseaudio config directory, in case anyone is using the [workaround for PulseAudio 7](https://github.com/netblue30/firejail/blob/master/README.md#pulseaudio-70)

Add a profile for Spotify

---

Makefile.in

The Makefile should use the autoconf values for `bindir`, `libdir`, `datarootdir`, and `mandir`.
It looks like using lowercase variable names for the above variables is acceptable based on the following examples:
* https://www.gnu.org/prep/standards/html_node/DESTDIR.html
* http://www.netperf.org/svn/netperf2/trunk/doc/examples/Makefile.in

use configure options in Makefile

---

etc/steam.profile

seccomp not included due to the 32/64bit issue noted seen in the bug reports.
Also included a little snippet regarding my experiment with using private directories for it.
The two noblacklist lines are just in case.

Create Steam profile

---

src/firejail/Makefile.in
src/firejail/bandwidth.c
src/firejail/fs_trace.c
src/firejail/output.c

When a non-default libdir is used, firejail installs
some components in this directory, but the hardcoded
paths to ftee etc. still point to $prefix/lib.
Use the configured libdir path instead.

Use configured libdir instead of $prefix/lib

---

etc/firefox.profile

User can have gtk themes installed locally. This directory is pretty safe to read, no private data there.

Allow firefox theming with non-global themes

---

etc/disable-common.inc
etc/skype.profile

It seems that default Skype profile, introduced in 4faa338ca738a0bf40d07b6d4b9b98f62a3cb34f, is and exact duplicate of Steam profile. Thus, Skype has access to Steam directories.
Besides, file containing Skype account credentials could be stolen and used to login from another machine.
Thus in this commit, I:
1) blacklisted ~/.Skype directory in `disable-common.inc`
2) revoked Skype access to Steam dirs, and granted it access to Skype dirs in `skype.profile`

Fixed Skype profile: was a copy of Steam profile

---

src/firejail/fs_whitelist.c
src/firejail/util.c
src/lib/libnetlink.c

This fixes a few minor problems found by scan-build.

Fix warnings by clang-analyzer (scan-build)

---

src/firejail/main.c

This seems to fix the problem with the spaces when a program is started through a shell (Bug #58).
Starting a program without using a shell is still working.
I haven't tested this thoroughly though, so I'm not sure if this causes any other problems.
---
However, spaces are not the only characters that can cause problems when starting a program through a shell.
If, for example, you open a file that contains `"` somewhere, it will probably fail.
So, to fully fix this, `"` characters will have to be escaped. Other characters, like `\` and `!` may also have to be escaped.
*Or* set "shell=none" as default, which would be even easier :smile: (but I suppose this is not the default for a reason).

Add '"' chars around every argument passed to bash

---

src/firejail/fs_whitelist.c

Don't force 0755 permissions for whitelisted files. (#149)

keep original file permissions

---

src/man/firejail-profile.txt

I took the liberty to reword and reorder the caps part in the manpage, to make it more clear and less self-contradictory about what it does.
Renamed /etc/password to /etc/passwd, too.

clarify firejail-profile manpage

---

Makefile.in
etc/parole.profile
platform/debian/conffiles

Why are those entries scattered around in some profiles? Shouldn't they go to some common profile like disable-secret.inc?
```
blacklist ${HOME}/.pki/nssdb
blacklist ${HOME}/.lastpass
blacklist ${HOME}/.keepassx
blacklist ${HOME}/.password-store
```

add parole.profile

---

etc/firefox.profile

This whitelists [keysnail](https://github.com/mooz/keysnail/wiki)'s config (extension like vimperator and pentadactyl). This is the default place for the config.

whitelist keysnail config for firefox

---

mkman.sh
src/firejail/Makefile.in
src/firemon/Makefile.in
src/ftee/Makefile.in
src/lib/Makefile.in
src/libtrace/Makefile.in
src/libtracelog/Makefile.in

Firejail is currently not building reproducibly [1].
The order of object files is random while linking. This is easily fixed by sorting the filelists.
A timestamp from the current date is also embedded into manpages.
By making use of the SOURCE_DATE_EPOCH variable [2] (when available), the timestamp can
be set to a deterministic one.
[1]: https://reproducible.debian.net/rb-pkg/unstable/armhf/firejail.html
[2]: https://reproducible-builds.org/specs/source-date-epoch/

Make the build reproducible

---

src/firejail/fs_var.c

With musl libc `UTMP_FILE` is defined as `/dev/null/utmp`, on my system `/var/run/utmp` existed too but its just an empty file.
`fs_var_utmp` checks `/var/run/utmp` and then later opens `UTMP_FILE` resulting in following error:
```
Error fopen:fs_var_utmp(324): Not a directory
```

use UTMP_FILE to check for its existence

---

etc/disable-secret.inc

As of version 2.0, KeePassX now uses the `.kdbx` file extension instead of the already blacklisted `.kdb`.
See https://www.keepassx.org/news/2015/12/533 for more information.

Disallow access to kdbx files

---

etc/disable-secret.inc

Reasons:
* many modern GUI applications need this file
* it doesn't contain secret information (passwords, keys) but private information as is most other data in ~/

Don't blacklist recently-used.xbel

---

etc/disable-mgmt.inc

`/usr/local/sbin` might also contain administrative tools.

blacklist /usr/local/sbin

---

RELNOTES
mkdeb.sh
platform/debian/firejail.lintian-overrides

Lintian (debian package static analyzer) has been reporting two issues:
* malformed changelof: added required info to RELNOTES based on commit date
* setuid binary: added it to lintian-overrides

Fixing lintian warnings

---

src/man/firejail.txt

This fixes a typo in the man file. The option read --debug-blackilsts instead of --debug-blacklists.

changed typo in man file (namely --debug-blackilsts)

---

etc/disable-secret.inc

(at least on Arch Linux) Kwallet saves encrypted passwords at `~/.local/share/kwalletd`.

Blacklisting ~/.local/share/kwalletd

---

src/firejail/sandbox.c

Quick patch for netblue30/firejail#256
Instead of running waitpid(app) in the sandbox, run waitpid(-1) in a loop and check the return value until the original app dies.
I'm not sure you should trust me to write C code, but this patch has been running my KMail for several minutes now without eating any kittens :)

Make the sandbox process reap all children.

---

etc/uget-gtk.profile

Hey, thanks for the merge. I just saw you duplicated the whitelist include that was already in the profile, this deletes the first entry.

remove duplicate include from uGet profile

---

etc/disable-common.inc

By default mutt looks for ~/.muttrc or ~/.mutt/muttrc files.

Add alternative location for muttrc

---

src/firejail/caps.c
src/firejail/usage.c

CAP_SYSLOG was retroactively split from CAP_SYSADMIN (Linux
kernel commit ce6ada35bdf710d16582cc4869c26722547e6f11). Existing
supported systems might not yet have this commit (eg RHEL 6.6) in
which case compilation fails.

Fix for systems that don't have CAP_SYSLOG

---

src/include/libnetlink.h

Seems this is a long-running dependency issue: http://comments.gmane.org/gmane.linux.network/203185
I have tested on Ubuntu 14.04 and RHEL 6.6 but this probably needs also testing on RH/CentOS 7 and a more recent Ubuntu/Debian before merge.

Include <sys/socket.h> for sa_family_t (RHEL 6.6)

---

etc/disable-common.inc

Add .gvimrc and _ versions of other files used by vim when no dot-version available.
Add .xscreensaver that can be used for arbitrary command execution by setting "textProgram" (instead of default fortune) and screensaver that launches it.

Make additional vimrc files; .xscreensaver file read only

---

etc/wesnoth.profile

The profile is a _white_list (in contrast to blacklist).
All standard game actions work:
create-save-load games,
multiplayer (online) game, downloading addons and using them.

profile for wesnoth

---

etc/epiphany.profile

For some reason, Epiphany was able to save the settings even without access to the `.config/dconf` directory, but it did not show them in the settings window.

Epiphany: Fix settings being saved but not loaded

---

src/man/firejail.txt

If you obtain ipv6 connectivity from router via SLAAC/RA, IPv6 works without this option (and worked even before e669dbee639c4956430bc90345e1f05687c9d50a). Moreover, manual twiddling with IPv6 addresses/routes can do more harm than good in this configuration (e.g. when prefix is not static and changes midway due to ADSL reconnect, kernel handles this transparently, while with `--ip6=` option you are stick to (obsolete and non-working) address specified on firejail start).
Disclaimer: feel free to fix/polish wording/expand/etc, /me not a native speaker.

man/firejail.txt: note you don't need --ip6= with SLAAC

---

configure.ac
src/firejail/main.c

./configure --enable-network=restricted allows only `--net=none` to non-root users.
Other variants delegate too much power to non-root users and dangerous (it completely bypasses system-wide firewall and routing, it allows introducing arbitrary-chosen MAC and IP interfaces on LAN [disregarding DHCP policy], etc).
Root already had power to twiddle with anything, so no sense to restrain her, and `--net=none` looks safe enough (and still useful) for ordinary users (and permitted via `unshare -rn` anyway).
See #290

Add compile-time option to restrict --net= to root only

---

etc/vivaldi-beta.profile
etc/vivaldi.profile

Hi netblue30. I've created two profiles for the vivaldi browser: etc/vivaldi.profile and etc/vivaldi-beta.profile. Since vivaldi is still in beta (and resides in /usr/bin/vivaldi-beta) I made vivaldi-beta.profile; however, it points back to vivaldi.profile in the same way that google-chrome-stable.profile points to google-chrome.profile.
I'm pretty new at GitHub so hopefully this is the correct way to go about this. I had to Google (well, DDG actually) to find instructions. :-) Let me know if this is okay! I've got a few other profiles I was thinking of committing if all goes well. 
Thanks,
Fred Barclay

Added profiles for vivaldi

---

platform/rpm/mkrpm.sh

A couple of rpm fixes, the first is needed to build rpms from the rc as it stands, the second saves space in /tmp while building.

More rpm fixes

---

etc/atril.profile

Atril is the default pdf viewer for the Mate DE.
I (mostly) forked the existing etc/evince.profile. I noticed that evice.profile and generic.profile were almost identical, so I told atril.profile to include generic.profile rather than have redundant code. I also added disable-devel.inc (which was already present in evince.profile) and blacklisted ~/.wine (also present in evince.profile).
"Netfilter" is in atril.profile due to the generic profile, while it is not present in the existing evince.profile, but I saw no reason to remove it from atril. 
Hope this isn't too confusing. :)
EDIT: one more thing. The sandbox profile for Atril (as for evince) is somewhat lax; I'll work on hardening it if you like. As it is, most of the directories/files in my /home are visible to the sandbox.

Created Atril profile

---

src/firejail/main.c
src/firejail/sandbox.c

This PR reads the status code of the child process run inside the
sandbox and forwards it to the outer process. Which in turn makes that
result its own exiting status code.
This changes the behaviour of firejail in the sense that the following would prior give you the (misleading) status `0`:
```
$> firejail 'echo 1'
Parent pid 13488, child pid 13489
The new log directory is /proc/13489/root/var/log
Child process initialized
/bin/bash: echo 1: command not found
parent is shutting down, bye...
$> echo $?
127
```
Fixes #358.

Forward exit code from child process

---

etc/qutebrowser.profile

Add profile for qutebrowser, a Qt5-Webkit based browser that allows
customization and extension via Python.  This profile follows Firefox
and Chromium/Chrome profile settings.
More details about qutebrowser at its upstream repo.
https://github.com/The-Compiler/qutebrowser

Add profile for qutebrowser.

---

src/firejail/fs_etc.c

Currently if one file fails when copying private-etc files the process stop and doesn't copy the other files. Also it doesn't log which file failed.
```
private-etc localtime,foo,resolv.conf
```
only copied `localtime`
```
/run/firejail/mnt/cp: failed to restore the default file creation context: No such file or directory
```
copy `localtime` and `resolv.conf`
```
Warning (fs_etc): error copying file /etc/foo, skipping...
```

fs_etc: continue to copy files if one fails.

---

src/firejail/x11.c

A few lines in the Xephyr methods were still referring to or using xpra methods (most importantly line 176).
Does the if-statement after line 169 ("xpra does a number of weird things") also apply to Xephyr?

Fix xephyr methods referring to xpra

---

etc/disable-programs.inc
etc/opera.profile

Petter Reinholdtsen reported in [1] that ~/.opera is used by older Opera versions, so this path should also be allowed.
[1] https://bugs.debian.org/819950

Allow alternative opera config path

---

etc/disable-devel.inc
etc/palemoon.profile

Hey netblue30! This should (hopefully) be working well now. I grabbed the firejail_0.9.40-rc1_1_amd64.deb from Sourceforge and replaced my usual 0.9.38 install from the debian testing repos--you've been pretty busy since my last attempt at a Pale Moon profile!
Re: https://github.com/netblue30/firejail/issues/343
`.mozilla` is still visible, but the only contents visible in it is the `extensions` subdirectory. The contents of `extensions` are not visible to Pale Moon so I feel pretty comfortable with this.
(Though I still would like to be able to blacklist `.mozilla` once and for all.) :-)
EDIT: just added python2 and python3 blacklists to etc/disable-devel. Would have made a separate pull request but apparently GitHub is smarter than I... :-)

Pale Moon profile && python blacklists

---

etc/icedove.profile
etc/thunderbird.profile

This makes it easier for the weirdos like me who use both Thunderbird and Icedove. :) TB can't see ID's profile; ID can't see TB's config.

Separated thunderbird/icedove profiles

---

README
etc/disable-common.inc

Found this while working on another profile and thought it might be a good idea to blacklist VeraCrypt and its directories. Just in case... :)
I took the somewhat unusual step of blacklisting the veracrypt uninstall script too--I could think of a couple of rare instances to make it an attack vector.

Blacklist vera crypt

---

todo

"11. cleanup thunderbird profile - disable-common was commented out" isn't an issue now that the thunderbird profile includes the firefox profile and therefore includes disable-common.

Removed thunderbird todo

---

Makefile.in
README
README.md
etc/aweather.profile
etc/disable-programs.inc
etc/stellarium.profile
platform/debian/conffiles
src/firecfg/firecfg.config

Profiles for aweather and stellarium. Aweather is a weather programme (shows radar, warnings, etc; though unfortunately only for the States) and Stellarium is a planetarium.
I also added 0ad to the list of games in src/firecfg/firecfg.config since I'd missed that earlier.

Aweather && Stellarium

---

README.md
src/firecfg/main.c
src/man/firecfg.txt

Finish of the migration from "clear" to "clean" wording.

fix "clean/clear" typos

---

README
etc/disable-common.inc

These are the additional terminals that can escape firejail as in #472 as tested by xenopeek.

blacklisted additional terminals

---

etc/hexchat.profile

HexChat uses python3 under Arch Linux, so this is required for it to launch.
Also, links can't be clicked on since whitelist-common.inc isn't currently included (launching default browser requires mime types, otherwise it falls back to launching "perl" and fails).

Fixes for hexchat.profile

---

test/apps-x11/apps-x11.sh
test/apps/apps.sh
test/environment/environment.sh
test/utils/utils.sh

This makes it easier to see in the result if tests were skipped.

Mark skipped tests differently

---

test/fs/private-etc.exp

On systems without installed/configured locales, the file
list is sorted by byte comparison.
On some locales it is sorted differently (e.g. X11 at the end).

Use locale-independent sorting

---

etc/cmus.profile

This reverts commit 471bba3242b01d91e6b1f52b9b12d2e88b5cf533.
Fucked up testing before, sorry.
Tried `--private-etc=null` on the CLI, while I had `--private-etc=group` in the profile and thought the CLI would override the profile, but it turns out it's complementary.

Revert "cmus.profile: use empty /etc"

---

README.md
etc/firejail.config
src/firejail/checkcfg.c
src/firejail/firejail.h
src/firejail/main.c
src/firejail/profile.c
src/firejail/sandbox.c
src/firejail/usage.c
src/man/firejail-config.txt
src/man/firejail-profile.txt
src/man/firejail.txt

> Any task can set `no_new_privs`.  Once the bit is set, it is inherited across `fork`,
> `clone`, and `execve` and cannot be unset.  With `no_new_privs` set, `execve`
> promises not to grant the privilege to do anything that could not have been
> done without the `execve` call.  For example, the setuid and setgid bits will no
> longer change the uid or gid; file capabilities will not add to the permitted set,
> and LSMs will not relax constraints after `execve`.
> -- [Linux kernel documentation](https://www.kernel.org/doc/Documentation/prctl/no_new_privs.txt)
Judicious use of `no_new_privs` can both:
- prevent sandboxed applications from (attempting to) exploit privileged (setuid, setgid or fcaps) binaries;
- prevent malicious users from (attempting to) exploit privileged binaries *using …

Enable using the NO_NEW_PRIVS prctl(2) flag

---

README.md
etc/firejail.config
src/firejail/main.c
src/man/firejail-config.txt

I suggest `netfilter` to be affected by `restricted-network` because it is a traditionally-privileged interface to the kernel, and the security impact of letting untrusted users run their own netfilter scripts (even on their own network namespace) is non-obvious.
Is that OK, or should I introduce a separate config flag for this?

Make `restricted-network` prevent use of netfilter

---

src/firejail/appimage.c

Partly fixes #560
The software inside AppImages might may the following [environment variables to be set:](https://github.com/probonopd/AppImageKit/blob/34defc0d9fc0b79735b3cdf84cd5c4d3234f9639/runtime.c#L360-L361)
* `$APPIMAGE` should contain the full path of the AppImage that has been mounted
* `$APPDIR` should contain the full path to the mountpoint where the AppImage that has been mounted
Please [squash commits](https://help.github.com/articles/about-pull-request-merge-squashing/) when merging, thanks.

Set $APPIMAGE and $APPDIR environment variables

---

etc/disable-common.inc

kde and kde4 are hidden. At least on my pc

kwallet typo

---

platform/debian/conffiles

When building a .deb package from source, lintian warns that "file in etc not marked as conffile **etc/firejail/soffice.profile**". This should handle that.

Fixed conffiles warning for soffice

---

strings.profile

From: https://lcamtuf.blogspot.com/2014/10/psa-dont-run-strings-on-untrusted-files.html
Many shell users, and certainly most of the people working in computer forensics or other fields of information security, have a habit of running /usr/bin/strings on binary files originating from the Internet. Their understanding is that the tool simply scans the file for runs of printable characters and dumps them to stdout - something that is very unlikely to put you at any risk.

add a firejail profile for strings

---

etc/cpio.profile

For decompression purposes, this will allows CPIO to execute in a sandbox environment.
FYI, according to CVE 2016-2037, the cpio_safer_name_suffix function in util.c in cpio 2.11 allows remote attackers to cause a denial of service (out-of-bounds write) via a crafted cpio file.
Other vulnerabilities listed are:
https://www.cvedetails.com/vulnerability-list/vendor_id-72/product_id-5080/GNU-Cpio.html

cpio sandbox profile for decompression

---

src/firejail/join.c
src/firejail/main.c

Using double quote instead of single quote for `cfg.command_line` allows  arbitrary command execution inside of jail if command args (eg. filenames) contain special sequences (backtick, $(), etc).
How to reproduce:
`touch '`uname -a`'`
`touch '$(cal)'`
in same directory:
`firejail cat *uname*`
command `uname -a` will be executed in jail
`firejail cat *cal*`
command `cal` will be executed in jail.
This hopefully fixes it.

Fix improper quoting of arguments

---

etc/disable-common.inc

This is used by keybase.io's client to store secrets.

disable-common: Blacklist ~/.config/keybase

---

README
README.md
etc/0ad.profile
etc/atril.profile
etc/evince.profile
etc/gthumb.profile
etc/pix.profile
etc/qtox.profile
etc/xreader.profile
platform/debian/conffiles

Apparently you can't comment conffiles without problems.  This should fix my last commit that swapped one warning for another. :stuck_out_tongue_winking_eye:
EDIT: converted qtox to private-bin and tightened the profile a bit more.
EDIT 2: okay, apparently I'm editing more than I planned! So here's what's in this PR:
1. A fix for the debian conffiles that fixes my original fix (fixed by a fixated fixer). 
2. Conversion to private-bin: atril, xreader, evince, and qtox.
3. Fixed permissions warning in 0ad that brought up a debug window when launching.
4. Removed network capabilities from atril, evince, gthumb, pix, and xreader.
5. Added some security filters where appropriate.
Cheers!

correction no. 2

---

etc/dropbox.profile

This restricts Dropbox's file access to its own directories. I think it's worth doing this by default because Dropbox is a proprietary app. 
The whitelisted directories are the default locations used by Dropbox.

restrict Dropbox to its own directories

---

README
README.md
etc/pidgin.profile

This converts pidgin to private-bin, and tightens the profile a bit.
I included `private-dev` which will break video chatting on pidgin, but searching online indicated that this is already broken in pidgin for the most part so `private-dev` will probably have no practical effect on users. What do you think?

Pidgin private-bin conversion

---

src/firejail/main.c
src/firejail/run_symlink.c

[Previous fix](https://github.com/netblue30/firejail/pull/613) of command line quoting was only partial.
Code execution still was possible using constructions like this:
`firejail 'echo $(uname -a) && echo'`
`firejail -c 'echo $(uname -a)'`
Changes to `main.c`:
I see only 2 cases for quoting:
1. Arguments passed to shell should always be quoted by single quotes.
2. Arguments passed directly to program (--shell=none) should never be quoted.
Code removed from `run_symlink.c` not just redundant, but also caused obscure problems when symlinked program used with `shell none` in profile.
For example:
```
touch '1&2'
$SUCH_PROGRAM 1\&2
```
results in  "file not found" error, while
`firejail $SUCH_PROGRAM 1\&2`
and
`firejail $SUCH_PROGRAM '1&2'`
both work fine.
`--join` command's behaviour is …

Additional fixes of command line quoting

---

src/firejail/join.c

* Honor `--nice` option when joining. Fixes https://github.com/netblue30/firejail/issues/632.
This is simplest implementation, and niceness is set independently on each join:
```firejail --name=test --nice=10```
and then
```firejail --join=test cmd1```
will start `cmd1` with default niceness (usually 0).
```firejail --nice=5 --join=test cmd2```
will start `cmd2` with niceness 5.
* Honor `--shell` option when joining, including `--shell=none`

Two fixes to --join behaviour

---

Makefile.in
README
README.md
RELNOTES
etc/uudeview.profile
platform/debian/conffiles

uudeview might access unsafe email content,
therefore restrict it as much as possible.
In fact it's best to call firejail with a private home dir, too.

Add profile for uudeview

---

etc/bitlbee.profile

Bitlbee stores its configuration in /var/lib/bitlbee. It must be able to write to this directory in order to save config changes (adding accounts, writing OTR keys, etc).

Allow BitlBee to write /var/lib/bitlbee

---

etc/skypeforlinux.profile

Per recommendation of @netblue30, allow use of the netlink protocol in order for skypeforlinux to properly function in a firejail environment, per discussion in Github issue #656.

Add new skypeforlinux profile.

---

README
src/libtrace/libtrace.c
src/libtracelog/libtracelog.c

Small improvements for libtrace / libtracelog.
If a program would have called stat() and then stat64(),
the traced program probably would crash with a NULL pointer access on orig_stat64.

Improve libtrace / libtracelog

---

Makefile.in
README
README.md
RELNOTES
etc/file.profile
etc/gtar.profile
etc/tar.profile
etc/unrar.profile
etc/unzip.profile
platform/debian/conffiles

I've tested compression and uncompression of
various tar formats and also straced unzip/unrar
regarding their file access in /etc.
-> should be fine.
If you want to unpack files in /usr/bin or so,
then use the --ignore=private-bin switch.

Add profiles for tar (gtar), unzip and unrar

---

src/firejail/x11.c

See https://github.com/netblue30/firejail/issues/676.
* Change  default hard-coded option from `-noreset` to `-terminate`.
* Allow override of hard-coded options.
Tested it a bit with both single apps and openbox WM, everything works fine for me.
Old behavior can be restored by adding `xephyr-extra-params -noreset` to `/etc/firejail/firejail.config`.

Change hardcoded Xephyr options to close window at exit of last client.

---

src/firejail/firejail.h
src/firejail/fs_home.c
src/firejail/main.c
src/firejail/profile.c
src/firejail/sandbox.c
src/firejail/usage.c
src/man/firejail.txt

--private mount a tmpfs over the user home, so, things like browser extensions and configurations are back to the defaults and you cannot pre-configure it easily.
--private=directory, on the other side, make the user home persistent.
--private-template=directory aim to /opt/firejail/templates/usernamebe an alternative, it act like --private mounting a tmpfs over the user home, and then it copy recursively all the files and dirs from a template directory to the created empty user home.
This way you can put, for example, a preconfigured .config/cromium directory let's says in /opt/firejail/templates/username, and then use 
`firejail --private-template=/opt/firejail/templates/username cromium` 
NOTE: as the copy from template is done after mounting the tmpfs to mask the user home, the …

add --private-template=directory option

---

src/firejail/env.c
src/libtracelog/libtracelog.c

1. Simplify window title setting code in `env.c`.
2. Add missing `#include <limits.h>` to `libtracelog.c`, fixes build on musl systems.

Pair of small fixes

---

Makefile.in
configure
configure.ac
mketc.sh
src/firejail/fs.c

* Workaround for systems where common UNIX utilities are symlinks to busybox.
Aside of embedded, this includes Alpine Linux, for example.
* Expand `${PATH}` macro in `noblacklist` entries.
My busybox workaround depends on this.

Busybox workaround + expand ${PATH} macro in noblacklist entries

---

src/firejail/x11.c

Sorry for for pull request that can't be automatically merged.
I pulled your latest commits too late. But my rewrite, as seems, also fixes https://github.com/netblue30/firejail/issues/671.
Main points:
* no shell used to start commands
* don't end starting process. Old behavior can be mimicked by `firejail --x11 ... &`
* wait for jail process to terminate, and then stop X11 processes, this seems to work way better than relying on X11 servers for this.
* no problems with stdout/stderr output (except of `xpra` being noisy)
* `firejail --x11 --audit` works, leaving no dormant X11 servers behind
* should fix https://github.com/netblue30/firejail/issues/671, https://github.com/netblue30/firejail/issues/693, https://github.com/netblue30/firejail/issues/648
P.S: I used `firejail --x11 echo` and …

rewrite of X11 support

---

src/firejail/bandwidth.c
src/firejail/env.c
src/firejail/firejail.h
src/firejail/fs.c
src/firejail/fs_home.c
src/firejail/join.c
src/firejail/main.c
src/firejail/sandbox.c

Shell selection code scattered everywere in code and causes bugs like this https://github.com/netblue30/firejail/issues/703.
So:
* new `guess_shell` function
* shell selection done once (well, except join), kept in `cfg.shell` variable.
* check for `/bin/bash` in chroot re-enabled as check for `cfg.shell`
For now calls `guess_shell` independently; also I noted that join never honored `--shell` and `--shell=none`. Will try to fix this latter.

Gather shell selection code in one place

---

src/firejail/firejail.h
src/firejail/fs.c
src/firejail/main.c
src/firejail/usage.c
src/man/firejail.txt

This pull request adds two new overlay options:
-  `--overlay-named` - creates and uses a named overlay in the ~/.firejail directory
- `--overlay-path` - creates and uses an overlay in an arbitrary location
These changes fulfil the enhancement requests outlined in #239. 
Now, the comments in that issue did mention a security problem with this feature, so I am not sure if my changes qualify as safe. Would love to see some comments about that.

Added more overlay options

---

etc/spotify.profile

The rule `private-bin spotify` appears to prevent Spotify from loading. This seems to be a regression on the git version, compared to the release, and removing this rule will let Spotify run again.

Fix Spotify - "private-bin spotify" prevents Spotify loading

---

etc/disable-programs.inc
etc/slack.profile

Add a profile for Slack, and include Slack's config directory within the global blacklist

Add profile support for Slack

---

etc/disable-common.inc
etc/icecat.profile
etc/whitelist-common.inc

Hi!
Three pretty small fixes:
1. The `icecat.profile` was updated (some dir paths mismatch with the generic `firefox.profile`).
2. New KDE terminal emulators added (_Konsole_ and _Yakuake_) besides adding a new blacklist rule.
3. GTK rendering issues fixed (related to _oxygen-gtk_) in some distributions still use KDE4, Slackware for example.
I appreciate your effort. Have a nice day!

Small fixes (icecat.profile, disable-common.inc and whitelist-common.inc)

---

src/firejail/firejail.h
src/firejail/no_sandbox.c
src/firejail/sandbox.c

Fixed problem with cmdline quoting, (see https://github.com/netblue30/firejail/issues/718#issuecomment-240412040)
To avoid code duplication `start_application` function from `sandbox.c` used.
Shell choice taken from `SHELL` env variable or guessed by `guess_shell` function.
Parses and honors `--shell`, `--zsh`, and `--csh` functions.
Should fix https://github.com/netblue30/firejail/issues/718

run_no_sandbox fix

---

etc/slack.profile

noblacklist must appear before the includes, to avoid the default
profiles from invoking blacklists. This commit resolves this.

Fix error in Slack profile

---

src/firejail/join.c

* simplify `join` function by reusing `start_application`. Honor `--audit` option on joining as result.
* fix caps filter setting being affected by setting user namespace, same way as in https://github.com/netblue30/firejail/blob/master/src/firejail/sandbox.c#L789. Don't know if setting caps after setting user namespace is enough, or one on line 286 is required too. I left if as is currently.

join fixes

---

src/firejail/appimage.c
src/firejail/firejail.h
src/firejail/fs.c
src/firejail/fs_home.c
src/firejail/ls.c
src/firejail/pulseaudio.c
src/firejail/util.c
src/include/euid_common.h

**appimage.c**:
* remove redundant `mkdir`, `chown`, `chmod` calls, last two also pose race condition risk.
* open appimage file as user, to avoid race condition, that may alllow attacker mount appimage/iso file that unreadable to user.
**firejail.h**:
* add `ASSERT_PERMS` macros
**util.c**:
* change `copy_file` function to take `uid`, `gid`, and `mode` for new file, use `fchown` and `fchmod` to prevent race condition when setting owner and permissions.
**euid_common.h**:
* set `egid` when switching `euid`, so files created as root won't need additional `chown` to change group.
* exit with error if unable to switch `euid`/`egid` to user - if we continue to run code than intended to run as user with root privileges - this is disaster.
**fs.c** and other:
* Avoid `chown` and `chroot` where …

Tighten security

---

etc/0ad.profile
etc/atom-beta.profile
etc/atom.profile
etc/atril.profile
etc/audacity.profile
etc/aweather.profile
etc/dosbox.profile
etc/eom.profile
etc/gitter.profile
etc/gthumb.profile
etc/hexchat.profile
etc/libreoffice.profile
etc/palemoon.profile
etc/pidgin.profile
etc/qtox.profile
etc/rhythmbox.profile
etc/stellarium.profile
etc/vlc.profile
etc/warzone2100.profile
etc/xplayer.profile
etc/xreader.profile
etc/xviewer.profile

These tighten many profiles a bit--mostly via `private-tmp`. I've also added a profile for dosbox, and removed private-tmp from the gthumb profile since it already had a /tmp whitelist. 
The profiles in the "tested and stable" commit have all been tested and I don't expect them to break anything.
I've also committed a revised hexchat profile in "may break on some systems" and added a private-bin filter. It works perfectly on my machine, but I suspect it may break on other distros that require python or perl for hexchat since they are not included in the private-bin filter (I don't know which distros these would be, but I remember something about this from an old bug report). If you do commit this, we'll probably need to revise the profile a couple of times based on the bug reports that …

Profile tightening

---

src/firejail/main.c
src/man/firejail.txt

* Add shell selection code to `--join-network` and `--join-filesystem`
* Update examples in firejail man page broken by changes in arg quoting

small fixes

---

src/firecfg/main.c
src/man/firecfg.txt

Some `.desktop` files use full path to executable. As result, just running `firecfg` is not enough to run those apps in firejail using menu or file manager.
With `--fix` option firecfg will check `.desktop` files in `/usr/share/applications/`, replace full path by name if it is in PATH, and write result to `$HOME/.local/share/applications/`.

Option to fix .desktop files for firecfg

---

src/firejail/firejail.h
src/firejail/main.c
src/firejail/profile.c
src/firejail/x11.c
src/man/firejail-profile.txt
src/man/firejail.txt

Add `--x11=block` command line option, `x11 block`, `x11 xephyr`, `x11 xpra` profile options.
X11 blacklisting implemented simplest way:
* Blacklist `/tmp/.X11-unix` and `.Xauthority`
* It's up to user to decide how to deal with abstract sockets, just stop with explanatory error message if abstract socket will be accessible in jail.

Add option to block X11

---

etc/steam.profile

Fixes #779 - Steam games unable to detect gamepads via udev

Add netlink to --protocols in steam profile

---

etc/ssh.profile

firejail output in ssh client breaks git+ssh for me, e.g.,
$ git clone git@github.com:netblue30/firejail.git
Cloning into 'firejail'...
Reading profile /etc/firejail/ssh.profile
Reading profile /etc/firejail/disable-passwdmgr.inc
fatal: protocol error: bad line length character: Pare
The "Pare" comes from "Parent pid x, child pid y".

Quiet SSH config

---

src/firejail/main.c
src/firejail/sandbox.c

Improved your fix a bit: it's better to flush `/dev/tty` than `stdin`, as `stdin` descriptor may be redirected to something else.
Test program
```c
#include <unistd.h>
#include <sys/ioctl.h>
#include <termios.h>
#include <fcntl.h>
int main()
{
char *cmd = "ls /proc\n";
while(*cmd)
ioctl(1, TIOCSTI, cmd++);
return 0;
}
```
and command
`firejail ./CVE-2016-7545 </dev/null`

CVE-2016-7545 fix improvement

---

src/firejail/fs_home.c

`~/.Xauthority` being symlink is not fatal error, warning about this and skipping it in further processing is enough.
Fix for https://github.com/netblue30/firejail/issues/821

If .Xauthority is symlink, skip and warn

---

etc/libreoffice.profile

When starting two instances of libreoffice, the second one will start the document recovery for already open documents of the first instance.
This was caused by using a too restrictive whitelist on /tmp, which prevented libreoffice from writing several temporary files.
There was also an issue about libreoffice not being able to look for java in /usr/local/sbin.
This was solved by noblacklist /usr/local/sbin

fixed recovery issue

---

etc/evince.profile

firefox will save files under /tmp/mozilla_* and try to open
them with evince when evince is the default PDF reader.

Allow evince to access /tmp

---

etc/chromium.profile

Hi,
Arch has an optional configuration file for Chromium (https://wiki.archlinux.org/index.php/Chromium/Tips_and_tricks#Making_flags_persistent) that needs to be readable by /usr/bin/chromium. I just whitelisted it.
Best regards!

Whitelist Arch's chromium-flags.conf to Chromium

---

etc/disable-programs.inc
etc/mutt.profile
mkuid.sh
src/firemon/procevent.c

* fix building on systems without bash
* add missing include: `writev` on [src/firemon/procevent.c:176](https://github.com/manevich/firejail/blob/4ac74f0621fbb33a90dd4e3aa181ccd727c57514/src/firemon/procevent.c#L176) requires `sys/uio.h`
* fix mutt.profile

Misc fixes

---

README
etc/disable-common.inc
etc/spotify.profile

This should tighten the Spotify profile a good bit. Mainly I added a `private-etc` filter and blacklisted unneeded files and directories. (Some of these directories are already read-only but why even expose them since they're not necessary?)

Tightened Spotify profile

---

README
README.md
RELNOTES
etc/disable-programs.inc
etc/gpredict.profile
etc/start-tor-browser.profile
etc/xiphos.profile
platform/debian/conffiles
src/firecfg/firecfg.config

I've edited the gpredict profile and added profiles for xiphos and the Tor Browser Bundle (the bundle from upstream, not the one from the PPA mentioned in #825). The TBB profile may need to be tweaked over time as other people test it but it's working pretty well on my end. 
(Credits to chiraag-nataraj's repo (https://github.com/chiraag-nataraj/firejail-profiles) for the `private-bin` filters.)

Extra profiles

---

etc/disable-programs.inc
etc/guayadeque.profile

I created a profile for Guayadeque which works well for me on Fedora 24. I also added 
`blacklist ${HOME}/.guayadeque`
to the media players section in disable-programs.inc.

Guayadeque profile

---

etc/qutebrowser.profile

qutebrowser stores sessions/history and other stuff in ~/.local/share/qutebrowser when using the webengine backend.

qutebrowser fixes

---

src/firejail/fs.c

This patch prevents applications inside firejail to start services outside the jail via dbus IPC sockets
Using --ipc-namespace does not suffice here.
This attempt to block breaking out of the jail via ipc is a just an early workaround.
It will likely break some applications, that depend on such services. 
For a final solution, an additional option to disable this change is needed, as well as a way to start those services inside the jail by providing dbus and possibly systemd services.
It does not prevent kde applications to start services via the kdeinit5 socket.
When the sockets blacklisted by this patch are created after the jail is launched, the blacklist has no effect.

block dbus ipc

---

etc/quiterss.profile

I've added 2 changes:
1. Added missing noblacklist entries to nullify the corresponding blacklist entries in disable-programs.inc.
2. More specific whitelist rule for ~/.local/share

Correct and tighten QuiteRss profile

---

src/firejail/fs.c
src/firejail/fs_var.c
src/man/firejail.txt

when blacklisted directories in /run/user/{uid}/gnupg and systemd do not exists when firejail is launched, they were not blacklisted before.
also in fs_var.c see the included comment

make ipc blacklist more reliable

---

README.md
RELNOTES
etc/disable-common.inc
etc/disable-programs.inc
etc/keepassx2.profile
platform/debian/conffiles
src/firecfg/firecfg.config

Arch uses the `keepassx2` command for keepassx v2, while Debian (Stable, at least) just used `keepassx` for both v1 and v2, so we've now got separate but identical profiles. 
I also removed a bunch of whitespace from disable-common.inc. :smile: 
EDIT: Apparently Atom automatically removes trailing whitespaces, so a few are gone as well.

Add keepassx2 profile

---

src/firejail/firejail.h
src/firejail/fs.c
src/firejail/fs_etc.c
src/firejail/main.c
src/firejail/usage.c

This patch implements the `--allow-private-blacklist` command line option and disables blacklists in `${HOME}` by default if `${HOME}` is a private directory. The `--allow-private-blacklist` option makes them take effect again (the previous default behaviour).
The patch also cleans up a few compiler warnings in Ubuntu 16.04 and tidies up some miscellaneous code formatting issues.

Implement the --allow-private-blacklist option

---

src/firejail/cmdline.c
src/firejail/firejail.h
src/firejail/main.c

commandline arguments are not being passed to appimage,
which hinders some functionality. This adds the function
build_appimage_cmdline based on build_cmdline which
works by calling quote_cmdline with passed argv, and
then replaces initial argument with AppRun path generated
in appimage_set.
TODO: deal with extra memory allocation. The 'quoted'
length of the first '*.AppImage' argument may or may not
be greater than the 'quoted' AppRun path.

appimage: pass commandline arguments

---

etc/fix_private-bin_for_symlinked_sh.py

It fixes the profiles in order to give access to symlinked binaries (for example if sh -> dash and dash is not in private-bin, you can't use sh).
@netblue30 , please add it into installation script.
To do it you should change it a bit to fix the following issues:
1 it doesn't take arguments now
2 the items not in ```bin```s are not fixed.

Added symlink fixer.

---

etc/abrowser.profile
etc/chromium.profile
etc/cyberfox.profile
etc/firefox.profile
etc/flashpeak-slimjet.profile
etc/google-chrome-beta.profile
etc/google-chrome-unstable.profile
etc/google-chrome.profile
etc/icecat.profile
etc/inox.profile
etc/netsurf.profile
etc/opera-beta.profile
etc/opera.profile
etc/palemoon.profile
etc/seamonkey.profile
etc/vivaldi.profile

1. Removing KeePassX from browser profiles: KeePassX currently doesn't support browser extensions, and thus all browser extensions continue to rely on KeePass, a fitting KeePass plugin and Mono. While this may change in the future and make it necessary to include whitelisting for KeePassX again, its configuration file contains information that can be valuable for attackers (password generator settings, other security settings), and so I would like to join the suggestion of @derekyerger to remove KeePassX whitelisting from browser profiles as long as it is not necessary.
2. Addition of KeePass to browser profiles: as detailed above.
3. Removing the `whitelist ~/keepassx.kdbx`: Harmonized with keepass.profile, where this file is blacklisted (via disable-passwdmgr.inc).
#937

Replace keepassx whitelisting with keepass whitelisting

---

src/firejail/main.c
src/firejail/profile.c

take an example of this ```test.profile```.
```
private-home testA
private-home testB
include /usr/local/etc/firejail/default.profile
```
- running ```firejail --private --profile=test.profile``` copies only ```testB```.
- running ```firejail --private --profile=test.profile --private-home=testC``` copies only ```testC```
- running ```firejail --private --profile=test.profile --private-home=testC --private-home=testD``` copies only ```testD```
after this patch:
- running ```firejail --private --profile=test.profile``` copies  ```testA``` and ```testB```.
- running ```firejail --private --profile=test.profile --private-home=testC``` copies ```testA```, ```testB``` and ```testC```
- running ```firejail --private --profile=test.profile --private-home=testC --private-home=testD``` copies …

allow multiple private-argv

---

etc/FossaMail.profile
etc/fossamail.profile

FossaMail is mail client, uses the Pale Moon browser core. Just edited Thunderbird rule.

Add FossaMail profile

---

etc/disable-common.inc

.bash_aliases is called from .bashrc and can contain any kind of bash script. As a consequence, this file (which usually only exists if created deliberately) should be restricted as read-only.

Don't touch aliases

---

etc/evolution.profile

`/var/spool/mail/$USERNAME` and `/var/mail/$USERNAME` are valid paths for local mails.
This change is probably also required on other email clients.

evolution.profile: add local mail dirs

---

etc/disable-common.inc

Those allow arbitrary command executions through various mechanisms

disable-common: Make mutt and msmtp's rc files read-only

---

etc/disable-common.inc
etc/disable-common.local
etc/disable-devel.inc
etc/disable-devel.local
etc/disable-passwdmgr.inc
etc/disable-passwdmgr.local
etc/disable-programs.inc
etc/disable-programs.local
etc/whitelist-common.inc
etc/whitelist-common.local

This is useful for places, like [hashbang.sh](https://hashbang.sh), which have site-specific modifications of the *.inc files.
With the current setup, the package manager cannot automatically install updated versions of those files, as it would need to somehow merge the site-specific and upstream changes.  Having the site-specific changes in separate files solves this.

etc: Support local customizations in *.inc

---

etc/disable-common.inc
etc/disable-programs.inc

- Storage locations for GNOME keyring should be blacklisted.
- Blacklisting data and configuration files associated with Konqueror.

blacklist GNOME keyring and Konqueror

---

etc/disable-common.inc

This is a stab at handling @reinerh's comments in #1036:
making `~/.local` read-only, and `~/.local/share` read-writeable.
Pro:
- likely doesn't break most things;
- provides sensible protection for `~/.local/{bin,lib,...}`
Con:
- breaks the few applications that write to `~/.local/${app}` directly (I'm not aware of any impacted profile, though);
- doesn't provide any isolation in `~/.local/share`.
I would happily welcome some discussion about what are our options there.

Make ~/.local read-only

---

etc/disable-common.inc

This covers node's NPM, Ruby gems, luarocks packages and the `~/.local` directory.

disable-common: Make directories commonly found in $PATH read-only

---

etc/uzbl-browser.profile

Personally, I only whitelist **~/.gnupg/gpg-agent.conf** and **~/.gnupg/pubring.gpg**, but that might be too restrictive for other users.

uzbl-browser.profile: enabled support for pass password-manager

---

src/firejail/firejail.h
src/firejail/fs.c
src/firejail/main.c
src/firejail/netns.c
src/firejail/sandbox.c
src/man/firejail.txt

This implements the feature requested in issue #1058: `--netns=NAME` puts the sandbox into the network namespace NAME, which must already exist and be fully configured.
I haven't tested this at all yet but I thought I'd show it to you anyway.

Add support for joining a persistent, named network namespace.

---

etc/disable-common.inc

It breaks tmux inside firejail. 
--private-tmp should be used in order to use tmux inside firejail safely.

Prevent tmux connecting to an existing session

---

etc/uudeview.profile

Hopefully this fixes #1032. The error was from the `blacklist /etc` line so I replaced it with `private-etc ld.so.preload`.
Cheers!
Fred

Fix for uudeview

---

src/firejail/firejail.h
src/firejail/fs_hostname.c
src/firejail/util.c

Currently the code uses the access() call to check if the user has an access to a file that is copied into the root as /etc/hosts. This inevitably adds a race when the user changes the file to a symbolic link pointing to an arbitrary location on the filsystem after the access check is done but before opening the file to copy it. This potentially allows to read any file on the system.
To close this the code adds a utility copy_file_from_user_to_root . It opens the copy destination file as root and then forks/drop privileges. Then as a user the utility opens the source file and do the copy into the destination descriptor that is preserved accross the fork.

fixing --hosts-file privelege check

---

etc/palemoon.profile
etc/qbittorrent.profile

The palemoon installer installs the palemoon binary to /opt (and links /usr/bin/palemoon to it) so, since the profile already has private-bin, I added a private-opt filter as well.
Also `nogroups` was added to the qbittorrent profile - I've tested it and it still seems to be working great.
Cheers!

Security filters

---

etc/unbound.profile

There is no legitimate reason for a caching DNS resolver to need 3D acceleration.  Unbound adheres to this already, so any attempts to access GPU hardware from it are by definition either bugs or the result of an exploit, so let's just block access to the GPU.
Tested on my local systems with about 2 dozen different permutations of unbound configuration, double checked by looking through the source code for Unbound.

Update unbound profile to block 3D acceleration.

---

etc/keepassx.profile
etc/keepassx2.profile

G'day @netblue30 . This tightens the keepassx profiles a little bit.
I was under the impression `net none` meant the netlink socket was closed, but `firejail --audit` says:
```MAYBE: I can connect to netlink socket. Network utilities such as iproute2 will work fine in the sandbox. You can use "--protocol" to disable the socket.```
So I've kept `protocol unix` in addition to adding `net none`. Is that correct?
Cheers!

Tighten keepassx

---

etc/disable-passwdmgr.inc
etc/keepass.profile
etc/keepass2.profile
etc/keepassx.profile
etc/keepassx2.profile

*.kdb and *.kdbx files were blacklisted in ${HOME} via diable-common.inc, but this was not disabled for Keepass and KeepassX.
Further, ${HOME}/keepassx.kdbx doesn't need to be blacklisted separately, as it is already contained in above mentioned blacklist.

fixing and tidying up Keepass(x) profiles

---

etc/engrampa.profile
etc/file-roller.profile

Forked from file-roller.profile. Tested and works well for me.
At first I had `no3d` in the profile, but then I was under the impression that `no3d` is already included in `nogroups` (membership in the video group should be a precondition for access to hardware acceleration), and so I removed it again.
Please correct as necessary.

profile for engrampa

---

etc/disable-common.inc

Terminix is being renamed to tilix. This adds `${PATH}/tilix` to the blacklisted terminals in disable-common.inc without removing terminix (since there will still be users of terminix).
Thanks to @glitsj16 for pointing this out. :smile:

Handles #1150

---

etc/disable-common.inc

One more autostart folder used by Plasma ([ArchWiki](https://wiki.archlinux.org/index.php/KDE#Autostarting_applications))

complete autostart blacklist for KDE

---

src/include/syscall.h

Extracted from Arch Linux (kernel 4.9.4) using src/tools/extract_syscalls.c.

syscall list update

---

etc/firejail.config
src/firejail/checkcfg.c
src/firejail/firejail.h
src/firejail/main.c

I introduced a config param in /etc/fierjail/firejail.confg to disable --join command for non-root users.

enable/disable join support in /etc/firejail/firejail.config

---

etc/thunderbird.profile

In debian stretch icedove is renamed to thunderbird. This happens
as of icedove version 1:45.7.1-1, see debian bug #816679 for
details.
Thunderbird debian package, as of stretch, contains a migration
script for user profiles. Namely /usr/bin/thunderbird is a wrapper
script, thunderbird-wrapper.sh. This scripts symlinks ~/.icedove
(if exists) to ~/.thunderbird thus ensuring Thunderbird will be
able to read old user's profiles.
That symlink breaks thunderbird when run with firejail since
firejail thunderbird.profile does not allow access to ~/.icedove.
This commit modifies accordingly the thunderbird.profile.

Adds icedove directories in thunderbird profile

---

etc/audacious.profile
etc/disable-common.inc
etc/disable-passwdmgr.inc
etc/disable-programs.inc
etc/gwenview.profile
etc/scribus.profile

- harden audacious profile
- added KFileDialog history to blacklist (~/.config/Audaciousrc, ~/.config/scribusrc)
- added pdf reader support to scribus profile (feature is not yet available in scribus stable though)
- `netlink` added to gwenview profile.
**EDIT/REPEATED UPDATE:** during startup there is a complaint `UdevQt: unable to create udev monitor connection`, which disappears when the netlink protocol is allowed. 
Google shows this string is in the [sources](https://github.com/KDE/solid/blob/master/src/solid/devices/backends/shared/udevqtclient.cpp) of [solid](https://techbase.kde.org/Development/Architecture/KDE4/Solid), and apparently it is printed when monitoring of the kernel uevent netlink socket fails. Btw, other programs that depend on the solid library and show exactly the …

profile enhancements

---

src/fseccomp/seccomp.c

Added the following: bpf, clock_settime, personality, process_vm_writev, query_module,  settimeofday, stime, umount, userfaultfd, ustat, vm86, vm86old

add new syscalls in default seccomp filter

---

etc/disable-programs.inc
etc/firefox.profile
etc/gwenview.profile
etc/okular.profile
etc/scribus.profile

- Gwenview: This patch is necessary for the KDE4 build, the KF5 build doesn't need any of it.
- Okular: It was already described in #421, and I can confirm that printing from okular is not possible without `private-bin lpr`

Okular and Gwenview profiles, Baloo blacklist

---

etc/baloo_file.profile
etc/disable-programs.inc

seccomp needs to stay disabled, because baloo makes ioprio_set system calls, which are on the seccomp blacklist.
Tested both on KDE4 and KDE5.

new baloo profile

---

contrib/fj-mkdeb.py

See https://github.com/netblue30/firejail/issues/772

Add a script to build a .deb with custom configure options

---

etc/baloo_file.profile

The last one of my commits from yesterday introduced X11 isolation but also a bug into the profile. Blacklisting /tmp/.X11-unix causes Baloo to hang after a while. I don't know why Baloo cares about X11, but we need to either remove this line or replace it with `x11 xorg`, which works for me.

fix baloo_file.profile (x11 isolation)

---

contrib/fj-mkdeb.py

This takes care of the problem mentioned in https://github.com/netblue30/firejail/pull/1205#issuecomment-292813894

Fix fj-mkdeb.py not functional when installed

---

src/fcopy/main.c
src/firejail/join.c
src/firejail/sbox.c
src/fnet/fnet.h
src/fnet/interface.c
src/fnet/main.c
src/fseccomp/fseccomp.h
src/fseccomp/main.c
src/fseccomp/protocol.c
src/fseccomp/syscall.c

Several fixes for --quiet:
* firejail/join.c - fix issue #1203 
* firejail/sbox.c - export FIREJAIL_QUIET env variable to signal --quiet
* fseccomp, fnet, fcopy - --quiet support based on FIREJAIL_QUIET env variable
* fcopy - code formating

--quiet fixes

---

etc/baloo_file.profile

Baloo will fail to update its configuration file, unless the whole config folder is writable (it seems it wants to create a lock file). But if the whole config folder writable, having ${HOME} read-only doesn't make so much sense any more.
So I propose to remove not necessary lines and to add a note.

make Baloo experiment more meaningful

---

src/firejail/no_sandbox.c

When running a login shell, it occurred to me that the shell was being opened recursively. This commit will prevent recursive login shells.

Prevent running shells recursively

---

etc/caja.profile
etc/disable-programs.inc
etc/nautilus.profile
etc/nemo.profile

and
- permit Nautilus to access Trash
- remove `noblacklist ~/.local/share/caja` from profile, as folder is not used by Caja

blacklist file-manager python scripts

---

etc/disable-passwdmgr.inc
etc/keepass.profile

write access to keepass plugins is a security risk, and on the keepass homepage stated as such

blacklist keepass plugins

---

etc/baloo_file.profile

but loosen write-protections in commented section. Stricter settings for ~/.local/share won't work, due to write-locks set by KDE

harden baloo_file

---

etc/gimp.profile

removing `ipc-namespace` fixes:
```
The program 'gimp' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
(Details: serial 194 error_code 10 request_code 130 minor_code 1)
(Note to programmers: normally, X errors are reported asynchronously;
that is, you will receive the error a while after causing it.
To debug your program, run it with the --sync command line
option to change this behavior. You can then get a meaningful
backtrace from your debugger if you break on the gdk_x_error() function.)
```

gimp profile fix

---

Makefile.in

This patch allows to build firejail again for architectures that don't support seccomp yet.

make seccomp optional again

---

etc/mpv.profile

This is required for MPV to successfully use youtube-dl on Arch. I'm not sure if other distros still ship youtube-dl with python2, or if python2.7 can be removed.

allow python and python3 for youtube-dl in MPV profile

---

src/firejail/firejail.h
src/firejail/fs_dev.c
src/firejail/main.c
src/firejail/profile.c
src/firejail/sandbox.c
src/firejail/usage.c
src/man/firejail-profile.txt
src/man/firejail.txt

Since `--private-dev` allows video devices as of 1328d523ed62dfcdb205580ce7c126813b592cb7, this gives us a way to block video devices in almost exactly the same way as `--nosound`.
Still a work in progress. Code needs cleanup and improvement, but
it does block /dev/video* in all of my tests so far.
Please review and let me know your thoughts, but don't merge! 😄 It's still got some issues to be fixed.
EDIT: sorry for the large diff. My editor (Atom) automatically removes trailing whitespace.

WIP: --novideo option

---

src/firejail/main.c
src/firejail/profile.c

cppcheck reported:
[firejail/main.c:1335]: (warning) Char literal compared with pointer 'subdirname'. Did you intend to dereference it?

minor bugfix: Correctly dereference "subdirname" variable

---

src/firejail/util.c

This attempts to fix #1013 
Which is caused by a race condition in `create_empty_dir_as_root` between `stat` and `mkdir`.
Note 1: I'm not quite sure what the comment `/* coverity[toctou] */` does. Is it necessary that it stays in the line right above to the if statement? If yes, please tell me, then I'll reorder the comments.
Note 2: There are a bunch of calls to `mkdir` throughout the code, some of them behind a similar `stat`-gate. Should I also add a similar change to these?
Note 3: For testing, I forced race conditions by inserting a sleep right after the call to `stat`

Fix race condition when setting up /run/firejail files (#1013)

---

README.md
etc/liferea.profile
src/firecfg/firecfg.config

Note that profile comes with a small problem:
Liferea allows to import and export the current feed list.
However, I don't know which directory I should allow for this?
Maybe ~/Downloads?
With the current profile, the export/import feature does NOT work.

Add profile for Liferea

---

src/firejail/fs_whitelist.c

was causing a SEGV when processing nonexistent directory

fix empty-string assignment

---

etc/mpv.profile

youtube-dl uses `/usr/bin/env` as its interpreter.
If `env` is not available, mpvʼs execution of youtube-dl fails.

Allow env for youtube-dl in mpv profile

---

etc/mpv.profile
etc/youtube-dl.profile

youtube-dl can use `.netrc` for site authentication ([`netrc` option](https://github.com/rg3/youtube-dl/blob/master/README.md#authentication-with-netrc-file)).

Allow ~/.netrc for youtube-dl

---

etc/exiftool.profile

Firejail output interferes with usage in a pipeline.
Example (without `quiet`):
```
exiftool -q -q -p '$ImageWidth/$ImageHeight' firetools-main.png | bc -l
Reading profile /etc/firejail/exiftool.profile
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Warning: skipping none for private /etc
(standard_in) 1: syntax error
(standard_in) 2: illegal character: ^[
(standard_in) 2: illegal character: $
(standard_in) 2: illegal character: I
(standard_in) 2: syntax error
(standard_in) 2: illegal character: W
(standard_in) 2: illegal character: $
(standard_in) 2: illegal character: I
(standard_in) 2: illegal character: H
(standard_in) 2: syntax error …
```

Add quiet to exiftool profile

---

etc/chromium.profile

Hi,
Since a recent update, Chromium on Arch can't access ~/.config/chromium-flags.conf anymore (permission denied).
That is fixed simply adding a noblacklist line to the profile.
Thank you for Firejail.

Fix permission denied for chromium-flags.conf in Arch

---

src/firejail/fs.c

This typo may have prevented blacklists of /run/user/{uid}/gnupg and
/run/user/{uid}/systemd from working.

Fix typo usr->user

---

etc/eog.profile

Eog needs access to the users trash folder to delete files.

Add access to trash for eog

---

etc/electron.profile
etc/riot-web.profile

* Add a generic profile for Electron applications.
* Add a specific profile for Riot based on this new Electron profile.
* Addresses vector-im/riot-web#3004
* Fulfils profile request for Riot.im in netblue30/firejail#1139

Add Electron and Riot profiles

---

etc/zoom.profile

Zoom seems to use of a QT cache-disk feature which depends upon a `~/.cache/<app>/qmlcache` directory.
If it can not, Zoom will segfault with
`mprotect failed in ExecutableAllocator::makeExecutable: Permission denied`

Zoom cache dir

---

src/firejail/network_main.c

I noticed a fair bit of copy pasta here.  While that may not necessarily be bad in itself, is there a reason where the duplication can be easily parameterized to avoid using C preprocessor macros with the ## operator to avoid this sort of typo?

Fix typo for fnet moveif invocation on 2nd interface.

---

etc/telegram-desktop.profile
etc/telegram.profile

The Telegram client is called `telegram-desktop` in Debian: https://packages.debian.org/sid/telegram-desktop. (It's also not an IRC client, but uses its own protocol.

telegram is called telegram-desktop in Debian

---

Makefile.in
src/firejail/firejail.h
src/firejail/main.c
src/firejail/preproc.c
src/firejail/profile.c
src/firejail/sandbox.c
src/firejail/seccomp.c
src/fseccomp/fseccomp.h
src/fseccomp/main.c
src/fseccomp/seccomp.c
src/fseccomp/seccomp_file.c
src/man/firejail.txt

The seccomp patch also fixes a memory leak and double load.
Memory-deny-write-execute is similar to systemd directive with same name (sans CamelCase).

Improve loading of seccomp filter and memory-deny-write-execute feature

---

etc/firejail-default

This adds some additional paths to /proc whitelist in firejail-default aparmor profile. Those were detected by audit system logs.
```
AVC apparmor="DENIED" operation="open" profile="firejail-default" name="/proc/27/net/dev" pid=6143 comm="kodi.bin" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
AVC apparmor="DENIED" operation="open" profile="firejail-default" name="/proc/27/net/dev" pid=6143 comm="kodi.bin" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
AVC apparmor="DENIED" operation="open" profile="firejail-default" name="/proc/12/loginuid" pid=9570 comm="zsh" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
AVC apparmor="DENIED" operation="open" profile="firejail-default" name="/proc/80/auxv" pid=9570 comm="firefox" requested_mask="r" denied_mask="r" fsuid=1000 …
```

Add some /proc dirs to firejail apparmor profile

---

etc/disable-common.inc

`${HOME}/.local/share/kservices5` is blacklisted since https://github.com/netblue30/firejail/pull/1177 but there is no explanation for this. Some applications try to read this directory and it has legitimate use cases. Also `/usr/share/kservices5` isn't blacklisted so blacklisting only it's local variant isn't consistent. Changing it to read-only is both safe and don't trigger blacklist violations.
```
blacklist violation - sandbox 20831, exe okular, syscall opendir, path /home/mr/.local/share/kservices5
blacklist violation - sandbox 22050, exe gwenview, syscall opendir, path /home/mr/.local/share/kservices5
blacklist violation - sandbox 22386, exe kde-open5, syscall opendir, path /home/mr/.local/share/kservices5
```

Change ${HOME}/.local/share/kservices5 to read-only

---

etc/disable-programs.inc
etc/gwenview.profile
etc/qbittorrent.profile

Added directories which are used for tracking recently opened files and dirs by `qBittorrent` and `gwenview` apps. Similar dirs are already included in many other profiles. Also added KDE 5 version of `kbuildsycoca` to private-bin for `gwenview`.

profile fixes

---

etc/gwenview.profile

According to https://github.com/netblue30/firejail/pull/1430#pullrequestreview-54257466 it may be unnecessary. It was also proposed and dropped from okular profile https://github.com/netblue30/firejail/pull/1198/commits/fbfa5df3ba9e92c256101c0c3eddb98d102c9b8a . No other profile uses it currently so adding it was probably mistake. Sorry.

Gwenview: drop kbuildsycoca5 from private-bin

---

etc/steam.profile

`libGL: dlopen /usr/lib32/dri/nouveau_dri.so failed (libLLVMObjCARCOpts.so.4: cannot open shared object file: No such file or directory)`

fix steam startup with >=llvm-4

---

etc/disable-common.inc
etc/dolphin.profile

Parallels #1428
Configurations in this location don't have much value as a secret, but need to be protected from manipulation. Let's make them available to all KDE apps for legitimate use. 
Looking at Dolphin, it is actually a security improvement.

Change KDE4 services folder to read-only

---

platform/rpm/firejail.spec

Known license tag should be `GPLv2+` ([full list](https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#SoftwareLicenses)).

Match RPM license tag with license set in COPYING

---

etc/dolphin.profile
etc/k3b.profile
etc/kate.profile
etc/keepass.profile
etc/keepassx.profile
etc/keepassx2.profile
etc/kwrite.profile
etc/mediathekview.profile
etc/pdftotext.profile

- A couple of novideo additions
- While VLC is the default, other media players can be used in Mediathekview also. The current list might be not complete yet, but these are all players with a Firejail profile from which I know they work with Mediathekview.

more novideo options, enhanced mediathekview

---

etc/apktool.profile
etc/arm.profile
etc/baobab.profile
etc/bless.profile
etc/chromium.profile
etc/dex2jar.profile
etc/flashpeak-slimjet.profile
etc/gitg.profile
etc/google-chrome-beta.profile
etc/google-chrome-unstable.profile
etc/google-chrome.profile
etc/hashcat.profile
etc/jd-gui.profile
etc/meld.profile
etc/multimc5.profile
etc/obs.profile
etc/pdfsam.profile
etc/peek.profile
etc/pithos.profile
etc/sdat2img.profile
etc/strings.profile

What is the proper way to handle python versions?
- Chromium on Arch no longer launches via a perl script [1](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/chromium&id=a2d61887394fd1fec63d9fe5ba0d2c07325164e) [2](https://github.com/foutrelis/chromium-launcher/commit/9d112db0d19e581ba816cb552a527b5b6a4d9f2f) [3](https://github.com/foutrelis/chromium-launcher/commit/44fa2a2b57dfd3f2bc9f2bf17e738ea964f2dce2)
- strings will be the first profile with private-lib

Harden 18 profiles using private-bin

---

.travis.yml

Currently, no binaries of recent versions are available for download.
This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload it to a temporary download URL on transfer.sh (available for 14 days). The download URL is toward the end of each Travis CI build log of each build (see below for how to set up automatic uploading to your GitHub Releases page).
For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) __prior to merging this__, if you haven't already done so.
__Please note:__ Instead of storing AppImage builds temporarily for 14 days each on transfer.sh, you could use GitHub Releases to store the binaries permanently. This way, they would be …

Automatically build each commit on Travis CI and upload

---

etc/cvlc.profile
etc/konversation.profile
etc/skanlite.profile
etc/tracker.profile
etc/tuxguitar.profile

A note regarding Skanlite: The default seccomp filter seems to break device discovery for Skanlite on Debian Stretch. Also I had mixed results with network namespaces. What worked for me on all platforms including Fedora is `protocol unix,netlink`, which is why I suggest bringing the option back.

some fixes and enhancements

---

etc/simple-scan.profile

Fix for broken device discovery. 
Mirrors recent changes for skanlite (#1475), which uses the same backend (SANE).
As tested on Debian Jessie.

fix simple-scan

---

etc/disable-common.inc

`pass` is a password manager that keeps files under `~/.password-store` by default.
See http://www.passwordstore.org/ for more info

Add pass to common blacklist

---

etc/atril.profile
etc/audacious.profile
etc/audacity.profile
etc/cvlc.profile
etc/engrampa.profile
etc/eog.profile
etc/eom.profile
etc/file-roller.profile
etc/fossamail.profile
etc/gedit.profile
etc/goobox.profile
etc/handbrake.profile
etc/konversation.profile
etc/mediathekview.profile
etc/pluma.profile
etc/qpdfview.profile
etc/scribus.profile
etc/simple-scan.profile
etc/skanlite.profile
etc/vlc.profile
etc/xed.profile
etc/xfburn.profile
etc/xplayer.profile
etc/xreader.profile
etc/xviewer.profile

- an attempt to bring the forks gedit-pluma-xed, evince-atril-xreader, eog-eom-xviewer, totem-xplayer, engrampa-file-roller to the same level.
`net none` makes the settings of various programs immutable, which is both a bug and a feature (dconf isolation). This pull request would make the feature opt-in. If we instead leave it as it is now, maybe we should at least put a comment in the profiles.
- added `memory-deny-write-execute` to audacious, audacity, qpdfview. As it seems to work for some, may I also propose putting this option back (but commented) in the vlc profile?
- commented recently added `novideo` in skanlite, simple-scan profiles. Apparently these scanning tools can make snapshots with the webcam, too.
- fixed some more `nodvd`, `notv` options
- EDIT: vlc and cvlc profiles are …

profile fixes and enhancements

---

README
etc/cpio.profile
etc/cvlc.profile
etc/dnscrypt-proxy.profile
etc/dnsmasq.profile
etc/file.profile
etc/musescore.profile
etc/unbound.profile

- harden server profiles
- the default `netfilter` seems to be not compatible with running a server in the sandbox, my proposal is to remove it from the dnsmasq profile
- fix copy/paste mistake in musescore profile

improve servers, harden musescore

---

src/fseccomp/syscall.c

Group `@module` is already included in group `@privileged`. Tiny fix for syscalls in `@module` being printed twice with `seccomp.print`

syscalls blacklisted twice

---

etc/disable-common.inc
src/firejail/pulseaudio.c

in case #1529 is favorably received.

remount ~/.config/pulse with noexec

---

etc/gitg.profile

Fixes #1537. This should probably be backported to 0.9.50-bugfixes.
Old versions of gitg fail to display git diffs when mdwe is enabled.

Fix gitg diff not showing

---

etc/goobox.profile

1) Permitting internet access fixes broken metadata retrieval (relevant for the rip functionality)
2) We can safely enable private-dev after the introduction of nodvd

goobox enhancements

---

etc/baloo_file.profile
etc/clementine.profile

updates the seccomp filter for baloo and clementine, to include all new blacklisted syscalls. 
seems to work well.

harden baloo, clementine

---

etc/ssh-agent.profile

It's common to invoke ssh-agent in shell login config, so if firejail launches it through a shell, that can lead to an infinite loop

Set `shell none` for ssh-agent configuration

---

etc/steam.profile

steam.sh executes `/sbin/ldconfig -XNv 2> /dev/null` when STEAM_RUNTIME_PREFER_HOST_LIBRARIES is not zero and fails in some cases (see https://github.com/ValveSoftware/steam-for-linux/issues/4768) because of blacklisted /sbin and missing ld.so.conf{,.d}
https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/586991182161672256

fix usage of STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1 in steam.profile

---

etc/firejail-default

Replace opaque character class with an explicit list of root-level directories to be granted access.
The replaced line in the apparmor profile deceptively granted access to all root-level directories that did not start with the letters any of the characters `coprsy,^`, which is probably not what was intended. 
Once apparmor supports the [proposed addition](http://wiki.apparmor.net/index.php/QuickProfileLanguage#Proposed_additions), this line can be replaced with  `{**^sys,proc}`, which is what (I am guessing) was intended.
I'm currently running with this rule loaded. Other tools may need more liberal permissions. Notice that this **adds** access to `opt` and `srv`, which previously would not have been whitelisted.

Enumerate root directories in apparmor profile

---

src/man/firecfg.txt
src/man/firejail-login.txt
src/man/firejail-profile.txt
src/man/firejail.txt

All of these websites support HTTPS, and nearly all of them redirect
to it anyways.

Update manpages to use HTTPS links

---

cmake-build-debug/CMakeFiles/clion-log.txt
src/firejail/firejail.h
src/firejail/main.c
src/firejail/profile.c
src/firejail/rlimit.c

Addition of RLIMIT_AS for limiting process's virtual memory. Kept the same format as your previous rlimit implementations.

Addition of RLIMIT_AS

---

etc/qtox.profile

`qtox: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory`
Related https://github.com/netblue30/firejail/issues/1320

qtox needs libstdc++.so.6

---

etc/brave.profile
etc/chromium.profile
etc/conkeror.profile
etc/cyberfox.profile
etc/flashpeak-slimjet.profile
etc/google-chrome.profile
etc/icecat.profile
etc/midori.profile
etc/netsurf.profile
etc/opera-beta.profile
etc/opera.profile
etc/palemoon.profile
etc/seamonkey.profile
etc/start-tor-browser.profile
etc/surf.profile
etc/torbrowser-launcher.profile
etc/vivaldi.profile
etc/yandex-browser.profile

Let's don't merge this just yet. 
This adds disable-mnt to most (all?) of our browser profiles as per the discussion in #1660, blocking access to mount points. This does mean some users (relatively few) will have some problems if their ${DOWNLOADS}, etc, are on external media, but I think it's an acceptable tradeoff for the increased sandbox tightness that will benefit the majority of users. 
Thoughts/comments/suggestions/"we-shouldn't-do-this-because-xyz"? :grin:

In Testing: (Re)add disable-mnt to common browser profiles.

---

src/libtrace/libtrace.c

Fix build on Musl systems, tested on x86_64-musl Void Linux
Build error
```
libtrace.c: In function 'log_exec':
libtrace.c:683:18: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'AF_MAX'?
static char buf[PATH_MAX + 1];
^~~~~~~~
AF_MAX
libtrace.c:683:18: note: each undeclared identifier is reported only once for each function it appears in
```

libtrace/libtrace.c: add missing limits.h include

---

etc/disable-common.inc

disable-common.inc blacklists whole .ssh, but some profiles (e.g. idea.sh)
unblacklists it to allow git over ssh with public key auth.
But this creates security hole, since firejailed app could modify
~/.ssh/authorized_keys and allow arbitrary code execution on the host with sshd
installed (e.g. ssh localhost and run any program) or even open backdoor for
remote attacker.
This commits disallows write access to ~/.ssh/authorized_keys even if .ssh was
unblacklisted.
Signed-off-by: Alexander GQ Gerasiov <gq@cs.msu.su>

disable-common.inc: read-only access to ~/.ssh/authorized_keys

---

etc/okular.profile

Without it, recent okular versions (here 17.12.0-1 on Arch Linux) crash with
mprotect failed in ExecutableAllocator::makeExecutable: Permission denied
due to the noexec constraints in the firejail profile.

Added environment variable QML_DISABLE_DISK_CACHE=1 to okular.profile.

---

etc/deluge.profile

Deluge needs access to more than the deluge binary if it runs as a daemon (or if you want to access it via the web or command line)

Fix Deluge

---

etc/disable-programs.inc

~/Monero/wallets is the default path suggested by the official wallet application, but it can be changed by user.

Blacklist the monero wallets directory

---

etc/minetest.profile

This removes the "private-etc" line from the "minetest"-profile for a successfully start of the game.

Fix #1702 - Couldn't start 'minetest' in Debian Testing

---

etc/playonlinux.profile

This profile have been successfully tested by starting a windows application through it.
"wine.profile" has been used as template for this. Only "noblacklist ${PATH}/nc" has been added because playonlinux needs it to run.
**Please note** that this is currently not tested due to security aspects, so it may need a rework later on. Because opening a unknown windows application through it could possibly be a security risk.

Add profile for "playonlinux"

---

.gitignore

- Ignore built package archive files (.tar.xz and .deb) from Git repository
- Avoid accidentally committing unneeded files in the future

chore(.gitignore) ignore built packages

---

etc/firejail-default

1. Allow for seven digit PID same as upstream do https://gitlab.com/apparmor/apparmor/commit/630cb2a981cdc731847e8fdaafc45bcd337fe747
2. Fixed dbus functionality. Disabled by default.

Apparmor: minor fixes

---

etc/spotify.profile

Zenity is needed to add local music.

Allow Spotify to run Zenity

---

etc/remmina.profile

To derive the filters I ran: `strace -qcf remmina` then connected to a remote host via RDP.
The previous filter (just the default list) allowed Remmina to start, but would fail to establish the connection (it got as far as validating credentials; bad creds gave a different error).
The specific problematic sys call when I checked the audit log was `access` - but I didn't try incrementally building up from there, I just took the whole strace output.

Add seccomp filters for remmina, from an strace session connecting via RDP

---

etc/playonlinux.profile

Playonlinux uses perl internally: https://github.com/PlayOnLinux/POL-POM-4/search?utf8=%E2%9C%93&q=perl&type=

playonlinux: unblacklist perl usage

---

etc/firejail-default

Firejail does blacklisting sensitive /proc and /sys files on its own: https://github.com/netblue30/firejail/blob/master/src/firejail/fs.c#L530
There is no need to duplicate this in apparmor using whitelisting approach which is much harder to do and needs never ending maintenance.
See discussion in https://github.com/netblue30/firejail/pull/1766#issuecomment-364786746

Apparmor: blacklist /proc and /sys access from firejail

---

etc/evince-previewer.profile
etc/evince-thumbnailer.profile
etc/evince.profile

Seems the current evince profile has issues with dconf, user icons and themes. These can all be easily fixed by including `whitelist-common.inc`. Also adding 2 redirect profiles for evince-previewer and evince-thumbnailer, both executables are included in evince as packaged on Arch Linux (and probably other distro's too).
After seeing [#1711](https://github.com/netblue30/firejail/issues/1711), I took another crack at trying to fix the `private-lib` condition, something I had fiddled with before without succes. But this time it looks as if things are settling nicely in that regard. I added what works for me after extensive testing. Leaving commented, so other people can take a closer look.
For what it's worth, these all work, ordered from less to more granular/restrictive:
- private-lib …

evince fixes

---

etc/eog.profile

Using Arch Linux (Gnome Shell 3.26.2, Mutter WM, as in [#1711](https://github.com/netblue30/firejail/issues/1711)). After playing with several Gnome apps and `private-lib` conditions, it looks like there's progress to report. I made a few PR's today on the same topic, usually leaving things commented as to leave room for more eyes to double-check. In this case I took the liberty to throw in an uncommented one for eog. Please respond or rectify if this was uncalled for.

private-lib fix

---

etc/disable-common.inc

AWS and GCP store credentials in local directories as part of project setup.
Configuration for cloud providers is sensitive information; it should be
in the default block list. I didn't see profiles for gcloud or awscli,
so haven't added any exclusions.
boto and kubectl are not provider-specific, but also store credentials for
whichever platforms they happen to be being used with.

Add a section for cloud-providers to the default block-list

---

etc/gcloud.profile

Hi, another quick one hopefully. I tested the profile out with the following workflows:
* `gcloud init`
* `gcloud docker -- push ...`
* `gcloud compute instances list`
All seemed okay; I think the docker integration is the only thing that requires any "interesting" permissions, and the rest is just speaking to an API.
gcloud is the Google Cloud Platform's cli. It understands how to interact with GCP's endpoint, and it need to read config and creds from the user's $HOME, plus it integrates with docker-cli.

Added a basic profile for gcloud

---

etc/evince.profile

During conversation on an [earlier attempt at fixing evince](https://github.com/netblue30/firejail/pull/1829) and the entailing [revert-commit](https://github.com/netblue30/firejail/pull/1829/commits/45732a22d1ea4ec0ade0775be7243e8669b7f850) this slipped through the cracks. The fix is tested on Gnome Shell 3.26.2 and 3.28.0 (on Arch).
I noticed the original issue #1711 is closed and tagged `in testing`. Feel free to postpone/close/disregard this fix untill testing is finished. Just wanted to remind people that a fix is available.

Fix private-lib again

---

etc/disable-programs.inc
etc/mpd.profile

Current mpd profile uses outdated ${HOME}/.mpdconf noblacklist location. Not sure that was ever actually used (I remember ~/.mpd). Bring in support for freedesktop location `${HOME}/.config/mpd`, as per [official documentation](https://www.musicpd.org/doc/user/config.html#config_file).

mpd config modernizing

---

etc/makepkg.profile

Using `PKGBUILD` instead of `pckgbuild` might be slightly more familiar for Arch users.

syntax fixup

---

etc/atool.profile

Now there's  `disable-interpreters.inc` atool profile needs allowing `perl` access.

Allow perl

---

src/man/firejail.txt

Nitpicking. Seems there's a pattern throughout the manual, using `pid` for arguments and `PID` in descriptions and examples. Fix some inconsistencies in that regard. Changed `--fs.print=name|print` to `--fs.print=name|pid` as 'print' would be regarded as the name of the sandbox.

consistent pid/PID usage

---

etc/disable-programs.inc
etc/mpd.profile

Support less/non-standard config dir too. On Ubuntu 16.04 mpd still looks at ` ~/.mpd` for defaults.

Config support fixup

---

etc/enchant-2.profile
etc/enchant-lsmod-2.profile
etc/enchant-lsmod.profile
etc/enchant.profile

Added `nodbus` and brushed-up the profile some more. Arch uses `enchant-2` & `enchant-lsmod-2` executables, while Debian/Ubuntu have `enchant` & `enchant-lsmod`. Introduced new redirect files to cope with those differences.

Update enchant profile

---

etc/atool.profile
etc/bunzip2
etc/gunzip

Adding 'private-etc' `passwd,group` to unbreak the profile, fixes [issue 1869](https://github.com/netblue30/firejail/issues/1869).
Add 2 'redirect' profiles for gzip: `bunzip2` and `gunzip` (which atool uses to handle .gz archives).

atool fixes

---

etc/firefox-common-addons.inc

```
$ firejail firefox
...
TESTING warning: noblacklist /home/glitsj16/.local/share/gnome-shell/extensions not matched by a proper blacklist command in disable*.inc
...
$ grep gnome-shell /etc/firejail/disable-common.inc
blacklist ${HOME}/.local/share/gnome-shell
$ grep gnome-shell /etc/firejail/firefox-common-addons.inc
noblacklist ${HOME}/.local/share/gnome-shell/extensions
whitelist ${HOME}/.local/share/gnome-shell/extensions
```
Dropping `/extensions` in `firefox-common-addons.inc` fixes things.

avoid TESTING warning in firefox-common-addons.inc

---

src/firejail/env.c
src/firejail/join.c
src/firejail/sandbox.c

Lowering privileges for setting cpu affinity was no primary objective, it just turned out to be possible (from `man sched_setaffinity`: The caller needs an effective user ID equal to the real user ID or effective user ID of the thread identified by pid, or it must possess the CAP_SYS_NICE capability)

priv tweaks

---

src/firejail/main.c

The `join-or-start` option has been broken since 3374e24eb, when that code got out of sync with the new `read_pid` approach to handling sandbox names.
This pair of patches
1. Separates the validation of the existence of a named sandbox out of `read_pid` into `require_pid`
2. Updates all old `read_pid` calls to the new `require_pid` function.
3. Re-enables the `join-or-start` option, using the non-validating `read_pid` function.

Re-enable join-or-start

---

etc/unzip.profile

Without granting access to `${HOME}/.local/share/gnome-shell` unzip fails (silently) when updating GNOME Shell extensions. As removing outdated extension(s) prior to unzipping works as expected, this leaves users with crippled extensions.

Allow GNOME Shell integration in unzip

---

etc/gnome-logs.profile

Besides adding `include /etc/firejail/disable-interpreters.inc`, enabling both `private-etc` and `private-lib` (tested with systemd default storage and volatile journal).

add disable-interpreters.inc to gnome-logs

---

etc/gnome-logs.profile

@Fred-Barclay @SkewedZeppelin Did some further testing, especially when using systemd's `volatile` storage (which is stored only in memory, i.e. below /run/log/journal). In that case `machine-id` needs to be added to private-etc, as well as commenting both `nogroups` and `noroot`. Realizing this is not a default setup and the release of 0.9.54 is approaching, it's probably better to not mess with nogroups/noroot now. Perhaps adding `machine-id` to private-etc is not that problematic. Adding a reminder for users who run a volatile storage setup might be doable. Thoughts?

add note for 'volatile' storage support

---

etc/firefox-common.profile

tracelog breaks firefox 60+ catastrophically in my testing

disable tracelog in firefox-common.profile

---

etc/blender.profile
src/firejail/firejail.h
src/firejail/fs.c
src/firejail/fs_whitelist.c

This pull request allows whitelisting of directories under `/sys/module`. It's necessary for Blender to work with AMD graphics cards.
`/sys/module` is blacklisted by default, to keep compatibility with the current version, but its subdirectories can now be whitelisted.
There is also a new version of `blender.profile` making use of those capabilities.

Fixes to make Blender with AMD GPU work under firejail (#1931)

---

etc/slack.profile

This tiny PR adds dictionary access to Slack when launched via firejail. Helps prevent typos when quickly typing on Slack.
I tested this on Debian testing/unstable.

Add dictionary access to Slack

---

etc/evince.profile

Access to `libdjvulibre.so.*` is required for opening DjVu documents.
Otherwise, Evince does open, but fails to load the file with the error: `Failed to load backend for 'image/vnd.djvu+multipage': libdjvulibre.so.21: cannot open shared object file: No such file or directory`

Fix DjVu opening in Evince

---

etc/qmmp.profile

qmmp requires these unzipping programs in order to install skins, so i've added them to private-bin

Fix installing skins on qmmp.profile

---

etc/7za.profile
etc/7zr.profile
etc/p7zip.profile

At least Debian/Ubuntu distro's (and possibly others) carry both `p7zip` and `p7zip-full` packages. Besides `7z` these offer additional commands `7za`, `7zr` and `p7zip`. The redirect profiles offered here to cover these use the same format as used in https://github.com/netblue30/firejail/commit/edfefbe194ea0ff7a8fa9939e0dece61bea9ca5b and https://github.com/netblue30/firejail/pull/2010 (avoiding inclusion of globals.local more than once).

7z redirect profiles

---

etc/7z.profile
etc/gzip.profile
etc/less.profile
etc/strings.profile
etc/tar.profile
etc/unrar.profile
etc/unzip.profile
etc/uudeview.profile
etc/xzdec.profile

Similar to https://github.com/netblue30/firejail/issues/2006. This time we avoid including globals.local twice in profiles that include default.profile.

don't include globals.local twice (take two)

---

etc/2048-qt.profile
etc/Fritzing.profile
etc/android-studio.profile
etc/aosp.profile
etc/apktool.profile
etc/arch-audit.profile
etc/archaudit-report.profile
etc/disable-xdg.inc
etc/gnome-books.profile
etc/gnome-calculator.profile
etc/gnome-chess.profile
etc/gnome-clocks.profile
etc/gnome-contacts.profile
etc/gnome-documents.profile
etc/gnome-font-viewer.profile
etc/gnome-logs.profile
etc/gnome-maps.profile
etc/gnome-weather.profile

Now that @chiraag-nataraj added support for more XDG user dirs in fff306c991ff1f33ccb56313e4c166a169555656, we can blacklist these in many profiles that don't utilize whitelist.
I created a disable-xdg.inc. Downloads and Desktop are commented as they are usually a catch-all for most people.
And I included it in a small amount of profiles identified using the following command:
```
grep "disable-xdg" -RL $(grep 'whitelist \$' -RL $(grep "redirect" . -RiL))
```
there are still ~270 remaining, and strong discretion is needed, so I figured I'd get some discussion going before I went at it. Feel free to push to the branch at will.

WIP: Add new disable-xdg.inc

---

etc/evince.profile

Upon testing evince, I figured out dbus may not be needed and my printer is still working.
In the initial commit 7a37dc31ab907d55eb88f2fa259f37046952a0c5 or issue #1843 
there is reasoning, however the profile still works for me.
The current apparmor profile does use dbus.
Upon use I found no side effects crashing the app when dbus was disabled.

hardening evince, dbus not needed

---

src/firejail/util.c

This fixes #2045, which might be used to trick firejail into not auto-detecting a profile or auto-detecting the wrong profile.

FIX-2045: Fix command name parsing for program paths with spaces.

---

src/lib/pid.c

Firejail should look for processes with names exactly named "firejail" to avoid accounting for processes with a "firejail" prefix.  For example, I have a script named `firejail-bridged.sh` which forks a `firejail` child.  When it is running, `firejail --list` shows the script rather than the child firejail process and `firejail --tree` shows the process tree for the script and all its subprocesses.

Fix incorrect --list and --tree output under certain circumstances

---

etc/authenticator.profile
etc/disable-programs.inc
src/firecfg/firecfg.config

Not sure how/when the GNOME filenaming guru's came up with something so ugly (personal opinion), but that's the actual name of the .desktop file (https://gitlab.gnome.org/World/Authenticator/blob/master/data/com.github.bilelmoussaoui.Authenticator.desktop.in)...
Side-note: personally I don't use `firecfg`, but I assume the list entree should be pointing to the program's .desktop file... may need a double-check from someone that does use it.
Regards.

Authenticator

---

src/firejail/bandwidth.c
src/firejail/firejail.h
src/firejail/fs_trace.c
src/firejail/main.c
src/firejail/output.c
src/firejail/preproc.c

These changes allow firejail to always be able to find and run its helper libraries even when they are installed in a location that would otherwise be inaccessible in the sandbox (eg. under `${HOME}` or `/media` when `disable-mnt` is enabled), which fixes #2148.  The basic idea behind the implementation is to first unshare firejail's mount namespace and make all mounts private.  Then early on we bind-mount `LIBDIR`, where the helpers programs are actually stored, to `/run/firejail/lib` and have all the helpers be run from there.
Despite there being a fair amount of lines to the changeset, the magic really happens in only a few lines.  The unsharing of the mount namespace and making mounts private happens in `src/firejail/main.c` line 883-886, and the bind-mount of `LIBDIR` in …

Fix issue #2148: Make sure firejail can find helper programs in sandbox regardless of options.

---

src/firejail/join.c

This PR changes the behavior of --join command, making it return the exit code of the invoked program.
```
pawel@azath:~$ firejail --join=test exit 123
Switching to pid 10387, the first child process inside the sandbox
Warning: cleaning all supplementary groups
Child process initialized in 45.88 ms
pawel@azath:~$ echo $?
123
```

Make --join return exit code of the invoked program

---

src/firejail/fs_trace.c

This got broken in pq #2190, which partially reverted #2186.

The path in ld.so.preload should point to RUN_FIREJAIL_LIB_DIR, as LIBDIR may not exist.

---

src/man/firejail.txt

I'm not sure the list is 100% accurate now, but at least its closer to 100%.

Fix docs to more correctly list the syscalls in the @default seccomp group.

---

src/firejail/sandbox.c

Do not override user provided seccomp lists when in chroot/overlay/appimage, but to use the default if none is provided.  This is a more general fix.  I see no reason we are forcing users to use a default seccomp filter with those options.  There should be a default if no seccomp filter is provided, but if one is provided, it should not be ignored in favor of the default.  This allows the firefox appimage to work, because its sandboxing need chroot, which is disabled in the @default seccomp filter (see #2142).

Fix #2142: Firefox appimage fails because it needs non-default seccomp

---

etc/git.profile

[Oh My Zsh](https://ohmyz.sh/) is installed to `${HOME}/.oh-my-zsh` by default. Installation and upgrading use `git` and will fail if it gets sandboxed (since commit 6b84a6a9e82affa460e46790da542dbf3b1b84f9):
```
$ upgrade_oh_my_zsh
Updating Oh My Zsh
error: cannot open .git/FETCH_HEAD: Read-only file system
There was an error updating. Try again later?
```
[Topgrade](https://github.com/r-darwish/topgrade) and anything or anyone else trying to upgrade Oh My Zsh using a sandboxed `git` will encounter the same error.
Disabling blacklisting of the default Oh My Zsh installation directory for the `git` profile fixes this.

git.profile: Disable blacklist for default Oh My Zsh directory

---

etc/firefox-common.profile

As I figured out nodbus may break the streaming experience with Firefox 63.0 on Plasma 5.14.2, Framework 5.51.0
* KDE Connect: Users won't be able to control a stream with KDE Connect anymore
* power management: During a stream the screen may dim or turn off

Expanded the comment about nodbus breaking stuff

---

etc/dig.profile

Moved `quiet` option below the newly added description for consistency.

Add description to dig.profile

---

etc/tar.profile

This fixes https://github.com/netblue30/firejail/issues/2239.

Fix tar.profile on Debian based distributions

---

etc/brackets.profile

The seccomp filter has `vmsplic` instead of `vmsplice`, let's fix that.

Fix typo in brackets.profile

---

etc/mpd.profile

The current mpd profile breaks MPD's music database auto-updating feature. Changing the seccomp option fixes this.

Fix seccomp in mpd.profile

---

src/firejail/main.c

When not using `--` on the command line along with `--appimage`, `extract_command_name` is not run and instead `cfg.command_name` is set and `arg_shell_none` is set to `0`.  This is what one wants when running appimages where the `AppRun` is a shell script (eg. digikam).  However, this logic is not consistently applied when processing the `--` special option.
The effect of this is that using `--` with the digikam appimage and digikam profile fails to run digikam because the digikam profile sets `shell none`.  This can be overcome by adding `ignore=shell`, but that shouldn't be necessary.

Have appimage handling be the same with or with out special -- argument.

---

src/firejail/main.c
src/man/firejail.txt

I ran into this while executing digikam with firejail while in the current directory there was a file named `digikam`.  So firejail was trying to read that file as a profile file.  This patch would allow me to use `--profile=:digikam` to force digikam to do a profile search instead of looking in the current directory for profiles.

Allow prefixing colon to profile argument of --profile to for a profile search

---

etc/evince.profile

Evince 3.30.1 on Ubuntu 18.10 fails to open with the following error unless `private-etc machine-id` is allowed:
```
dbus[194]: D-Bus library appears to be incorrectly set up: see the manual page for dbus-uuidgen to correct this issue. (Failed to open "/var/lib/dbus/machine-id": No such file or directory; Failed to open "/etc/machine-id": No such file or directory)
D-Bus not built with -rdynamic so unable to print a backtrace
```

Fix Evince profile

---

src/firejail/usage.c
src/man/firejail.txt

I've taken a stab at updating the documentation on the `-c` option per the discussion in #2252.  Let me know if its incorrect or should be changed in some way.

Add better documentation for "-c" option.

---

src/firecfg/firecfg.config

ranger is a file manager - https://github.com/netblue30/firejail/issues/1261
vim is often used to edit system files - sandboxing breaks functionality.

removing vim and ranger from firecfg

---

etc/mpv.profile
etc/youtube-dl.profile

allowing local python* in mpv and youtube-dl #2262 .For use with latest youtube-dl installed with pip. Having the latest is very important here.
Maybe others are using it? grep only gives these two.

allowing local python* in mpv and youtube-dl #2262

---

etc/gnome-mpv.profile

like the title says. Allowing youtube-dl.

allowing youtube-dl and python in gnome-mpv

---

src/firejail/firejail.h
src/firejail/fs.c
src/man/firejail.txt

has the immediate benefit that the result of combining `--noexec` and `--tmpfs` does not depend on the sequence of the options.

refactor private-cache and tmpfs

---

etc/bibletime.profile

Fix: bibletime don't starts on Fedora and Arch if `seccomp` and `tracelog` are used.

Fix bibletime.profile

---

etc/disable-programs.inc
etc/supertuxkart.profile
src/firecfg/firecfg.config

Add a new profile for supertuxkart (STK), add STK directories in $HOME to `disable-programms.inc` and enable STK for firecfg.
This profile is still under development and may be too strict under some distributions.
Tested:

New profile for supertuxkart.

---

src/firejail/main.c
src/firejail/sandbox.c
src/firejail/seccomp.c
src/man/firejail.txt

Currently users are always able to specify a seccomp filter of their choosing, including for chroot, appimage and overlay sandboxes. For example, Firejail allows me to do something like:
`firejail --noprofile --chroot=/somedir --seccomp.drop=merry,christmas`
Since the requirement for seccomp looks more or less obsolete now, this PR proposes to remove it entirely and replace it with an explicit nonewprivs enforcement.
There is no security benefit (or harm, AFAICT) in this. It is only about the streamlining of requirements and keeping things easy to explain. While I would regard the patch as ready for merging, I was also hoping to inspire an exchange if it is actually heading in the right direction.
Cheers!

enforce nonewprivs instead of seccomp for chroot sandboxes

---

src/firejail/arp.c
src/fnet/arp.c

Kernel commit [99137b7](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=99137b7888f4058087895d035d81c6b2d31015c5) introduced an additional check of the address
length. This exposed a bug in the arp code where the address length was
being set incorrectly.
Now the length is set from the `ETH_ALEN` constant declared in
`linux/if_ether.h`.
This fixes #2314

Correctly set address length in arp frames

---

etc/gnome-maps.profile

Without `noblacklist ${HOME}/.local/share/flatpak` gnome-maps not start on Fedora 29.

Fix gnome-maps

---

etc/audacious.profile
etc/spotify.profile
etc/vlc.profile

MPRIS is a D-Bus interface for controlling media players. The nodbus
option prevents these players from being controlled through MPRIS.
It seems that most of the other media players did not have the nodbus
option or it was already commented out.

remove nodbus from MPRIS client profiles

---

etc/celluloid.profile
etc/disable-programs.inc
etc/gnome-mpv.profile
src/firecfg/firecfg.config

gnome-mpv has renamed to celluloid. (https://www.omgubuntu.co.uk/2019/01/celluloid-new-name-for-gnome-mpv)

gnome-mpv -> celluloid

---

etc/mpDris2.profile

A few extra items are needed in private-lib on Debian/Ubuntu.

Fix mpDris2 for Debian/Ubuntu

---

etc/pavucontrol.profile
etc/regextester.profile

No need to use /usr/lib prefix in private-lib.

Fix private-lib in regextester profile

---

etc/disable-programs.inc
etc/gnome-schedule.profile
src/firecfg/firecfg.config

I'll leave this unmerged for now until someone reviews the profile. Was'nt sure this is the way to properly whitelist a terminal (which the app needs for testing user cron job execution).

Add new profile for gnome-schedule

---

etc/pavucontrol.profile

```
...
mkfile ${HOME}/.config/pavucontrol.ini
whitelist ${HOME}/.config/pavucontrol.ini
include whitelist-common.inc
...
```
pavucontrol pops an error window with the message:
Error writing config file %s/home/glitsj16/.config/pavucontrol.ini: Bad state
Taking out those options fixes things.

Fix pavucontrol

---

etc/sqlitebrowser.profile

The profile crippled working (securely) with remote databases. That is now working as expected. Also, `memory-deny-write-execute` is no longer breaking on Arch, tested with recent [mdwx: block memfd_create](https://github.com/netblue30/firejail/commit/59e30614ad1cd7a8d6f3c685472fada37d1ed2d7) introduction.

Hardening and added network functionality in sqlitebrowser.profile

---

etc/patch.profile
etc/strings.profile
etc/tar.profile

As per discussion in https://github.com/netblue30/firejail/issues/2507, there are a few profiles that could benefit from adding `libfakeroot` to `private-lib` for the Arch `makepkg` routine. This PR fixes this for `patch`, `strings` and `tar` (file was already covered).

Add fakeroot support for makepkg on Arch

---

etc/code-oss.profile

Adds a profile alias for `code-oss`, which is the open-source build of Visual Studio Code from the official Arch community repository.

Add code-oss profile

---

etc/code.profile

Adds the `code-oss` config directory to the `noblacklist` list. I'm guessing this makes sense to add here since `${HOME}/.vscode-oss` has already been added. Sorry I missed this in #2539

Add code-oss config directory

---

etc/clawsker.profile

Some distributions still ship older GTK2 versions of clawsker. Let's support those too.

Fix clawsker for older GTK2 versions

---

etc/d-feet.profile

Some distributions ship d-feet with python2. Let's support those too.

Fixes for d-feet

---

etc/viewnior.profile

error message:
> Cannot open display: 
> Run 'viewnior --help' to see a full list of available command line options.
> monitoring pid 10
> 
> Sandbox monitor: waitpid 10 retval 10 status 256
> 
> Parent is shutting down, bye...

viewnior is completely broken with 'hostname viewnior'

---

etc/viewnior.profile

After some more back-and-forth with @veloute in https://github.com/netblue30/firejail/pull/2573, the viewnior profile needed to loose ipc-namespace.

Drop ipc-namespace from viewnior.profile

---

etc/acat.profile
etc/adiff.profile
etc/als.profile
etc/apack.profile
etc/arepack.profile
etc/aunpack.profile
etc/bunzip2.profile
etc/gunzip.profile
etc/gzip.profile

This is similar to what happened for https://github.com/netblue30/firejail/issues/2006 and extended in https://github.com/netblue30/firejail/pull/2010. All current profiles checked and fixed as of this PR.

Avoid including globals.local twice

---

src/firejail/main.c

The command was only recognized if it was passed as the first argument.
Passing it on any other position on the command line caused the following
error:
Error: invalid --keep-var-tmp command line option
Supplying it as the first argument also resulted in other commands that are
parsed after it to be silently ignored.

Fix incorrect parsing of --keep-var-tmp command

---

etc/exiftool.profile

i couldn't get private-bin to work with directories, if there is a way, that'd be preferred over commenting out private-bin completely.

exiftool needs access to the /usr/bin/vendor_perl directory in archlinux

---

etc/atool.profile
etc/bsdtar.profile
etc/bunzip2.profile
etc/bzip2.profile
etc/cpio.profile
etc/gzip.profile
etc/tar.profile
src/firecfg/firecfg.config

Incorporating `disable-exec.inc` into main compressor profiles and other hardening.

Hardening compressors

---

etc/seahorse-tool.profile
etc/seahorse.profile

Remove `mkdir` beacause it is not needed anymore since https://github.com/netblue30/firejail/commit/f55071c5f9c349a7bb9af08d2d8d1476341c4bf3.

Fix seahorse.profile seahorse-tool.profile

---

etc/seahorse-daemon.profile
etc/seahorse-tool.profile
etc/seahorse.profile
src/firecfg/firecfg.config

Currently the seahorse{-tool} profiles include gpg.profile, which works fine. IMHO this could be improved upon. This draft attempts to do so by decoupling seahorse{-tool} from the gpg profile and by making seahorse profiles fully whitelist profiles instead.
Comments, opinions, etcetera very welcome.

Seahorse revisited

---

etc/pidgin.profile

Whitelist profile for pidgin should be more secure. Also might fix https://github.com/netblue30/firejail/issues/2550.

Refactor pidgin as whitelist profile

---

src/man/firejail.txt

Section `DESKTOP INTEGRATION`:
- example to make firefox symlink fails without `sudo` (as it needs write access to /usr/local/bin);
- fix the link to man firecfg.

Fixes for man firejail

---

etc/evince.profile

See https://github.com/netblue30/firejail/issues/2621

Add warning about nodbus breaking evince two-page-view on some systems

---

etc/filezilla.profile

perhaps there's another solution, but this is the only fix i could find for fixing --join.
error i get:
```
Switching to pid 13327, the first child process inside the sandbox
Warning: cleaning all supplementary groups
Child process initialized in 10.86 ms
execvp: No such file or directory
```

private-bin breaks --join for filezilla

---

etc/disable-common.inc

Python 2 executes ``~/.pythonrc.py`` when importing the [``user`` module](https://docs.python.org/2/library/user.html).
Users might also source it from the interactive startup file of their Python interpreter or directly point the [``PYTHONSTARTUP`` environment variable](https://docs.python.org/using/cmdline.html#envvar-PYTHONSTARTUP) to it.

Add .pythonrc.py to disable-common.inc

---

etc/evince.profile

Evince uses [libspectre](https://www.freedesktop.org/wiki/Software/libspectre/) as its PostScript backend. Without access to this library, PostScript documents fail to open.

Fix PostScript file opening in Evince

---

etc/smplayer.profile

This PR adds support for playing videos from streaming sites in SMPlayer, when it is set to use `mpv+youtube-dl` in *Options -> Preferences -> Network -> YouTube (and other sites) -> Support for video sites*.
Profile changes are the same as in #2279 for *gnome-mpv*. Not sure why `env` was needed in `private-bin`, because in my setup it looks not necessary. Perhaps it was needed for other distributions or setups, so I added it just in case.
Tested changes in freshly updated Arch Linux with smplayer 19.1.0-1 and firejail 0.9.60-rc1 (custom built using official PKGBUILD where only version number was changed).

SMPlayer: Add support for python and youtube-dl

---

etc/gajim.profile

Gajim will not start without being able to read this file, even if it
doesn't exist.

Gajim: Allow reading of system-wide Flatpak locale

---

etc/disable-programs.inc
etc/enpass.profile

Added support for latest upstream version and refactored enpass.profile as a whitelisting profile.
`Note`: when sandboxing enpass, I couldn't get its companion webextension to work in browsers that already run firejailed. Not sure whether or not this was already the case with Enpass versions pre-dating v6. In all honesty I didn't spend all that much time testing different browsers/extensions as I personally moved to Bitwarden (which has a similar if not larger feature-set, is fully open-source and doesn't suffer from this dysfunctionality). Perhaps someone who actively uses Enpass can confirm all this and add a note to the profile accordingly.

Support Enpass v6

---

contrib/vim/ftdetect/firejail.vim
contrib/vim/syntax/firejail.vim

Hi!
Here are vim syntax and ftdetect files to automatically detect and syntax-highlight firejail profiles in vim.
I built those for myself over the last few days and I feel they are functional enough for a wider audience. :-)
Please note these are my first ever written vim syntax/ftdetect files, so there's likely to be room for improvement. However, they seem to be doing alright with all the profiles I could get my hands on.
Cheers and thanks for making the awesome piece of software that firejail is. :)

Add vim syntax and ftdetect files

---

etc/mumble.profile

Since Mumble 1.3, client data was moved from $HOME/.local/share/data/Mumble to $HOME/.local/share/Mumble.
See https://wiki.mumble.info/wiki/Client_Settings

Mumble: add new path for client data

---

src/firejail/fs.c
src/firejail/fs_home.c
src/firejail/fs_whitelist.c
src/firejail/mountinfo.c
src/firejail/pulseaudio.c
src/firejail/util.c
src/firejail/x11.c

There has been decbe96a48fc21c11349867ff2c1ada7c88a0113 and b65dfff0f3b7ff5a16771ac4eca80d0609cbbf44, but CentOS 6 is an actively maintained distribution, unlike Debian 7.
So I'd propose to bring back the fix.
#2696

glibc missing O_PATH definition on CentOS 6

---

src/firejail/env.c
src/firejail/main.c

Some Firejailed programs end up calling other programs for which a symlink to Firejail is also set up. When the child Firejailed process detects this, it prints on `stderr` a message along the lines of:
Warning: an existing sandbox was detected. /usr/bin/foobar will run without any additional sandboxing features
This breaks the behavior of some programs, which actually capture the standard error of their child process and don't expect to see Firejail output there. Examples include:
* Github's [hub](https://github.com/github/hub): breaks when resolving `git` aliases
* tpope's [vim-fugitive](https://github.com/tpope/vim-fugitive): breaks the `fugitive://` URLs built to view e.g. a commit from a blame window
Using `--quiet` (or `quiet` in the profile) for either the parent Firejailed process …

Propagate --quiet to children Firejail'ed processes

---

src/firejail/dbus.c

Hi,
This PR adds/changes the following behaviors of `nodbus`:
* blacklist `~/.dbus` by default
* fix the overridden value of `DBUS_SESSION_BUS_ADDRESS`
`~/.dbus` is created by `dbus-launch` and contains an environment file that can be sourced by the shell. It sets the values of `DBUS_SESSION_BUS_ADDRESS` and other DBus-related envvars, so that processes spawned by the shell can communicate with the session bus. Blacklisting it removes one way for firejailed programs to find out about the real address of the session bus (though other ways sadly still remain).
As for the overridden value of `DBUS_SESSION_BUS_ADDRESS`, it contained `DBUS_SESSION_BUS_ADDRESS=` itself at the start, which seemed like a mistake.
Hope this is helpful!

nodbus enhancements

---

etc/eo-common.profile
etc/eog.profile
etc/eom.profile

These profiles have mostly identical options, so it might be handy for future changes to refactor both with a common redirect file.

Refactor eog and eom profiles with common redirect

---

etc/gpg.profile
etc/seahorse.profile

The 'shell none' option is no longer causing hangs. Although I can't find the exact PR right now, I'm quite sure something recent solved this. The corresponding comment in seahorse.profile also becomes obsolete.

Re-add 'shell none' to gpg.profile

---

src/firejail/firejail.h
src/firejail/main.c
src/firejail/profile.c
src/firejail/sandbox.c
src/firejail/usage.c
src/man/firejail-profile.txt
src/man/firejail.txt
test/environment/deterministic-exit-code.exp
test/environment/environment.sh

Ensures firejail exits with the first childs exit code regardless of the termination ordering of orphaned children.
Firejail currently exits with the status code of whatever child itself exits last.
This can be non-deterministic if there are any orphaned children that outlive the process firejail launches.
Another patch motivated by [compiler-explorer](https://github.com/mattgodbolt/compiler-explorer).
We care about the exit status of the process we run within firejail.
Some compilers we run potentially spawn and orphan non-critical background tasks, telemetry agents for example.  We don't care if these auxiliary processes exit with an error.  If they do exit with an error *after* the compiler itself exits, we lose the exit status of the compiler. If the compiler exits with an error, and …

Add deterministic-exit-code option

---

etc/gnome-chess.profile

I have hardened the gnome-chess profile a bit, but am not sure if it should be a whitelisting profile. On the one hand gnoem-chess need only to read/write his config, but on the other hand it can save games in *.pgn files where the user choose the location to save.

Harden gnome-chess

---

src/firejail/firejail.h
src/firejail/fs_home.c
src/firejail/main.c
src/firejail/profile.c
src/firejail/sandbox.c
src/firejail/usage.c
src/man/firejail-profile.txt
src/man/firejail.txt
test/fs/fs.sh
test/fs/private-cwd.exp

Main motivating use case for this patch is within [compiler-explorer](https://github.com/mattgodbolt/compiler-explorer).
We want to use relative paths in profile include statements, which requires a specific working directory when launching firejail.
However, we also need to ensure the application *within* firejail runs in another working directory.
`--private-cwd` causes the jail to change to the users home directory
`--private-cwd=/path` causes the jail to change to the specified directory once inside the filesystem namespace of the jail

Add private-cwd option to control working directory within jail

---

etc/templates/profile.template

This replaces the outdated templates from #1734
with new templates from the program used in #2093
Making as a PR, because I know we had concerns with some of these, as commented in #2093.
Since this is a template, and nothing automatic it should be OK, as they should be suggestions to the profile creator and used with discretion.
Feel free to push any changes at will.

template profile: update private-etc templates

---

etc/disable-common.inc

The files holds credentials to WebDAV servers in plaintext
hence it's probably a good idea to limit access to them.

Add davfs2 secrets file to blacklist

---

contrib/syscalls
contrib/syscalls.sh

A little script to determine the necessary syscalls for a program.

Create syscalls file

---

etc/totem.profile

Hello,
In totem (GNOME Videos), Lua is required to play youtube (online?) videos.

Fix youtube video in totem

---

etc/assogiate.profile
etc/evince.profile
etc/gedit.profile
etc/gnome-nettool.profile

In similar vain as https://github.com/netblue30/firejail/pull/2766, but this time for private-lib. The little [gem](https://gist.github.com/rusty-snake/a1010a3daf3c54e93dfe03f2f5ce3d96) from @rusty-snake was easily extended to handle private-lib besides private-bin and private-etc. Might be another nice addition for contrib.

Sort private-lib

---

etc/chromium-common.profile

Unfortunately `nodbus` prevents access to site passwords if they are stored in [GNOME Keyring](https://wiki.gnome.org/Projects/GnomeKeyring). According to [docs](https://chromium.googlesource.com/chromium/src.git/+/master/docs/linux_password_storage.md) chromium can store password in 3 different ways:
- GNOME Keyring
- KWallet 4
- plain text
As KWallet storage may be broken in a same way, using `nodbus` will force chromium to store passwords in plain text which isn't best option for security and for firejail default.

chromium: disable nodbus

---

etc/chromium-common.profile
etc/dnscrypt-proxy.profile
etc/qgis.profile
etc/tor.profile
etc/unbound.profile

Follow-up on https://github.com/netblue30/firejail/pull/2766, https://github.com/netblue30/firejail/pull/2778 and https://github.com/netblue30/firejail/pull/2779. This time caps.{drop,keep} and seccomp.{drop,keep} lines are alphabetically sorted.
Again, all credit goes to @rusty-snake for having started the sorting work and for creating and extending [sort.py](https://gist.github.com/rusty-snake/a1010a3daf3c54e93dfe03f2f5ce3d96). I took the liberty of [building upon his script](https://gist.github.com/glitsj16/5304988cfa7fd2d7f8db2d88cc6e86cf) to account for caps.{drop,keep} and seccomp.{drop,keep}.

Sort caps.keep and seccomp.drop options

---

etc/thunderbird.profile

The current state is not consistent, in that we permit access to the gnupg-agent sockets but disallow
access to the d-bus.
Both of them tear a hole into the sandbox, the question is if the profile should support enigmail out of the box or not (as you could guess from the pull request I'm leaning more to supporting it).

allow nodbus in thunderbird profile

---

etc/ssh-agent.profile
etc/ssh.profile

I've been running a few weeks with `nodbus` added to ssh{,-agent}.profile. No mishaps so far. Obviously SSH has a wide variety of use-cases, of which I personally run only a fraction on a daily basis. Hence the `draft` status, to get more feedback on the topic. Any reason(s) why D-Bus might be required in these profiles?

Tighten SSH with nodbus

---

etc/Discord.profile
etc/DiscordCanary.profile
etc/atom-beta.profile
etc/autokey-gtk.profile
etc/autokey-qt.profile
etc/autokey-run.profile
etc/autokey-shell.profile
etc/chromium-common.profile
etc/cryptocat.profile
etc/discord-canary.profile
etc/discord-common.profile
etc/discord.profile
etc/firefox-common.profile

I missed these in https://github.com/netblue30/firejail/pull/2802. Thanks at @rusty-snake for nudging me about this.
@rusty-snake I didn't fully understand your message in https://github.com/netblue30/firejail/pull/2802. GH hides something that I can read in the email version:
> Great, still need streamlining:
> * atom-beta.profile
> * cryptocat.profile
> * cyberfox.profile
> * discord-canary.profile
> * DiscordCanary.profile
> * discord.profile
> * Discord.profile
> 
> 
> > @@ -16,6 +16,5 @@ whitelist ${HOME}/.mozilla  
>  \# private-etc must first be enabled in firefox-common.profile
> 
> `include globals.local`
If this relates to cyberfox.profile: that redirects to firefox-common.profile, which does not include globals.local (cfr. the comment inside). So I didn't need to touch …

Streamline redirect profiles (follow-up)

---

etc/autokey-common.profile
etc/autokey-gtk.profile
etc/autokey-qt.profile
etc/autokey-run.profile
etc/autokey-shell.profile

This brings the autokey profiles inline with all other redirect profiles. It should help users who use the templates, now that the instructions are correctly implemented (especially from https://github.com/netblue30/firejail/commit/19e8ce46412670172e72cb987f085c770ae5c3ec).

Change include/redirect logic in autokey profiles

---

etc/templates/profile.template
etc/templates/redirect_alias-profile.template

Mostly nitpicks, except including note for #903.

Update wording in templates

---

etc/gconf-editor.profile

https://github.com/glitsj16/firejail/commit/dd0697a8155ff84183ff25eefc84f5eac883315a broke the redirect profile, let's fix that.

Unbreak gconf-editor

---

etc/thunderbird.profile

When clicking a link in an email in Thunderbird, Firefox profile is not loaded. 
This fix add the commented parameters required to load the Firefox profile when the user clicked in an email.

Run firefox with your profile when clicking a link

---

etc/celluloid.profile
etc/disable-programs.inc
etc/mpsyt.profile
etc/mpv.profile
etc/smplayer.profile
etc/youtube-dl.profile

Was there any reason not to handle `${HOME}/.config/youtube-dl` like the rest of the profiles do with application's configuration files?

Add youtube-dl config handling

---

etc/wire-desktop.profile

`electron` has recently been changed on Arch Linux and `wire-desktop` launches with `electron4` now instead of `electron`. This is the new launcher script from the Arch package:
```
#!/usr/bin/env sh
electron4 "/usr/lib/wire-desktop" "$@"
```
This PR adds `electron4` to the `private-bin` declaration to allow the program to successfully launch on Arch.

Add electron4 to allow wire-desktop to launch on Arch Linux

---

src/firejail/appimage.c

This fixes #2842 and can be verified by testing with the Inkscape appimage linked there.  I'll merge in a few days if there are no objections.

Add OWD and ARGV0 environment variables. Correctly create APPIMAGE envvar.

---

src/libtrace/libtrace.c

This fixes #561, which is misnamed.  This issue affects just about any non-trivial shell scripts under firejail.  Its just more obvious with appimage because the vast majority of AppRun programs are shell scripts.
The issue is that the preloaded libtrace library writes log messages to stdout and not directly to the console/tty.  So a bash construct like `FILEPATH=$(readlink -a file)`, will contain the output of `readlink` but also trace log messages for exec, stat, etc.  Thus `FILEPATH` will not just be a file path.  And the process tree then opens `FILEPATH`, which its highly likely to do, a process will try to open with a string that is not a path.
This change has log messages written to `/dev/tty`, which is the tty firejail is run with and the one you'd expect to get output on.  Also, …

Fix issue #561. Refactor/Optimize code to get and use pid and process name.

---

src/firejail/profile.c

When debugging applications inside an IDE regularly, always passing the command line option `--allow-debuggers` becomes cumbersome.
This fix adds a new option `allow-debuggers` to the profile code, so if debugging capabilities are always needed, the profile of the application can simply be extended with that option.

Make 'allow-debuggers' configurable in profiles

---

src/man/firejail-profile.txt

Adds documentation to firejail-profile man page for the new `allow-debuggers` profile option from #2856 as discussed by @SkewedZeppelin  in https://github.com/netblue30/firejail/pull/2856#issuecomment-511560561.

document profile support for allow-debuggers in firejail-profile man page

---

etc/disable-programs.inc
etc/tor-browser.profile
etc/torbrowser-launcher.profile
src/firecfg/firecfg.config

- tor-browser in the AUR is an international package; all other
individual language variants have been removed, so, add new alias
- Add 'tor-browser' and 'mv' to private-bin in launcher profile ('mv' is
required when upgrading tor-browser versions)
- Add 'tor-browser' to firecfg.config
- Add config dir to disable-programs.inc

Add new Tor Browser alias

---

etc/disable-programs.inc
etc/whalebird.profile
src/firecfg/firecfg.config

Program tested to open, connect to a TLS server, open dialog boxes (right-click) and save files using GTK's file chooser, and play sound using PulseAudio.

Add Whalebird profile

---

etc/QOwnNotes.profile

Every time QOwnNotes was started, setup Wizard was shown. Log shown:
`Warning: cannot create xxx.config directory`

Fix QOwnNotes path

---

etc/tb-starter-wrapper.profile

https://forums.whonix.org/t/automatically-firejailing-tor-browser/4767/29
If you make a PR for new profiles or changeing profiles please do the following:
- The ordering of options follow the rules descripted in [/usr/share/doc/firejail/profile.template](https://github.com/netblue30/firejail/blob/master/etc/templates/profile.template).  
> Hint: The profile-template is very new, if you install firejail with your package-manager, it maybe missing, therefore, and to follow the latest rules, it is recommended to use the template from the repository.
- Order the arguments of options alphabetical, you can easy do this with the …

remove x11 xorg

---

etc/Xephyr.profile
etc/Xvfb.profile
etc/dnscrypt-proxy.profile
etc/dnsmasq.profile
etc/ffmpegthumbnailer.profile
etc/ffplay.profile
etc/ffprobe.profile
etc/nano.profile
etc/qt-faststart.profile
etc/rnano.profile
etc/scp.profile
etc/seahorse-daemon.profile
etc/sftp.profile
etc/transmission-create.profile
etc/transmission-edit.profile
etc/transmission-remote-cli.profile
etc/transmission-remote-gtk.profile
etc/xpra.profile

https://github.com/netblue30/firejail/pull/2907 fixed the `quiet` option in archiver redirect profiles, preventing potential output leakage. This PR does the same for other relevant profiles.

Prevent quiet option output leakage

---

etc/torbrowser-launcher.profile

Tor Browser occupies a very interesting space with firejail, as ideally we would not only want to prevent further system compromise, but also to prevent further de-anonymization (beyond your ip address, which I assume is trivially easy to get if Tor Browser is compromised, regardless of firejail).
To aid in this, Tor Browser should not be able to gain access to the name of the user, and the name of the home directory. As such,
`id` can expose user name
`pwd` can expose name of host directory
`readlink` can expose name of host directory
`realpath` can expose name of host directory
should be removed from private-bin.
Ideally, Tor Browser should not be able to access `env` (also can leak user name and name of host directory), but the program will not work if it is removed (cannot access …

tighten private-bin and etc for torbrowser-launcher.profile

---

src/firecfg/main.c

getlogin() is unreliable, see the [manual](http://man7.org/linux/man-pages/man3/getlogin.3.html#BUGS):
> BUGS
>       Unfortunately, it is often rather easy to fool getlogin().  Sometimes
>       it does not work at all, because some program messed up the utmp
>       file.  Often, it gives only the first 8 characters of the login name.
>       The user currently logged in on the controlling terminal of our
>       program need not be the user who started it.  Avoid getlogin() for
>       security-related purposes.
It certainly fails on my systems, making it impossible to use `firecfg` without `sudo` or setting SUDO_USER manually. 
With this PR the process owner's name is returned if SUDO_USER is not in the environment.

get_user() do not use the unreliable getlogin()

---

etc/disable-programs.inc
etc/i2prouter.profile
src/firecfg/firecfg.config

Added an I2P profile.
This was tested with Arch/KDE, installing I2P using the official distro-independent java installer and  Xubuntu, installing I2P using the official PPA. 
This does not support the AUR packages for I2P, as they install it really funky and require root privileges to run I2P. Didn't see the point of supporting that when there is an official distro-independent java installer, that only requires normal user privileges to run I2P.
Was not able to create a private-bin for I2P, unfortunately. I'm sure it is possible, but it uses a java wrapper shell script to start I2P, and I thought I copied all the necessary binaries to get it running, but no luck. Are there some debugging tools for firejail that simplifies the process of creating a private-bin?
By default, after starting …

Profiles: add I2P

---

etc/qpdfview.profile

I can confirm https://github.com/netblue30/firejail/pull/2837#issuecomment-511334363 when opening a file from `pcmanfm`, it doesn't open if qpdfview contains `nodbus`

qpdfview: Fix issue when opening a file from file manager

---

src/common.mk.in
src/fbuilder/build_profile.c
src/firejail/firejail.h
src/firejail/fs_trace.c
src/firejail/main.c
src/include/rundefs.h
src/libtrace/libtrace.c
src/man/firejail.txt

@netblue30 
Per @smitsohu's suggestion, I've fixed the `--build` option to work with fix for `--trace`.  This actually was a little more involved because the builder parses the trace output to build an rough profile.  Since `--trace` outputs to console now and not `stdout`, the output would be harder to capture.  So I've allowed `--trace` to accept an optional parameter which is a path to the trace log file.  Now the builder logs to a logfile and parses that log file. This is actually better than before, where program, firejail debug, and trace output were all combined together.
One part I'm slightly concerned with is that `--output` has code that has a bit of validation on the given path and then pipes `ftee` to capture the output.  Is the usage of `ftee` just to make sure all the output …

Fix profile builder

---

etc/w3m.profile

Including disable-interpreters.inc consistently prevents the help screen from loading within w3m.

Removed disable-interpreters.inc from w3m.profile

---

etc/steam.profile

With the default steam profile, steam runs fine, but several games (all running via proton) do not open or open to a black screen. Checking `journalctl`, each segfaulted with firejail reporting they tried to access syscall 101, which is `ptrace`.
Games: Twilight Struggle, ZeroK, Supreme Commander 2
Adding `seccomp !ptrace` or `allow-debuggers` seemed to fix the problem, and now the games run fine.
I added `allow-debuggers` to the profile, as I think that was the preferred method of allowing `ptrace`, but I can change it to `seccomp !ptrace` instead.
Just checked now, and seems like other people are having this problem: [Issue 2860](https://github.com/netblue30/firejail/issues/2860)

Add allow-debuggers to steam.profile

---

etc/keepassxc.profile

nodbus also breaks the (minimize to-) system tray feature of KeePassXC. Users should be aware of that.

KeePassXC: Added a warning regarding tray icon

---

etc/eom.profile
etc/firefox.profile
etc/meld.profile

Some fixes for #2972. @rusty-snake Apologies for not responding earlier to your excellent work with wusc, been a bit hectic on the personal front...

Wusc fixes

---

etc/firefox-common.profile

After installing a notification daemon yesterday, I realized that `nodus` in the `firefox-common.profile` also breaks native notifications.
So I extended the comment to mention that, so that users have an easier time discovering this issue in the future.

Add Comment Mentioning that `nodbus` Breaks Native Notifications

---

etc/checkbashisms.profile
etc/clawsker.profile
etc/conplay.profile
etc/exiftool.profile
etc/spectre-meltdown-checker.profile

These were overlooked previously. If someone could confirm /usr/share/perl5 is the correct path on Fedora that would be nice.

Wusc fixes for profiles allowing perl

---

etc/ssh.profile

nc is currently disallowed in the ssh profile.
I think it could be allowed by default, as it can not only be used for tor, but has more general uses (see ProxyCommand in ssh_config(5)). And I think it's also not harmful to allow it.
Not blacklisting nc would allow a smoother out-of-the-box experience for tor users that use nc in ProxyCommand.
But I'm interested in other opinions if it's a sensible change, or if the profile should be kept more closed.

RFC: profiles: allow nc in ssh profile by default

---

etc/ffmpeg.profile

Fix broken libx265 encoding (needs the set_mempolicy syscall).

Fix profile: ffmpeg

---

etc/brave.profile
etc/disable-common.inc
src/firejail/fs.c

**IMPORTANT**: leave this unmerged until collaborators have had ample opportunity to review.
This is a tentative fix for #2944. The patch enables using `noblacklist /proc/config.gz` in `/etc/firejail/brave.profile`. Momentarily this is only needed for that one profile, so I'm not entirely convinced this is the best way to fix #2914. Thoughts?

Fix Brave's native sandbox

---

etc/firejail.config
src/firejail/caps.c
src/firejail/checkcfg.c
src/firejail/cpu.c
src/firejail/firejail.h
src/firejail/join.c
src/firejail/ls.c
src/firejail/network_main.c
src/firejail/protocol.c
src/firejail/sandbox.c
src/firejail/seccomp.c
src/firejail/util.c

per this patch, firejail tries for 5 seconds to join a sandbox, and only then exits with an error. I'm not sure if the defaults are chosen wisely, you may want to adjust both the default timeout and the frequency of the checks (every 100 msec currently)
see #2139

add join timeout and make it configurable

---

src/firecfg/firecfg.config

More research/testing is needed to make CLI-based archivers work with makepkg on Arch (based distributions). See ongoing discussion in #3095.

Drop CLI archivers from firecfg

---

etc/barrier.profile
etc/disable-programs.inc
src/firecfg/firecfg.config

Barrier is a keyboard and mouse sharing application that can be used across multiple networked computers. Here is a profile for it. 
I tried to make a whitelist for it but it was taking a huge amount of time. So here it is as a blacklist. It needs dbus, netlink, and doesn't work with a private /etc or private binary.

Add barrier profile

---

etc/torbrowser-launcher.profile

The `start-tor-browser` script tries to run `/usr/bin/id` to check that
it isn't root before starting the browser. See
https://gitweb.torproject.org/builders/tor-browser-build.git/tree/projects/tor-browser/RelativeLink/start-tor-browser?id=41fd236bbb7d3d75a27473f927be31f7dd8fdc99#n94
If `id` is not in the `private-bin` directory, the test still works by
accident, but prints these error messages:
```
./Browser/start-tor-browser: line 94: id: command not found
./Browser/start-tor-browser: line 94: [: : integer expression expected
```
Add `id` to the `private-bin` directory to make it run as intended.

Allow Tor Browser to run /usr/bin/id

---

etc/hexchat.profile

Hexchat can play sounds for notifications or other events. It makes sense to allow it to play them.
Cheers!

Allow sound for hexchat

---

src/firejail/dhcp.c
src/firejail/firejail.h
src/firejail/fs_hostname.c
src/firejail/main.c
src/firejail/network_main.c
src/firejail/profile.c
src/firejail/sandbox.c
src/firejail/sbox.c
src/fnet/fnet.h
src/fnet/interface.c
src/fnet/main.c
src/include/rundefs.h

As per my issue in #3026, I was trying to use DHCP to configure network interfaces in firejail. This patch implements integration with the ISC dhclient for both IPv4 and IPv6.
I left the commits as-is so that they can be reviewed individually, but I can squash them if that is preferred.
* Added the options `--ip=dhcp` and `--ip6=dhcp` for IPv4 and IPv6 configuration by DHCP.
* `--ip=dhcp` is handled similarly to `--ip=none`. In particular, firejail does not do any network configuration on its own, not even setting up routing.
* dhclient is invoked in forking mode. Its main process exits when it successfully acquired a lease, while the daemon keeps running in the background. This ensures that firejail only proceeds when the network is working inside the container (running dhclient as a …

DHCP client support

---

etc/cmus.profile

DNS resolution is useful in case streams are referenced by DNS.

cmus: allow access to resolv.conf

---

etc/anki.profile
etc/digikam.profile
etc/musescore.profile
etc/psi-plus.profile
etc/quassel.profile

If unprivileged user namespaces are enabled, [QtWebengine](https://doc.qt.io/qt-5/qtwebengine-overview.html) needs chroot to set up its own sandbox. We adapted a number of profiles already, see for instance the Qutebrowser, Akregator, Bibletime, Calibre, Falkon or Kmail profiles.
This pull request adds the same exception to the Anki, Digikam, MuseScore, Psi+ and Quassel profiles. Note that this is mostly untested, and based only on [reverse dependencies](https://www.archlinux.org/packages/extra/x86_64/qt5-webengine) in Arch and some coarse understanding of the use of QtWebengine in respective apps.
fixes #3124

allow chroot syscall where apps depend on QtWebengine

---

etc/aria2c.profile
etc/disable-programs.inc

Until now we only supported the legacy ${HOME}/.aria2 path. Let's include support for ${HOME}/.config/aria2 too (cfr. https://aria2.github.io/manual/en/html/aria2c.html#files). Fixes https://github.com/netblue30/firejail/issues/3142.
Additionally add a comment to inform users that have [custom event hooks](https://aria2.github.io/manual/en/html/aria2c.html#event-hook) to add these to private-bin.

aria2c fixes

---

etc/i2prouter.profile
src/firecfg/firecfg.config

- Added some networking options to private-etc copied from firefox-common, as I2P wasn't able to reseed, leading to it being unable to bootstrap into the I2P network.
- Removed from firecfg, as it only works if using the ubuntu PPA, but not if using the distro-independent java installer, or the AUR file. I2P also is manually started on the command line in any case, there is no desktop file, so it doesn't really make sense to have a firecfg entry anyways.
- Edited the comments to make them more clear.
- As of now, I2P only officially supports using openJDK 8 and 9, but in the interests of "future-proofing" I added some extra java versions.

Update i2prouter profile, and remove from firecfg

---

etc/standardnotes-desktop.profile

To fix:
```shell
$ firejail --profile=/etc/firejail/standardnotes-desktop.profile /usr/bin/standardnotes-desktop
Reading profile /etc/firejail/standardnotes-desktop.profile
Reading profile /etc/firejail/standardnotes-desktop.local
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 292648, child pid 292675
Warning: skipping alternatives for private /etc
Warning: skipping crypto-policies for private /etc
Warning: skipping pki for private /etc
Private /etc installed in 47.93 ms …
```

Fix missing lib libmfx.so.1 (standardnotes-desktop)

---

etc/transmission-daemon.profile

Reported at: https://bugs.debian.org/948993

profiles: whitelist transmission-daemon config directory

---

etc/audio-recorder.profile
etc/ddgtk.profile
etc/dnscrypt-proxy.profile
etc/gconf-editor.profile
etc/seahorse.profile

We need to support both X11 and Wayland by default in GUI applications. See discussion in https://github.com/netblue30/firejail/commit/dead61dd2447a9583af8a0d240a4520aa692c79d.

fixes for 'blacklist ${RUNUSER}/wayland-*'

---

etc/whitelist-usr-share-common.inc

Fixes #3171 by adding `/usr/share/icu` (http://site.icu-project.org/) to whitelist-usr-share-common.profile.

Fix firefox (#3171)

---

etc/thunderbird.profile

- ~remove `include firefox-common.profile`; make standalone profile~
- enable wusc; **need some test users**
- add disable-passwdmgr.inc and disable-xdg.inc, novideo.
- reorder
- improve some other deficit
---
**Tested:**
Arch:
Debian:
Fedora:

Rework thunderbird.profile

---

etc/gimp.profile

Allow mbind syscall for GIMP

---

etc/allow-gjs.inc
etc/disable-interpreters.inc
etc/gjs.profile
etc/gnome-books.profile
etc/gnome-characters.profile
etc/gnome-documents.profile
etc/gnome-maps.profile
etc/gnome-sound-recorder.profile
etc/gnome-weather.profile
etc/polari.profile
etc/templates/profile.template

TODO: reverse dependencies check on more distros (actually only Fedora).

blacklist gjs in disable-interpreters

---

etc/disable-common.inc

This PR blacklists openrc path that could be used to identify running services out of the sandbox, which could be used for information gathering.

Blacklisting openrc paths by defaults

---

etc/meld.profile

This is just a suggestion relating to the discussion on dropping support for python2 in https://github.com/netblue30/firejail/issues/3164.

clarify dropping python2 support in meld.profile

---

src/firejail/dhcp.c
src/firejail/firejail.h
src/firejail/fs_hostname.c
src/firejail/main.c
src/firejail/network_main.c
src/firejail/profile.c
src/firejail/sandbox.c
src/firejail/sbox.c
src/firejail/usage.c
src/fnet/interface.c
src/include/rundefs.h
src/man/firejail-profile.txt
src/man/firejail.txt

I finally had some time to fix up my implementation for DHCP client support. Sorry for the delay!
* Unfortunately, I used spaces instead of tabs for my code in #3102  (I messed up something in Emacs, I think), which resulted in inconsistent indentation at least on GIthub. My first commit replaces the spaces with tabs, however, it does mess up `git blame` output a bit, so it is debatable whether we should merge it.
* I fixed the unsigned comparison warning in #3174 that made the build fail due to `-Werror`.
* Updated documentation (usage, firejail(1) and firejail-profile(5) manpages) with the new options.
By the way, there seem to be some differences between default CFLAGS produces by `./configure` on my machine and on Travis. ~Compiling with `-Wall -Wextra -Werror` seems prudent, but does …

DHCP client code quality fixes

---

etc/zathura.profile

After seeing #3192 it seemed the zathura profile could be hardened considerably. I've tested this PR on Arch Linux and will be asking OP of #3192 to do the same. Additional input is always welcome as this was the first time I used zathura so there might be omissions.

updates for zathura.profile

---

etc/devhelp.profile
etc/evince.profile
etc/firefox.profile
etc/yelp.profile
etc/zathura.profile

It contains documentation and example files for installed programs and libraries.
I'm not sure if it should be allowed here globally, or in individual profiles, where it makes sense.
(For example in browsers, which are often used for reading documentation from there.)
Reported at: https://bugs.debian.org/950007

profiles: whitelist /usr/share/doc

---

src/firejail/macros.c

provide feedback about why a filename was rejected; see issue #3001

print rejected character in invalid filenames

---

etc/aria2c.profile
etc/clawsker.profile
etc/conky.profile
etc/dconf-editor.profile
etc/dconf.profile
etc/exiftool.profile
etc/font-manager.profile
etc/gconf.profile
etc/git.profile
etc/gjs.profile
etc/gpg.profile
etc/img2txt.profile
etc/mediainfo.profile
etc/mpd.profile
etc/nitroshare.profile
etc/ocenaudio.profile
etc/ping.profile
etc/simple-scan.profile
etc/simplescreenrecorder.profile
etc/sysprof.profile
etc/tshark.profile
etc/uget-gtk.profile
etc/viewnior.profile
etc/weechat.profile

Adding 'include whitelist-var-common.profile' to more profiles. Inspired by discussion in #3189 to avoid potential data sharing via /var.

include wvc to more profiles

---

etc/okular.profile
etc/whitelist-usr-share-common.inc

Some distributions include fonts in the `/usr/share/texmf` and `/usr/share/texlive`. This makes those fonts accessible, addressing buggy behavior in okular where some text fails to render.
This also whitelists `/usr/share/config.kcfg` which, on Debian, contains some default settings.

Whitelist more /usr/share for okular and others

---

etc/firejail-default

With AppArmor enabled and the `firejail-default` profile, execution is not allowed from `/usr/libexec`. On my machine (Gentoo), Git stores its helpers in `/usr/libexec/git-core/`, so Firejail's `git.profile` (which has AppArmor enabled) prevents it from executing these helpers (which are needed for e.g. cloning a repo over HTTPS).
This PR adds `/usr/libexec` and friends to the paths where execution is allowed in Firejail's AppArmor profile.

Allow exec from /usr/libexec & co. with AppArmor

---

etc/disable-programs.inc
etc/teams.profile
src/firecfg/firecfg.config

Based on the existing teams-for-linux profile here's the profile which matches with Microsoft's official Teams application for Linux.
Currently I had to disable private-bin and private-etc because of immediate crashes after start but it's worth having it in the repo nevertheless so others can contribute to that profile to enhance it if someone come up with the fix for private-bin and private-etc.

Add profile for offical Linux Teams application

---

src/firejail/dhcp.c

In order to avoid picking up some random executable from `$PATH` and potentially running it root privileges, `dhcp.c` should check for `/sbin/dhclient` or `/usr/sbin/dhclient` directly. This might cause problems on distributions where `dhclient` is located elsewhere, but as far as I know, `/sbin` is the default location (and even Arch, which uses only `/usr/bin`, symlinks `/sbin` to `/usr/bin`). This is the same approach that `netfilter.c` takes when running `iptables-restore`.
I formulated the check for root privileges according to https://github.com/netblue30/firejail/blob/master/src/firejail/x11.c#L1103, which allows the binary to either be owned by root, or the root group. A more paranoid version would use `open`, `fstat` and `fexecve` to make sure ownership of the binary does not …

Harden dhcp by checking for /sbin/dhclient

---

src/firejail/dhcp.c
src/firejail/sbox.c

Based on the discussion in #3239, this patch aims to make `sbox_run` less likely to execute malicious binaries as root.
* The `execvp` call is replaces with `fexecve`, which does not perform PATH resolution. Because the environment was already cleared, this already wasn't a serious problem. But now, by passing absolute paths only to sbox_run, we get a bit more control.
* We check the binary to be owned by root (either the user or the group) and not be world-writable. As we are running system utilities, not having these would indicate a serious and dangerous misconfiguration, or some kind of an attack.
* The use of `open` with `O_PATH` and `fexecve` prevents TOCTOU errors with the permission check. This prevents a situation when the containing folder is somehow owned by a normal user …

Harden sbox_run by using fexecve instead of execvp

---

etc/allow-lua.inc
etc/disable-interpreters.inc
etc/mpv.profile

On Arch mpv needs access to lua:
```
$ pacman -Q mpv
mpv 1:0.32.0-1
$ firejail /usr/bin/mpv ~/Downloads/video.mp4
/usr/bin/mpv: error while loading shared libraries: liblua5.2.so.5.2: cannot open shared object file: Permission denied
```
On a side-note, Python support (enabled in the mpv profile) doesn't seem to be needed, at least not on Arch. Need to check on a Ubuntu machine to confirm.

add lua support for mpv

---

README.md
RELNOTES
etc/xournal.profile
src/firecfg/firecfg.config

xournal is a funny document editor that can do overlay edits on PDFs.  It is meant as a diary/journal note taking app.  It turns out it is a great app for overlaying images of signatures onto PDF contracts.  Since it means editing PDFs from outside sources, it should be firejailed.  Also, it needs very little access to work.
I'm new to this, so I didn't attempt _private-lib_ at all.  This should probably have a custom _private-lib_ entry.

add xournal.profile

---

etc/firefox.profile
etc/thunderbird.profile

Not whitelisting these directories causes firefox to not apply some settings on startup (e.g. it asks whether it should be default browser).
(See also: https://bugs.debian.org/948656)

profiles: whitelist firefox/thunderbird default directories

---

etc/zoom.profile

The zoom SSO workflow launches an embedded sandboxed browser
(QtWebEngineProcess) which requires chroot and netlink to work.
Fixes #3272

zoom.profile: fix zoom SSO workflow

---

src/firejail/firejail.h
src/firejail/fs.c

Harden `noexec`, `read-only`, `read-write` options by moving entirely to file descriptor based mounts.
Along the way fix long-time broken `writable-var-log` option, which didn't work any more because of an ownership check.

remount hardening: move to file descriptor based mounts

---

src/firejail/x11.c

First, thanks for making firejail available.  It is outstanding.
I use a number of different private directories, and wanted some kind of visual indication of which private directory was being used by each instance of a running firefox.  This PR adds this information to the window title when xpra is being used.  I find this to be very valuable for me, and maybe others will as well.
This PR may be related to at least some of this prior issues (in no particular order):
https://github.com/netblue30/firejail/issues/1983
https://github.com/netblue30/firejail/issues/1350
https://github.com/netblue30/firejail/issues/1308
https://github.com/netblue30/firejail/issues/281
https://github.com/netblue30/firejail/issues/303
https://github.com/netblue30/firejail/issues/424 …

add name or private directory being used to the window title when xpra is being used

---

src/fsec-print/print.c

Since target addresses for other (conditional) jumps are in hex, it's
very confusing to have one jump address in decimal.

fsec-print: print address of BPF_JA jump in hex

---

etc/discord-common.profile

BetterDiscord is a nice utility that allows direct modifications to Discord if the user wishes so. To make it work, dirs in .config and .local/share need to be whitelisted.
Signed-off-by: Atrate <Atrate@protonmail.com>

Added compatibility with BetterDiscord

---

etc/steam.profile

`noblacklist` directives prevent following ones from blacklisting the specified directory/file.
The profile currently has a `noblacklist` directive for each directory used by Steam and/or its games, which is fine.
However, there are no directives blacklisting the user's home, thus all directories and files inside it are accessible by Steam.
This pull request fixes the issue by adding `whitelist` directives, which automatically blacklist the parent directory (in this case the user's home).
`mkdir` and `mkfile` directives are added so that the directories/files are created if they don't exist.
Thanks to @SkewedZeppelin for suggesting to keep `noblacklist` and use `mkdir` and `mkfile`.

steam.profile: correctly blacklist unneeded directories in user's home

---

Makefile.in
mketc.sh

- replaing 'include /etc/firejail/foobar.inc' with
'include $(sysconfdir)/firejail/foobar.inc' is useless since 0.9.58
- onetime calling install with globbing is faster the a loop calling
install nearly 1000 times

Speedup the buildsystem

---

src/firejail/firejail.h
src/firejail/main.c

Restrict number of program arguments and their length as well as
number of environment variables and their length.

Simple sanity checks for arguments and environment

---

RELNOTES
etc/firejail.config
src/firejail/checkcfg.c
src/firejail/firejail.h
src/firejail/main.c
src/firejail/profile.c
src/firejail/sandbox.c
src/firejail/sbox.c
src/firejail/seccomp.c
src/firejail/usage.c
src/fsec-print/main.c
src/fseccomp/main.c
src/fseccomp/seccomp.c
src/fseccomp/seccomp_file.c
src/fseccomp/seccomp_secondary.c
src/include/seccomp.h
src/include/syscall.h
src/lib/syscall.c
src/man/firejail-profile.txt
src/man/firejail.txt

Let user specify the action when seccomp filters trigger:
- 'kill' (default): kill the process as before
- errno name like EPERM/ENOSYS: return errno and let the process continue.
Not killing the process weakens Firejail slightly when trying to
contain intrusion, but it may also allow tighter filters if the
alternative is to always allow a system call. It's still possible to
use errno return per syscall.

Changeable seccomp error action

---

src/firejail/dbus.c
src/firejail/firejail.h
src/firejail/fs.c
src/firejail/main.c
src/firejail/preproc.c
src/firejail/profile.c
src/firejail/sandbox.c
src/firejail/sbox.c
src/firejail/usage.c
src/include/rundefs.h
src/man/firejail-profile.txt
src/man/firejail.txt

This PR adds the `dbus-user` and `dbus-system` options to individually control access to the session and system DBus buses, as per #3184. Access policies to the buses can be `allow`, which completely allows the bus, `filter`, which runs [`xdg-dbus-proxy`](https://github.com/flatpak/xdg-dbus-proxy), and `none`, which disables access. The `nodbus` options, which is equivalent to `dbus-user none` `dbus-system none` is kept for compatibility.
Filter rules for `xdg-dbus-proxy` can be specified with the `dbus-user.talk`, `dbus-user.own`, `dbus-system.talk`, and `dbus-system.own` options. While `xdg-dbus-proxy` implements finer-grained rules, these four should hopefully be enough to convert filter rules from Flatpak manifests.
On the implementation side:
- The new filter rules are added to the …

Fine-grained DBus sandboxing

---

contrib/syscalls.sh

Fixed the identation for copy/past problems and added a console character that returns the console to it's original colour after the SYSCALLS_OUTPUT_FILE param is printed.
If you make a PR for new profiles or changeing profiles please do the following:
- The ordering of options follow the rules descripted in [/usr/share/doc/firejail/profile.template](https://github.com/netblue30/firejail/blob/master/etc/templates/profile.template).  
> Hint: The profile-template is very new, if you install firejail with your package-manager, it maybe missing, therefore, and to follow the latest rules, it is recommended to use the template from the repository.
- Order the arguments of …

Improvements for syscalls.sh contib file

---

Makefile.in

Sometimes concurrent build could fail if the filter apps were not
made before attempting to make the filters.

Build improvements

---

src/man/firejail-profile.txt
src/man/firejail.txt

firejail can blacklist (and now also whitelist) files based on glob pattern.  This pattern is evaluated at firejail start, and not updated at run time.  This patch documents this behavior.
You should be able to reproduce this behavior by:
```bash
firejail --blacklist="${HOME}/somedir/*" /bin/bash
```
Then, in another shell,
```bash
mkdir "${HOME}/somedir"
touch mkdir "${HOME}/somedir/something"
```
You can access this in the jailed shell. Stopping and restarting it gives the proper blacklisting.
Ideally, the blacklist glob would be evaluated at runtime, but that doesn't seem compatible with the approach firejail uses.

Clarify that file globbing occurs only at start

---

etc/disable-programs.inc
etc/nicotine.profile
src/firecfg/firecfg.config

New profile for Nicotine Plus Soulseek client. 
I realized you were asking contribution for another Soulseek client (soulseekqt), but this is the one I use.
The profile is heavily based on Amule profile and I tried to follow your contribution guidelines.
Tested in Arch Linux with Nicotine Plus 1.4.1-4 and Firejail 0.9.62-1.

Add new profile: nicotine

---

etc/profile-m-z/steam-runtime.profile
src/firecfg/firecfg.config

Simple alias as the desktop file calls it by default on Arch.

Add steam-runtime alias

---

src/firejail/firejail.h

Some applications like Byobu, tmux and screen like to use environment
and then 100 environment variables may be too few.
Closes #3350

Increase MAX_ENVS to 256

---

etc/profile-a-l/celluloid.profile
etc/profile-a-l/com.github.dahenson.agenda.profile
etc/profile-a-l/dconf-editor.profile
etc/profile-a-l/eog.profile
etc/profile-a-l/feedreader.profile
etc/profile-a-l/firefox.profile
etc/profile-a-l/gfeeds.profile
etc/profile-a-l/ghostwriter.profile
etc/profile-a-l/gitg.profile
etc/profile-a-l/gnome-maps.profile
etc/profile-a-l/gnome-pomodoro.profile
etc/profile-a-l/gnome-screenshot.profile
etc/profile-a-l/gnome-todo.profile
etc/profile-a-l/keepassxc.profile
etc/profile-a-l/libreoffice.profile
etc/profile-m-z/rhythmbox.profile
etc/profile-m-z/seahorse.profile
etc/profile-m-z/wireshark.profile
etc/templates/profile.template

Opening as PR so we can disscuss about them. The most are just extracted from flathub, see https://github.com/netblue30/firejail/pull/3265#issuecomment-606030794.
**EDIT:** everyone fell free to push more profiles here.

dbus filter profiles (1)

---

src/firejail/checkcfg.c

Browser DRM was not disabled by default, even though etc/firejail/firejail.config stated that it was.

Disable browser drm by default.

---

etc/firejail.config
etc/profile-a-l/chromium-common.profile

Purely cosmetic stuff, no functional changes.

Follow-up for #3326

---

etc/inc/disable-programs.inc
etc/profile-m-z/steam.profile

Add Faster Than Light, Into the Breach, Paradox Interactive, and mbwarband
to disable-programs.inc.
Also, add Faster Than Light and Into the Breach into steam.profile. This
fixes saved games being lost when steam is closed, and also lets Steam
cloud sync work properly.
Lastly, remove a duplicate whitelist ${HOME}/.steampid from
steam.profile.

Add several games to steam and disable-programs

---

RELNOTES
etc/inc/disable-programs.inc
etc/profile-m-z/plv.profile
src/firecfg/firecfg.config

Add profile for [pacmanlogviewer](https://www.archlinux.org/packages/community/x86_64/pacmanlogviewer/).

add new profile: plv

---

etc/inc/disable-programs.inc
etc/profile-a-l/google-chrome-beta.profile
etc/profile-a-l/google-chrome-unstable.profile
etc/profile-a-l/google-chrome.profile

This PR modifies the google-chrome.profile to allow chrome access to its custom flag files in ~/.config.

Allow google-chrome access to the custom flags files in ~/.config.

---

platform/rpm/firejail.spec
platform/rpm/mkrpm.sh

It seems configure options are hard-coded when building the RPM. I wish to use different config options with RPM, so I added a third argument to `platform/rpm/mkrpm.sh`, which can change the configure options in firejail.spec file.

Add configure options when building rpm

---

etc/profile-a-l/dino-im.profile
src/firecfg/firecfg.config

Ubuntu ships the dino instant messenger as ``dino-im``, so I added a profile for it, which adds the name to the private-bin parameter and then redirects to the dino profile. Also it's added to firecfg.

Add Ubuntu's renamed version of dino

---

etc/profile-m-z/mpg123.profile

AFAIK mpg123 doesn't do video, so we can harden the profile accordingly.

harden mpg123.profile

---

etc/profile-m-z/w3m.profile

w3m is a text-based web browser as well as a pager like `more' or `less'. With w3m you can browse web pages through a terminal emulator window (xterm, rxvt or something like that).
As it outputs I suppose setting quiet in its profile is appropriate.

Set quiet in w3m profile

---

Makefile.in

- remove -c, the manpage says it is ignored
- $(DESTDIR)/$(bindir)/. -> $(DESTDIR)$(bindir) and so on
- install contrib by file glob (*.py, *.sh)
- split long lines

rework make realinstall and uninstall

---

src/firecfg/main.c

It also fixes this error when running `firecfg` as root:
```
Error: this option is not supported for root user; please run as a regular user.
```

firecfg: Only use fix_desktop_files automatically when run through sudo

---

src/man/firejail-profile.txt
src/man/firejail.txt

Add verbiage to the man pages clarifying that the files/directories in the lists given to options such as --private-bin must be relative to the directory that is being limited (e.g., --private-bin requires a list of files/directories that are relative to /bin).
Signed-off-by: Jeff Squyres <jeff@squyres.com>
I made this PR because it took me a while to figure out why I couldn't properly restrict things with `--private-opt`.  Adding this verbiage will hopefully save another newbie like me some time in the future!

man: minor clarifications to man pages

---

src/man/firejail-profile.txt
src/man/firejail.txt

Kind of hot fix to explained how .profile/.local resolution works. This was something I was confused about as someone who goes for man pages at first shot.
Partial info is copy pasted and linked from https://github.com/netblue30/firejail/wiki/Creating-Profiles#locations-and-types
This addresses larger issue that documentation is currently scattered cross man, github and web.
I have added links to SEE ALSO paragraph to somehow make user see that there is some more info.

Man pages: were missing info about .profile .local resolution

---

etc/profile-a-l/emacs.profile

Ignore read-only mount of emacs configuration in the emacs profile.

---

etc/inc/disable-programs.inc
etc/profile-m-z/strawberry.profile
src/firecfg/firecfg.config

> Strawberry is a music player and music collection organizer. It is a fork of Clementine released in 2018 aimed at music collectors and audiophiles. It's written in C++ using the Qt 5 framework.
> 
> Website: https://www.strawberrymusicplayer.org/
> Github: https://github.com/strawberrymusicplayer/strawberry
I just copied clementine profile, changed all clementine(s) to strawberry, I checked and everything's fine.

Add strawberry profile

---

contrib/update_deb.sh

IMO enabling apparmor support by default here ensures a git installation that is compatible with the OS repository and PPA packages (see the firejail-from-git wiki page).
One thing I'm not sure of is how we can patch firejail.config to accomodate https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916920.

enable apparmor support by default in update_deb.sh

---

etc/profile-m-z/totem.profile

Totem crashes because it can't access python:
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
PYTHONHOME = (not set)
PYTHONPATH = (not set)
program name = 'python3'
isolated = 0
environment = 1
user site = 1
import site = 1
sys._base_executable = ''
sys.base_prefix = '/usr'
sys.base_exec_prefix = '/usr'
sys.executable = ''
sys.prefix = '/usr'
sys.exec_prefix = '/usr'
sys.path = [
'/usr/lib/python38.zip',
'/usr/lib/python3.8',
'/usr/lib/lib-dynload',
]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings' …
```

Allow python3 in totem profile

---

etc/profile-a-l/email-common.profile
etc/profile-a-l/evolution.profile
etc/profile-m-z/mutt.profile

Streamlined some fixes in mail client profiles for accessing /var/mail. IMO the most complete comment is that in the thunderbird.profile, so I based these changes on that.

fixes for /var/mail in mail clients

---

etc/apparmor/firejail-default

Thunderbird seems to be our only mail client profile that enables the `apparmor` option. Users need this when they follow instructions on how to allow reading local mail.
@Vincent43 Could you take a look at the rule I added please? Not sure if it is the correct syntax...

clarify writing to /var/mail and /var/spool/mail in apparmor

---

etc/profile-a-l/konversation.profile

Without this, konversation doesn't remember the settings for notifications.

noblacklist a config file in konversation profile

---

etc/profile-m-z/simple-scan.profile

hplip is required for scanning using HP printer/scanners.

Whitelist /usr/share/hplip for simple-scan

---

etc/profile-a-l/blender.profile

Many Blender add-ons make use of `numpy`, and with the default `seccomp` filter, the whole program crashes. `numpy` requires the `mbind` `seccomp` filter to be disabled, so this pull request should fix that issue

Fixed Blender profile being unable to import numpy

---

etc/inc/firefox-common-addons.inc
etc/profile-m-z/okular.profile

The default okular profile doesn't whitelist some config files which are used to store keyboard shortcuts and toolbar configuration. This pull request whitelists those files in `okular.profile` and `firefox-common-addons.inc`

Okular profile fixes

---

README.md
RELNOTES
etc/profile-a-l/flameshot.profile
etc/profile-a-l/frogatto.profile
etc/profile-a-l/ghostwriter.profile
etc/profile-a-l/gnome-latex.profile
etc/profile-a-l/keepassxc.profile
etc/profile-m-z/minetest.profile
etc/profile-m-z/openarena.profile
etc/profile-m-z/openarena_ded.profile
etc/profile-m-z/tremulous.profile
etc/profile-m-z/xonotic-sdl-wrapper.profile
etc/profile-m-z/xonotic.profile
src/firecfg/firecfg.config

- harden and fix flameshot
- wruc: frogatto, ghostwriter
- harden gnome-latex
- add whitelist opt-in note to keepassxc
- add comment to minetest
- harden openarena, tremulous, xonotic
- add profile for xonotic-sdl-wrapper, openarena_ded

hardening some profiles

---

etc/inc/disable-programs.inc
etc/inc/firefox-common-addons.inc
etc/profile-a-l/akregator.profile
etc/profile-a-l/ark.profile
etc/profile-a-l/calligra.profile
etc/profile-a-l/calligraplan.profile
etc/profile-a-l/calligraplanwork.profile
etc/profile-a-l/calligrasheets.profile
etc/profile-a-l/calligrastage.profile
etc/profile-a-l/calligrawords.profile
etc/profile-a-l/gwenview.profile
etc/profile-a-l/k3b.profile
etc/profile-a-l/karbon.profile
etc/profile-a-l/kate.profile
etc/profile-a-l/kcalc.profile
etc/profile-a-l/kdenlive.profile
etc/profile-a-l/kget.profile
etc/profile-a-l/kid3.profile
etc/profile-a-l/kmail.profile
etc/profile-a-l/knotes.profile
etc/profile-a-l/konversation.profile
etc/profile-a-l/kopete.profile
etc/profile-a-l/ktorrent.profile
etc/profile-a-l/kwrite.profile
etc/profile-m-z/okular.profile

Multiple KDE applications store their keyboard shortcut and toolbar config in subdirectories of `.local/share/kxmlgui5`. This pull request blacklists these directories in `disable-programs.inc`, and then noblacklists them in the profiles of the applications which require access to them.

Blacklist .local/share/kxmlgui5 and allow access only for applications which use it.

---

RELNOTES
etc/inc/disable-programs.inc
etc/profile-a-l/element-desktop.profile
src/firecfg/firecfg.config

This PR accomodates the [name change](https://element.io/blog/welcome-to-element/) from Riot to Element.

add element-desktop redirect profile

---

etc/inc/disable-programs.inc
etc/profile-a-l/cawbird.profile
src/firecfg/firecfg.config

https://github.com/netblue30/firejail/pull/3532#discussion_r458142466
It has the ability to copy paste links... https://github.com/netblue30/firejail/pull/3532#discussion_r458149934 so it should be better this way?
The only real use of browser,imo comes from setting it up for the first time,ie, linking it to Twitter via OAuth which needs the link to opened in browser, but fortunately we can copy-paste: https://imgur.com/6iGonmb

Added cawbird profile

---

etc/inc/disable-programs.inc
etc/profile-a-l/freetube.profile
src/firecfg/firecfg.config

Request: https://github.com/netblue30/firejail/issues/1139#issue-213330086
What to do about the appimage? Do I delete it entirely? Tried with `?HAS_APPIMAGE: ignore ...` doesn't work.

Added freetube profile

---

etc/profile-a-l/github-desktop.profile

Can't start on Ubuntu or Debian
```
:~$ journalctl --grep=syscall --follow
-- Logs begin at Thu 2020-07-24 07:12:31 GMT. --
Jul 24 09:10:45 korte audit[14351]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=14351 comm="github-desktop" exe="/usr/lib/github-desktop/github-desktop" sig=31 arch=c000003e syscall=161 compat=0 ip=0x7f024fe5d70d code=0x0
Jul 24 09:10:46 korte kernel: audit: type=1326 audit(1595581845.049:36): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=14351 comm="github-desktop" exe="/usr/lib/github-desktop/github-desktop" sig=31 arch=c000003e syscall=161 compat=0 ip=0x7f024fe5d70d code=0x0
Jul 24 09:10:46 korte audit[14476]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=14476 comm="github-desktop" …
```

Github-desktop: Add chroot to seccomp

---

etc/net/nolocal.net

The current rule for dropping outgoing traffic to multicast addresses in nolocal.net does not properly prohibit multicasting due to a typo. The multicast CIDR should be 224.0.0.0/4 and not 244.0.0.0/4.

fix typo in multicast CIDR

---

etc/profile-m-z/xfce4-screenshooter.profile
src/firecfg/firecfg.config

`private-bin` disables an editor,open in browser etc.. Comment it or put this as a comment?

Added xfce4-screenshooter profile

---

etc/inc/disable-programs.inc
etc/profile-m-z/minecraft-launcher.profile
src/firecfg/firecfg.config

Request:# 1139
<s>What to do with `private-etc`? In game multiplayer or realms doesn't work with it, tried with many combinations. Single player works fine with/without.</s> Should be okay now.

Added minecraft-launcher profile

---

src/firejail/dbus.c
src/firejail/firejail.h
src/firejail/join.c

update D-Bus environment variables during `join`, so that
a joining process is able to use D-Bus, too.

integrate join(-or-start) with dbus options (partial fix)

---

etc/inc/disable-programs.inc
etc/profile-a-l/lyx.profile
src/firecfg/firecfg.config

Request: # 1139
I had to create this on a _very_ _temporary_ LaTeX setup, would appreciate some additional testing. Thanks.
`disable-shell` breaks luatex etc from converting files, `private-tmp` breaks temporary copies of files,too many programs to add to `private-bin`.

Added lyx profile

---

etc/inc/disable-programs.inc
etc/profile-m-z/otter-browser.profile
src/firecfg/firecfg.config

Add profile for otter-browser

---

src/firejail/arp.c
src/firejail/firejail.h
src/firejail/join.c
src/firejail/main.c
src/firejail/protocol.c
src/firejail/sbox.c
src/firejail/x11.c
src/firemon/firemon.h
src/firemon/procevent.c
src/include/syscall.h
src/lib/errno.c

I noticed some comments in the code like "// it will never get here", so I added some annotations to make this assumption also clear to the compiler.

annotate some functions as non-returning

---

etc/inc/disable-programs.inc
etc/inc/whitelist-usr-share-common.inc
etc/profile-a-l/gtk-youtube-viewer
etc/profile-a-l/gtk2-youtube-viewer
etc/profile-a-l/gtk3-youtube-viewer
etc/profile-m-z/youtube-viewer.profile
src/firecfg/firecfg.config

Request: # 1139
Not sure if I should've made redirect profiles or separate.
Too many programs to add to private-bin, in my opinion, we should keep it commented.

Added youtube-viewer profile with Gtk frontends

---

etc/firejail.config
src/firejail/checkcfg.c
src/firejail/firejail.h
src/firejail/main.c
src/firejail/profile.c
src/firejail/usage.c
src/fseccomp/main.c
src/include/seccomp.h
src/man/firejail-profile.txt
src/man/firejail.txt

Allow `log` as an alternative seccomp error action instead of killing
or returning an errno code.
Signed-off-by: Topi Miettinen <toiwoton@gmail.com>

seccomp: logging

---

mkdeb.sh.in

With this change you can build firejail deb with only `firejail-*.tar.xz` and `mkdeb.sh` in current dir.
Currently (as well as in 9.62) such build fails:
```
install: cannot stat ‘platform/debian/copyright’: No such file or directory
```

mkdeb.sh should not use files outside $CODE_DIR

---

etc/profile-m-z/nomacs.profile

Probably very recently `ImageLounge 3.17.0`
```
Aug 11 16:32:32 korte audit[29004]: SECCOMP auid=1000 uid=1000 gid=1000
ses=2 subj==firejail-default (enforce) pid=29004 comm="nomacs"
exe="/usr/bin/nomacs" sig=31 arch=c000003e syscall=9 compat=0
ip=0x7fa2a1cc98c6 code=0x0
```

Fix nomacs

---

etc/profile-a-l/celluloid.profile
etc/profile-m-z/mplayer.profile
etc/profile-m-z/mpv.profile
etc/profile-m-z/totem.profile
etc/profile-m-z/vlc.profile
etc/profile-m-z/xplayer.profile

Switches video players over to a whitelist basis.
I've tested celluloid, vlc, and xplayer and they seem to be fine - would really appreciate additional testing! 😃

Use whitelisting for video players

---

etc/inc/whitelist-common.inc
etc/inc/whitelist-var-common.inc

If you make a PR for new profiles or changeing profiles please do the following:
- The ordering of options follow the rules descripted in [/usr/share/doc/firejail/profile.template](https://github.com/netblue30/firejail/blob/master/etc/templates/profile.template).  
> Hint: The profile-template is very new, if you install firejail with your package-manager, it maybe missing, therefore, and to follow the latest rules, it is recommended to use the template from the repository.
- Order the arguments of options alphabetical, you can easy do this with the [sort.py](https://github.com/netblue30/firejail/tree/master/contrib/sort.py).  
The path to it depends on your distro:
| …

add whitelist items for uim

---

etc/inc/disable-programs.inc
etc/profile-a-l/kazam.profile
etc/profile-m-z/menulibre.profile
etc/profile-m-z/musictube.profile
etc/profile-m-z/onboard.profile
src/firecfg/firecfg.config

Various profiles

---

etc/inc/disable-programs.inc
etc/profile-m-z/man.profile
etc/profile-m-z/pidgin.profile
etc/profile-m-z/psi.profile
etc/profile-m-z/smuxi-frontend-gnome.profile
src/firecfg/firecfg.config

<s>Will add smuxi to this PR later...</s> Done I think...

New profile for man,psi,smuxi; fix pidgin

---

etc/inc/disable-write-mnt.inc
etc/profile-a-l/default.profile
etc/profile-a-l/eo-common.profile
etc/templates/profile.template

It is for profiles which have a reasonable mnt access (we can not add
disable-mnt), but no edit function (e.g. any kind of viewer).
Added to
- profile.template
- default.profile
- eo-common.profile

New disable include: disable-write-mnt.inc

---

src/firejail/main.c

add --include

---

Makefile.in
configure

Those are unnecessary in embedded environment. Besides, in our particular build environment, man page generation simply fails.

added configure option to disable man pages

---

src/firejail/selinux.c

Fixes the crash on systems where SELinux is not enabled.
Also in case SELinux is enabled but the handle can't be opened, exit, as otherwise it would also crash.

Fix SELinux crash

---

contrib/jail_prober.py

In jail_prober.py, a bug prevent a correct testing :
Argument of the firejail command  aren't tested when they are presented to the user, but one loop after (once they're added to "goodargs" array).
This also imply that they're not removed if they doesn't work 
This little modification correct these two problems.

fix command test in jail_prober.py

---

etc/apparmor/firejail-default

AppArmor introduces the @{run} variable, which is used in
<abstractions/dbus-strict> and <abstractions/dbus-session-strict> among
other places. Thus, we must #include <tunables/run> to be able to call
these abstractions.
Standard profiles rely on <tunables/global> to include <tunables/run>, since it exists in previous AppArmor versions, too.
~As an attempt at backwards compatibility, we #include if exists instead
of #include, since there is no <tunables/run> in AppArmor 2.x.~
~However, if exists is a relatively new feature, see e.g.
https://phabricator.kde.org/D14526
(However, do note that if exists does not appear as a new feature in
https://gitlab.com/apparmor/apparmor/-/wikis/Release_Notes_2.13).
Therefore, this commit restricts our compatibility to relatively new
(<10 months) old …

Fix AppArmor 3.0 support (closes #3659)

---

src/firejail/netns.c

Hello,
In Linux it is possible to expose the network of a Docker container as a network namespace of the host with the following commands:
```
NAME="my_container"
pid="$(docker inspect -f '{{.State.Pid}}' "$NAME")"
mkdir -p /var/run/netns
ln -nsf "/proc/$pid/ns/net" "/var/run/netns/$NAME"
```
However, since that is created as a symlink (and it is not a regular file), Firejail fails to recognize it:
```
$ /usr/bin/firejail --noprofile --netns=my_container /usr/bin/firefox
Error: invalid netns 'my_container' (/var/run/netns/my_container: not a regular file)
```
This tiny PR allows using symlinks as arguments of the `netns` option.

Allowing links in netns

---

etc/profile-m-z/wire-desktop.profile

On arch,wire-desktop is now depending on electron9. Using wildcard for this sorta packages would be better.

Update wire-desktop.profile (again)

---

contrib/fix_private-bin.py

This will simplify some distro packagings of firejail.
Signed-off-by: Hank Leininger <hlein@korelogic.com>

Updated fix_private-bin.py shebang to use env python3 like other contrib/*.py scripts

---

src/firejail/main.c
src/firejail/profile.c

Remove environment variables with --rmenv (and profile rmenv)
immediately. This fixes removing long environment variables (LS_COLORS
generated by vivid), previously the length filter would trip before
the command was processed.
This changes user visible behavior slightly, for example --rmenv=LANG
now applies also to Firejail, while earlier it would only apply to
sandboxed program.
Closes #3673.
Signed-off-by: Topi Miettinen <toiwoton@gmail.com>

Apply --rmenv immediately to help to avoid the env var length check

---

etc/inc/disable-programs.inc
etc/profile-m-z/vlc.profile

This fixes #3682 by allowing access to ~/.config/aacs, where the key database for libaacs resides.

Fix blu-ray playback with libaacs

---

etc/profile-a-l/evolution.profile
etc/profile-a-l/kmail.profile

I might do kmail too, if I can. Will be same format, pushed in this PR.

Switch mails to whitelisting

---

RELNOTES
src/firejail/fs.c
src/firejail/profile.c

--tmpfs was added in 0.9.14 and restricted to root only in 0.9.38
due to priv-esc CVE-2016-10117 (e.g. --tmpfs=/etc and modify
/etc/sudoers). This commit reintroduce it for normal users, if the
realpath of it is inside users-home.
BTW: Could we not allow tmpfs complete if nnp is enforced?

Allow --tmpfs and --bind inside $HOME for unprivileged users

---

etc/profile-a-l/firefox.profile

`org.freedesktop.ScreenSaver` allows to unlock the screen, that not something we want browsers can do. So add it commented for now.

fix #3699 -- Firefox can't inhibit screensavers/screen blanking

---

etc/profile-a-l/email-common.profile
etc/profile-a-l/geary.profile
etc/profile-m-z/thunderbird.profile

'read-only ${HOME}/.config/mimeapps.list' is already part of disable-common.inc, no need to add it twice.

Remove redundant read-only item

---

etc/profile-m-z/okular.profile

okular has support for reading cbr (rar-compressed comic book). without unrar or unar  in private-bin, okular fails to decompress the files for viewing.
If you make a PR for new profiles or changeing profiles please do the following:
- The ordering of options follow the rules descripted in [/usr/share/doc/firejail/profile.template](https://github.com/netblue30/firejail/blob/master/etc/templates/profile.template).  
> Hint: The profile-template is very new, if you install firejail with your package-manager, it maybe missing, therefore, and to follow the latest rules, it is recommended to use the template from the repository.
- Order the arguments of options …

Update okular.profile to support cbr files

---

etc/profile-m-z/ssh.profile

[OpenSSH 8.2 added support for U2F](https://www.openssh.com/txt/release-8.2) but the current Firejail SSH profile has nou2f configured. 
My Yubikeys are working fine with the option commented out and I see no reason why U2F shouldn't be enabled in the profile now.

Remove nou2f in ssh profile

---

etc/inc/disable-programs.inc
etc/profile-a-l/linphone.profile

linphone 4.0 changed the location of config and database files to respect freedesktop standards.

Update linphone profile

---

etc/inc/chromium-common-hardened.inc
etc/inc/disable-programs.inc
etc/profile-a-l/bnox.profile
etc/profile-a-l/brave.profile
etc/profile-a-l/chromium-browser-privacy.profile
etc/profile-a-l/chromium-common.profile
etc/profile-a-l/dnox.profile
etc/profile-a-l/enox.profile
etc/profile-a-l/flashpeak-slimjet.profile
etc/profile-a-l/google-chrome-beta.profile
etc/profile-a-l/google-chrome-unstable.profile
etc/profile-a-l/google-chrome.profile
etc/profile-a-l/inox.profile
etc/profile-a-l/iridium.profile
etc/profile-m-z/min.profile
etc/profile-m-z/opera-beta.profile
etc/profile-m-z/opera.profile
etc/profile-m-z/snox.profile
etc/profile-m-z/vivaldi-beta.profile
etc/profile-m-z/vivaldi-snapshot.profile
etc/profile-m-z/vivaldi-stable.profile
etc/profile-m-z/vivaldi.profile
etc/profile-m-z/yandex-browser.profile
src/firecfg/firecfg.config

+ 516d0811 has removed fundamental security features.
(remove caps.drop=all, nonewprivs, noroot, seccomp, protocol; add
caps.keep)  Though this is only necessary if running under a kernel which
disallow   unprivileged userns clones. Arch's linux-hardened and debian kernel
are   patched accordingly. Arch's linux and linux-lts kernels support this
restriction via sysctk (kernel.unprivileged_userns_clone=0) as users
opt-in.   Other kernels such as mainline or fedora/redhat always support
unprivileged   userns clone and have no sysctl parameter to disable it. Debian and
Arch   users can enable it with 'sysctl kernel.unprivileged_userns_clone=1'.
This commit adds a chromium-common-hardened.inc which can be included
in   chromium-common to enhance security of chromium-based programs.
+ …

rework chromium

---

etc/profile-m-z/minetest.profile

It's the path to the game's data in the official Debian package.

minetest.profile: whitelist /usr/share/games/minetest

---

etc/profile-m-z/minetest.profile

Minetest uses `rm` to delete files (saved data and mods).
https://github.com/minetest/minetest/blob/07500479191ed927ab661b3758ffcd2fd43158c5/src/filesys.cpp#L309

minetest: Enable rm

---

src/firejail/fs.c
src/firejail/sandbox.c
test/fs/private-cache.exp

Use new `--tmpfs` functionality to implement `--private-cache`. This has the added advantage that Firejail can now deal with symlinked ~/.cache directories, at least as long as the symlink's target lives in user home.
The new `--private-cache` is less verbose and now behaves like `--blacklist`, `--read-only` and so on, which is why the test had to be adapted.

reimplement --private-cache using --tmpfs

---

etc/inc/whitelist-runuser-common.inc
etc/profile-m-z/thunderbird.profile

1. We must ignore include `whitelist-runuser-common.profile` because it breaks Enigmail (TB 68) and GnuPG smartcard (TB 78) support. The current `thunderbird.profile` had a small typo, so the include wasn't ignored.
However, since the update to Thunderbird 78, Thunderbird does not call the gnupg agent for any GPG public key operations, and only calls it for private key operations if `mail.openpgp.allow_external_gnupg` is set (to allow the use of smart cards). So, this being a quite niche use-case, we might think about including `whitelist-runuser-common.profile` anyways, and leaving only a comment for gnupg agent users.
Alternatively, I had some success with just `whitelist ${RUNUSER}/gnupg` (in conjunction with `writable-run-user` already in `thunderbird.profile`), but that only works if …

Miscellaneous whitelist-runuser-common fixes

---

etc/profile-a-l/firefox.profile

Firefox has gnome-shell search-provider support since version 78:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1239694
- https://mastransky.wordpress.com/2020/09/25/firefox-gnome-shell-search-provider/
Let's add a comment on how to enable this in firejail.

add gnome-shell search-provider file to firefox.profile

---

etc/profile-a-l/godot.profile

Since version 3.0 Godot is supporting C# as a language for writing scripts. The C# solution can be built directly in Godot editor using MSBuild, which requires access to directory /etc/mono. This directory contains configuration of Mono enviroment. If MSBuild don't have access to this directory, it's not able to determine location of DLL files and it's throwing System.DllNotFoundException at beginning of the build process.

Fix building C# projects in Godot

---

etc/inc/disable-programs.inc
etc/profile-a-l/authenticator-rs.profile
etc/profile-a-l/balsa.profile
etc/profile-a-l/falkon.profile
src/firecfg/firecfg.config

> `# private-tmp - interferes with the opening of downloaded files` 
Is that currently supported in browsers? If not we can harden it more by adding private-bin, disable-shell.inc etc.
The dbus permissions is taken from flatpak. It'd be best if `email-common.profile` or at least sylpheed/claws had some dbus restrictions of their own.

Add profile for authenticator-rs, improve falkon

---

etc/profile-m-z/server.profile

Try to uplift our server.profile by bringing in relevant options that got introduced recently. As an experiment in hardening a few options are flipped on by default:
- include disable-write-mnt.inc
- include disable-xdg.inc
- apparmor
- machine-id
- disable-mnt
- dbus-user none

integrate relevant options into server.profile

---

etc/profile-m-z/playonlinux.profile

Playonlinux is only a (graphical) wrapper around wine. Everything required for wine is therefore required for PoL.
https://github.com/netblue30/firejail/issues/3800#issuecomment-742603654
This adds `private-dev` and `whitelist-var-common` as additional restriction to PoL, I don't think that it breaks but testing would be greate. (@Rosika2 would you be so kind `firejail --include=/etc/firejail/whitelist-var-common.inc --private-dev '--noblacklist=/tmp/.wine-*' --private=media/rosika/f14a27c2-0b49-4607-94ea-2e56bbf76fe1/DATEN-PARTITION/PLAYONLINUX playonlinux`).

refactor playonlinux as wine redirect

---

etc/inc/disable-programs.inc
etc/profile-a-l/curl.profile

curl 7.74.0 introduces experimental support for [HSTS cache](https://daniel.haxx.se/blog/2020/11/03/hsts-your-curl/). Assume this file to be ${HOME}/.curl-hsts and (no)blacklist that accordingly.

curl HSTS cache support

---

etc/inc/disable-common.inc

disable-common.inc: blacklist ldns tools
drill(1) from ldns is the first tool suggested on the Arch Wiki for DNS
lookup:
https://wiki.archlinux.org/index.php/Domain_name_resolution#Lookup_utilities
Home page: https://www.nlnetlabs.nl/projects/ldns/about/
$ pacman -Q ldns
ldns 1.7.1-2
$ pacman -Qlq ldns | grep bin
/usr/bin/
/usr/bin/drill
/usr/bin/ldns-chaos
/usr/bin/ldns-compare-zones
/usr/bin/ldns-config
/usr/bin/ldns-dane
/usr/bin/ldns-dpa
/usr/bin/ldns-gen-zone
/usr/bin/ldns-key2ds
/usr/bin/ldns-keyfetcher
/usr/bin/ldns-keygen
/usr/bin/ldns-mx
/usr/bin/ldns-notify
/usr/bin/ldns-nsec3-hash
/usr/bin/ldns-read-zone
/usr/bin/ldns-resolver
/usr/bin/ldns-revoke
/usr/bin/ldns-rrsig
/usr/bin/ldns-signzone
/usr/bin/ldns-test-edns
/usr/bin/ldns-testns
/usr/bin/ldns-update …

Dc add ldns

---

etc/inc/whitelist-common.inc
etc/inc/whitelist-players.inc
etc/inc/whitelist-runuser-common.inc
etc/inc/whitelist-usr-share-common.inc
etc/inc/whitelist-var-common.inc

Use the same wording in our includes as we do in all other files that get overwritten after every install/update.

streamline comments in inc files

---

etc/profile-m-z/steam.profile

I've noticed that profile template has `alsa` in `private-etc`, and `steam.profile` does not, which breaks sound in games using FMOD (Pillars of Eternity in my case, but it should also fix problems mentioned in #3508).

Fix sound in games using FMOD

---

etc/inc/whitelist-player-common.inc
etc/profile-a-l/celluloid.profile
etc/profile-m-z/mplayer.profile
etc/profile-m-z/mpsyt.profile
etc/profile-m-z/mpv.profile
etc/profile-m-z/totem.profile
etc/profile-m-z/vlc.profile
etc/profile-m-z/xplayer.profile

whitelist-player-common.inc fits in with the naming-scheme used throughout our codebase
IMPORTANT NOTE:
users will have to rename their whitelist-players.local to whitelist-player-common.local to ensure stuff stays working as expected

rename whitelist-players.inc to whitelist-player-common.inc

---

etc/profile-m-z/zoom.profile

Better fix for #3711, see discussion there.

re-enable nogroups with a comment in zoom.profile

---

etc/profile-a-l/curl.profile
etc/profile-a-l/dig.profile
etc/profile-a-l/drill.profile
etc/profile-a-l/file.profile
etc/profile-a-l/gtk2-youtube-viewer.profile
etc/profile-a-l/gtk3-youtube-viewer.profile
etc/profile-a-l/highlight.profile
etc/profile-a-l/less.profile
etc/profile-m-z/nslookup.profile
etc/profile-m-z/pandoc.profile
etc/profile-m-z/patch.profile
etc/profile-m-z/pdftotext.profile
etc/profile-m-z/ping.profile
etc/profile-m-z/qrencode.profile
etc/profile-m-z/rsync-download_only.profile
etc/profile-m-z/shellcheck.profile
etc/profile-m-z/strings.profile
etc/profile-m-z/wget.profile
etc/profile-m-z/whois.profile
etc/profile-m-z/youtube-dl.profile

Some profiles blacklisted both ${RUNUSER} and ${RUNUSER}/wayland-*, which doesn't make much sense. This PR removes the latter to avoid potential confusion. See discussion in https://github.com/netblue30/firejail/pull/3820.

Runuser fixes

---

etc/inc/archiver-common.inc
etc/profile-a-l/7z.profile
etc/profile-a-l/ar.profile
etc/profile-a-l/atool.profile
etc/profile-a-l/bsdtar.profile
etc/profile-a-l/cpio.profile
etc/profile-a-l/gzip.profile
etc/profile-m-z/tar.profile
etc/profile-m-z/unrar.profile
etc/profile-m-z/unzip.profile
etc/profile-m-z/xzdec.profile
etc/profile-m-z/zstd.profile

Introduce `archive-common.inc`: common file for all archivers.
For now this WIP simply recreates existing archiver profiles.
It's intention is to:
- simplify adding new archiver profile(s);
- review potential inconsistencies in existing archiver profile(s).
E.g. most have nogroups and have noroot commented, but a few divert from this pattern. I intend to do a follow-up review after extended testing, so for now this is a WIP.

Refactor archivers

---

etc/profile-a-l/7z.profile
etc/profile-a-l/atool.profile
etc/profile-a-l/bsdtar.profile
etc/profile-a-l/cpio.profile
etc/profile-a-l/gzip.profile
etc/profile-m-z/tar.profile
etc/profile-m-z/unrar.profile
etc/profile-m-z/unzip.profile
etc/profile-m-z/xzdec.profile
etc/profile-m-z/zstd.profile

Now that #3820 landed, we can easily bring some extra hardening to our archivers. This follow-up PR concludes upstreaming what I have been using in local overrides for quite some time.

Refactor archivers ii

---

etc/inc/disable-shell.inc

"Portable OpenBSD ksh, based on the Public Domain Korn Shell (pdksh)."
Project page: https://github.com/ibara/oksh
$ pacman -Q oksh
oksh 6.8.1-1
$ pacman -Qlq oksh | grep bin/
/usr/bin/
/usr/bin/oksh

disable-shell.inc: add oksh

---

etc/profile-a-l/7z.profile
etc/profile-a-l/ar.profile
etc/profile-a-l/bsdtar.profile
etc/profile-m-z/tar.profile
etc/profile-m-z/unzip.profile

Archivers should be able to compress binaries (see discussion in https://github.com/netblue30/firejail/commit/95ad89d24e8e75f2f52defbb80d0d4ee0f27d31e). Let's drop private-bin in relevant profiles.

Archiver fixes - drop private-bin

---

etc/inc/archiver-common.inc

Preliminary work based on discussion in #3833. As suggested there we take a similar approach as in our meld profile.

archivers: limiting file system access

---

etc/inc/disable-common.inc

* disable-common.inc: split bind and knot tools
* disable-common.inc: blacklist missing bind tools
* disable-common.inc: blacklist missing knot tools
* disable-common.inc: blacklist unbound tools
* dnscrypt-proxy.profile: fix section structure
* disable-common.inc: add misc dns tools

Dc add dns

---

etc/inc/disable-programs.inc
etc/profile-m-z/matrix-mirage.profile
etc/profile-m-z/mirage.profile
src/firecfg/firecfg.config

In Debian mirage is packaged as matrix-mirage (as mirage was already taken by a different program).
This creates a redirect profile.
It also adds ldconfig to private-bin (and noblacklists /sbin), as otherwise some Python/Qt related modules were not loading:
```
! 18:17:41 | QSystemTrayIcon::setVisible: No Icon set
~ 18:17:42 | "PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:/src/backend/qml_bridge.py\", line 27, in <module>\n    from .pyotherside_events import CoroutineDone, LoopException\n\n  File \"qrc:/src/backend/pyotherside_events.py\", line 8, in <module>\n    from .utils import serialize_value_for_qml\n\n  File \"qrc:/src/backend/utils.py\", line 26, in <module>\n    import magic\n\n  File \"/usr/lib/python3/dist-packages/magic/__init__.py\", line 361, in …
```

profiles: add redirect from matrix-mirage to mirage

---

src/firejail/firejail.h
src/firejail/join.c
src/firejail/main.c
src/firejail/no_sandbox.c
src/firejail/sandbox.c

Allows users to join a sandbox and get a shell even if there is none in the sandbox mount namespace.
Limitations are described in https://github.com/netblue30/firejail/issues/2934#issuecomment-747819719

join: add fexecve fallback for shells

---

etc/profile-a-l/keepassxc.profile

With the current profile, keepassxc hangs on startup, before showing the
main window:
$ uname -r -m
5.9.1-artix1-1 x86_64
$ firejail --version | head -n 1
firejail version 0.9.64
$ firejail --quiet keepassxc --version
KeePassXC 2.6.2
$ firejail --quiet keepassxc
^C
Seccomp debugging as explained on etc/templates/syscalls.txt:
$ sudo grep -Eo 'keepassxc.* syscall=[0-9]+' /var/log/messages.log | tail -n 1
keepassxc" exe="/usr/bin/keepassxc" sig=31 arch=c000003e syscall=303
$ firejail --debug-syscalls | grep 303
303     - name_to_handle_at
So allow the name_to_handle_at syscall.
Relates to #3549.

keepassxc.profile: Fix hang due to seccomp

---

etc/profile-m-z/zcat.profile
etc/profile-m-z/zgrep.profile

Our archiver-common.inc includes `disable-shell.inc`, breaking running kernel config check with zcat or zgrep.

really fix running kernel config check

---

etc/profile-m-z/signal-desktop.profile

disable-exec.inc is already included in electron redirect

drop doubled disable-exec in signal-desktop

---

README.md
etc/inc/disable-programs.inc
etc/profile-m-z/tutanota-desktop.profile
src/firecfg/firecfg.config

Profile [request](https://github.com/netblue30/firejail/issues/1139#issuecomment-754291416).

new profile: tutanota-desktop

---

etc/profile-a-l/evince.profile

bookmarks are saved unter $HOME/.local/share/gvfs-metadata
since evince is the primary pdf reader, a firejailed evince can't read
or write those
this commit makes them available in the sandbox

evince.profile: noblacklist bookmark folder

---

etc/profile-a-l/discord-common.profile

Discord needs PulseAudio. Without it, it's unable to play any audio.

discord-common.profile: Fix audio support

---

etc/inc/disable-programs.inc
etc/profile-m-z/steam.profile

At least Arma 3 stores its config directory under
~/.local/share/bohemiainteractive
Without this, Arma 3's configuration and game save do not persist across Steam firejail sessions.

Whitelist Bohemia Interactive config dir for Steam

---

README.md
etc/inc/allow-common-devel.inc
etc/inc/disable-common.inc
etc/inc/disable-programs.inc
etc/profile-m-z/nodejs-common.profile
etc/profile-m-z/npm.profile
etc/profile-m-z/yarn.profile

This PR does the following:
- add new yarn.profile
- add new nodejs-common.profile (common for npm & yarn)
- refactor npm.profile

refactor nodejs applications (npm & yarn)

---

.github/ISSUE_TEMPLATE/bug_report.md

Clarify that:
* "upstream profile" means the profile version on the master branch
* "duplicates" refer to duplicate issues
As suggested by @scruloose on
https://github.com/netblue30/firejail/issues/3884#issue-784605766
https://github.com/netblue30/firejail/issues/3884#issuecomment-759528185

bug_report.md: improve wording (upstream/duplicates)

---

etc/inc/allow-bin-sh.inc
etc/profile-m-z/mpv.profile
etc/profile-m-z/nodejs-common.profile

/bin/sh is usually just a symlink to bash. However this is not the case
for every distro, debian for example uses dash. bash,dash and sh have a
blacklist command in disable-shell.inc. An own allow-*.inc for it
enusres usage of all necessary nolacklists.
For private-bin sh is enough because it follows symlinks.

Add new allow include allow-bin-sh.inc

---

src/firejail/fs_lib.c

little patch to add timetrace for Firejail libraries, and a few extra debug messages.

private-lib: add new timetrace

---

etc/profile-a-l/bibletime.profile

To fix issue #3907, doc directory of the bibletime has to be whitelisted. Otherwise, it always fails to start.

Update bibletime.profile, add new whitelist

---

etc/inc/disable-programs.inc
etc/profile-a-l/coyim.profile
src/firecfg/firecfg.config

I have created here a first profile for CoyIM. I have tried to make it as restrictive as I could and follow the guidelines of the template. It is however the first firejail profile I create, so any input or feedback would be very welcome.

New profile for CoyIM

---

etc/profile-a-l/aosp.profile
etc/profile-a-l/gnome-builder.profile

${HOME}/.bash_history is not blacklisted anywhere. Hence a noblacklist doesn't make sense. Affected profiles: aosp & gnome-builder.

remove noblacklist without blacklist

---

etc/inc/allow-ssh.inc
etc/inc/disable-common.inc
etc/inc/disable-programs.inc
etc/profile-a-l/android-studio.profile
etc/profile-a-l/aosp.profile
etc/profile-a-l/clion.profile
etc/profile-a-l/filezilla.profile
etc/profile-a-l/git-cola.profile
etc/profile-a-l/git.profile
etc/profile-a-l/gitg.profile
etc/profile-a-l/idea.sh.profile
etc/profile-m-z/meld.profile
etc/profile-m-z/remmina.profile
etc/profile-m-z/seahorse.profile
etc/profile-m-z/ssh-agent.profile
etc/profile-m-z/ssh.profile
etc/profile-m-z/webstorm.profile
etc/profile-m-z/x2goclient.profile
etc/templates/profile.template

```console
* etc: add allow-ssh.inc
* allow-ssh.inc: allow /etc/ssh/ssh_config
* ssh: deny access to the rest of /etc/ssh/*
* allow-ssh.inc: allow access to ssh-agent(1)
* disable-common.inc: add missing openssh paths
* disable-common.inc: mark ~/.ssh as read-only
```
Note: As mentioned on #3845, please don't squash any commits; use normal merge
or rebase instead.

ssh: Refactor, fix bugs & harden

---

test/environment/environment.sh

tests: improve check for sound capabilities

---

etc/profile-a-l/bijiben.profile

webkit2gtk uses a bwrap based sandbox by default since 4.0, see #3647.
This is good as it means more security by default on for linux system.
Unfortunately is it not possible to run bwrap inside firejail if bwrap
is started with --unshare-pid --proc /proc at all. In general we should
exclude a program from firecfg until a final solution is found. But
bijiben is special, while epiphany or evolution display random stuff
from the internet is webkit2gtk in bijiben used to display local files
create by the user. Bijiben has a thight profile (net none, whitelist,
private-bin, ...) therefore my decision here was to disable the
webkit2gtk sandbox rather then firejail.

Disable the webkit2gtk-4.0 sandbox in bijiben

---

src/man/firecfg.txt

I believe this to be a minor typo, given the precedence of `/usr` as a directory on many Linux distributions, and the lines following this which explicitly reference `/usr/local/bin `instead of `/user/local/bin` .

Fix minor typo in firecfg's manual page

---

src/firejail/sbox.c
src/firejail/seccomp.c
src/fsec-optimize/Makefile.in
src/fsec-optimize/main.c
src/fsec-optimize/optimizer.c
src/fseccomp/main.c
src/fseccomp/seccomp_secondary.c
src/include/seccomp.h

fsec-optimize: Optimize BPF with current seccomp error action, not
just KILL
fseccomp: use correct BPF code for errno action
Closes: #3933
Signed-off-by: Topi Miettinen <toiwoton@gmail.com>

Seccomp error action fixes

---

etc/inc/whitelist-usr-share-common.inc

uim is a multilingual input method framework, so any program that takes user input potentially needs it to work.

add a /usr/share whitelist item for uim

---

etc/inc/allow-gjs.inc
etc/inc/disable-interpreters.inc

And sort the paths on allow-gjs.inc.
$ pacman -Q js78
js78 78.6.0-1
$ pacman -Qlq js78 | grep -v /usr/include/
/usr/
/usr/bin/
/usr/bin/js78
/usr/bin/js78-config
/usr/lib/
/usr/lib/libmozjs-78.so
/usr/lib/pkgconfig/
/usr/lib/pkgconfig/mozjs-78.pc
This appears to be the only counterpart path missing when looking at the
current lib64 entries with:
$ grep -Fnr lib64 etc
---
Note: As mentioned on #3845, please don't squash any commits; use normal merge
or rebase instead.

disable-interpreters.inc: blacklist the other libmozjs

---

etc/profile-a-l/keepassxc.profile
etc/profile-m-z/Mathematica.profile

Currently, some paths are hard-coded:
$ grep -Fnr '${HOME}/Documents' etc etc-fixes
etc/profile-m-z/Mathematica.profile:19:mkdir ${HOME}/Documents/Wolfram Mathematica
etc/profile-m-z/Mathematica.profile:22:whitelist ${HOME}/Documents/Wolfram Mathematica
etc/profile-a-l/keepassxc.profile:34:# If you do so, you MUST store your database under ${HOME}/Documents/KeePassXC/foo.kdbx
etc/profile-a-l/keepassxc.profile:35:#mkdir ${HOME}/Documents/KeePassXC
etc/profile-a-l/keepassxc.profile:36:#whitelist ${HOME}/Documents/KeePassXC
Commands used to search and replace:
$ find etc etc-fixes/ -type f -exec \
sed -i.bak -e 's|\${HOME}/Documents|${DOCUMENTS}|' '{}' +
Related to that, the (lack of) usage of ${DOWNLOADS} has been recently
fixed on commit deae31301 ("use ${DOWNLOADS} in lutris.profile …

etc: use ${DOCUMENTS} macro where appropriate

---

src/firejail/appimage.c
src/firejail/checkcfg.c
src/firejail/chroot.c
src/firejail/dbus.c
src/firejail/env.c
src/firejail/firejail.h
src/firejail/fs.c
src/firejail/fs_whitelist.c
src/firejail/join.c
src/firejail/main.c
src/firejail/no_sandbox.c
src/firejail/output.c
src/firejail/paths.c
src/firejail/profile.c
src/firejail/pulseaudio.c
src/firejail/run_symlink.c
src/firejail/sandbox.c
src/firejail/sbox.c
src/firejail/x11.c

Save all environment variables for later use in sandboxes, clear
environment and re-apply only whitelisted variables for the main
firejail process. All variables will be reapplied for the sandboxes by
env_apply().

Filter environment variables

---

etc/inc/disable-programs.inc
etc/profile-a-l/claws-mail.profile
etc/profile-a-l/email-common.profile
etc/profile-a-l/geary.profile
etc/profile-m-z/mutt.profile
etc/profile-m-z/neomutt.profile
etc/profile-m-z/sylpheed.profile
src/firecfg/firecfg.config

Continuation of https://github.com/netblue30/firejail/pull/3607
Mutt/Neomutt needs some testing I may not have went through all use cases, leaving a (neo)muttrc if anyone wants to do some testing https://termbin.com/tryb

Email part (2)
