netblue30/firejail

- etc/disable-history.inc
In CVE-2015-4495 — the Firefox PDF.js exploit — an examined payload searched for various history files in order to find potentially sensitive information.
> Block access to history files

- src/man/firejail-profile.txt
- src/man/firejail.txt
Signed-off-By: Michael Haas <haas@computerlinguist.org>
> Fix typos in firejail and firejail-profile man

- src/firejail/firejail.h
- src/firejail/main.c
- src/firejail/usage.c
- src/man/firejail.txt
Addressing #45 (Use generic.profile by default)
I managed to find enough time tonight.  I'm happy to change anything if there's an issue.
> Use generic.profile by default

- etc/chromium.profile
- etc/filezilla.profile
- etc/firefox.profile
- etc/midori.profile
- etc/opera.profile
- etc/server.profile
- src/firejail/caps.c
- src/firejail/fs.c
- src/firejail/profile.c
- src/include/common.h
- src/man/firejail-profile.txt
Fixes netblue30/firejail#50
* Basic implementation
* Updates to standard profiles
* Update to firejail-profile manpage
> Noblacklist

- configure
- configure.ac
- platform/debian/control
- platform/debian/copyright
- platform/rpm/mkrpm.sh
- src/firejail/usage.c
- src/firemon/usage.c
- src/man/firejail-login.txt
- src/man/firejail-profile.txt
- src/man/firejail.txt
- src/man/firemon.txt
See Issue #80 for justification
> switch project url to github

- etc/disable-common.inc
- etc/disable-secret.inc
I've found a few more files that should be blacklisted as they contain potentially useful information to an attacker.
> add a few new items to blacklist

- etc/conkeror.profile
Add profile for Conkeror browser: http://conkeror.org/
> Added profile for Conkeror Browser

- etc/disable-mgmt.inc
That's the nmap implementation of netcat.
> blacklist ncat

- Makefile.in
- etc/chromium-browser.profile
- etc/chromium-common.profile
- etc/chromium.profile
- etc/google-chrome-beta.profile
- etc/google-chrome-stable.profile
- etc/google-chrome-unstable.profile
- etc/google-chrome.profile
- platform/debian/conffiles
> add google-chrome{,-stable,-beta,-unstable}.profile

- etc/spotify.profile
> Allow netlink for Spotify

- src/firejail/fs.c
Instead of a statically allocated buffer for noblacklist entries, a buffer of same size is allocated dynamically instead. The size of the buffer is doubled every time it runs out of space.
> dynamic allocation of noblacklist buffer

- etc/telegram.profile
First commit for telegram.profile, with a basic (tested) configuration.
> Added Telegram profile

- src/firejail/run_symlink.c
Some programs place symlinks in $PATH.
> Fix symlink invocation for programs placing symlinks in $PATH

- etc/Mathematica.profile
- etc/mathematica.profile
This adds a profile for [Wolfram Mathematica](https://en.wikipedia.org/wiki/Mathematica).
> add Mathematica profile

- etc/uget-gtk.profile
profile for the uGet download manager
> add uGet profile

- src/libtracelog/libtracelog.c
storage_find function fails on relative path, so nothing reported to log when blacklisted file accessed by relative path.
This is because CWD is NULL when realpath function called.
How to reproduce:
```
touch /home/user/somefile
firejail --blacklist=somefile --tracelog cat somefile
```
Solution: keep CWD value and set it before calling realpath. In order to do this:
* new wrapper for chdir call, and variable to keep CWD added.
* storage_find modified to chdir before calling realpath function.
* order of storage_find and orig_* calls in syscall wrappers changed,
to prevent error set by calls in storage_find leak outside.
* condition for calling realpath changed to include double-slash
and path without initial slash
> Fix problem with relative path in storage_find function

- etc/cherrytree.profile
http://www.giuspen.com/cherrytree/
> Adding cherrytree profile

- Makefile.in
- README
- RELNOTES
- etc/polari.profile
- platform/debian/conffiles
Added a profile for [Polari](https://wiki.gnome.org/Apps/Polari), an IRC client for GNOME.
> Add Polari profile

- etc/wesnoth.profile
* allow X11 communcation via /tmp (just for completeness sake)
* fix typo
> edit wesnoth profile (small fix)

- Makefile.in
- README
- README.md
- etc/qtox.profile
- platform/debian/conffiles
Added a profile for [qTox](https://github.com/tux3/qTox), a [Tox](https://tox.chat/) cilent.
> Add qTox profile

- src/man/firejail.txt
Rather unfortunate commit message, I think, but please don't kill me.
> "/etc/password" -> "/etc/passwd"

- Makefile.in
- README
- README.md
- etc/cmus.profile
- platform/debian/conffiles
At last, goddamn.
Or is there something I'm still missing? RELNOTES? disable-programs.inc?
Does it have to be ${HOME}, by the way? Or can it be ~/ ? Is any one preferable?
> add cmus.profile

- src/firejail/profile.c
- src/man/firejail-profile.txt
#414 
You want to review this.
> profile.c: add --net <iface>

- etc/abrowser.profile
I've written a simple profile for Abrowser [1]. Feel free to merge if you want.
1: https://trisquel.info/en/wiki/abrowser-help
> Abrowser profile, based on Firefox

- Makefile.in
- etc/disable-programs.inc
- etc/warzone2100.profile
- platform/debian/conffiles
- src/firecfg/firecfg.config
Profile for warzone2100. 
So far I haven't been modifying the README or README.MD files to reflect my changes.
Would it be easier on you if I started modifying these and submitting them along with the pull request? Or would you rather handle that yourself?
> warzone2100 profile

- Makefile.in
- README
- README.md
- etc/disable-programs.inc
- etc/gpredict.profile
- platform/debian/conffiles
- src/firecfg/firecfg.config
Added profile for Gpredict (a satellite tracking program).
> added gpredict profile

- etc/google-play-music-desktop-player.profile
Here is the github of this app, really useful to play music:
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> added google-play-music-desktop-player profile

- etc/disable-common.inc
This is a (temporary) fix for #472. Hope it helps!
> Temp fix for #472

- etc/cyberfox.profile
I was testing this fork of Firefox these days. Could be useful for some people.
I didn't modified Firefox base profile, just the properly directories.
> cyberfox profile

- README
- etc/disable-devel.inc
I added g++ blacklists to etc/disable-devel.inc. Hope this helps. :)
> blacklisted g++

- src/man/firejail-profile.txt
> update seccomp default list in firejail-profile

- etc/franz.profile
added profile for franz messenger app based n electron
> added profile for franz messenger

- etc/disable-common.inc
This adds a number of things to `disable-common.inc`.
> Complete disable-common.inc

- Makefile.in
- README
- README.md
- RELNOTES
- etc/disable-programs.inc
- etc/libreoffice.profile
- platform/debian/conffiles
- src/firecfg/firecfg.config
Here's the libreoffice profile I promised in #576. :)
I thought about doing a more restrictive profile but there's no telling where a user will want to save files. What do you think?
> added libreoffice profile

- etc/xzdec.profile
Decompressing .xz file within a sandboxing environment.
> xz decompressor

- etc/gzip.profile
Desctiption: Gzip sandbox profile for decompression
Changes to be committed:
new file:   gzip.profile
To prevent further vulnerabilities such as shown below from being used to target users, this firejail profile has been made.
https://www.cvedetails.com/vulnerability-list/vendor_id-72/product_id-1670/GNU-Gzip.html
>   Committer: Paupiah Yashvi <yash@hackers.mu>

- etc/firejail.config
- src/firejail/usage.c
- src/man/firejail-config.txt
- src/man/firejail-login.txt
- src/man/firejail-profile.txt
- src/man/firejail.txt
GNPR (Grammar Nazi Pull Request).
> fix some typos

- src/libtracelog/libtracelog.c
Fix [bug](https://github.com/netblue30/firejail/issues/326) in libtracelog (introduced by me while fixing another).
* Add fchdir wrapper and convert file descriptor to pathname to keep as CWD.
* Instead of doing chdir (that was really bad decision) just add CWD to relative path.
> Fix chdir bug in libtracelog

- etc/disable-common.inc
> Blacklist .gnomerc

- etc/disable-passwdmgr.inc
It contains the path to the last used database.
> disable-passwdmgr.inc: Don't leak keepassx config

- .gitignore
- Makefile.in
Fixes the rpm build from the tarball.
I'm fine if you cherry-pick this commit instead of a merge commit :)
> Include mkuid.sh in "make dist"

- Makefile.in
- mkasc.sh
- mkdeb.sh
- src/tools/mkcoverit.sh
- test/dist-compile/compile.sh
- Use xz instead of bz2
- Sign source tarballs
> Suggestions to release process

- etc/gnome-chess.profile
This should fix some issues I introduced in the initial commit (oops!) plus add `private-etc` and `private-tmp` :smile:
> Fixed & tightened gnome-chess

- src/firejail/network.txt
- test/network/net_arp.exp
Just fixing "snad" instead of "sand". :)
> Sandy shores

- src/firejail/fs.c
- src/firejail/main.c
This PR fix the #712 issue.
Thank you for your interest.
> Fixed #712

- etc/gnome-mplayer.profile
- etc/gpredict.profile
- etc/gthumb.profile
- etc/hedgewars.profile
- etc/hexchat.profile
- etc/jitsi.profile
- etc/kmail.profile
- etc/konversation.profile
G'day netblue30! This is the first of (I hope) several commits that should tighten profiles when appropriate. In particular, I'm targeting `nosound`, `nogroups`, and `private-tmp` being added.
> tightened profiles

- etc/disable-programs.inc
- etc/gajim.profile
Add profile for Gajim (Python GTK-based IM client), as well as adding Gajim's files to the disable-programs common list
> Add profile for Gajim IM client

- src/firejail/bandwidth.c
- src/firejail/cgroup.c
- src/firejail/cpu.c
- src/firejail/firejail.h
- src/firejail/fs.c
- src/firejail/fs_bin.c
- src/firejail/fs_dev.c
- src/firejail/fs_etc.c
- src/firejail/fs_home.c
- src/firejail/fs_hostname.c
- src/firejail/fs_logger.c
- src/firejail/fs_mkdir.c
- src/firejail/fs_trace.c
- src/firejail/fs_var.c
- src/firejail/fs_whitelist.c
- src/firejail/main.c
- src/firejail/protocol.c
- src/firejail/pulseaudio.c
- src/firejail/restrict_users.c
- src/firejail/sandbox.c
- src/firejail/seccomp.c
- src/firejail/x11.c
* add SET_PERMS macros
* more `chown`/`chmod` changes
> additional batch of chown/chmod changes

- src/firejail/x11.c
> Fix spelling error

- src/firejail/appimage.c
- src/firejail/fs.c
- src/firejail/fs_bin.c
- src/firejail/fs_dev.c
- src/firejail/fs_etc.c
- src/include/common.h
Put back previously removed chmod calls.
Fixes https://github.com/netblue30/firejail/issues/749
> Fix chmod/umask problem

- README
- README.md
- RELNOTES
- etc/disable-programs.inc
- platform/debian/conffiles
- src/firecfg/firecfg.config
I forgot the extra files for the new dosbox profile in my last PR.
> extra dosbox files

- src/firejail/main.c
fix for https://github.com/netblue30/firejail/issues/765
> fix read_pid

- src/firejail/x11.c
* fix for grsecurity systems
* error message changed to mention display managers, as noted by @xahare
> small --x11=block fixes

- src/firejail/firejail.h
- src/firejail/fs_whitelist.c
- src/man/firejail-profile.txt
- src/man/firejail.txt
For https://github.com/netblue30/firejail/issues/781
Essentially, copy-paste of `/media` code.
> Accept /mnt in --whitelist option

- src/firejail/main.c
- src/firejail/profile.c
- src/man/firejail-profile.txt
- src/man/firejail.txt
Command line and profile option to run apps in one sandbox without need to handle starting and joining separately.
> join-or-start option

- etc/evince.profile
Added tracelog to the profile.
> Added tracelog

- src/firejail/restrict_users.c
I fixed typo in a comment, it bothered me. If you don't really care about this kind of stuff, just reject this PR :)
> Fixed typo in comment

- README.md
- etc/feh.profile
- etc/ranger.profile
- etc/zathura.profile
- platform/debian/conffiles
- src/firecfg/firecfg.config
Profiles added for:
feh image viewer
ranger file manager
zathura document viewer
Also fixed the order of the program and profile list
> Added profiles for feh, ranger and zathura

- etc/cherrytree.profile
- etc/disable-common.inc
- etc/disable-programs.inc
- etc/feh.profile
- etc/mupdf.profile
- etc/ranger.profile
- etc/zathura.profile
hardening for
mupdf
ranger
feh
zathura
fixed cherrytree whitelisting
added muttrc to blacklisted files in disable-common.inc and disable-programs.inc
> hardened profiles and fixed blacklisting

- etc/cherrytree.profile
fix for https://github.com/netblue30/firejail/issues/850
> fixed database not found error

- etc/xpdf.profile
> add xpdf profile

- src/firejail/firejail.h
- src/firejail/fs_whitelist.c
- src/man/firejail-profile.txt
- src/man/firejail.txt
> added /srv in whitelist option

- etc/deluge.profile
- etc/eog.profile
- etc/evince.profile
- etc/evolution.profile
- etc/fbreader.profile
- etc/feh.profile
- etc/filezilla.profile
- etc/firefox.profile
- etc/gthumb.profile
- etc/mupdf.profile
- etc/pix.profile
- etc/qbittorrent.profile
- etc/rtorrent.profile
- etc/transmission-gtk.profile
- etc/transmission-qt.profile
- etc/uget-gtk.profile
- etc/wesnoth.profile
- etc/zathura.profile
- src/man/firejail-profile.txt
- src/man/firejail.txt
added nosound to eog and evolution
> various changes

- etc/zoom.profile
Inspired from skype profile. 
Tested mic & camera
> Added profile for zoom.us messanger

- etc/disable-common.inc
> Blacklist ecryptfs files

- etc/disable-common.inc
added /home/.ecryptfs to blacklist
> completed ecryptfs blacklist

- etc/mutt.profile
I need to be able to send mail too!
> do not blacklist msmtprc in mutt

- etc/keepass2.profile
- etc/kmail.profile
- etc/mupdf.profile
- etc/qemu-launcher.profile
- etc/qemu-system-x86_64.profile
- platform/debian/conffiles
- src/firecfg/firecfg.config
- added profile for qemu
- fixed error in kmail profile
- hardened empathy profile
- added keepass2 to program list
> various fixes

- etc/wget.profile
added wget and fixed profile for transmission-cli
> added wget profile

- README
- README.md
- RELNOTES
- etc/disable-programs.inc
- etc/pluma.profile
- etc/xed.profile
- platform/debian/conffiles
- src/firecfg/firecfg.config
Since we have a gedit profile I figured it wouldn't be a bad idea to add profiles for xed and pluma as well.
> Text editors

- etc/bless.profile
- etc/disable-programs.inc
- etc/gnome-2048.profile
- etc/gnome-calculator.profile
- etc/gnome-contacts.profile
- etc/jd-gui.profile
- etc/lollypop.profile
- etc/multimc5.profile
- etc/pdfsam.profile
- etc/pithos.profile
- etc/xonotic-glx.profile
- etc/xonotic-sdl.profile
- etc/xonotic.profile
Added profiles for Bless, Gnome 2048, Gnome Calculator, Gnome Contacts, JD-GUI, Lollypop, MultiMC5, PDFSam, Pithos, and Xonotic
From https://github.com/SpotComms/FirejailProfileGenerator
> Added 10 new profiles

- etc/disable-common.inc
Added truecrypt and zuluCrypt files
> Added profiles for truecrypt and zuluCrypt

- etc/7z.profile
- etc/atool.profile
- etc/cpio.profile
- etc/elinks.profile
- etc/exiftool.profile
- etc/git.profile
- etc/gpg-agent.profile
- etc/gpg.profile
- etc/highlight.profile
- etc/less.profile
- etc/lynx.profile
- etc/mediainfo.profile
- etc/mutt.profile
- etc/odt2txt.profile
- etc/pdftotext.profile
- etc/ssh-agent.profile
- etc/strings.profile
- etc/tracker.profile
- etc/w3m.profile
- etc/wget.profile
- etc/xpra.profile
> profile improvements

- src/firejail/main.c
> main: guess_shell: use $SHELL variable if set

- RELNOTES
> Add references to CVEs in release notes

- RELNOTES
> Reference new CVEs

- etc/uzbl-browser.profile
(adapted from netsurf.profile)
> added uzbl-browser.profile (refs #825)

- contrib/update_deb.sh
- contrib/update_src.sh
For #1049 
I kept the `if [ $EUID != 0 ]; then...` bit - you might not need it (especially if this is called from firejail) but I figured it was better to have too much than to not send in enough. :)
I also added a `sleep 3` line so there's enough time for the user to see that firejail was updated.
Cheers!
Fred
> added update scripts

- etc/iridium-browser.profile
- etc/iridium.profile
added profile for the privacy enhanced chromium browser #825
> added iridium browser profile

- etc/disable-common.inc
- etc/disable-programs.inc
More KDE files and folders I would suggest to blacklist.
> blacklist more KDE files

- src/firecfg/main.c
> firecfg: create ~/.local/share/applications directory if it doesn't exist

- etc/firejail.config
Fixing https://github.com/netblue30/firejail/issues/1171 and https://github.com/netblue30/firejail/issues/1170
> firejail.config cleanup

- etc/dino.profile
A profile for the new Dino XMPP client https://github.com/dino/dino
> Add a profile for Dino

- etc/bless.profile
- etc/dino.profile
- etc/eog.profile
- etc/evince.profile
- etc/evolution.profile
- etc/file-roller.profile
- etc/gedit.profile
- etc/gimp.profile
- etc/gnome-calculator.profile
- etc/hexchat.profile
- etc/jd-gui.profile
- etc/keepass.profile
- etc/keepassx.profile
- etc/keepassx2.profile
- etc/keepassxc.profile
- etc/libreoffice.profile
- etc/lollypop.profile
- etc/multimc5.profile
- etc/mumble.profile
- etc/pdfsam.profile
- etc/pithos.profile
- etc/steam.profile
- etc/totem.profile
- etc/vlc.profile
- etc/xonotic.profile
Hardens some profiles I added in #946 and some others.
Can we also get a per profile disable-mnt? Also what exactly are the side-effects of 'ipc-namespace'?
> Harden some profiles

- etc/disable-common.inc
> noexec ~/.local/share

- etc/k3b.profile
- update noblacklist
- remove commented private-dev (it will always break k3b)
- remove nogroups (it should break k3b in some cases)
> update k3b profile

- src/firejail/profile.c
This commit will add the overlay configurations overlay, overlay-named and overlay-tmp to profile configuration files. 
Adding these configurations will allow profiles to be started by default within overlays.
> Add overlay configuration to profiles

- etc/vlc.profile
> Fix VLC GUI artifacts #1277

- etc/disable-common.inc
- src/firejail/sandbox.c
- fixes #1238 
- little layout improvement (I think) for disable-common.inc
> completing noexec

- etc/clementine.profile
> Clementine seccomp update

- etc/gnome-calculator.profile
> gnome-calculator profile fix

- src/floader/README.md
- src/floader/loader.c
- src/floader/makefile
Related to: https://github.com/netblue30/firejail/issues/1275#issuecomment-302434890
> added floader files

- etc/peek.profile
Profile for https://github.com/phw/peek a gif recorder
> Add profile for Peek

- etc/silentarmy.profile
Profile for https://github.com/mbevand/silentarmy a zcash miner
- private-bin prevents it from starting, probably due to python
- disable-devel.inc prevents it from accessing any GPUs, not sure why
> Add a profile for SILENTARMY

- etc/android-studio.profile
- etc/idea.sh.profile
Profile for the open source Java IDE, IntelliJ IDEA.
- The IDEA profile is for Community Edition, although it'd prob work with Ultimate/others with minor tweaks.
- Android Studio is based off of Community Edition. Did not test AVD emulator.
> Add profiles for IntelliJ IDEA and Android Studio

- etc/arduino.profile
- etc/jd-gui.profile
- etc/libreoffice.profile
- etc/multimc5.profile
- etc/pdfsam.profile
- etc/steam.profile
> Fix .java after e2449ae7d25925cec444ac08bbfb9cbc7199e647

- src/firejail/fs.c
noexec/read-only/read-write handling: copy underlying FS flags
before remounting. If the flags are already OK, don't remount unnecessarily.
> Improve mount handling

- etc/arm.profile
- src/firecfg/firecfg.config
profile for arm https://www.torproject.org/projects/arm.html.en
> Add a profile for arm

- src/firejail/x11.c
Fix for recent versions of `xpra` not working properly.
> Tentative implementation for #1405

- etc/firejail-default
This adds some additional whitelist paths in `/run/user` dir used by KDE plasma environment in file dialogs and inter-connectivity between apps. Those were detected by audit system logs.
```
AVC apparmor="ALLOWED" operation="mknod" profile="firejail-default" name="/run/user/1000/kmozillahelperBCjd35.1.slave-socket" pid=21758 comm="kmozillahelper" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
AVC apparmor="ALLOWED" operation="open" profile="firejail-default" name="/run/user/1000/kmozillahelperBCjd35.1.slave-socket" pid=21758 comm="kmozillahelper" requested_mask="wc" denied_mask="wc" fsuid=1000 ouid=1000
AVC apparmor="ALLOWED" operation="unlink" profile="firejail-default" name="/run/user/1000/kmozillahelperBCjd35.1.slave-socket" pid=21758 comm="kmozillahelper" requested_mask="d" …
```
> Apparmor: update whitelist path for kde

- Makefile.in
- etc/firejail-default
- etc/firejail-local
This adds possibility for local enchantments of firejail apparmor profile configuration. It's designed same way as in most upstream apparmor profiles.
> Apparmor: add local configuration

- etc/apktool.profile
- etc/baobab.profile
- etc/dex2jar.profile
- etc/gitg.profile
- etc/hashcat.profile
- etc/obs.profile
- etc/picard.profile
- etc/remmina.profile
- etc/sdat2img.profile
- etc/soundconverter.profile
- etc/sqlitebrowser.profile
- etc/truecraft.profile
I was unable to fully test TrueCraft due to https://github.com/SirCmpwn/TrueCraft/issues/268 , but the launcher and world generation seems to work fine.
> Add 8 new profiles

- etc/calibre.profile
- etc/mpv.profile
- etc/qbittorrent.profile
- etc/vlc.profile
- etc/wine.profile
- etc/wireshark.profile
Here are various fixes for calibre, mpv, qbittorrent, wireshark, wine and vlc profiles. All are tested by me. Explanations are in comments.
> various profile fixes

- etc/ark.profile
- etc/audacious.profile
- etc/baloo_file.profile
- etc/clementine.profile
- etc/disable-programs.inc
- etc/geary.profile
- etc/gwenview.profile
- etc/mediathekview.profile
- etc/okular.profile
- etc/scribus.profile
- etc/start-tor-browser.profile
- etc/thunderbird.profile
- more novideo options, without any systematics. Works as in _worksforme_
- blacklist the clementine database  and configuration
- better privacy for the tor-browser
> various little profile fixes and enhancements

- etc/tuxguitar.profile
sorry for the commit mess, thanks for your patience. Like this it is right finally.
> fix tuxguitar comments

- etc/smplayer.profile
this fixes smplayer if you use the mpv backend
> fix smplayer for mpv

- etc/torbrowser-launcher.profile
firejail profile for torbrowser-launcher
> firejail profile for torbrowser-launcher

- etc/k3b.profile
> unbreak k3b

- README.md
- RELNOTES
- etc/disable-programs.inc
- etc/musescore.profile
- platform/debian/conffiles
- src/firecfg/firecfg.config
https://github.com/musescore/MuseScore
> new MuseScore profile

- src/firejail/fs_bin.c
With Ubuntu 16.04, /usr/bin/which is a symlink to /bin/which. So, using "private-bin which" finds "which" in /usr/bin and adds the symlink to "which" in /bin mapped directory. The /bin directory thus contains a symlink named "which" pointing to "/bin/which" (itself). This creates a symlink loop, and does not work. In order to solve this, the full path can now be used, such as "private-bin /bin/which". This fixes #1133.
> Allow private-bin parameters to be absolute paths

- etc/disable-programs.inc
- etc/lollypop.profile
- etc/multimc5.profile
- etc/xonotic.profile
- MultiMC5 now has a 3rd path it uses
- Fix sound in Xonotic mentioned in #1492 
- Fix Lollypop not having certificate access
> Fix MulitMC5 and Xonotic

- etc/dnscrypt-proxy.profile
- etc/dnsmasq.profile
- etc/unbound.profile
Caused by a7f934325a3a4f8ca0dd35e5aaf38d309c46da00
> Fix logging for servers

- etc/disable-programs.inc
- etc/yandex-browser.profile
Closes #1517 and #1516 
The beta and stable versions seem to use the same executable name.
> Add a profile for Yandex Browser

- etc/spotify.profile
> Fix Spotify #1513

- etc/disable-programs.inc
- etc/itch.profile
I've not used itch.io but should we also remove whitelist? Do games actually store their configs in ~/.config/itch, or is itch purely a launcher and games can store wherever like Steam?
> Tweak itch.io profile

- smtube.profile
if you think private-bin needs to be there, feel free to edit the profile, and users would need to add their own players via the smtube.local file
> firejail profile for smtube

- etc/slack.profile
> Fix broken audio in Slack

- etc/disable-common.inc
- etc/mutt.profile
- ~~fixes #1454~~
- brings support for local mailbox
- makes blacklisting more robust
> localhost mail fix for mutt

- etc/7z.profile
- etc/atom.profile
- etc/bluefish.profile
- etc/calligra.profile
- etc/cin.profile
- etc/cinelerra.profile
- etc/cliqz.profile
- etc/dia.profile
- etc/evince.profile
- etc/hugin.profile
- etc/inox.profile
- etc/kdenlive.profile
- etc/libreoffice.profile
- etc/natron.profile
- etc/openshot-qt.profile
- etc/pinta.profile
- etc/scribus.profile
- etc/shotcut.profile
- etc/synfigstudio.profile
- etc/tar.profile
- etc/unrar.profile
- etc/unzip.profile
* Fixed Profiles: Kdenlive, Shotcut
* New Profile: Cinelerra, Cliqz, Bluefish
* Some hardening for some profiles
> Some profiles

- etc/gnome-ring.profile
Added profile for gnome-ring in /etc. Pretty much the same as the Skype profile.
> Add profile for gnome-ring

- etc/franz.profile
Starting with version 5.0.0 I had to remove this line, otherwise Franz would not start properly
> Update franz.profile to work with version 5 upwards

- etc/bnox.profile
- etc/dnox.profile
bnox and dnox doesnt work fine (i cant see my history, and my extensions)
> inox edgy flavours fix (doesnt work history and extensions)

- etc/sylpheed.profile
This profile have been successfully tested by sending and receiving an Email. "claws-mail.profile" has been used as template for this.
> Add "sylpheed" to profiles

- etc/disable-programs.inc
- etc/tor-browser-ar.profile
- etc/tor-browser-en-us.profile
- etc/tor-browser-en.profile
- etc/tor-browser-es-es.profile
- etc/tor-browser-es.profile
- etc/tor-browser-fa.profile
- etc/tor-browser-fr.profile
- etc/tor-browser-it.profile
- etc/tor-browser-ja.profile
- etc/tor-browser-ko.profile
- etc/tor-browser-pl.profile
- etc/tor-browser-pt-br.profile
- etc/tor-browser-ru.profile
- etc/tor-browser-vi.profile
- etc/tor-browser-zh-cn.profile
- etc/torbrowser-launcher.profile
all tor-browser langpacks
bugfixes:
* its posible run it with tor launcher, but i cant see my downloads
* personalized profiles (if we use a shared profile  we may get a data leak)
> tor flavours

- src/include/syscall.h
File generated by ../tools/extract_syscall, as per instructions
> add new syscalls from glibc 2.26-10

- README.md
- etc/abrowser.profile
- etc/bnox.profile
- etc/brave.profile
- etc/chromium-common.profile
- etc/chromium.profile
- etc/cliqz.profile
- etc/cyberfox.profile
- etc/dnox.profile
- etc/firefox-common-addons.inc
- etc/firefox-common.profile
- etc/firefox.profile
- etc/flashpeak-slimjet.profile
- etc/google-chrome-beta.profile
- etc/google-chrome-unstable.profile
- etc/google-chrome.profile
- etc/icecat.profile
- etc/iceweasel.profile
- etc/inox.profile
- etc/iridium.profile
- etc/opera-beta.profile
- etc/opera.profile
- etc/palemoon.profile
- etc/vivaldi.profile
- etc/waterfox.profile
- etc/yandex-browser.profile
> Unify all Chromium and Firefox based browser profiles

- etc/firejail-default
Fixes following erros:
wine:
```
AVC apparmor="DENIED" operation="unlink" profile="firejail-default" name="/run/firejail/profile/11526" pid=11533 comm="wine" requested_mask="d" denied_mask="d" fsuid=1000 ouid=0
AVC apparmor="DENIED" operation="unlink" profile="firejail-default" name="/run/firejail/profile/5807" pid=11533 comm="wine" requested_mask="d" denied_mask="d" fsuid=1000 ouid=0
AVC apparmor="DENIED" operation="unlink" profile="firejail-default" name="/run/firejail/profile/2017" pid=11533 comm="wine" requested_mask="d"
```
cups:
```
AVC apparmor="DENIED" operation="connect" profile="firejail-default" name="/run/cups/cups.sock" pid=11682 comm="lpr" requested_mask="w" denied_mask="w" fsuid=1000 ouid=0
AVC apparmor="DENIED" operation="connect" profile="firejail-default" …
```
> Apparmor: fix various denials

- etc/disable-programs.inc
- etc/vivaldi-snapshot.profile
> Add a profile for Vivaldi Snapshot

- etc/bibletime.profile
- etc/disable-common.inc
- etc/viewnior.profile
- etc/xiphos.profile
@Fred-Barclay, request created, thanks.
[FYI](https://github.com/netblue30/firejail/pull/1783)
> .Xauthority moved from blacklist to read-only

- src/libtrace/libtrace.c
https://github.com/gentoo/musl/issues/109
> Fix compilation with musl

- etc/disable-programs.inc
- etc/gnome-recipes.profile
Not a very widely used app perhaps, but tasty nonetheless... Leaving out the `private-lib` part, as per the comment inside. I noticed some issues regarding `private-lib` and Gnome apps in general, [evince](https://github.com/netblue30/firejail/issues/1711) in particular. Will open a new issue on that shortly, I *think* I made some progress in that regard. More eyes needed though.
> gnome-recipes profile

- README.md
- RELNOTES
- etc/blender-2.8.profile
- etc/thunderbird-beta.profile
- src/firecfg/firecfg.config
Adding profiles for thunderbird-beta and blender-2.8
Solving #1833 and #1834
> Adding thunderbird-beta and Blender-28

- etc/gnome-calculator.profile
The fix is there, tried & tested. [Issue #1841 ](https://github.com/netblue30/firejail/issues/1841) can be closed.
> Fix private-lib

- etc/musixmatch.profile
> Add support for the devil musixmatch

- etc/arduino.profile
- etc/jd-gui.profile
- etc/pycharm-community.profile
- etc/steam.profile
- etc/terasology.profile
- etc/zaproxy.profile
based on the presence of `noblacklist ${HOME}/.java`. I would merge if no one spots a false positive (Steam?)
> allow java in some more profiles

- etc/android-studio.profile
Current profile denies access to /dev/kvm.
> Enable KVM on Android Studio

- etc/disable-programs.inc
- etc/gajim.profile
- Version 1 ported to Python 3, so remove 2.7-related settings
- Plugins get installed in ~/.local/share/gajim/plugins
- Enable private-{etc,tmp}
> Update Gajim profile

- src/firejail/fs_whitelist.c
> priv tweak

- etc/webstorm.profile
- Add Android development-related paths
- Don't blacklist node/nvm for e.g. Node.js-related development
- Remove noexec from /tmp for e.g. same Node.js case
> Amend WebStorm profile

- src/firejail/firejail.h
- src/firejail/fs.c
- src/firejail/main.c
- src/firejail/profile.c
- src/firejail/usage.c
- src/man/firejail-profile.txt
- src/man/firejail.txt
> Add --keep-var-tmp and associated profile option

- etc/tor-browser-en.profile
- etc/torbrowser-launcher.profile
tar and xz are needed on first run.
> Create tor-browser-en directory, add missing bin programs

- etc/chromium-common.profile
- etc/discord-common.profile
- etc/firefox-common.profile
This should fix https://github.com/netblue30/firejail/issues/2006.
> include globals.local only once

- etc/enox.profile
- etc/snox.profile
can you add this for  support my changes?
snox comes from https://en.wikipedia.org/wiki/SNOX_process
> i'm modifying inox-hard (aur)  

- etc/geary.profile
- etc/gradio.profile
For geary, look at issue #2018. **Ignore dbus** does not work, it is necessary to **ignore nodbus** for launch geary.
Thanks.
> Creating the gradio profile and editing the geary profile

- src/firejail/fs_whitelist.c
- src/firejail/util.c
Two commits with a relatively large diff, take your time to review. Also contains quite some nitpicking.
> additional whitelist hardening

- etc/ktorrent.profile
Because otherwise it can't work.
> Add netlink protocol

- src/firejail/appimage_size.c
These changes specifically allow the `61.0.1.glibc2.7` version of the firefox appimage to run successfully.  Currently firejail errors out printing that the ELF size is 0 and its an appimage type 1, both of which are incorrect.  I've updated for both 32 and 64-bit appimages, but I've only tested with this 64-bit one (which loads the appimage successfully, but I can't get a successful connection).  But I believe my copy/paste skills are up to par.
This can be tested with the appimage here:
https://bintray.com/probono/AppImages/Firefox/61.0.1.glibc2.7#files
> Update appimage size calculation to newest code from libappimage.

- src/firejail/firejail.h
- src/firejail/fs.c
- src/firejail/sandbox.c
> allow overriding of disable-mnt with noblacklist

- etc/aria2c.profile
- etc/disable-programs.inc
This program hasn't got a GUI (at least not in aria2c itself), so no need to add it to firecfg I guess.
Regards.
> New profile aria2c

- etc/devilspie2.profile
- etc/disable-programs.inc
This successor to devilspie works rather smoothly. I have been using it for quite some time without hiccups, so I thought it was time to add a firejail profile.
Regards.
> New profile devilspie2

- etc/devilspie.profile
- etc/disable-programs.inc
This is the older version, not to be confused with devilspie2. Offers a few extra's that aren't in devilspie2, so it might be of interest to people still (especially because it has a GUI called gdevilspie, which I'm working on to add to the profiles).
Regards.
> New profile devilspie

- etc/disable-programs.inc
- etc/easystroke.profile
- src/firecfg/firecfg.config
Feeling nostalgic, so here's another 'oldie' gem for the firejail collection.
Regards.
> New profile easystroke

- etc/disable-programs.inc
- etc/min.profile
- src/firecfg/firecfg.config
Can't try a new(ish) web browser without a firejail profile...
Regards.
> New profile min

- etc/lbunzip2.profile
- etc/lbzcat.profile
- etc/lbzip2.profile
These should complete known gzip aliases.
> Add gzip aliases

- etc/lzcat.profile
- etc/lzcmp.profile
- etc/lzdiff.profile
- etc/lzegrep.profile
- etc/lzfgrep.profile
- etc/lzgrep.profile
- etc/lzip.profile
- etc/lzless.profile
- etc/lzma.profile
- etc/lzmainfo.profile
- etc/lzmore.profile
- etc/unlzma.profile
- etc/unxz.profile
- etc/xzcat.profile
- etc/xzcmp.profile
- etc/xzdiff.profile
- etc/xzegrep.profile
- etc/xzfgrep.profile
- etc/xzgrep.profile
- etc/xzless.profile
- etc/xzmore.profile
Another round of aliases, for `cpio` this time.
> Add some more cpio aliases

- etc/baloo_file.profile
- etc/disable-common.inc
- src/firejail/firejail.h
- src/firejail/fs.c
- src/firejail/mountinfo.c
- src/firejail/pulseaudio.c
- src/firejail/x11.c
Discussion still ongoing in #2200.
> experimental: remounts child mount points as well

- etc/whois.profile
Moved `quiet` option below newly added description for consistency.
> Reorganize whois.profile

- etc/gpg.profile
These changes should fix https://github.com/netblue30/firejail/issues/2242.
> Fix gpg.profile for Arch users

- etc/mpsyt.profile
new profile, application mpsyt.
I based it on mpv profile. It seams to work fine.
> new profile mpsyt.profile

- etc/mpsyt.profile
Of course i got it wrong XD
Restricting HOME and tmp in mpsyt.profile
> restricting more, HOME and tmp in mpsyt.profile

- etc/thunderbird-wayland.profile
- src/firecfg/firecfg.config
Add a profile for thunderbird-wayland and enable ist for firecfg.
> Add a profile for thunderbird-wayland

- etc/atom.profile
- etc/bibletime.profile
- etc/brackets.profile
- etc/disable-common.inc
- etc/disable-programs.inc
- etc/gnome-builder.profile
- etc/rhythmbox.profile
Add some missing paths to disable-programs.inc and add some paths to disable-common.inc.
<br><br>
By the way, what about the paths of programs for which there is no profile, can you simply add them? (e.g. zim, tilix, aqemu, eclipse,...)
> Update disable-common.inc, disable-programs.inc.

- etc/gajim-history-manager.profile
- etc/gajim.profile
On my system (F29) gajim only starts if it has access to the user default shell.
> Fix gajim.profile

- etc/disable-programs.inc
- etc/ghostwriter.profile
- src/firecfg/firecfg.config
Add a profile for ghostwriter.
Ghostwriter is a text editor for Markdown.
> Add a profile for ghostwriter

- etc/libreoffice.profile
I made a presentation with impress. The presentation contains a video. The video also worked but when machine-id is on, the sound doesn't work.
> comment `machine-id` in libreoffice.profile

- etc/github-desktop.profile
- src/firecfg/firecfg.config
These changes are a response to https://github.com/netblue30/firejail/issues/2361. Please wait to merge until approved by people contributing to that issue.
Regards
> Refactoring github-desktop profile and firecfg

- etc/firefox-common.profile
- etc/kodi.profile
- etc/youtube-dl.profile
We are probably missing more, feel free to commit directly to this branch
Closes #2385, #2383, #2380, #2378, #2375
> Temporary fix for noexec ${HOME} breakage

- Makefile.in
- etc/firejail-local
- src/man/firejail.txt
**Please don't merge before someone truly competent in Makefile writing approves this**.
Fixes https://github.com/netblue30/firejail/issues/2388.
> Retain local apparmor customizations

- etc/keepassxc.profile
a few fixes for auto-type in keepassxc.
> changes fixing keepassxc auto-type

- etc/snap.profile
Probably not the best of descriptions, suggestions welcome.
> Fix snap.profile description

- etc/webui-aria2.profile
[webui-aria2](https://github.com/ziahamza/webui-aria2) is a popular UI
for the aria2 download manager.
> Added profile for webui-aria2

- etc/transmission-cli.profile
- etc/transmission-create.profile
- etc/transmission-daemon.profile
- etc/transmission-edit.profile
- etc/transmission-gtk.profile
- etc/transmission-qt.profile
- etc/transmission-remote-cli.profile
- etc/transmission-remote-gtk.profile
- etc/transmission-remote.profile
- etc/transmission-show.profile
- src/firecfg/firecfg.config
This PR hardens existing transmission profiles and creates a few missing redirect profiles.
> Refactor Transmission profiles

- etc/devhelp.profile
Support older versions shipped by some distributions.
> Fix devhelp

- src/firecfg/desktop_files.c
Was that comment meant to say "convert"?
> Fix possible typo

- etc/lrunzip.profile
- etc/lrz.profile
- etc/lrzcat.profile
- etc/lrzip.profile
- etc/lrztar.profile
- etc/lrzuntar.profile
- etc/zpaq.profile
- src/firecfg/firecfg.config
Implemented as redirect profiles for cpio. I'll add a note to https://github.com/netblue30/firejail/issues/2507 for these.
> Add new profiles for lrzip and friends

- etc/gucharmap.profile
Thanks to @SkewedZeppelin's review of https://github.com/netblue30/firejail/pull/2566 for catching this sillyness on my part.
> Drop private-home from gucharmap profile

- etc/seahorse-tool.profile
- etc/seahorse.profile
Let's support user's GTK theme in seahorse GUI.
> Fixes for seahorse/seahorse-tool

- RELNOTES
- etc/disable-programs.inc
- etc/pycharm-community.profile
- src/man/firejail.txt
Edit relevant some files in relation to removal of snap support. See 
https://github.com/netblue30/firejail/pull/2402 and https://github.com/netblue30/firejail/issues/2397. Might help to un-confuse users/avoid irrelevant issues being filed on this topic.
There could be additional work needed/wanted in https://github.com/netblue30/firejail/src/faudit/pid.c - where snap is handled, but flatpak isn't. No clue if that is at all possible and shouldn't affect functionality as far as I can ascertain.
> Follow-up on flatpak/snap support

- etc/gnome-chess.profile
see dependencies on https://www.archlinux.org/packages/extra/x86_64/gnome-chess/
> add gnuchess to play against computer

- README
- etc/gnome-logs.profile
mdwe fully break the application.
> Fix gnome-logs.profile

- etc/Builder.profile
- etc/Logs.profile
- etc/Maps.profile
- etc/clocks.profile
- src/firecfg/desktop_files.c
- src/firecfg/firecfg.config
Until a proper fix for #2624 is implemented, lets introduce a **temporary** workaround.
> Temp fix firecfg

- etc/electrum.profile
> fixed electrum not resolving domains

- etc/min.profile
Under the hood min is based on chromium. Lets adjust the min profile so it supports chrome-sandbox.
> Refactor min as chromium redirect profile

- etc/bitwarden.profile
Thanks @rusty-snake for catching this. Old habits die hard...
> Drop noblacklist ${DOWNLOADS} in bitwarden.profile

- src/firejail/dbus.c
- src/firejail/firejail.h
- src/firejail/sandbox.c
- src/man/firejail.txt
Signed-off-by: Topi Miettinen <toiwoton@gmail.com>
> dbus: make --nodbus block also system D-Bus socket

- etc/artha.profile
- etc/clipit.profile
- etc/devilspie.profile
- etc/devilspie2.profile
- etc/exfalso.profile
- etc/pavucontrol.profile
- etc/pdftotext.profile
- etc/redshift.profile
- etc/soundconverter.profile
This should (slightly) harden the sandbox for a few applications that seem fit to be re-written as whitelist profiles.
> Refactoring as whitelist profile

- etc/feh-network.inc
- etc/seahorse.profile
These got overlooked by https://github.com/netblue30/firejail/pull/2766 it seems.
> More sorting private-etc

- etc/spotify.profile
Fixes #2760 (Thank you rusty-snake)
- add commands to the private-bin line
- add a comment that inform of the lack of the radio and albums covers unless the user comments the private-etc line
> Fix spotify.profile

- src/firejail/fs.c
- src/firejail/sandbox.c
a precondition for using proc magic links in the early phase of sandbox setup
> mount new proc filesystem earlier

- src/firejail/x11.c
Try fixing https://github.com/netblue30/firejail/issues/2787. While going over src/firejail/x11.c I also corrected a few typo's and added missing install instructions for Arch where relevant.
> Silence xauth output in src/firejail/x11.c

- etc/udiskie.profile
This prevents from seeing Fontconfig error in udiskie output.
> Add fonts to private-etc in udiskie profile

- etc/arch-audit.profile
- etc/archaudit-report.profile
- etc/aria2c.profile
- etc/curl.profile
- etc/dnscrypt-proxy.profile
- etc/wget.profile
Sorry for breaking things temporarily. Thanks to @rusty-snake for catching this.
> Revert #2816 (except gconf-editor)

- etc/riot-desktop.profile
Making a PR of @rusty-snake 's fix.
> Fixes #2821, riot-desktop

- etc/firejail.config
- src/firejail/checkcfg.c
- src/firejail/firejail.h
- src/firejail/fs.c
- src/firejail/fs_home.c
- src/firejail/fs_whitelist.c
- src/firejail/main.c
- src/firejail/restrict_users.c
whitelisting is still half broken in some cases (when home directory is in one of the other allowed top level directories), but the workarounds are getting easier :)
> improve support for home directories outside /home

- etc/conplay.profile
- etc/mpg123-alsa.profile
- etc/mpg123-id3dump.profile
- etc/mpg123-jack.profile
- etc/mpg123-nas.profile
- etc/mpg123-openal.profile
- etc/mpg123-oss.profile
- etc/mpg123-portaudio.profile
- etc/mpg123-pulse.profile
- etc/mpg123-strip.profile
- etc/mpg123.bin.profile
- etc/out123.profile
- src/firecfg/firecfg.config
Follow-up for https://github.com/netblue30/firejail/commit/f874afd8c7e998a57528c3d5a34a4558c6b7f0a6.
> Add redirects for mpg123

- etc/disable-programs.inc
- etc/itch.profile
itch now also uses ~/.itch for application updates
> Update itch profile

- etc/slack.profile
Fixes slack in fedora (addition to https://github.com/netblue30/firejail/commit/08c67ad01037f9fc74f587ba69953c65e2f12128)
> Fix #2866 -- private-etc needed fedora-release

- etc/mpv.profile
${PICTURES} should be accessible to mpv.
> added 'noblacklist ${PICTURES}' to mpv.profile

- etc/7za.profile
- etc/7zr.profile
- etc/acat.profile
- etc/adiff.profile
- etc/als.profile
- etc/apack.profile
- etc/arepack.profile
- etc/aunpack.profile
- etc/lrunzip.profile
- etc/lrz.profile
- etc/lrzcat.profile
- etc/lrzip.profile
- etc/lrztar.profile
- etc/lrzuntar.profile
- etc/p7zip.profile
- etc/zpaq.profile
> Fix quiet option in archiver redirect profiles

- etc/atom.profile
- etc/code.profile
- etc/disable-programs.inc
- etc/emacs.profile
- etc/geany.profile
- etc/gedit.profile
- etc/git.profile
- etc/gnome-builder.profile
- etc/gnome-schedule.profile
- etc/gnome-system-log.profile
- etc/mutt.profile
- etc/nethack-vultures.profile
- etc/pluma.profile
- etc/ppsspp.profile
- etc/pycharm-community.profile
- etc/qutebrowser.profile
- etc/scallion.profile
- etc/seahorse-tool.profile
- etc/seahorse.profile
- etc/steam.profile
- etc/vim.profile
- etc/wine.profile
- etc/xed.profile
- etc/xmr-stak.profile
Fix `noblacklist SOME` in profiles, where never is a `blacklist SOME`.
Program: https://gist.github.com/rusty-snake/9035b6d9330968322356918a7834eb86
> noblacklist but no blacklist

- src/fseccomp/syscall.c
- src/man/firejail.txt
Get further seccomp group definitions from systemd.
> Add further seccomp groups

- etc/Viber.profile
- etc/akonadi_control.profile
- etc/akregator.profile
- etc/baloo_file.profile
- etc/basilisk.profile
- etc/bibletime.profile
- etc/brackets.profile
- etc/clementine.profile
- etc/falkon.profile
- etc/firefox-common.profile
- etc/kiwix-desktop.profile
- etc/kmail.profile
- etc/mpd.profile
- etc/palemoon.profile
- etc/qgis.profile
- etc/qutebrowser.profile
- etc/riot-desktop.profile
- etc/simple-scan.profile
- etc/skanlite.profile
- etc/skypeforlinux.profile
- etc/standardnotes-desktop.profile
- etc/start-tor-browser.profile
- etc/teamspeak3.profile
- etc/torbrowser-launcher.profile
Use the new seccomp-syntax from #2926
> Use new seccomp syntax

- etc/skypeforlinux.profile
> Update SkypeForLinux profile for latest version

- etc/code.profile
In my opinion "Netfilter" option is enough, but "net none" option breaks functionality of marketplace.
> "Net None" Option Breaks Functionality

- .gitlab-ci.yml
- contrib/sort.py
> Adding sort.py to GitLab CI

- etc/waterfox-classic.profile
- etc/waterfox-current.profile
- etc/waterfox.profile
- src/firecfg/firecfg.config
> Rework waterfox profile

- etc/calibre.profile
- etc/ebook-viewer.profile
> Fix ebook-viewer/calibre on manjaro

- etc/slack.profile
> Slack profile: use temporary cache

- etc/dia.profile
Even though it is written in C, maybe another fix would be better
> dia apparently wants access to python and crashes without

- etc/disable-programs.inc
- etc/electron-mail.profile
- src/firecfg/firecfg.config
Fixes #3052. Thanks @rusty-snake for the seccomp filter.
> Add new electron-mail profile

- etc/profanity.profile
My profile for profanity. Comments welcome.
> Add profanity profile

- etc/audio-recorder.profile
- src/firecfg/firecfg.config
https://launchpad.net/~audio-recorder
> New profile: audio-recorder

- etc/cameramonitor.profile
- src/firecfg/firecfg.config
https://launchpad.net/cameramonitor
> Add new profile: cameramonitor

- etc/ddgtk.profile
- src/firecfg/firecfg.config
https://github.com/gort818/ddgtk
> Add new profile: ddgtk

- etc/disable-programs.inc
- etc/drawio.profile
- src/firecfg/firecfg.config
https://github.com/jgraph/drawio-desktop
> Add new profile: drawio

- etc/disable-programs.inc
- etc/gmpc.profile
- src/firecfg/firecfg.config
> Add new profile: gmpc

- etc/unf.profile
- src/firecfg/firecfg.config
> Add new profile: unf

- README.md
- RELNOTES
- etc/disable-programs.inc
- etc/gist.profile
- src/firecfg/firecfg.config
https://github.com/defunkt/gist
> Add new profile: gist

- etc/firefox-wayland.profile
- etc/thunderbird-wayland.profile
thunderbird-wayland profile did not include thunderbird-wayland.local
> Minor profile tweaks.

- etc/gpg-agent.profile
- etc/gpg.profile
- etc/gpg2.profile
Add `quiet` option to gpg{,-agent}.profile files and introduce gpg2 redirect profile.
> gpg additions

- etc/mpv.profile
> Fix wusc in mpv

- etc/qutebrowser.profile
@D-Nice @f4814 @q3cpma can someone confirm that this profile works.
> Get rid of #2302

- etc/claws-mail.profile
- etc/curl.profile
- etc/devilspie.profile
- etc/devilspie2.profile
- etc/dig.profile
- etc/dnscrypt-proxy.profile
- etc/easystroke.profile
- etc/enchant.profile
- etc/exfalso.profile
- etc/wget.profile
Based on daily used .local files on Arch and Ubuntu. I would appreciate a review before merging. TIA.
> hardenings for various profiles

- README
- platform/debian/copyright
- platform/rpm/mkrpm.sh
- test/network/interface.exp
This should finalize the copyright move to 2020.
> move copyright statement to 2020 (part 3)

- etc/udiskie.profile
> Allow request_key syscall for udiskie

- etc/allow-common-devel.inc
- etc/allow-java.inc
- etc/allow-lua.inc
- etc/allow-perl.inc
- etc/allow-python2.inc
- etc/allow-python3.inc
- etc/allow-ruby.inc
We have disable-*.inc including disable-*.local but we don't have a similar routine for the counterpart allow-*.inc files. Simple PR to implement this.
> allow-*.local customizations

- etc/bibtex.profile
- etc/disable-programs.inc
- etc/gummi.profile
- etc/latex-common.profile
- etc/latex.profile
- etc/pdflatex.profile
- etc/tex.profile
- src/firecfg/firecfg.config
This is just a suggestion, hope it helps.
Cheers
> Add profiles for common (la)tex commands

- etc/transmission-common.profile
As discussed in https://github.com/netblue30/firejail/pull/3159#discussion_r372360381
> fix missing global include documentation

- .gitignore
- contrib/fix_private-bin.py
Added typing.
Replaced os.path with pathlib.
Made it work.
Fixes in .gitignore.
> Fixes for fix_private-bin.py

- etc/allow-lua.inc
- etc/disable-interpreters.inc
> additional Lua blacklisting

- etc/conky.profile
> conky needs lua

- etc/thunderbird.profile
> thunderbird.profile: harden and enable the rules necessary to make Firefox open links

- etc/firejail.config
No functionality changes, just some more alphabetical ordering. Nevertheless I would appreciate a review, as this file is pretty damn important.
> Alphabetically order firejail.config

- .github/ISSUE_TEMPLATE/bug_report.md
Do not miss firejail --noprofile PROGRAM as default bug reporter input.
> Request behavior change description in bug reports

- etc/disable-programs.inc
- etc/jitsi-meet-desktop.profile
- src/firecfg/firecfg.config
Profile for the Jitsi (https://jitsi.org/jitsi-meet/) desktop app. Jitsi works with this profile on my machine.
> Profile for jitsi-meet-desktop 

- etc/profile-a-l/caja.profile
- etc/profile-a-l/dolphin.profile
- etc/profile-a-l/file-manager-common.profile
- etc/profile-m-z/Thunar.profile
- etc/profile-m-z/nautilus.profile
- etc/profile-m-z/nemo.profile
- etc/profile-m-z/pcmanfm.profile
- etc/profile-m-z/ranger.profile
Pretty straightforward PR. No functional changes.
> file managers refactoring

- .github/ISSUE_TEMPLATE/bug_report.md
interaction with other programs, profile existence, lookup for installed profiles and user investigation on related problems
> bug_template: more specific information

- Makefile.in
Don't build all filters many times over but instead let them be built
in parallel.
Closes #3393
> Build improvements

- README.md
First attempt to tackle some of the issues that came up in #3440.
> prioritize installing via OS

- README
- README.md
- RELNOTES
https://github.com/netblue30/firejail/pull/3459#issuecomment-643795928
> Add strawberry profile to README{,.md} & RELNOTES

- Makefile.in
- mketc.sh
let's update the installed disable-common.inc, rather than the file in the repo.
> fixing busybox workaround

- src/firejail/util.c
This avoids/fixes the issue reported in #3500 .
> Ignore SIGTTOU during flush_stdin()

- etc/inc/disable-programs.inc
- etc/profile-m-z/nuclear.profile
- src/firecfg/firecfg.config
[Nuclear](https://github.com/nukeop/nuclear/)
> Added Nuclear profile

- etc/inc/disable-programs.inc
- etc/profile-m-z/minitube.profile
- src/firecfg/firecfg.config
Request: # 1139
This needs to be merged before I push profiles for apps from the same author. They all have common directory `Flavio Tordini`
> Added minitube profile

- src/firejail/bandwidth.c
* add extra checks to defend against command injection (strings are already controlled by Firejail, so this should be redundant and only for the paranoid)
* run shell in a minimal sandbox
> harden bandwidth command

- etc/profile-m-z/signal-desktop.profile
Signal is adding support for video calls on desktop, see
https://signal.org/blog/desktop-calling-beta/
> Allow video for Signal profile

- etc/inc/disable-programs.inc
- etc/profile-a-l/fractal.profile
- etc/profile-m-z/mirage.profile
- etc/profile-m-z/quaternion.profile
- etc/profile-m-z/spectral.profile
- src/firecfg/firecfg.config
- [mirage](https://github.com/mirukana/mirage)
- [Quaternion](https://github.com/quotient-im/Quaternion) # 1139
- [Spectral](https://gitlab.com/spectral-im/spectral)
- fractal # 1139
> Various profiles # 2

- etc/profile-m-z/mpv.profile
- etc/profile-m-z/smplayer.profile
> Fixes smplayer

- etc/inc/disable-programs.inc
- etc/profile-a-l/electron-mail.profile
- etc/profile-a-l/geary.profile
- etc/profile-m-z/minitube.profile
https://imgur.com/nKwR29x
Does someone want to make this a redirect to electron too, it'd be easier to manage that way since most of them are such...?
> Fix private-etc of electron-mail, fix geary,minitube

- etc/profile-a-l/claws-mail.profile
- etc/profile-a-l/email-common.profile
Add some dbus comments/options to our claws-mail profile.
> Dbus fixes

- src/firejail/fs_lib.c
- test/profiles/profiles.sh
> install libraries needed by fcopy when using private-lib

- src/firejail/ls.c
> reimplement --get using --cat

- src/firejail/util.c
Kernel 5.6 added a new system call [openat2](https://man7.org/linux/man-pages/man2/openat2.2.html) which can help us in dealing with symbolic links.
`safe_fd()` also had a tiny bug where the root directory would be opened with the wrongs flags. While not very relevant to current Firejail, fixing it allowed sorting instructions in a different and imho slightly more logic way.
> use openat2 syscall when available

- etc/profile-m-z/sysprof.profile
A bit of hardening:
- refactored as whitelist profile
- enable help menu functionality
- add specific dbus-user filtering
> harden sysprof

- etc/profile-a-l/gzip.profile
- etc/profile-m-z/tar.profile
I broke the gzip and tar test trying to make these profiles as tight as possible. Apparently overdid things. Let's revert.
> archiver fixes

- etc/profile-a-l/liferea.profile
- enable novideo
- dbus filtering
> harden liferea

- etc/profile-a-l/atom.profile
- etc/profile-m-z/tutanota-desktop.profile
Remove doubled options in electron redirect profiles.
> electron redirect fixes

- Makefile.in
- src/fcopy/Makefile.in
- src/fcopy/main.c
- src/firejail/firejail.h
- src/firejail/fs_lib.c
- src/firejail/fs_lib2.c
- src/firejail/main.c
- src/firejail/util.c
- src/fldd/Makefile.in
- src/fldd/main.c
- src/fnet/Makefile.in
- src/fnet/main.c
- src/fnetfilter/Makefile.in
- src/fnetfilter/main.c
- src/fsec-optimize/Makefile.in
- src/fsec-optimize/fsec_optimize.h
- src/fsec-optimize/main.c
- src/fsec-print/Makefile.in
- src/fsec-print/fsec_print.h
- src/fsec-print/main.c
- src/fseccomp/Makefile.in
- src/fseccomp/fseccomp.h
- src/fseccomp/main.c
- src/include/common.h
- src/lib/common.c
(hopefully) fixes the issues that led to reverting
commits 6abb65d328af61d67361890743190bd4c57f8e3c and 98e42dc6da4e4b1e47ed2aa020012d4dedc1e80e
> return to non-dumpable plugins

- etc/profile-m-z/newsboat.profile
solves issue #3894 
- add support to spawn lynx browser
- options taken from issue #3312
> newsboat: add lynx support

- etc/inc/disable-programs.inc
- etc/profile-a-l/google-earth-pro.profile
- etc/profile-a-l/google-earth.profile
> refactor google-earth{-pro}

- etc/profile-a-l/blackbox.profile
- etc/profile-a-l/fluxbox.profile
- etc/profile-a-l/i3.profile
- etc/profile-a-l/krunner.profile
- etc/profile-m-z/openbox.profile
Streamlining some comments. No functional changes.
> Misc comment fixes

- etc/profile-a-l/aosp.profile
- etc/profile-a-l/gnome-builder.profile
He Who Is Blind Shall Not Make Foolish Edits. A big thanks @rusty-snake for saving the bacon :-)
> revert #3920

- etc/inc/firefox-common-addons.inc
- etc/profile-a-l/alacarte.profile
- etc/profile-a-l/celluloid.profile
- etc/profile-a-l/dia.profile
- etc/profile-a-l/file-manager-common.profile
- etc/profile-a-l/fractal.profile
- etc/profile-a-l/gummi.profile
- etc/profile-a-l/hexchat.profile
- etc/profile-a-l/jumpnbump-menu.profile
- etc/profile-a-l/kazam.profile
- etc/profile-a-l/lyx.profile
- etc/profile-m-z/meld.profile
- etc/profile-m-z/menulibre.profile
- etc/profile-m-z/mirage.profile
- etc/profile-m-z/mpv.profile
- etc/profile-m-z/nicotine.profile
- etc/profile-m-z/onboard.profile
- etc/profile-m-z/pkglog.profile
- etc/profile-m-z/playonlinux.profile
- etc/profile-m-z/smplayer.profile
- etc/profile-m-z/straw-viewer.profile
- etc/profile-m-z/totem.profile
- etc/profile-m-z/youtube-viewer.profile
> streamline 'Allow xxx' comments

- etc/inc/disable-programs.inc
- etc/profile-a-l/calligra.profile
- etc/profile-a-l/calligragemini.profile
- src/firecfg/firecfg.config
Gemini is part of Calligra's office suite.
> Add profile for Gemini

- etc/inc/archiver-common.inc
- etc/profile-a-l/7z.profile
- etc/profile-a-l/ar.profile
- etc/profile-a-l/atool.profile
- etc/profile-a-l/bsdtar.profile
- etc/profile-a-l/cpio.profile
- etc/profile-a-l/gzip.profile
- etc/profile-m-z/tar.profile
- etc/profile-m-z/unrar.profile
- etc/profile-m-z/unzip.profile
- etc/profile-m-z/xzdec.profile
- etc/profile-m-z/zstd.profile
```console
* archivers: move archiver-common.inc include to the bottom
* archivers: wrap comments
```
Cc: @glitsj16 (as the author of archiver-common.inc)
---
Note: As mentioned on #3845, please don't squash any commits; use normal merge
or rebase instead.
> Organize archivers

- etc/profile-a-l/jitsi-meet-desktop.profile
> fix private-bin in jitsi-meet-desktop

- README.md
- RELNOTES
- etc/profile-a-l/lzop.profile
Somehow this archiver alias got overlooked.
> new profile: lzop

- etc/profile-a-l/ipcalc-ng.profile
- etc/profile-a-l/ipcalc.profile
```console
* ipcalc-ng.profile: fix double globals.local include
* ipcalc.profile: move allow include to proper place
```
Some misc issues that I noticed when pulling on master.
> ipcalc: misc fixes

- README.md
- RELNOTES
- etc/profile-a-l/gget.profile
See https://gget.io/ for details of the application.
> add new profile for gget

- src/firejail/fs_lib.c
Ensure that libraries are loaded from below a default ld.so search path
It is reasonable for firejail to expect that unprivileged users have
no write permission on these paths; lax permissions there would
mean that the system is probably screwed anyway.
A somewhat similar check exists already in `private-bin` : https://github.com/netblue30/firejail/blob/3565217343a64b71c60e376053dda6af1bfff42f/src/firejail/fs_bin.c#L166
From a functional perspective this should be no limitation, because
`private-lib` not need to bother about libraries from paths that are
not masked in the end.
> private-lib hardening

- etc/profile-a-l/firefox-common-addons.profile
adding support for "play with..." extension. It uses a clever hack, so it doesn't need an external application in order to launch mpv.
Also trimmed ff2mpv comment block.
and added .cache/youtube-dl
> adding support for "play with..." extension

- src/firejail/fs_lib.c
- src/firejail/fs_lib2.c
- src/lib/ldd_utils.c
Currently depends on #4043 (hopefully that makes sense)
Closes #3980
> private-lib: move to mount-only

- etc/profile-a-l/atril.profile
#4066
adding cbz, cbr, cbt, cb7
> atril support for cbz, cbr, cbt, cb7

- etc/inc/disable-programs.inc
- etc/profile-m-z/telegram.profile
- etc/profile-m-z/virtualbox.profile
- etc/profile-m-z/youtube-dl-gui.profile
- src/firecfg/firecfg.config
`private-bin` for telegram & virtualbox tested on `Arch Linux` & works pretty well. But don't know about other distro's, that's why I  commented out those lines.
> Add profile for youtube-dl-gui & some other changes

- etc/profile-a-l/engrampa.profile
> fixing dbus filtering for engrampa

- etc/inc/disable-programs.inc
- etc/profile-m-z/youtube-viewer.profile
EDIT: and noblacklist in .profile
> [minor] .cache/youtube-viewer in disable-programs.inc

- etc/apparmor/firejail-default
- etc/apparmor/firejail-local
Try to be more specific in out apparmor comments. Hopefully this will avoid issues like #4147.
> Improve comments in apparmor files

- etc/profile-a-l/librewolf-nightly.profile
- src/firecfg/firecfg.config
Librewolf with Firefox Nightly base
https://aur.archlinux.org/packages/librewolf-nightly/
> New profile: Librewolf Nightly

- etc/inc/disable-programs.inc
- etc/profile-m-z/steam.profile
Games added:
* Don't Starve
* Dungeons of Dredmor
* Epic
* Loop Hero
* Pillars of Eternity I
* Rogue Legacy I
* Slay the Spire modding
* Steam World Dig I & II
> steam: some more games added

- etc/inc/disable-programs.inc
- etc/profile-a-l/firedragon.profile
- src/firecfg/firecfg.config
Adding a profile for [FireDragon](https://forum.garudalinux.org/t/firedragon-librewolf-fork/5018), a Librewolf fork.
> Add FireDragon profile

- contrib/sort.py
Support "+", "-" and "=" prefixes (introduced in cddc4832 + 5ffd9287)
> Rework sort_protocol (sort.py)

- etc/profile-a-l/firefox.profile
As suggested by @smitsohu in [this thread](https://github.com/netblue30/firejail/issues/4206#issuecomment-824806968).
> add FAQ references to firefox.profile

- src/firejail/fs_etc.c
Gosh it's been a while since I wrote C, and this solution turned out to use more pointer-manipulation that I'd hoped to. I wanted to avoid allocations, but this solution... I don't like it.
But since I already wrote it, and it seems to work, I thought I'd add a PR and you can take a look to see if it's anything to keep.
Fixes #3991
> Add support for subdirs in private-etc

- etc/profile-m-z/wireshark.profile
Fixes https://github.com/netblue30/firejail/issues/4241.
> Disable seccomp in wireshark profile

- etc/profile-a-l/git-cola.profile
- etc/profile-a-l/gnome-logs.profile
- etc/profile-a-l/gnome-system-log.profile
- etc/profile-m-z/yelp.profile
Thanks to @rusty-snake for saving the [bacon](https://github.com/netblue30/firejail/pull/4257#pullrequestreview-654674926).
> revert comment changes from #4257

- etc/profile-a-l/amarok.profile
- etc/profile-a-l/cin.profile
- etc/profile-a-l/enpass.profile
- etc/profile-a-l/eog.profile
- etc/profile-a-l/eom.profile
- etc/profile-a-l/libreoffice.profile
- etc/profile-a-l/librewolf.profile
- etc/profile-m-z/minecraft-launcher.profile
- etc/profile-m-z/nano.profile
- etc/profile-m-z/ostrichriders.profile
- etc/profile-m-z/spotify.profile
- etc/profile-m-z/steam.profile
- etc/profile-m-z/sysprof.profile
Another batch of comments rewording to encourage using .local overrides.
> Follow-up for #4165

- etc/profile-a-l/discord-common.profile
> fix: discord logout on opening twice

- etc/profile-a-l/blobby.profile
- etc/profile-a-l/funnyboat.profile
- etc/profile-a-l/librecad.profile
Follow-up fixes for https://github.com/netblue30/firejail/commit/eb30ce54e7a8a75db773a1bbe762a3abdf2ccc42.
> fixes for eb30ce5 (new profiles)

- src/firejail/fs_whitelist.c
- test/fs/whitelist.exp
testing, minor bugfixes, cosmetics
#4229
> Whitelist2 follow-up

- etc/profile-a-l/0ad.profile
- etc/profile-a-l/apostrophe.profile
- etc/profile-a-l/bijiben.profile
- etc/profile-a-l/celluloid.profile
- etc/profile-a-l/chromium-browser-privacy.profile
- etc/profile-a-l/eo-common.profile
- etc/profile-a-l/etr.profile
- etc/profile-a-l/evince.profile
- etc/profile-a-l/file-roller.profile
- etc/profile-a-l/firefox.profile
- etc/profile-a-l/frogatto.profile
- etc/profile-a-l/gapplication.profile
- etc/profile-a-l/gfeeds.profile
- etc/profile-a-l/gnome-maps.profile
- etc/profile-a-l/gnome-passwordsafe.profile
- etc/profile-a-l/keepassxc.profile
- etc/profile-a-l/libreoffice.profile
- etc/profile-m-z/marker.profile
- etc/profile-m-z/meld.profile
- etc/profile-m-z/mpv.profile
- etc/profile-m-z/mrrescue.profile
- etc/profile-m-z/pingus.profile
- etc/profile-m-z/supertuxkart.profile
- etc/profile-m-z/yelp.profile
> Restrict /usr/libexec

- etc/templates/profile.template
> Fix sort error in profile.template

- etc/profile-a-l/googler-common.profile
```
seccomp
seccomp.block-secondary
```
> minor fix googler profile

- etc/profile-m-z/zathura.profile
> tightening zathura profile

- etc/profile-m-z/qcomicbook.profile
- src/firecfg/firecfg.config
the profile resembles mcomix and zathura profiles
> creating qcomicbook profile

- etc/profile-m-z/mcomix.profile
- src/firecfg/firecfg.config
new profile
copied a lot from zathura
> mcomix profile creation

- etc/profile-m-z/rtv-addons.profile
- etc/profile-m-z/rtv.profile
less is used to read comments
other minor corrections
> rtv profile correction

- etc/inc/disable-programs.inc
- etc/profile-a-l/clion-eap.profile
- etc/profile-a-l/clion.profile
- src/firecfg/firecfg.config
Clion cannot fetch settings and addons
> Update Clion profile and Add Clion EAP profile

- README.md
- etc/profile-m-z/ncdu2.profile
- src/firecfg/firecfg.config
https://aur.archlinux.org/packages/ncdu2/
https://dev.yorhel.nl/doc/ncdu2
> add ncdu2 redirect profile

- etc/inc/disable-common.inc
Redo https://github.com/netblue30/firejail/pull/4399.
> ordering and additions

- src/firejail/main.c
> Give fbuilder full original environment

- etc/profile-m-z/youtube-viewers-common.profile
> updating youtube-viewers-common.profile

- etc/inc/disable-programs.inc
- etc/profile-a-l/gallery-dl.profile
- src/firecfg/firecfg.config
gallery-dl, very similar to youyube-dl,but for images
youtube-dl is an optional dependency.
> creating gallery-dl.profile

- etc/profile-a-l/gallery-dl.profile
- etc/profile-m-z/yt-dlp.profile
i'm sure netblue was just testing us :P
> fix duplicate globals

- COPYING
> Use complete license file

- src/fcopy/main.c
- src/firejail/fs.c
- src/firejail/fs_dev.c
- src/firejail/fs_home.c
- src/firejail/fs_whitelist.c
- src/firejail/sandbox.c
- src/firejail/selinux.c
- src/firejail/util.c
Run more whitelist code with EUID of the user.
> add more EUID improvements

- etc/profile-a-l/imv.profile
- etc/profile-m-z/retroarch.profile
- etc/profile-m-z/torbrowser.profile
- src/firecfg/firecfg.config
The profiles are based on profile template.
> Add profiles for imv, retroarch, and torbrowser

- etc/inc/disable-common.inc
- etc/profile-a-l/bleachbit.profile
- etc/profile-a-l/img2txt.profile
- etc/profile-a-l/keepassxc-cli.profile
- etc/profile-m-z/ncdu.profile
- etc/profile-m-z/pdftotext.profile
- etc/profile-m-z/weechat.profile
"quiet" added to these profiles
- bleachbit
- img2txt
- keepassxc-cli
- ncdu
- pdftotext
- weechat
> Added `quiet` to some CLI profiles

- etc/profile-a-l/chromium-common.profile
- etc/profile-a-l/ephemeral.profile
- etc/profile-a-l/ferdi.profile
- etc/profile-a-l/firefox-common.profile
- etc/profile-a-l/franz.profile
- etc/profile-m-z/midori.profile
- etc/profile-m-z/otter-browser.profile
- etc/profile-m-z/rambox.profile
- etc/profile-m-z/seamonkey.profile
> profiles: ordering fixes

- etc/inc/disable-programs.inc
- etc/profile-m-z/rpcs3.profile
- src/firecfg/firecfg.config
RPCS3 is a popular video game emulator that uses JIT compilation. I've made a profile for it and have been testing it. It is distributed as an AppImage, and not packaged for system, which is a bit annoying, so I run it with the --appimage parameter.
Edit: fixed ldconfig issue
> RPCS3 profile

- README.md
- etc/profile-a-l/chromium-common.profile
- etc/profile-a-l/firefox-common.profile
- etc/profile-m-z/steam.profile
- etc/profile-m-z/wget2.profile
- etc/profile-m-z/youtube-viewers-common.profile
- src/firecfg/firecfg.config
This PR adds support for [wget2](https://gitlab.com/gnuwget/wget2) via redirect.
> Add wget2 support

- etc/profile-a-l/1password.profile
- src/firecfg/firecfg.config
I worked off of another electron-based app as a baseline instead of the template.  I hope that's alright!
> add a profile for 1password

- etc/profile-m-z/mediathekview.profile
> Fix MediathekView Profile

- RELNOTES
Note: #4780 was closed by commit d2e10f8b7 ("fix --private-cwd problem",
2021-12-19).
Relates to #4748 #4780.
Cc: @WhyNotHugo
> RELNOTES: add security-related items

- RELNOTES
Sort items, add category prefixes and add a few items.
> Organize relnotes

- etc/profile-a-l/keepass.profile
- etc/profile-a-l/keepassx.profile
- etc/profile-a-l/keepassxc.profile
> keepass*: remove nou2f & add note about private-dev

- etc/profile-a-l/dino.profile
dino.profile: Allow functionalities that require dbus
> Improve dino.profile.

- etc/profile-m-z/zeal.profile
Follow-up to https://github.com/netblue30/firejail/pull/4966. Add some extra hardening options.
> hardening zeal.profile

- etc/profile-a-l/gconf-editor.profile
mdwe breaks gconf-editor (GUI)
> gconf-editor fix

- etc/profile-a-l/geary.profile
Fixes for https://github.com/netblue30/firejail/issues/4982.
> geary fixes

- etc/profile-m-z/songrec.profile
It is a Rust application using Cargo, so harden based on common supply chain attacks seen.
https://github.com/marin-m/SongRec
Also based the config on other players in the repo (mpv etc.).
> Add songrec

- etc/profile-m-z/onionshare-gui.profile
Minor hardening of the profile.
> hardening onionshare-gui.profile

- etc/inc/disable-programs.inc
- etc/profile-m-z/steam.profile
https://store.steampowered.com/app/219150/Hotline_Miami/
> steam: add HotLine Miami

- etc/inc/disable-programs.inc
- etc/profile-m-z/wget2.profile
Add ${HOME}/.local/share/wget (no)blacklist to wget2 profile.
> updates for wget2

- etc/profile-a-l/git.profile
Add a few options that seem to be overlooked in current git.profile.
> minor fixes for git.profile

- etc/profile-m-z/transmission-gtk.profile
- etc/profile-m-z/transmission-qt.profile
The OP of https://github.com/netblue30/firejail/pull/5161 closed the PR but IMO this is still worth adding to the GUI parts of transmission.
See discussion in the original PR for context.
> Add comment for enabling D-Bus desktop notifications to transmission-{gtk,qt}

- src/firecfg/firejail-welcome.sh
> fix typo in firejail-welcome.sh

- etc/inc/disable-programs.inc
- etc/profile-m-z/steam.profile
> add Colossal Order to steam.profile

- README.md
- etc/profile-a-l/gdu.profile
- src/firecfg/firecfg.config
Add new profile for `gdu` (cfr. ncdu but optimized for SSD's):
https://github.com/dundee/gdu
https://archlinux.org/packages/community/x86_64/gdu/
> new profile: gdu

- etc/profile-m-z/man.profile
Came up on IRC when talking about #5321.
> man.profile needs additional private-etc items on arch

- etc/inc/disable-programs.inc
- etc/profile-m-z/tuir.profile
- src/firecfg/firecfg.config
> tuir.profile creation

- etc/inc/disable-programs.inc
- etc/profile-a-l/gtk-lbry-viewer.profile
- etc/profile-a-l/lbry-viewer.profile
- src/firecfg/firecfg.config
create profile for a lbry viewer
> lbry-viewer.profile create

- README.md
Thanks to @NetSysFire we now have an IRC channel on Libera. Let's make it visible in README.md
> Add IRC channel info to README.md

- etc/profile-a-l/Discord.profile
- etc/profile-a-l/DiscordCanary.profile
- etc/profile-a-l/discord-canary.profile
- etc/profile-a-l/discord-common.profile
- etc/profile-a-l/discord.profile
> discord: fix issues with command-line usage

- etc/profile-a-l/electron-mail.profile
title.
~~noroot is missing from all the chromium browsers that i checked and electron the electron sdk....~~
Now refactoring with electron.profile
> electron-mail.profile refactoring

- etc/profile-a-l/deluge.profile
Fixes #5463 by adding netlink to the list of allowed protocols
> Add netlink to list of allowed protocols

- README.md
- etc/profile-a-l/cinelerra-gg
- src/firecfg/firecfg.config
Relates to #5466 (cinelerra-gg part).
> Add support for cinelerra-gg

- etc/profile-m-z/nicotine.profile
Add Python 3 support. Also fixes private-bin (reported on IRC).
> Add python3 support/fixes to nicotine

- etc/profile-m-z/youtube-viewers-common.profile
> fix opening links in firefox youtube-viewers-common.profile

- etc/profile-a-l/email-common.profile
> [email-common.profile] add localtime to private-etc

- etc/profile-a-l/firefox-common-addons.profile
> firefox-common-addons: fix whitelisting in ${RUNUSER}

- README.md
- etc/profile-m-z/tesseract.profile
- src/firecfg/firecfg.config
An OCR program (CLI). Handy tool for creating PDF's and extracting text from PNG image(s).
https://github.com/tesseract-ocr/tesseract
> New profile: tesseract

- etc/profile-m-z/qutebrowser.profile
Overlooked [this comment](https://github.com/netblue30/firejail/pull/5389#discussion_r992471940) that pointed out a mistake I made. Thanks @kmk3 for reminding me!
> qutebrowser: fix whitelisting for wusc

- etc/profile-a-l/audacity.profile
> audacity: networking updates

- README.md
- etc/inc/disable-programs.inc
- etc/profile-m-z/ssmtp.profile
Old software, but still useful as MTA.
> New profile: ssmtp

- etc/inc/disable-common.inc
- etc/inc/disable-proc.inc
> clarify that duplicated blacklisting of /proc/config.gz is intentional

- etc/profile-a-l/gpg-agent.profile
No functional changes. Just some cleanup for the upcoming 0.9.72 release.
> gpg-agent: sort private-bin (even though it's commented)

- etc/profile-a-l/gpg.profile
No functional changes. Clean-up for upcoming 0.9.72 release.
> gpg: fix private-bin

- etc/profile-m-z/ytmdesktop.profile
> ytmdesktop: fix typo

- etc/profile-a-l/electron-hardened.inc.profile
- etc/profile-a-l/electron.profile
> electron hardening fixes

- src/firejail/usage.c
> Remove --profile-path from --help

- README
- README.md
- etc/inc/disable-programs.inc
- etc/profile-a-l/linuxqq.profile
- etc/profile-m-z/qq.profile
- src/firecfg/firecfg.config
Add profiles for https://im.qq.com/linuxqq/.
See https://github.com/BeautyYuYanli/linuxqq-new-firejail/issues/1 for context.
> New profiles: linuxqq/qq

- src/include/etc_groups.h
> etc_groups.h: sort groups alphabetically

- etc/profile-m-z/qutebrowser.profile
> qutebrowser: allow userscripts by default

- etc/profile-m-z/parsecd.profile
Ordering fixes for [New profile: parsecd](https://github.com/netblue30/firejail/commit/9b64b76cc940a323a9345b6f3da93d6e09bf1798).
> parsecd: ordering fixes

- etc/profile-a-l/chromium-common.profile
- etc/profile-a-l/electron.profile
- etc/profile-m-z/ping.profile
clean pull request from this discussion.
#5304
> profiles: clarify userns comments

- etc/profile-a-l/gajim.profile
Closes https://github.com/netblue30/firejail/issues/5704
> gajim: allow loading plugins

- etc/profile-m-z/porn-cli.profile
- src/firecfg/firecfg.config
Python script for watching porn in the terminal.
a clone of mov-cli by the same devs. It's just a redirect to mov-cli
https://github.com/mov-cli/porn-cli
> add porn-cli.profile

- etc/apparmor/firejail-local
AppArmor syntax fixes.
Came up in review for #5715.
> firejail-local: fix examples

- etc/inc/disable-programs.inc
- etc/profile-a-l/DiscordPTB.profile
- etc/profile-a-l/discord-ptb.profile
- src/firecfg/firecfg.config
Same profile behavior as Discord Canary, but for PTB
> Add Discord PTB profile

- etc/profile-a-l/gallery-dl.profile
- etc/profile-m-z/youtube-dl.profile
- etc/profile-m-z/yt-dlp.profile
move content from youtube-dl to yt-dlp
youtude-dl and gallery-dl redirect to yt-dlp
yt-dlp has become the main program now. The future of youtube-dl is uncertain.
> refactor yt-dlp

- etc/profile-m-z/tutanota-desktop.profile
saving to disk is broken. Fixes other minor errors
> tutanota-desktop.profile improvements

- etc/profile-a-l/chafa.profile
- etc/profile-a-l/gdu.profile
- etc/profile-m-z/pngquant.profile
- etc/profile-m-z/qpdf.profile
No functional changes.
Relates to #639.
> profiles: streamline seccomp socket comment

- etc/inc/disable-common.inc
- etc/profile-m-z/microsoft-edge-beta.profile
- etc/profile-m-z/microsoft-edge-dev.profile
- etc/profile-m-z/microsoft-edge-stable.profile
- etc/profile-m-z/microsoft-edge.profile
- src/firecfg/firecfg.config
- add a redirect for microsoft-edge-stable
- add internal sandbox support
- add private-opt for extra hardening
Partly relates to #5696.
> microsoft-edge fixes

- etc/profile-a-l/engrampa.profile
Light refresh.
this is a bit tricky, because it uses a lot of cli tools to compress/decompress.
> refresh engrampa.profile

- etc/profile-a-l/ani-cli.profile
oups, missing nohup in private-bin
> fix ani-cli.profile

- src/firejail/fs_etc.c
> fs_etc.c: conditionally create /etc/resolv.conf

- etc/profile-m-z/pidgin.profile
> pidgin: allow netlink

- etc/profile-m-z/standardnotes-desktop.profile
Relates to https://github.com/netblue30/firejail/discussions/5758.
> standardnotes-desktop: add custom (cursor) theme support

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- CONTRIBUTING.md
- README
- README.md
- SECURITY.md
Mostly linting/formatting of markdown with a few corrections and improvements.
No major content changes.
> docs: markdown formatting and misc improvements

- RELNOTES
- etc/profile-m-z/url-eater.profile
- src/firecfg/firecfg.config
Clipboard URL privacy daemon: url-eater.
Homepage: https://github.com/AgathaSorceress/url-eater.
Works on Xorg and Wayland.
> New profile: url-eater

- etc/inc/allow-python2.inc
- etc/inc/allow-python3.inc
- etc/inc/disable-interpreters.inc
i'm proposing:
blacklist .local/lib/python* in disable interpreters
noblacklist in allow python
> profiles: block local python

- etc/profile-m-z/qutebrowser.profile
see https://github.com/qutebrowser/qutebrowser/issues/7431
> qutebrowser: update MPRIS name for qutebrowser-qt6

- src/firecfg/desktop_files.c
- src/firecfg/firecfg.h
- src/firecfg/main.c
- src/jailcheck/main.c
- src/jailcheck/utils.c
- src/man/firecfg.1.in
- src/man/jailcheck.1.in
Closes #5899.
Suggested-by: @shaggonit
> feature: add doas support in firecfg and jailcheck 

- etc/firejail.config
- etc/inc/disable-interpreters.inc
- etc/profile-a-l/1password.profile
- etc/profile-a-l/brave.profile
- etc/profile-a-l/cachy-browser.profile
- etc/profile-a-l/discord-ptb.profile
- etc/profile-a-l/firefox.profile
- etc/profile-a-l/gnome-calendar.profile
- etc/profile-a-l/krunner.profile
- etc/profile-a-l/librewolf.profile
- etc/profile-m-z/minetest.profile
- etc/profile-m-z/mpv.profile
- etc/profile-m-z/nodejs-common.profile
- etc/profile-m-z/noprofile.profile
- etc/profile-m-z/pingus.profile
- etc/profile-m-z/rtin.profile
- etc/profile-m-z/steam.profile
- etc/profile-m-z/tin.profile
> profiles: Miscellaneous cleanups

- etc/inc/disable-programs.inc
- etc/profile-m-z/sniffnet.profile
- src/firecfg/firecfg.config
https://www.sniffnet.net/
https://github.com/GyulyVGC/sniffnet
> New profile: sniffnet

- Makefile
- mkasc.sh
Relates to:
* #5140
* #5142
* <https://github.com/netblue30/firejail/pull/5154#pullrequestreview-980810845>
* #5182
* #5911
> build: dist and asc improvements

- etc/inc/disable-programs.inc
- etc/profile-a-l/gramps.profile
> gramps: bring in new config directory

- etc/profile-a-l/daisy.profile
- src/firecfg/firecfg.config
TUI scientific calculator with support for units:
https://git.betalupi.com/Mark/daisy
> New profile: daisy

- etc/inc/disable-programs.inc
- etc/profile-a-l/journal-viewer.profile
- src/firecfg/firecfg.config
journal-viewer
Visualize systemd logs
https://github.com/mingue/journal-viewer
> New profile: journal viewer

- etc/profile-a-l/clac.profile
- src/firecfg/firecfg.config
clac
Simple command-line calculator
https://github.com/alex-laycalvert/clac
Note: the app has no configuration.
> New profile: clac

- etc/profile-a-l/ani-cli.profile
> ani-cli.profile: allow mktemp

- etc/profile-m-z/transgui.profile
Partly relates to https://github.com/netblue30/firejail/discussions/5610.
> transgui: hardening

- etc/profile-a-l/gwenview.profile
> gwenview: add Trash support

- etc/inc/disable-programs.inc
- etc/profile-m-z/steam.profile
Add directories to config so Factorio runs correctly.
> steam.profile: Allow Factorio

- etc/profile-m-z/mocp.profile
> mocp: fix networking

- etc/inc/disable-common.inc
https://codeberg.org/dnkl/foot
> disable-common.inc: add foot to 'bad terminals' section

- etc/inc/disable-programs.inc
- etc/profile-a-l/brz.profile
- etc/profile-a-l/bzr.profile
https://www.breezy-vcs.org/
https://github.com/breezy-team/breezy
Implemented as git redirect
> New profile: brz

- etc/inc/disable-programs.inc
- etc/profile-a-l/floorp.profile
floorp
A customisable Firefox fork with excellent privacy protection
https://floorp.app/en/
https://github.com/Floorp-Projects/Floorp
https://aur.archlinux.org/packages/floorp
> New profile: floorp

- etc/profile-m-z/nicotine.profile
> nicotine: allow sound notifications

- etc/profile-m-z/termshark.profile
- src/firecfg/firecfg.config
termshark
Terminal UI for tshark, inspired by Wireshark
https://github.com/gcla/termshark
> New profile: termshark

- etc/profile-m-z/ssmtp.profile
> ssmtp: allow (SUID) binary

- etc/inc/disable-programs.inc
- etc/profile-m-z/steam.profile
Baba Is You settings and save data are stored in `~/.local/share/Baba_Is_You`.
> steam.profile: Allow Baba Is You

- etc/inc/disable-programs.inc
- etc/profile-m-z/nodejs-common.profile
- etc/profile-m-z/pnpm.profile
- etc/profile-m-z/pnpx.profile
pnpm
Fast, disk space efficient package manager
https://pnpm.io/
> profiles: Extend node stack support for pnpm

- etc/profile-a-l/freshclam.profile
> freshclam: fix .local include

- etc/profile-a-l/clamtk.profile
> clamtk: fix scanning

- etc/inc/disable-programs.inc
- etc/profile-m-z/steam.profile
Add directories to config so Project Zomboid runs correctly.
> steam.profile: Allow Project Zomboid

- etc/profile-m-z/man.profile
gropdf needs Perl: see https://github.com/netblue30/firejail/discussions/6142.
> man: allow Perl

- etc/profile-a-l/lobster.profile
command is builtin in bash
adding basename.
> lobster.profile: allow basename

- etc/profile-a-l/lbry-viewer-gtk.profile
- etc/profile-m-z/pipe-viewer-gtk.profile
- etc/profile-m-z/youtube-viewer-gtk.profile
- src/firecfg/firecfg.config
Convenience symlinks for youtube-viewers-gtk
> profiles: add profiles for gtk youtube viewers symlinks

- etc/inc/disable-programs.inc
- etc/profile-a-l/electron-cash.profile
This is a profile for the [Electron Cash](https://electroncash.org/) Bitcoin Cash SPV client.
> Profile for Electron Cash

- etc/profile-a-l/gnome-boxes.profile
See https://github.com/netblue30/firejail/discussions/6215 for context.
> New profile: gnome-boxes

- etc/profile-m-z/virt-manager.profile
Restrict access to /usr/libexec.
> virt-manager: deny access to /usr/libexec

- etc/inc/disable-programs.inc
- etc/profile-a-l/green-recoder.profile
- src/firecfg/firecfg.config
green-recorder
Simple screen recorder for Linux desktop, supports Wayland & Xorg
https://github.com/dvershinin/green-recorder
https://aur.archlinux.org/packages/green-recorder
https://aur.archlinux.org/packages/green-recorder-git
> New profile: green-recorder

- etc/profile-a-l/bpftop.profile
- src/firecfg/firecfg.config
bpftop
Description: Dynamic real-time view of running eBPF programs.
https://github.com/Netflix/bpftop
https://aur.archlinux.org/packages/bpftop
https://aur.archlinux.org/packages/bpftop-bin
https://aur.archlinux.org/packages/bpftop-git
> New profile: bpftop

- etc/profile-a-l/erd.profile
- src/firecfg/firecfg.config
erd
Description: Multi-threaded file-tree visualizer and disk usage
analyzer.
https://github.com/solidiquis/erdtree
https://archlinux.org/packages/extra/x86_64/erdtree/
Note: The repo and package are called `erdtree`, but the executable is
`erd`.
> New profile: erd

- etc/profile-a-l/lyriek.profile
- src/firecfg/firecfg.config
lyriek
Description: A multi-threaded GTK application to fetch lyrics of
currently playing songs.
https://gitlab.com/bartwillems/lyriek
> New profile: lyriek

- etc/profile-m-z/statusof.profile
- src/firecfg/firecfg.config
statusof
Description: Python script to check the status of a list of URLs.
https://github.com/Arthurdw/statusof
> New profile: statusof

- etc/profile-a-l/cloneit.profile
- src/firecfg/firecfg.config
cloneit
Description: A CLI tool to download specific GitHub directories or
files.
https://github.com/alok8bb/cloneit
https://aur.archlinux.org/packages/cloneit-git
> New profile: cloneit

- etc/inc/disable-programs.inc
- etc/profile-a-l/deadlink.profile
- src/firecfg/firecfg.config
deadlink
Description: Checks and fixes URLs in code and documentation.
https://github.com/nschloe/deadlink
https://aur.archlinux.org/packages/deadlink
> New profile: deadlink

- etc/profile-a-l/dexios.profile
- src/firecfg/firecfg.config
dexios
Description: CLI encryption tool
https://github.com/brxken128/dexios
https://aur.archlinux.org/packages/dexios-bin
> New profile: dexios

- etc/inc/disable-programs.inc
- etc/profile-a-l/koreader.profile
- src/firecfg/firecfg.config
koreader
Description: Ebook reader application.
https://koreader.rocks/
> New profile: koreader

- etc/inc/disable-programs.inc
- etc/profile-a-l/localsend_app.profile
- src/firecfg/firecfg.config
localsend
Description: An open source cross-platform alternative to AirDrop.
https://github.com/localsend/localsend
> New profile: localsend_app

- etc/inc/disable-programs.inc
- etc/profile-m-z/rymdport.profile
- src/firecfg/firecfg.config
rymdport
Description: Encrypted sharing of files, folders, and text between
devices.
https://github.com/Jacalz/rymdport
> New profile: rymdport

- etc/inc/disable-programs.inc
- etc/profile-m-z/textroom.profile
- src/firecfg/firecfg.config
textroom
Description: Full Screen text editor heavily inspired by Q10 and
JDarkRoom.
https://code.google.com/p/textroom/
https://aur.archlinux.org/packages/textroom
> New profile: textroom

- etc/inc/disable-programs.inc
- etc/profile-m-z/session-messenger-desktop.profile
- etc/profile-m-z/session-messenger.profile
- etc/session-desktop.profile
- src/firecfg/firecfg.config
session-desktop
Description: Encrypted messenger.
https://github.com/oxen-io/session-desktop/
https://aur.archlinux.org/packages/session-desktop
https://aur.archlinux.org/packages/session-desktop-bin
https://aur.archlinux.org/packages/session-desktop-appimage
Note: The AUR packages all work with the profiles.
> New profile: session-desktop

- etc/profile-m-z/metadata-cleaner.profile
- src/firecfg/firecfg.config
metadata-cleaner
Description: Python GTK3 application to view and clean metadata in
files, using mat2.
https://gitlab.com/rmnvgr/metadata-cleaner
> New profile: metadata-cleaner

- etc/inc/disable-programs.inc
- etc/profile-a-l/gh.profile
- src/firecfg/firecfg.config
Description: GitHub's official command-line tool.
https://github.com/cli/cli
> New profile: gh (GitHub CLI)

- etc/profile-m-z/mov-cli.profile
Changes:
* Remove ffmpeg from private-bin
* Allow download folder
* It needs an editor to allow editing the config, so I put in nano; sh
and uname are used for launching nano
> profiles: mov-cli: remove ffmpeg & allow more paths

- etc/inc/disable-programs.inc
- etc/profile-a-l/axel.profile
- src/firecfg/firecfg.config
Axel
Lightweight CLI download accelerator
https://github.com/axel-download-accelerator/axel
> New profile: axel

- etc/profile-m-z/okular.profile
> profiles: okular: fix "Print to PDF"

- etc/profile-a-l/dtui.profile
- src/firecfg/firecfg.config
Description: TUI for introspecting the state of the system/session dbus.
https://github.com/Troels51/dtui
https://aur.archlinux.org/packages/dtui
Relates to https://github.com/netblue30/firejail/pull/6420.
> New profile: dtui

- src/fshaper/fshaper.sh
> feature: fshaper.sh: support tc on NixOS

- .github/ISSUE_TEMPLATE/build_issue.md
Based on `.github/ISSUE_TEMPLATE/bug_report.md`.
Relates to #6417.
Cc: @glitsj16 @rusty-snake
> docs: add build_issue.md issue template

- etc/inc/disable-programs.inc
- etc/profile-m-z/steam.profile
Whitelist ~/.config/UNDERTALE to allow the game to save.
> profiles: steam: add ~/.config/UNDERTALE

- README.md
Relates to #6406.
Reported-by: @Lidoca
Cc: @reinerh
> docs: clarify that other tools may not be in PPA

- src/firejail/profile.c
> modif: clarify error messages in profile.c

- etc/profile-a-l/buku.profile
> New profile: buku

- etc/profile-m-z/monero-wallet-cli.profile
> New profile: monero-wallet-cli

- .github/ISSUE_TEMPLATE/bug_report.md
See also commit 9bccccfa7 ("docs: github: streamline environment in
issue templates (#6471)", 2024-09-13).
> docs: github: add program name/version to bug_report.md

- src/man/firejail-profile.5.in
- src/man/firejail.1.in
Inspired by discussion: https://github.com/netblue30/firejail/discussions/6621
> docs: improve whitelist and blacklist descriptions in man pages

- Makefile
- contrib/vim/ftplugin/firejail.vim
Add a simple vim filetype plugin.
> contrib/vim: add ftplugin file (based on cfg.vim)

- etc/profile-m-z/ouch.profile
CLI utility for easily compressing and decompressing files and dirs.
https://github.com/ouch-org/ouch
> New profile: ouch

- etc/inc/disable-programs.inc
- etc/profile-m-z/xarchiver.profile
Lightweight desktop-independent archive manager.
https://github.com/ib/xarchiver
> New profile: xarchiver

- etc/inc/disable-programs.inc
- etc/profile-a-l/ansel.profile
This adds support for Ansel, a Darktable fork:
https://github.com/aurelienpierreeng/ansel/
The profile is based on darktable.profile. I have personally tested it
and it works.
> New profile: ansel

- src/firejail/preproc.c
As reported by @hlein in #6729, if a firejailed process is `^Z`'d at the wrong time during startup, other firejail processes will be unable to proceed because they'll wait forever for an flock on `/run/firejail/firejail-run.lock`.
This fixes that by installing a signal handler to catch SIGTSTP (Ctrl-Z) before acquiring locks. The handler increments a flag to allow for re-sending the SIGTSTP signal after locks have been released.
The length of the sleep should be adjusted until the debug output resembles below
```sh
$ firejail --debug id & P=$!;sleep 0.0005;kill -TSTP $P
[1] 16130
Looking for kernel processes
Found kthreadd process, we are not running in a sandbox
pid=16130: locking /run/firejail/firejail-run.lock ...
pid=16130: locked /run/firejail/firejail-run.lock
[1]+  Stopped …
```
> bugfix: fix potential deadlock with flock + SIGTSTP

- src/firejail/preproc.c
As reported by @hlein in #6729, if a firejailed process is `^Z`'d at the
wrong time during startup, other firejail processes will be unable to
proceed because they'll wait forever for an flock on
`/run/firejail/firejail-run.lock`.
This builds upon commit f4b8c6dbb ("bugfix: fix potential deadlock with
flock + SIGTSTP (#6750)", 2025-05-21) to add a busy wait while
attempting to acquire a lock. This allows the application to bail out if
it fails to acquire a lock after a given timeout.
Behavior after this patch (we use SIGSTOP, as that cannot be
caught/ignored):
$ firejail --debug id & P=$!;sleep 0.00001;kill -STOP $P
[1] 14411
Looking for kernel processes
Found kthreadd process, we are not running in a sandbox
pid=14411: locking /run/firejail/firejail-run.lock ...
pid=14411: locked …
> feature: use non-blocking flock calls

- src/firejail/sandbox.c
- src/firejail/sbox.c
> modif: improve error messages in sandbox.c/sbox.c
