netblue30/firejail

etc/profile-a-l/keepassxc.profile, etc/profile-m-z/Mathematica.profile
This reverts commit 5df1f27c638c487dfd664ea3a0f756565e1e57bd.
That commit breaks things, as pointed out by @rusty-snake[1]:
> @kmk3 @glitsj16 The xdg macros are treated literally if they have sub
> components (#2359):
>
> ```
> Error: "${DOCUMENTS}/KeePassXC" is an invalid filename: rejected character: "{"
> ```
[1]: https://github.com/netblue30/firejail/commit/3fa2927c3c1c5cf583864746538ea791c1ba2dc4#commitcomment-46913219
=> Revert "etc: use ${DOCUMENTS} macro where appropriate"

configure, configure.ac
Added on commit 64a8d6a7f ("compile time option to disable
--private-cache and --tmpfs for regular user").
These are the only occurrences:
$ git ls-files -z | xargs -0 grep -Fin USERTMPS
configure:3542:HAVE_USERTMPS=""
configure.ac:80:HAVE_USERTMPS=""
=> configure*: fix typo of HAVE_USERTMPFS

src/firejail/env.c, src/firejail/firejail.h, src/firejail/main.c
With the recent changes to environment variable handling, it should be
safe to always allow empty variables.
Closes: #3965
=> Always allow empty environment variables

.gitignore, Makefile.in, configure, configure.ac, src/bash_completion/Makefile.in, src/bash_completion/firejail.bash_completion.in, src/zsh_completion/Makefile.in, src/zsh_completion/_firejail.in
Adding a zsh completion script. Tested extensively for the options I use a lot.
I put the file into contrib/zsh_completion instead of src/ where the bash_completion is as makes more sense to me. Feel free to move it around if you prefer. Or move the back_completion into contrib/
=> Add first version of zsh completion

etc/profile-m-z/torbrowser-launcher.profile
At least on Arch Linux torbrowser-launcher comes with AppArmor support. Enabling apparmor in our profile sounds reasonable and shouldn't break on other distro's that do packaging differently.
=> add apparmor to torbrowser-launcher

etc/apparmor/firejail-default, etc/apparmor/firejail-local, etc/profile-m-z/start-tor-browser.desktop.profile, etc/profile-m-z/start-tor-browser.profile, etc/profile-m-z/torbrowser-launcher.profile
I retested enabling the apparmor option after legitimate questions posed by @rusty-snake and @Vincent43 in #3988 - thanks!. Apologies for the confusion, I forgot to add the AppArmor rule to allow access to the torbrowser-launcher executables installed under ${HOME}.
=> Follow-up fixes for torbrowser-launcher

.github/workflows/sort.yml, contrib/sort.py
0f76e53 sort.py: Better error message
19c92f2 sort.py: Print the fixed line when running in a CI
9f939b8 workflows/sort.yml: Run also if sort.py is changed
=> Sort.py updates

contrib/firejail-welcome.sh
Append the current year rather than replace the previous one.
This amends commit 2609e5cf0 ("copyright update").
Commands that helped catch this:
$ git show --pretty='' 2609e5cf0 | sed -n 's/^-.*Copyright //p' |
LC_ALL=C sort | uniq
(C) 2014-2020 Firejail Authors
(C) 2014-2020 Firejail Authors (see README file for more details)
(C) 2020 Firejail Authors
(C) 2020 Firejail and systemd authors
(c) 2019,2020 rusty-snake
$ git show --pretty='' 2609e5cf0 | sed -n 's/^+.*Copyright //p' |
LC_ALL=C sort | uniq
(C) 2014-2021 Firejail Authors
(C) 2014-2021 Firejail Authors (see README file for more details)
(C) 2020-2021 Firejail Authors
(C) 2020-2021 Firejail and systemd authors
(C) 2021 Firejail Authors
(c) 2019-2021 rusty-snake
---
@startx2017 When doing the mass replace, checking for the …
=> contrib/firejail-welcome.sh: fix copyright year

etc/profile-m-z/patch.profile
As mentioned here https://github.com/netblue30/firetools/issues/55 I ran into this issue today and including libdl.so as per rusty-snake's advice fixes this error for me.
=> Fix patch-util not having access to libdl.so

etc/profile-m-z/vmware-player.profile, etc/profile-m-z/vmware-workstation.profile, src/firecfg/firecfg.config
These two profiles will allow `firecfg` to take care of vmware related `.desktop` files. Otherwise,manual intervention would be needed.
=> Minor fixes for vmware

etc/profile-m-z/signal-desktop.profile
Added on commit f4f676745 ("Refactor electron.profile and electron based
programs (#3807)").
This appears to be the only instance of that:
$ grep -Fnr 'include-xdg' etc
etc/profile-m-z/signal-desktop.profile:9:ignore include-xdg.inc
Credits go to syntax highlighting on vim.
---
Also, note that the file says this:
```firejail
ignore include-xdg.inc
```
So if there was no negative feedback, should xdg dirs (other than
`${DOWNLOADS}`, that is) be allowed or should we just remove that line instead?
As all this PR would do is allow xdg dirs for the first time since at least
commit f4f676745.
=> signal-desktop.profile: fix typo of disable-xdg.profile

src/fcopy/main.c, src/firejail/firejail.h, src/firejail/fs_etc.c, src/firejail/fs_mkdir.c, src/firejail/main.c, src/firejail/network_main.c, src/firejail/sandbox.c
This is upstreaming first set of fixes from [Sailfish's firejail packaging](https://github.com/sailfishos/firejail/). These were developed as part of implementing firejail sandboxing in Sailfish OS. See also #3960 for discussion.
These are general fixes to firejail touching logging, private-etc, memory handing and symbolic link construction around /proc filesystem. Please see the commit messages for explanations. These were written by my colleague and previously reviewed by me or one of my other colleagues.
=> Upstreaming a set of fixes from Sailfish's packaging

src/firejail/fs_lib.c, src/firejail/fs_lib2.c, src/firejail/sbox.c
Essentially restores 45304621a6c600d8e30e98bfbef05149caaf56c5. Removing read permission on helper executables (fcopy) broke this original fix.
Now run fldd as root in order to fix #3741 without having to compromise or give up on the new permission system. It runs as root only on binaries that are not controlled by the user, and that Firejail needs to trust anyway. Also infrastructure is put in place to add more helper binaries to private-lib, should the need arise.
This pull request might be useful also for other reasons. For example, if one day we want to run the test suite with ASan/UBsan instrumentation, private-lib should now pick up all necessary libraries automatically (again).
=> add PATH_FCOPY to private-lib automatically

src/firejail/no_sandbox.c
Firejail symbolic link redirection currently depends
on a shell, but in restrictive sandboxes there
might be no execute permission, or `private-lib` might
have removed necessary libraries, or `seccomp` might
block required syscalls ...
Fix this by forcing `--shell=none`.
Closes #3911
=>  fix firecfg links in restrictive sandboxes

src/firejail/main.c, src/firejail/usage.c
Profile files are defined as a means to "pass several command line arguments to firejail" but apparently for example mkdir and mkfile options are available in context of profile files, but can't be specified directly from command line.
Add support for -mkdir and --mkfile options so that executing:
firejail --mkdir=${HOME}/directory/path\
--whitelist=${HOME}/directory/path
behaves similarly as having profile file content:
mkdir ${HOME}/directory/path
whitelist ${HOME}/directory/path
This patches was part of [Sailfish's firejail packaging](https://github.com/sailfishos/firejail/). It was developed as part of implementing firejail sandboxing in Sailfish OS and just like the previous patches written by my colleague and previously reviewed by me or one of my other colleagues. See also #3960 …
=> Add --mkdir and --mkfile command line options for firejail

src/firejail/firejail.h, src/firejail/main.c, src/firejail/profile.c
Firejail uses set-once logic for protocol list. This makes it impossible to accumulate list of allowed protocols from multiple include files. Instead of mandating that protocol is set once, allow constructing the list from multiple protocol rules.
These patches were part of [Sailfish's firejail packaging](https://github.com/sailfishos/firejail/). These were developed as part of implementing firejail sandboxing in Sailfish OS and just like the previous patches these were written by my colleague and previously reviewed by me or one of my other colleagues. See also #3960 for discussion.
=> Allow changing protocol list after initial set

src/firejail/dbus.c
Without this I get 
```
Error: Invalid dbus-user.call rule: org.kde.StatusNotifierWatcher=org.kde.StatusNotifierWatcher.*@/StatusNotifierWatcher
```
for
```
dbus-user.call org.kde.StatusNotifierWatcher=org.kde.StatusNotifierWatcher.*@/StatusNotifierWatcher
```
=> dbus.c: check_object_path: Allow /StatusNotifierWatcher

Makefile.in, src/bash_completion/Makefile.in, src/fbuilder/Makefile.in, src/fcopy/Makefile.in, src/firecfg/Makefile.in, src/firejail/Makefile.in, src/firemon/Makefile.in, src/fldd/Makefile.in, src/fnet/Makefile.in, src/fnetfilter/Makefile.in, src/fsec-optimize/Makefile.in, src/fsec-print/Makefile.in, src/fseccomp/Makefile.in, src/ftee/Makefile.in, src/jailtest/Makefile.in, src/lib/Makefile.in, src/libpostexecseccomp/Makefile.in, src/libtrace/Makefile.in, src/libtracelog/Makefile.in, src/man/Makefile.in, src/profstats/Makefile.in, src/zsh_completion/Makefile.in, test/Makefile.in
```console
* makefiles: fix whitespace
* makefiles: fix misc blank line consistency
* makefiles: make all, clean and distclean PHONY
```
Some minor cleanup and improvements before adding new stuff.
-----
@Fred-Barclay From the amount of whitespace-fixing commits, I think you'll like
the commands from commit 00437760d ("makefiles: fix whitespace"):
$ git ls-files -z -- '*Makefile*' |
xargs -0 -I '{}' sh -c \
"test -s '{}' && printf '%s\n' \"\`git stripspace <'{}'\`\" >'{}'"
I don't know if you've used something like that before, but to me it has been
very handy on many occasions.  From git-stripspace(1):
> Read text, such as commit messages, notes, tags and branch descriptions, from
> the standard input and clean it in the manner used by Git.
> …
=> Makefile improvements

src/firejail/fs_etc.c, src/firejail/sandbox.c
I sent some changes recently (#3998) and now I noticed that there were some minor things that could have been better.
The first commit moves error message of missing directory while mounting after debug logging so that it's easy to see when the error happens and adds a cause message. The second commit changes %m usages introduced by the changes I made. While %m is reentrant and allows very nice and clean code, it's not consistent with the rest of firejail and also not portable across libc implementations.
=> Improve error messages

src/firejail/profile.c, src/man/firejail-profile.txt
Idea from @vinc17fr
https://github.com/netblue30/firejail/issues/4026#issuecomment-789178572
dp gets included
```
?HAS_PRIVATE: ignore include disable-programs.inc
include disable-programs.inc
```
dp gets not included
```
private
?HAS_PRIVATE: ignore include disable-programs.inc
include disable-programs.inc
```
dp gets not included
```
private ${HOME}/foo
?HAS_PRIVATE: ignore include disable-programs.inc
include disable-programs.inc
```
=> Add new condition ?HAS_PRIVATE:

src/firejail/sandbox.c
Postpone writing of log file in order to also catch filesystem modifications from x11 code
=> sandbox setup: postpone fslogger

src/firejail/sandbox.c
Avoids mixing of `trace` from sandbox helpers into application `trace`.
=> sandbox setup: postpone library preloading

src/firejail/fs_lib.c, src/lib/ldd_utils.c
Currently depends on #4042 (hopefully that makes sense). 
~~I'll send another pull request to move private-lib from copying to mounting the next few days.~~ Done.
=> private-lib: mask /usr/local/lib[,64] directories, too

src/man/firejail.txt
Both --dbus-system.log and --dbus-user.log refer to a non-existing requirement --dbus-foo=log. The examples use the correct policy (filter).
```
$ firejail --dbus-system=log --dbus-system.log
Unknown dbus-system policy: log
$ firejail --dbus-user=log --dbus-user.log
Unknown dbus-user policy: log
```
=> man firejail: fix --dbus-{system,user}.log requirement

etc/templates/profile.template
In most profiles I've seen, this comment describes the program.
In some, it's missing, e.g. [Mathematica](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/Mathematica.profile)
In others, it's wrong (copy/pasted?), e.g. [Node.js](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/nodejs-common.profile#L2) says "Common profile for npm/yarn".
=> Clarify what the Description comment is for

etc/profile-a-l/engrampa.profile
`memory-deny-write-execute` causes the app to be unusable (you just get, a messed up window)
at least on ubuntu 18.04 32bit
with these
```
net none
dbus-user none
```
it complains a lot in the terminal about dbus
Nothing obvious is broken, but not tested thoroughly either.
=> fixing engrampa profile

src/firejail/appimage.c, src/firejail/appimage_size.c, src/firejail/cmdline.c, src/firejail/firejail.h, src/firejail/fs.c, src/firejail/main.c, src/firejail/sandbox.c, test/appimage/appimage-args.exp, test/appimage/appimage-trace.exp, test/appimage/appimage-v1.exp, test/appimage/appimage-v2.exp, test/appimage/appimage.sh, test/appimage/filename.exp
Mount AppImage on `/run/firejail/appimage` in the sandbox process, rather than on a subdirectory in the main process. This way the mount is destroyed automatically when the sandbox terminates, and it is private to the sandbox and not a global resource (except for root, who can always peek into the loop device).
=> make appimage mounts private to sandbox

etc/inc/disable-programs.inc
qcomicbook is the "PawelStolowski" folders
pipe-viewer doesn't has a .local folder.
EDIT: adding mcomix, it has no cache
=> [minor] qcomicbook and pipe-viewer in disable-programs

etc/profile-a-l/firefox.profile
KeePassXC changed the socket name.
https://github.com/keepassxreboot/keepassxc/commit/a145bf91191f0a4630a7e31654aff8a8dfd09bf0
Keep also old socket name in whitelist for back compatibility
=> Fix for KeePassXC plugin

etc/profile-a-l/b2sum.profile, etc/profile-a-l/cksum.profile, etc/profile-a-l/hasher-common.profile, etc/profile-m-z/md5sum.profile, etc/profile-m-z/sha1sum.profile, etc/profile-m-z/sha224sum.profile, etc/profile-m-z/sha256sum.profile, etc/profile-m-z/sha384sum.profile, etc/profile-m-z/sha512sum.profile, etc/profile-m-z/sum.profile
Someone told me that md5 is insecure, so I decided it is better to sandbox it so that is can be used securely. :upside_down_face:
---
hasher-common.profile is based on archiver-common.profile.
=> Add profile for checksum tools

src/common.mk.in, src/libpostexecseccomp/Makefile.in, src/libtrace/Makefile.in, src/libtracelog/Makefile.in
When using the "wildcard" internal functions.
This usage has been present since the first "real" commit in the
repository: commit 137985136 ("Baseline firejail 0.9.28").
>     H_FILE_LIST       = $(sort $(wildcard *.[h]))
>     C_FILE_LIST       = $(sort $(wildcard *.c))
There is only a single character (i.e.: "h") inside the character class,
so its usage should make no functional difference.  It may stem from a
construct that could have originally looked something like this:
C_FILE_LIST       = $(sort $(wildcard *.[ch]))
Which would match both the implementation files and the headers.
From Section 4.4, [Using Wildcard Characters in File Names][1] of the
GNU make manual:
> A single file name can specify many files using wildcard characters.
> The wildcard characters in make are ‘*’, ‘?’ …
=> makefiles: replace character class with plain char

etc/profile-a-l/amarok.profile, etc/profile-m-z/vmware.profile
should I create `mkdir` entry for `/var/lib/vmware`?
=> Update vmware.profile & dbus-policy for amarok

etc/profile-a-l/electron.profile, etc/profile-a-l/feh.profile
The renaming done in #4126 needs additional changes in affected profiles to keep functionality afloat.
=> Follow up for #4126

.github/ISSUE_TEMPLATE/bug_report.md
- Avoid confusing on "What changed calling the program by path"
- Checklist: Questions should be asked in discussions
=> Improve issue template

etc/profile-m-z/signal-desktop.profile
Without it, all chat timestamps are in UTC.
=> Add localtime to signal-desktop's profile.

etc/profile-a-l/dropbox.profile
/usr/bin/dropbox needs access to python3, at least for dropbox
command-line interface version 2020.03.04 as packaged by the RPM Fusion
project.  Fixes issue #4150
=> dropbox: allow python3, fix for issue #4150

etc/profile-m-z/signal-desktop.profile
Inspired by #4158.
Regarding the comment:
```
#include whitelist-runuser-common.inc
#include whitelist-usr-share-common.inc
#ignore private-cache --> signal-desktop doesn't use ~/.cache
```
IMO we can drop these. Both `whitelist-runuser-common.inc` and `whitelist-usr-share-common.inc` are already getting included via electron.profile and that seems to work as expected. On my Arch Linux box signal-desktop doesn't use ~/.cache so it should be safe to keep `private-cache` as well.
=> allow notifications + comment fixes

etc/profile-a-l/amarok.profile, etc/profile-m-z/spectacle.profile
`dbus-user.own org.kde.Spectacle` -is needed for keybindings to work.
`dbus-user.own org.kde.kglobalaccel` -is not necessary for keybindings to work as amarok already has ownership of `org.kde.amarok`.
=> Minor Fixes

etc/profile-m-z/quodlibet.profile
Now we have the new quodlibet.profile I've tested its functionality on a setup where users only have exfalso, but not quodlibet. Both profiles are looking good, but I noticed the below error when firejailing exfalso:
```
...
/usr/lib/python3.9/site-packages/quodlibet/qltk/filesel.py:130: Warning: getpwuid_r(): failed due to unknown user id (1001)
...
```
Adding `passwd` to private-etc fixes this for uid's > 1000.
=> add passwd to private-etc

etc/apparmor/firejail-local, etc/profile-a-l/brave.profile, etc/profile-a-l/chromium-common.profile
Fixes #4190. Instead of dropping apparmor here, it's better to add a comment directly into brave.profile. This keeps other apps including in chromium-common.profile. As the latter is included by profiles other than brave, this might not be the most elegant way to handle this. Open to suggestions!
UPDATE: changed the fix by adding instructions on how to opt-in to brave + tor into brave.profile. No need to affect all of the other apps that include chromium-common.profile.
=> unblock tor support in brave

etc/profile-a-l/chromium-common.profile, etc/profile-a-l/firefox-common-addons.profile
=> Add examples how to allow browser access to Gnome extensions connector

etc/inc/allow-opengl-game.inc, etc/inc/disable-programs.inc, etc/profile-a-l/alienarena-wrapper.profile, etc/profile-a-l/alienarena.profile, etc/profile-a-l/ballbuster-wrapper.profile, etc/profile-a-l/ballbuster.profile, etc/profile-a-l/colorful-wrapper.profile, etc/profile-a-l/colorful.profile, etc/profile-a-l/etr-wrapper.profile, etc/profile-a-l/gl-117-wrapper.profie, etc/profile-a-l/gl-117-wrapper.profile, etc/profile-a-l/gl-117.profile, etc/profile-a-l/glaxium-wrapper.profie, etc/profile-a-l/glaxium-wrapper.profile, etc/profile-a-l/glaxium.profile, etc/profile-m-z/neverball-wrapper.profie, etc/profile-m-z/neverball-wrapper.profile, etc/profile-m-z/neverputt-wrapper.profie, etc/profile-m-z/neverputt-wrapper.profile, etc/profile-m-z/pinball-wrapper.profie, etc/profile-m-z/pinball-wrapper.profile, etc/profile-m-z/pinball.profile, etc/profile-m-z/scorched3d-wrapper.profile, etc/profile-m-z/scorched3d.profile, etc/profile-m-z/supertuxkart-wrapper.profile, etc/profile-m-z/xonotic.profile, src/firecfg/firecfg.config
Add profiles for alienarena, ballbuster, colorful, gl-117, glaxium, pinball
Commons of opengl-game-wrapper.sh 
- Add allow-opengl-game.inc
- Add profiles for alienarena-wrapper, ballbuster-wrapper,
colorful-wrapper, etr-wrapper, gl-117-wrapper, glaxium-wrapper,
neverball-wrapper, neverputt-wrapper, pinball-wrapper,
supertuxkart-wrapper
- Use allow-opengl-game.inc in xonotic.profile and the profiles above
- xonotic.profile: simplify private-bin by using xonotic*
=> Commons of opengl-game-wrapper.sh

etc/inc/disable-programs.inc, etc/profile-m-z/steam.profile
Due to using globbing on mkdir, the current version causes this:
@davidebeatrici commented on 2021-04-23[1]:
> ```
> Error: "${HOME}/.local/share/RogueLegacy*" is an invalid filename: rejected character: "*"
> ```
Added on commit a603d4d ("steam: some more games added") / PR #4170.
The wildcard was used because Rogue Legacy apparently looks up multiple
different paths for the config and also for the data[1][2][3]:
1. ~/.config/RogueLegacy
2. ~/.config/RogueLegacyStorageContainer
3. ~/.local/share/RogueLegacy
4. ~/.local/share/RogueLegacyStorageContainer
The ones containing "RogueLegacyStorageContainer" appear to be legacy
paths (i.e.: paths which are only created by older versions of Rogue
Legacy)[2].
So replace all globs with the full paths because:
* The paths are known a priori …
=> steam.profile: fix rogue legacy paths and syntax

src/man/firejail-profile.txt, src/man/firejail.txt
Commit 0.9.60-1070-g40d3604f (40d3604f) updated the man pages with respect to
--private-opt, --private-etc, and --private-srv.  It was made after
testing firejail 0.9.52 (from Ubuntu 18.04).  However, it
unfortunately did not accurately reflect the the behavior of the
current HEAD at the time, because commit 0.9.56-rc1-14-ga9242301 (a9242301) had
previously slightly changed the behavior of these three options (after
0.9.52), and was released in 0.9.56.  The man pages changes made in
commit 40d3604f were therefore not entirely correct.
This commit updates the man pages to describe the behavior as
implemented in a9242301 (and is still the behavior as of the current
HEAD: 0.9.64-737-g937815ba (937815ba)).
Signed-off-by: Jeff Squyres <jsquyres@cisco.com>
=> man: corrections regarding --private-FOO options

etc/inc/disable-programs.inc, etc/inc/whitelist-1793-workaround.inc, etc/profile-m-z/neochat.profile, src/firecfg/firecfg.config
This is a firejail profile for Neochat, the KDE Matrix Client ( https://apps.kde.org/id/neochat/ ).
I have tested this only on Arch Linux (and everything seems to work).
I've also added the neochat config files to `disable-programs.inc`.
=> New profile for neochat

src/firejail/firejail.h, src/firejail/fs_dev.c, src/firejail/main.c, src/firejail/profile.c, src/firejail/sandbox.c, src/man/firejail-profile.txt, src/man/firejail.txt
Fixes #2203.
---
By default only joystick devices (`/dev/input/js*`) can be accessed.
At least, that's the case on Debian: the other entries have more restrictive permissions.
The original owner and group are `root` and `input`, respectively.
However, until we have granular input control options, allowing access to joysticks only is better than nothing.
```bash
$ ls -l /dev
total 0
lrwxrwxrwx  1 nobody nogroup      8 23 apr 07.22 cdrom -> /dev/sr0
lrwxrwxrwx  1 nobody nogroup      8 23 apr 07.22 cdrw -> /dev/sr0
drwxr-xr-x  3 nobody nogroup    100 22 apr 19.18 dri
lrwxrwxrwx  1 nobody nogroup      8 23 apr 07.22 dvd -> /dev/sr0
lrwxrwxrwx  1 nobody nogroup      8 23 apr 07.22 dvdrw -> /dev/sr0
lrwxrwxrwx  1 nobody nogroup     13 23 apr 07.22 fd -> /proc/self/fd
crw-rw-rw-  1 nobody …
```
=> Map /dev/input with "--private-dev", add "--no-input" option to disable it

etc/profile-a-l/chromium.profile
Webext browser extensions installed through packages are installed into `/usr/share/mozilla/extensions/` in Debian.
To make them usable in Chromium, symlinks are created from `/usr/share/chromium/extensions/` to the mozilla dir.
Reporty by Ralf Jung on [#986049](https://bugs.debian.org/986049).
=> profiles: whitelist mozilla (webext) extensions in chromium profile

etc/profile-a-l/git-cola.profile, etc/profile-a-l/gnome-logs.profile, etc/profile-a-l/gnome-system-log.profile, etc/profile-m-z/yelp.profile
Impacts comments only, no functional changes.
=> read-write fixes

etc/firejail.config, src/firejail/checkcfg.c, src/firejail/chroot.c, src/firejail/dbus.c, src/firejail/firejail.h, src/firejail/fs.c, src/firejail/fs_home.c, src/firejail/fs_whitelist.c, src/firejail/pulseaudio.c, src/firejail/restrict_users.c, src/firejail/util.c, src/firejail/x11.c, src/include/rundefs.h
Somewhat experimental whitelist implementation. Fixes #2041.
All top level directories are allowed except /proc, /sys and /run. As an exception from the exception, /sys/module and /run/user/$UID are allowed. This way all profiles will continue to work. Another special case is /usr, where the subdirectories (like /usr/share) are top level directories for the purpose of whitelisting.
For now all restrictions regarding symbolic links are gone (and `follow-symlink-as-user` from firejail.config is without effect). I'm not entirely sure if that is sustainable, but it can always be added back.
Otherwise this implementation should be very close to the current one.
Maybe it would also make sense to reimplement private-lib as whitelist then, in order to prevent name collisions as in #3236
=> Whitelist2

etc/profile-a-l/cargo.profile
@reinerh here is one :wink: (#4281)
=> Add cargo.profile

etc/profile-a-l/lutris.profile
Recently I updated my OS to Ubuntu 21.04 and I discovered that profile for Lutris has been added. Unfortunately Lutris v0.5.8.3 didn't start when I tried to use it. After spending some time on debugging I found two problems (both are fixed in this pull request):
1. Lutris is using ldconfig, so it requires access to /sbin and /usr/sbin. I've added noblacklist option for both paths.
2. Games with enabled Feral GameMode won't run if D-Bus is disabled. I've disabled options dbus-user and dbus-system.
=> Fix Lutris profile

etc/inc/allow-common-devel.inc, etc/inc/disable-programs.inc
This is a follow-up for https://github.com/netblue30/firejail/pull/4284. See [cargo book](https://doc.rust-lang.org/cargo/reference/config.html) and [discussion](https://github.com/netblue30/firejail/pull/4284#discussion_r633132914) for details.
=> add support for cargo toml/non-toml files

configure, configure.ac
The configure script happens to work if /bin/sh supports the non-POSIX
"+=" operator (e.g.: bash) and fails otherwise (e.g.: dash).
This usage first appeared on configure.ac on commit 66a476419 ("gcov
support"), which is from 2016.
If the --enable-apparmor flag is passed to ./configure (which is the
default on Arch Linux), running `make` fails due to the missing
-lapparmor LDFLAG.  Thus, building firejail-git from the AUR does not
work if /bin/sh is e.g.: dash.
Errors when running the build commands below from makepkg:
$ ./configure --prefix=/usr --enable-apparmor >/dev/null
./configure: 3174: EXTRA_CFLAGS+= -mindirect-branch=thunk: not found
./configure: 3246: EXTRA_CFLAGS+= -fstack-clash-protection: not found
./configure: 3282: EXTRA_CFLAGS+= -fstack-protector-strong: not found …
=> configure*: fix build with non-bash /bin/sh

.github/workflows/build.yml, configure, configure.ac
this fixes a new false positive memory leak (#4297), but unfortunately
opens a few new false positives (#4274).
therefore let it ignore memleak checks for now, until the detection
is a bit more stable in GCC.
Fixes: #4274, #4297
ping @smitsohu @rusty-snake @glitsj16 @kmk3
=> CI: build with GCC 11

src/man/firejail.txt
The example should explicitly pick krita profile. Otherwise it looks like firejail does automatically guess "krita" profile for "krita-3.0-x86_64.appimage" which is not true.
It may be not important in the case of `--private` (since non existing `.config/kritarc` is not blacklisted and krita can create and write to it), but if a user copy-paste the sample cmd and replace `--private` with `--private=some-dir`, krita would complain about `.config/kritarc` being not writable if only it exists (which means it would not complain on first run with empty `some-dir`, but the next run the file gets blacklisted since it exists).
=> Refine appimage example in docs

etc/profile-a-l/gunzip.profile
gunzip is a wrapper script of gzip
so it needs "ignore include disable-shell.inc"
=> [minor] gunzip profile broken

configure, configure.ac
```sh
$ git log --reverse --pretty='%s%n%n%b%n-----%n' master..HEAD
```
configure.ac: run autoupdate to fix autoconf warning
This fixes the following warning:
$ autoconf
configure.ac:306: warning: AC_OUTPUT should be used without arguments.
configure.ac:306: You should run autoupdate.
Environment:
$ grep '^NAME' /etc/os-release
NAME="Artix Linux"
$ pacman -Q autoconf
autoconf 2.71-1
Though keep `AC_PREREQ` at 2.68 (released on 2010-09-23[1]), as version
2.71 (which autoupdate automatically bumps to) is rather recent
(released on 2021-01-28[2]) and the changes do not appear to require a
version bump, as on `AC_INIT` it only adds some quotes, and the rest of
the changes are consistent with the autoconf 2.68 manual.  From Section
18.4, Obsolete Macros[3]:
> — Macro: AC_OUTPUT ([file]..., …
=> Configure improvements

etc/inc/disable-programs.inc, etc/profile-a-l/elinks.profile, etc/profile-a-l/links-common.profile, etc/profile-a-l/links.profile, etc/profile-a-l/links2.profile, etc/profile-m-z/xlinks.profile, etc/profile-m-z/xlinks2, src/firecfg/firecfg.config
they are a bunch of variants of links
created links-common.profile
adapted links, elinks
fixed xlinks
added links2, xlinks2
EDITED
=> reorganizing links browsers

etc/profile-m-z/telegram-desktop.profile
I changed `include tekegram-desktop.local` to `include telegram-desktop.local`.
=> Correct typo in telegram-desktop profile

contrib/jail_prober.py
contrib/jail_prober.py strips include directives which is what is most often the culprit. This PR remedies that.
In addition I decided to set the firejail profiles directory to '/etc/firejail'. If this is not desired please share your suggestions.
=> jail_prober: enable absolut include directives

src/firejail/cmdline.c, src/firejail/firejail.h, src/firejail/join.c, src/firejail/main.c, src/firejail/no_sandbox.c
The commit message contains an abbreviated version of this explanation.  This PR is a possible solution for #1644, #887, and #1817.
-----
`sshd` invokes firejail slightly differently than how firejail is normally invoked on the command line.  One possible fix is to recognize that firejail was launched by sshd and slightly modify its quoting behavior.
There's a difference between invoking firejail with a multi-token command:
```sh
$ firejail --quiet echo hello world
hello world
```
and ssh'ing in a non-interactive multi-token command with firejail as the login shell (assume a trivial `username: --shell=/bin/bash` line in `/etc/firejail/login.users`):
```
$ ssh username@othernode echo hello world
/bin/bash: echo hello world: command not found
```
The difference is that in the `ssh` case, …
=> cmdline.c: optionally quote the resulting command line

etc/profile-a-l/ddgr.profile, etc/profile-a-l/googler-common.profile, etc/profile-a-l/googler.profile, src/firecfg/firecfg.config
search google and duckduckgo from the terminal.
They are practically the same, from the same dev
i added w3m, so that it can launch a browser.
They have no configuration files
added noinput
googler doesn't use google's API, so it quickly bitrots in the repositories, the pip3 version was broken.
if it's broken in the repo
https://github.com/jarun/googler#downloading-a-single-file
ddgr page if needed, the repo version should be fine
https://github.com/jarun/ddgr/releases/latest
=> creating googler and ddgr profiles

etc/inc/disable-programs.inc, etc/profile-m-z/rtin.profile, etc/profile-m-z/tin.profile
Profile for the tin newsreader.
Tested subscribing + reading mailinglists via gmane.
Did not test reading local spool or replying by mail, which is not allowed in the profile (not sure if anyone uses that feature).
Also I can't whitelist files directly in $HOME, as it was not possible to overwrite files via rename. Is there any workaround?
=> profiles: add profile for tin news reader

src/firejail/appimage.c, src/firejail/chroot.c, src/firejail/fs.c, src/firejail/fs_mkdir.c, src/firejail/ls.c, src/firejail/main.c, src/firejail/profile.c, src/firejail/rlimit.c, src/firejail/sandbox.c, src/firejail/util.c, src/firemon/interface.c, src/firemon/netstats.c, src/firemon/procevent.c, src/firemon/top.c
Fixes the following "implicit declaration" warning (13 occurrences in
total) when building with gcov support:
$ pacman -Q gcc10
gcc10 1:10.2.0-3
$ CC=gcc-10 && export CC
$ ./configure --prefix=/usr --enable-apparmor --enable-gcov >/dev/null
$ make >/dev/null
appimage.c: In function ‘appimage_set’:
appimage.c:140:2: warning: implicit declaration of function ‘__gcov_flush’ [-Wimplicit-function-declaration]
140 |  __gcov_flush();
|  ^~~~~~~~~~~~
interface.c: In function ‘print_sandbox’:
interface.c:149:3: warning: implicit declaration of function ‘__gcov_flush’ [-Wimplicit-function-declaration]
149 |   __gcov_flush();
|   ^~~~~~~~~~~~
netstats.c: In function ‘netstats’:
netstats.c:246:4: warning: implicit declaration of function ‘__gcov_flush’ [-Wimplicit-function-declaration]
246 | …
=> gcov: add missing gcov.h includes

etc/profile-a-l/cargo.profile
Building (specific) packages on Arch Linux (from AUR) needs access to /usr/share/pkgconfig. I've only seen it happen with cargo, so I added the whitelist to cargo.profile. We might want to add it to wusc instead. Suggestions welcome!
=> allow access to pkgconfig

RELNOTES, etc/firejail.config, src/firejail/checkcfg.c, src/firejail/firejail.h, src/firejail/main.c, src/firejail/seccomp.c, src/man/firejail.txt
Contributes to #3219.
I didn't know where to put kcmp, so still no full solution.
=> augment seccomp lists in firejail.config

src/firejail/appimage.c, src/firejail/chroot.c, src/firejail/fs.c, src/firejail/fs_mkdir.c, src/firejail/ls.c, src/firejail/main.c, src/firejail/profile.c, src/firejail/rlimit.c, src/firejail/sandbox.c, src/firejail/util.c, src/firemon/interface.c, src/firemon/netstats.c, src/firemon/procevent.c, src/firemon/top.c, src/include/gcov_wrapper.h
The build currently fails if gcov support is enabled:
$ pacman -Q gcc
gcc 11.1.0-1
$ ./configure --prefix=/usr --enable-apparmor --enable-gcov >/dev/null
$ make >/dev/null
[...]
netstats.c: In function ‘netstats’:
netstats.c:250:25: warning: implicit declaration of function ‘__gcov_flush’; did you mean ‘__gcov_dump’? [-Wimplicit-function-declaration]
250 |                         __gcov_flush();
|                         ^~~~~~~~~~~~
|                         __gcov_dump
[...]
/usr/bin/ld: netstats.o: in function `netstats':
/tmp/firejail-git/src/firejail-git/src/firemon/netstats.c:250: undefined reference to `__gcov_flush'
[...]
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:10: firemon] Error 1
make: *** [Makefile:42: src/firemon/firemon] Error 2
[...]
This happens …
=> gcov: fix build failure with gcc 11.1.0

src/firejail/appimage.c, src/firejail/chroot.c, src/firejail/fs.c, src/firejail/fs_mkdir.c, src/firejail/ls.c, src/firejail/main.c, src/firejail/profile.c, src/firejail/rlimit.c, src/firejail/sandbox.c, src/firejail/util.c, src/firemon/interface.c, src/firemon/netstats.c, src/firemon/procevent.c, src/firemon/top.c, src/include/gcov_wrapper.h
Instead of wrapping every gcov function call in an ifdef.
Note: The usage of `((void)0)` is based on section 7.2 of the C99
standard (N1256)[1] [2]:
> 7.2 Diagnostics <assert.h>
>
> 1 The header <assert.h> defines the assert macro and refers to another
> macro,
>
>     NDEBUG
>
> which is not defined by <assert.h>. If NDEBUG is defined as a macro
> name at the point in the source file where <assert.h> is included, the
> assert macro is defined simply as
>
>     #define assert(ignore) ((void)0)
See also assert.h(0p) from POSIX.1-2017[3].
Note: This is a continuation of commit b408b20c7 ("gcov: fix build
failure with gcc 11.1.0") / PR #4373.
[1] http://www.open-std.org/JTC1/SC22/WG14/www/docs/n1256.pdf
[2] https://port70.net/~nsz/c/c99/n1256.html#7.2
[3] …
=> gcov: use no-op functions if not enabled

etc/profile-a-l/bitwarden.profile
See #4294.
@glitsj16 @iandstanley can you say something about the `ignore` block.
```
ignore include whitelist-runuser-common.inc
ignore include whitelist-usr-share-common.inc
ignore disable-mnt
ignore dbus-user none
ignore dbus-system none
```
=> Refactor bitwarden as electron redirect

etc/inc/whitelist-common.inc, src/firejail/fs.c
This patch allows sandboxed programs to access a sndiod server and play audio on systems where sndio handles audio.
=> Fix sndio support

.git-blame-ignore-revs
fe0f975f447d59977d90c3226cc8c623b31b20b3 (move whitelist/blacklist to
allow/deny) is just a huge rename¹ w/o effects to the profile. Ignoreing
it in git blame to see which commits actually added/changed a
allow/nodeny command.
Configure git to use .git-blame-ignore-revs:
git config blame.ignoreRevsFile .git-blame-ignore-revs
EDIT: ¹ but it also https://github.com/netblue30/firejail/commit/fe0f975f447d59977d90c3226cc8c623b31b20b3#diff-7c733ed074575806d2755a48dd858c22c318d0190737f64299fa6dda414ba29b and https://github.com/netblue30/firejail/commit/fe0f975f447d59977d90c3226cc8c623b31b20b3#diff-9f33b84e2dc73f7861f9d367b48fe0e3cf23832184311457b6ebef69714c358c
=> Exclude allow/deny move in profile from git blame

etc/inc/disable-common.inc
/etc/firejail/disable-common.inc has a blacklist for "${HOME}/.Private" but not for "${HOME}/Private"
=> Added ${HOME}/Private blacklist to disable-common

src/firejail/arp.c
arp_check relied on select(2) decreasing the timeout. This doesn't seem
to be the case on Linux anymore, thus arp_check tends to hang when the
interface sees a lot of traffic. Calculating the timeout explicitly
solves the problem.
Fixes #3958
=> Fix hanging arp_check

etc/profile-m-z/telegram.profile
Telegram loads packed resources dynamically since https://github.com/telegramdesktop/tdesktop/commit/443eef3202ee43c2e820cc550fbcc70a7609f452.
In the [official Debian package](https://packages.debian.org/bullseye/telegram-desktop), the relevant file can be found at `/usr/share/TelegramDesktop/tresources.rcc`.
If the file cannot be loaded, the program fails to launch and prints "Packed resources not found".
---
~Please note that a known issue remains: the tray icon is missing.~
The tray icon appears with Telegram Desktop 2.9.2.
=> telegram.profile: whitelist /usr/share/TelegramDesktop

etc/profile-m-z/multimc5.profile
The same `ignore` is used for the minecraft-launcher, necessary to execute the downloaded LWJGL native libraries.
If you submit a PR for new profiles or changing profiles, please do the following:
- The ordering of options follow the rules described in [/usr/share/doc/firejail/profile.template](https://github.com/netblue30/firejail/blob/master/etc/templates/profile.template).  
> Hint: The profile-template is very new. If you install firejail with your package manager, it may be missing. In order to follow the latest rules, it is recommended to use the template from the repository.
- Order the arguments of options alphabetically. You can easily do this with …
=> multimc5: fix exec of LWJGL libraries

.github/ISSUE_TEMPLATE/bug_report.md
Make sections easier to see and edit.
By the way, I've intended to do this for a while, as I always thought that the
template looked rather crooked.  I had assumed that it was just created from
scratch by hand like any other file, but recently I learned that GitHub is what
generates issue templates using such unusual markup for some reason.  Now I see
that it's even mentioned in the commit that adds the template:
```console
$ git show --pretty='%h %ai %s%n%n%b' --name-status bd29bf7202
bd29bf720 2020-04-07 16:40:07 -0500 Add bug report template
(Mostly) auto-generated with GitHub, will need tweaking over time
A       .github/ISSUE_TEMPLATE/bug_report.md
```
Cc: @Fred-Barclay (from the commit) @reinerh @rusty-snake (from #4468)
=> Issue template improvements

README.md
Home page: https://artixlinux.org
A few months ago, running `pacman -S firejail` would install it from
Arch's "community" repository by default.  But currently, Artix has its
own firejail package, in the "galaxy" repository:
* https://gitea.artixlinux.org/packagesF/firejail
* https://repology.org/project/firejail/versions
See also the following article from 2021-06-09:
https://artixlinux.org/news.php#Arch_repositories_made_optional
> Arch repositories made optional
>
> Artix has reached the stage where it can operate without the help of
> the Arch repositories, including the preparation of its installation
> media.  As such, all new weekly ISO images will ship without [extra],
> [community] and [multilib] enabled in pacman.conf.  Existing setups
> will not be affected, but new users may …
=> README.md: add artix linux to distro list

.git-blame-ignore-revs
Add commit f43382f1e ("Revert "move whitelist/blacklist to allow/deny"")
from PR #4410.
As mentioned on commit b023b9a6f ("Exclude allow/deny move in profile
from git blame") / PR #4390, commit fe0f975f4 ("move whitelist/blacklist
to allow/deny") "is just a huge rename", and so is the revert of it.
Note that there is a follow-up to f43382f1e: commit 2e4d52ec6 ("Revert
allow/deny additional files") (sort of related to #4421).  It renames a
bit too much, which is later fixed by commit 3836131f3 ("Fix zim and
rednotebook").  Since these are small changes and since they involve
regressions, neither commit is added.
=> .git-blame-ignore-revs: add revert of allow/deny move

etc/inc/whitelist-run-common.inc
This is a quick fix of #4482 for distributions that link `/etc/resolv.conf` to `/run/systemd/resolve/stub-resolv.conf`  (Arch Linux is one of them).
=> Fix broken DNS resolution on Arch Linux using systemd-resolved

etc/profile-a-l/evince.profile
Enable evince to display archived images (.cbz) file with plugin installed.
libarchive.so should be added to the private-lib option so that evince can extract images from the archived file.
Related issue: #4555
=> Fix #4555 - Allow evince to read .cbz file format

etc/inc/disable-programs.inc
Just blacklisting [Exodus](https://www.exodus.com). Haven't created a profile for it yet.
=> Blacklist Exodus wallet

etc/profile-a-l/librewolf.profile
This is a very simple pull request.
=> Let programs outside librewolf sandbox open new tabs in librewolf

src/firejail/join.c, src/firejail/main.c, src/firejail/sandbox.c
* add 128 to exitcode if child received a fatal signal
(this is similar to what bash and other shells do)
* unify exitcodes across firejail: treat processes created with `join`
the same as processes in the primary process tree
fixes #4474
=> rework exitcodes

src/firejail/fs_hostname.c
This patch fixes https://github.com/netblue30/firejail/issues/2758#issuecomment-805174951 . Especially for NixOS users, the file `/etc/hosts` is a symlink and firejail fails with exiting after `is_link()` check.
Removing this check fixes the issue.
=> Remove /etc/hosts is_link check

.github/pull_request_template.md, .github/workflows/sort.yml, README, RELNOTES, contrib/gdb-firejail.sh, etc-fixes/0.9.58/atom.profile, etc-fixes/seccomp-join-bug/README, etc/apparmor/firejail-default, etc/inc/disable-devel.inc, etc/profile-a-l/email-common.profile, etc/profile-a-l/kdiff3.profile, etc/profile-a-l/links-common.profile, etc/profile-m-z/spectacle.profile, etc/profile-m-z/sway.profile, gcov.sh, linecnt.sh, src/bash_completion/firejail.bash_completion.in, src/man/firejail-profile.txt, src/man/firejail.txt, src/man/firemon.txt
Split from #4497 for further discussion.
For trailing whitespace a commit hook/CI check could be implemented, but most of the excess whitespace is within other text which makes it harder for automated tools to deal with. I mainly spotted it when reading through the files.
=> Trim excess whitespace

etc/profile-a-l/amule.profile
In order UPnP to work netlink protocol must be added
=> Correct amule.profile for upnp

etc/inc/allow-common-devel.inc, etc/inc/allow-ruby.inc, etc/inc/disable-interpreters.inc, etc/inc/disable-programs.inc, etc/profile-a-l/build-systems-common.profile, etc/profile-a-l/bundle.profile, etc/profile-a-l/cargo.profile, etc/profile-a-l/cmake.profile, etc/profile-m-z/make.profile, etc/profile-m-z/meson.profile, etc/profile-m-z/pip.profile
Profiles: bunler, cargo (refactor), cmake (untested), make, meson, pip
All redirect to build-systems-common.profile
Other fixes:
- blacklist ${HOME}/.bundle
- blacklist ${HOME}/.cargo/* -> blacklist ${HOME}/.cargo
- blacklist /usr/lib64/ruby
You can now `firejail make` firejail :laughing:.
=> Add profiles for build-systems (/package-managers)

.github/ISSUE_TEMPLATE/bug_report.md
Use `LC_ALL` and add a checked item example.
Relates to #4479 and #4515.
=> Issue template improvements2

src/firejail/firejail.h, src/firejail/util.c
```console
* util.c: remove tty comment from get_group_id
* util.c: fix return type of get_group_id
* util.c: rename "group" arg to "groupname" in get_group_id
```
=> Fix misc in get_group_id

etc/profile-m-z/tremulous.profile
Tremulous on Arch (`tremulous-grangerhub-bin` in AUR) uses wrapper hence needs some modifications.
=> Fix tremulous profile for Arch users

gcov.sh, linecnt.sh, mkasc.sh, mkdeb.sh.in, mkman.sh, mkuid.sh
Split from  #4497 for further discussion.
I did not modify the configure script, which is a source of a lot of the remaining shellcheck warnings, because it comes from autoconf and so it makes little sense to try to fix it here.
I also did not modify the scripts in contrib, because they possibly are maintained at some other place. Similarly with the other scripts that don't appear to be called from any of the makefiles.
=> Fix shellcheck warnings

etc/inc/allow-ssh.inc, etc/inc/disable-common.inc
See https://github.com/netblue30/firejail/commit/9a81078ddbbb4215d06f7d1861481ece05ebda99#commitcomment-59921139 for details. Basically this PR (no)blacklists /usr/lib/{open,}ssh instead of referencing all possible individual files that might get installed there depending on OS and versioning.
=> more ssh fixes

Makefile.in, README.md, src/firecfg/firecfg.config, src/firecfg/main.c, src/firejail/appimage.c, src/man/firecfg.txt
This should make it easier for users, and distributions, to customize
which programs they want firejail to wrap.
Signed-off-by: Hank Leininger <hlein@korelogic.com>
Closes: https://github.com/netblue30/firejail/issues/408
Bug: https://github.com/netblue30/firejail/issues/2097
Bug: https://github.com/netblue30/firejail/issues/2829
Bug: https://github.com/netblue30/firejail/issues/3665
=> Relocate firecfg.config to /etc/firejail/

src/fids/main.c, src/firejail/fs.c, src/firejail/seccomp.c
This should fix all such warnings on the following files:
* src/fids/main.c
* src/firejail/seccomp.c
Misc: Besides the above reason, these are some of the more
straightforward TOCTOU warning fixes and they are done without any
additional refactor commits, so that's the reason for "easy ones".
List of TOCTOU warnings:
https://github.com/netblue30/firejail/security/code-scanning?query=id%3Acpp%2Ftoctou-race-condition
See https://cwe.mitre.org/data/definitions/367.html
Relates to #4503.
=> Fix TOCTOU/CodeQL CWE-367 warnings (easy ones + fs.c)

src/firejail/main.c, src/firejail/run_symlink.c
This change doesn't alter any checks, but it gives more specific
errors when a sanity check of env vars or argv does not pass, which
can point to limits to raise or at least give us better detailed bug
reports.
Signed-off-by: Hank Leininger <hlein@korelogic.com>
Bug: https://github.com/netblue30/firejail/issues/3678
Bug: https://github.com/netblue30/firejail/issues/3851
Bug: https://github.com/netblue30/firejail/issues/4633
=> Make env/arg sanity check failure messages more useful

etc/inc/disable-common.inc
Added on commit f0adf06c3 ("disable-common.inc: more SUID", 2021-11-09).
Relates to #4668.
=> disable-common.inc: fix paths of slock and physlock

etc/inc/disable-programs.inc, etc/profile-m-z/openstego.profile, src/firecfg/firecfg.config
This PR adds a profile for OpenStego as requested in #4677 
Advice regarding the proper whitelisting of XDG user directories would be welcome since I am not sure how restrictive this is supposed to be. A user probably would like to files access in all user dirs for convenience. Is there a standard regarding that?
I couldn't write a sensible `private-etc` since this seems very dependent on the specific Java environment used and is probably hard to maintain.
Have a nice day!
=> Add OpenStego profile

src/firejail/main.c, src/firejail/util.c
Even when `nogroups` is not used, avoid keeping the audio and video
groups when `nosound` and `novideo` are used, respectively.
Based on @rusty-snake's suggestion:
https://github.com/netblue30/firejail/issues/4603#issuecomment-944046299
Relates to #4603.
---
Note: I haven't tested this.
=> Consider nosound and novideo when keeping groups & misc refactors

etc/apparmor/firejail-local
Hi,
The Ipfs network of Brave is broken by firejail if in the profile of chromium-common 'apparmor' is activated.
Regards.
=> Update firejail-local for Brave + ipfs

etc/profile-a-l/display.profile
Various .so's are needed to allow execution, /etc/ImageMagick-7/ is
needed for various policy XML files, and /usr/$(libdir)/ImageMagick-x.y.z/
is needed in order to have access to decoders.
Tested on Gentoo; I don't know if other distros put the relevant bits
in different paths.
Signed-off-by: Hank Leininger <hlein@korelogic.com>
=> etc/profile-a-l/display.profile: additions needed on Gentoo

etc/profile-a-l/com.github.tchx84.Flatseal.profile, src/firecfg/firecfg.config
Flatseal is a GUI tool to configure permissions for Flatpak applications.
This restricts permissions as much as possible without affecting functionality.
=> Add a profile for Flatseal

etc/profile-a-l/dino.profile
According to my tests, without netlink protocol, audio/video calls keep trying to connect for ever without really connecting.
=> dino.profile: netlink protocol is required for audio/video calls.

src/firejail/firejail.h, src/firejail/main.c, src/firejail/profile.c, src/firejail/sandbox.c, src/firejail/util.c
This amends commit b828a9047 ("Keep audio and video groups regardless of
nogroups", 2021-11-28) from PR #4725.
The commit above did not change the behavior (the groups are still not
kept).  With this commit, it appears to work properly:
$ groups | grep audio >/dev/null && echo kept
kept
$ firejail --quiet --noprofile --nogroups groups |
grep audio >/dev/null && echo kept
kept
$ firejail --quiet --noprofile --nogroups groups |
grep audio >/dev/null && echo kept
$
Add a new check_can_drop_all_groups function to check whether the
supplementary groups can be safely dropped without potentially causing
issues with audio, 3D hardware acceleration or input (and maybe more).
It returns false if nvidia (and no `no3d`) is used or if (e)logind is
not running, as in either case the supplementary …
=> Fix keeping certain groups with nogroups

etc/profile-m-z/skypeforlinux.profile
I hope these are in-order, since this profile is a bit of an unusual one.
I added Skype's config directory to `whitelist` and `mkdir`, since otherwise the session is lost when closing and re-running it, requiring logging in again each time it's run.
I also hardened the D-Bus aspect of the profile: I started out blocking everything, and then unblocked the necessary bit. Surprisingly, Skype will log out immediately after starting _without_ `org.kde.StatusNotifierWatcher`, I've no idea about the correlation. It's probably good to keep it around for tray users too anyway.
Ran a test call and it worked fine. User session is retained when quitting/re-running too.
=> Skype profile tweaks

etc/profile-a-l/elinks.profile
By including allow-lua.inc.
Error log:
$ firejail elinks
elinks: error while loading shared libraries: liblua.so.5.4: cannot open shared object file: Permission denied
Environment: firejail-git (a82c8e021) and elinks 0.14.3-2 on Artix
Linux.
Fixes #4707.
Reported-by: @jose1711
=> elinks.profile: Fix missing access to liblua

README.md
Add the information posted by @reinerh on #4666 (related to
CVE-2021-26910 and Ubuntu's security policy) and also the instructions
from #4663 for installing from the PPA.
See also https://bugs.launchpad.net/ubuntu/+source/firejail/+bug/1916767
=> README.md: Mention security situation on Ubuntu and recommend PPA

etc/inc/disable-common.inc, etc/profile-m-z/tor-browser.profile
Thank you very much for this amazing project.
tor-browser 11.0.2-1 doesn't work without whitelisting this directory. The following was the message I got before whitelisting this directory.
>     Reading profile /etc/firejail/tor-browser.profile
>     Reading profile /etc/firejail/torbrowser-launcher.profile
>     Reading profile /etc/firejail/allow-python2.inc
>     Reading profile /etc/firejail/allow-python3.inc
>     Reading profile /etc/firejail/disable-common.inc
>     Reading profile /etc/firejail/disable-devel.inc
>     Reading profile /etc/firejail/disable-exec.inc
>     Reading profile /etc/firejail/disable-interpreters.inc
>     Reading profile /etc/firejail/disable-passwdmgr.inc
>     Reading profile /etc/firejail/disable-programs.inc
>     Reading profile …
=> Whitelist ${HOME}/.local/opt/tor-browser to make tor-browser work

etc/profile-m-z/teams-for-linux.profile, etc/profile-m-z/teams.profile
`teams-for-linux.profile` and `teams.profile` both include `electron.profile`, which has the `noinput` option, which blocks microphones and other input sources, so this option needs to be ignored.
=> Fix teams ignoring input sources e.g. microphones

etc/profile-m-z/telegram.profile
Without this fix, clicking hyperlinks in Telegram had no effect.
=> Allow telegram to open hyperlinks

etc/profile-m-z/torbrowser-launcher.profile
This fixes updating local Tor Browser installation in ~/.local/opt/tor-browser on Arch Linux. When package is updated, Tor Browser launcher extracts archive from /opt/tor-browser into user's local directory.
It seems that 
```
noblacklist /opt/tor-browser
blacklist /opt
```
doesn't work, all directories within /opt are blacklisted, and second rule has to be rewritten as `blacklist /opt/*`, but as side effect, in sandbox you can see all the names of directories in /opt, but cannot `cd` into them. I think it would be useful and intuitive if firejail would allow to write rules as I originally tried.
=> Allow /opt/tor-browser for Tor Browser profile

.github/dependabot.yml, .github/workflows/build-extra.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/profile-checks.yml
See:
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
and:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot
=> CI: pin GitHub actions to SHAs and use Dependabot to update them

etc/inc/disable-programs.inc, etc/profile-m-z/mpv.profile, etc/profile-m-z/yt-dlp.profile
Fixes #4754.
Relates to #3472, #4634 and <https://github.com/yt-dlp/yt-dlp/issues/19>.
Cc: @Fred-Barclay @NetSysFire @pirate486743186
=> yt-dlp: add missing paths & mpv.profile: whitelist paths for yt-dlp

etc/profile-m-z/skypeforlinux.profile
The downloads directory is used by skype to download files send by other parties.
=> skypeforlinux: Whitelist downloads directory

README.md, etc/inc/disable-programs.inc, etc/profile-m-z/notable.profile, src/firecfg/firecfg.config
See discussion [here](https://github.com/netblue30/firejail/discussions/4812).
=> add notable profile

etc/profile-a-l/chromium-common.profile, etc/profile-a-l/chromium.profile
Debian packages can distribute browser extensions in `/usr/share/webext`.
The directory is already allowed in Firefox (and related) profiles, but not yet for chromium.
For now I have added it to the chromium.profile, as this profile also contains whitelists another extension directory (`/usr/share/mozilla/extensions`), but maybe it would make sense to move both to chromium-common.profile?
Bug-Debian: https://bugs.debian.org/1003234
=> profiles: allow /usr/share/webext in chromium profile

etc/profile-a-l/firefox-developer-edition.profile
Firefox Developer Edition has a slightly different DBus path than stock Firefox. Without these filters, a firejailed browser instance cannot permit other programs to open tabs within it.
=> Add DBus filter rules specific to firefox-developer-edition

etc/profile-a-l/librewolf.profile
The librewolf upstream package has data in `/usr/share/librewolf`, which needed to be whitelisted.
Additionally it did not start with `apparmor` enabled (via `firefox-common.profile`), therefore I added the `ignore`.
=> profiles: fix librewolf

etc/inc/disable-interpreters.inc
rxvt needs Perl modules, thus does not work. And its blacklist is needed so that Firefox can run applications with `Terminal=true` in their .desktop file (depending on what is installed). The reason is that Firefox does this via glib, which currently uses a [hardcoded list of terminal emulators](https://gitlab.gnome.org/GNOME/glib/-/issues/338). And in this list, rxvt comes before xterm.
=> Blacklist rxvt after the blacklist of Perl.

etc/inc/allow-perl.inc
This is the counterpart of the blacklist of rxvt in commit ed5c259f,
as suggested in the discussion of pull request #4831.
=> Noblacklist rxvt in allow-perl.inc

src/firejail/main.c, src/firejail/util.c
virtualgl[1] runs `chown root:vglusers` on `/dev/nvidia*` and on devices
usually owned by the "render" group[2].  This makes them unavailable in
the sandbox if `noroot` (which causes groups to be dropped) is used.
Since firejail classifies all of the aforementioned devices as being
`DEV_3D` on fs_dev.c (which means that they are controlled by `no3d`),
treat the "vglusers" group the same as the "render" group (by always
keeping "vglusers" unless `no3d` is used).
See the discussion on #2042 (from this comment[3] onwards).
[1] https://virtualgl.org
[2] https://github.com/VirtualGL/virtualgl/blob/6f0b90be02d13171dfdfffb112485f4091a5904f/server/vglserver_config#L393
[3] https://github.com/netblue30/firejail/issues/2042#issuecomment-1007468715
Reported-by: @JCallicoat
=> Keep vglusers group unless no3d is used (virtualgl)

etc/profile-m-z/steam.profile
AMD Open Source Driver For Vulkan (amdvlk) installs ICD files to /etc/vulkan.
=> steam.profile: allow /etc/vulkan

etc/profile-m-z/ssh.profile
ssh can start in master mode, which will spawn an additional long
running process, which keeps connections to a server open, so that
it can be reused by later connection attempts.
But the lingering master process will prevent the jail from shutting
down, when `firejail ssh` tries to exit.
This breaks for example ansible when using a firejailed ssh, as it
calls ssh with ControlMaster flags.
deterministic-shutdown will kill the other process when the parent
exits.
---
does anyone see something negative with enabling this flag?
=> profiles: enable deterministic shutdown for ssh

etc/profile-m-z/signal-desktop.profile
Related to #4670.  Firefox now does inter-process communication using dbus.
=> signal-desktop: Allow Signal to open links in Firefox again

etc/inc/disable-programs.inc
These seem like reasonable places to blacklist in `default-programs.inc`.
=> Blacklist rclone, 1Password, Ledger Live and cointop

etc/inc/disable-programs.inc, etc/profile-a-l/lutris.profile, etc/profile-m-z/wine.profile
~/.cache/wine is a directory where wine stores .msi files for wine-gecko and wine-mono that it may download (with user's permission) and reuse every time a new prefix is created.
=> {lutris,wine}.profile: allow ~/.cache/wine

etc/inc/disable-common.inc, etc/inc/disable-programs.inc, etc/profile-m-z/nvim.profile
I have been sketchy about neovim extensions security, as there are couple extensions that required user to run bash script after pulling some code from git repository. 
My doubts are: 
1. `disable-xdg` is not a problem for me 
2. I am not sure to add it to `firecfg.config` as vim.profile wasn't there
3. There are many plugins manager with various installation path
please let me know if I miss something :)
=> Add neovim profile

RELNOTES
Note: They are added in the order that the issues were fixed/closed.
Note2: The issues were found through the following url:
https://github.com/netblue30/firejail/issues?q=is%3Aclosed+label%3Abug+-label%3Asecurity+closed%3A%3E2021-06-29+
The date used is the release date of 0.9.66, so in theory the query
should return every bug closed after that.  Security-related issues are
excluded because they will be added separately.
Note3: All issues other than #4328 were fixed before 0.9.68rc1.
Relates to #2758 #4235 #4328 #4387 #4395 #4460 #4467 #4558 #4560 #4586.
=> RELNOTES: add bugfixes

etc/inc/disable-programs.inc, etc/profile-m-z/steam.profile
MangoHud is a Vulkan and OpenGL overlay for monitoring FPS, temperatures, CPU/GPU load and more, and it can be configured by user in ~/.config/MangoHud/MangoHud.conf.
This probably could also go into profiles for lutris and wine... But also for every game as well. So maybe ~/.config/MangoHud can be allowed in general in one of the whitelist-*.inc files instead?
=> steam.profile: allow ~/.config/MangoHud

etc/inc/whitelist-usr-share-common.inc
This commit fixes #4893 by allowing access to the configuration directory for the Wayland EGL external platform library
=> Allow common access to EGL External platform configuration directory

etc/profile-m-z/shellcheck.profile
It breaks non-binary builds of shellcheck on Arch (e.g.: shellcheck-bin
vs shellcheck-git from the AUR).
Fixes #4875.
Reported-by: @redxef
=> shellcheck.profile: remove mdwe

etc/profile-a-l/librewolf.profile
Starting Librewolf 96.0, Librewolf switched from using d-bus `org.mozilla.librewolf.*` to `io.gitlab.librewolf.*` for communicating with open browser sessions.
=> Update librewolf.profile: use new d-bus message bus

etc/profile-m-z/mediainfo.profile
It's a CLI tool and its output is a key part of the functionality.
Fixes https://github.com/netblue30/firejail/issues/4900.
Reported-by: @rieje
=> mediainfo.profile: add quiet

RELNOTES
... otherwise the gitlab CI will complain.
---
Btw. does anyone have experience with Redhat/CentOS?
There is another job failing with this error:
```
$ dnf update -y
CentOS Linux 8 - AppStream                      276  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```
https://gitlab.com/Firejail/firejail_ci/-/jobs/2062852936
=> push changelog date, so that it's different from the previous one

etc/profile-a-l/keepassx.profile
I could not find anything to confirm that keepassx supports hardware
keys.  And as mentioned by @rusty-snake[1]:
> The yubikey support in kpxc seems to be based on
> https://github.com/kylemanna/keepassx /
> https://github.com/keepassx/keepassx/pull/52
> which was never merged. For me it looks like kpx never got official
> support for it.
>
> keepass seems to support hw keys (via plugin).
Also of note is the PR that added yubikey support to keepassxc:
https://github.com/keepassxreboot/keepassxc/pull/127
This partially reverts commit 09ac1a73e ("keepass*: remove nou2f",
2022-02-05) / PR #4903.  See also commit 91b04172b ("keepass*: fix typo
in private-dev note", 2022-02-06).
Closes #4883.
[1] https://github.com/netblue30/firejail/issues/4883#issuecomment-1031172309
=> keepassx: restore nou2f

etc/profile-a-l/iridium.profile
0319fbd enabled whitelisting in /usr/share for iridium but wusc
was still ignore causing iridium to crash.
Fixes  #4917
cc @frcl
=> Fix iridium.profile

etc/profile-m-z/man.profile
Having `read-only /tmp` yields the following:
$ man ls
[...]
man: /usr/share/man/man1/ls.1.gz: SYSERR: mkstemp: /tmp/man.XXXXxxxxxx: Read-only file system
[...]
It also causes the pager (e.g.: less(1)) to not be called, which means
that the entire man page is just printed all at once on the terminal.
Environment: mandoc 1.14.6-1 on Artix Linux.
Fixes #4927.
Reported-by: @hyder365
=> man.profile: remove read-only tmp to fix mandoc

etc/profile-m-z/onionshare-cli.profile, etc/profile-m-z/onionshare.profile, src/firecfg/firecfg.config
On Arch Linux the [onionshare](https://archlinux.org/packages/community/any/onionshare/) package from the community repo doesn't have the `onionshare-gui` executable. Instead it comes with `onionshare` and `onionshare-cli`. This PR adds redirect profiles for both of those commands and enables them in firecfg.
=> add onionshare redirects

etc/profile-m-z/wireshark.profile
This came up in https://github.com/netblue30/firejail/discussions/4949. I can reproduce that `private-dev` stops tshark/wireshark from showing interfaces.
=> drop private-dev from wireshark.profile

etc/firejail.config
According to #4053, there is currently no safe (in the sense of not
allowing to escape the sandbox) implementation of
`org.kde.StatusNotifierWatcher`, but it is required by multiple programs
for tray functionality.  Users may not be aware of this (for example,
see https://github.com/netblue30/firejail/issues/4508), so add a warning about it.
Note: allow-tray was added on commit c86cae2d0 ("Add new condition
ALLOW_TRAY", 2021-09-04) / PR #4510.
Cc: @davidebeatrici
=> firejail.config: add warning about allow-tray

etc/profile-m-z/wireshark.profile
On gentoo linux, /usr/bin/dumpcap requires dac_read_search instead of dac_override.
=> wireshark.profile: Add dac_read_search to caps.keep

etc/inc/disable-programs.inc, etc/profile-m-z/qbittorrent.profile
Since version 4.3.3 qBittorrent switched to new data directory location (`~/.local/share/qBittorrent` instead of `~/.local/share/data/qBittorrent`).
ChangeLog says that legacy 'data' directory is now used only as a fallback. Also, when using current profile the following warning appears on the terminal:
```
The legacy data directory '/home/avallac_h/.local/share/data/qBittorrent' is used. It is recommended to move its content to '/home/avallac_h/.local/share/qBittorrent'
```
The proposed pull request should fix this issue.
=> qbittorrent.profile: fix data directory location

etc/inc/whitelist-1793-workaround.inc, etc/inc/whitelist-common.inc, etc/inc/whitelist-usr-share-common.inc, etc/profile-a-l/bibletime.profile, etc/profile-m-z/zeal.profile
In Arch this applies at least to telegram-desktop, qmmp, qbittorrent and strawberry which are now built using Qt6 libraries. But I'm unsure about `whitelist-1793-workaround.inc` which is currently used by `neochat.profile` only.
Also I found a strange artifact in zeal.profile: https://github.com/netblue30/firejail/blob/070e78a8892d86687a1a3e74262628ee9c562c46/etc/profile-m-z/zeal.profile#L22
=> Add support for changing appearance of the Qt6 apps with qt6ct

etc/profile-m-z/mupdf.profile
All mupdf redirect profiles rely on mupdf.profile for including globals.local. Due to the include being commented in that file globals.local never makes it into the sandbox setup. Let's fix this.
This came up while trying to help in https://github.com/netblue30/firejail/discussions/4975.
=> fix globals.local in mupdf & redirects

etc/profile-m-z/opera-beta.profile, etc/profile-m-z/opera.profile
The URL for the 'Disable for now' comment seems out of place. After testing it looks like we can actually harden the profiles by dropping the disabled includes alltogether.
=> opera fixes/hardening

etc/profile-a-l/email-common.profile
Sylpheed needs access to /var/lib/dbus/machine-id, which usually is a symlink to /etc/machine-id. Fix for https://github.com/netblue30/firejail/issues/4995. Technically speaking we could add a private-etc to sylpheed.profile. I decided to add it in email-common.profile instead for ease-of-use/maintainability.
=> fix sylpheed

src/firejail/fs_whitelist.c, src/firejail/mountinfo.c
Some reorganization/cleanup of the whitelist code.  Also a new mechanism to detect earlier whitelist mounts.
There should be no functional changes.
=> whitelist restructuring

etc/profile-a-l/bnox.profile, etc/profile-a-l/dnox.profile, etc/profile-a-l/enox.profile, etc/profile-a-l/flashpeak-slimjet.profile, etc/profile-a-l/google-chrome-beta.profile, etc/profile-a-l/google-chrome-unstable.profile, etc/profile-a-l/google-chrome.profile, etc/profile-m-z/snox.profile, etc/profile-m-z/yandex-browser.profile
The `ignore whitelist /usr/share/chromium` can be dropped from profiles redirecting to chromium-common.profile, as that path is only whitelisted in chromium.profile.
=> drop redundant ignore in chromium-based browsers

etc/profile-a-l/atom.profile, etc/profile-a-l/code.profile, etc/profile-a-l/github-desktop.profile, etc/profile-m-z/skypeforlinux.profile
From discussion in #5012
skypeforlinux is whitelist profile, so adding more whitelisted paths will not break anything. Just cleaning up that profile.
notable.profile has 
```
ignore whitelist ${HOME}/.config/Electron
ignore whitelist ${HOME}/.config/electron-flag*.conf
```
already.
=> Electron app fixes

etc/profile-m-z/steam.profile
The directory is used by the Linux binary for Prey (2006), available at https://icculus.org/prey.
Not whitelisting the directory results in the game failing to launch:
```
found DLL in pak file: /home/user/.steam/steamapps/common/Prey 2006/base/game01.pk4/gamex86.so
copy gamex86.so to /home/user/.prey/base/gamex86.so
dlopen '/home/user/.prey/base/gamex86.so' failed: /home/user/.prey/base/gamex86.so: failed to map segment from shared object
```
=> steam.profile: allow "${HOME}/.prey"

src/include/gcov_wrapper.h
Currently, the check to enable gcov relies on a non-existent macro due
to a typo, which looks like it would cause the dummy/empty versions of
the gcov functions to always be declared (even with --enable-gcov),
instead of the real ones from gcov.h.  This commit fixes the typo
(HAS_GCOV -> HAVE_GCOV).  See configure.ac for the macro declaration.
This amends commit 5106b2ec4 ("gcov: use no-op functions if not
enabled", 2021-06-20) / PR #4376.
Occurrences of each macro with this commit applied:
$ git grep -F HAVE_GCOV | wc -l
16
$ git grep -F HAS_GCOV | wc -l
0
=> gcov: fix gcov functions always declared as dummy

etc/profile-m-z/steam.profile
Fixes latests Steam client (second commit) and Steam’s Proton versions starting from 5.13 (first commit). See https://github.com/netblue30/firejail/issues/5014#issue-1160458796 and https://github.com/netblue30/firejail/issues/4366#issuecomment-1053756405 for details.  
Afaict #4686 is just a duplicate of #4366 so it too should be fixed by the first commit.
=> Fix newest Steam client and Proton ≥ 5.13

src/man/firejail-profile.txt, src/man/firejail.txt
As mentioned by @rusty-snake[1].
This amends commit 39654d016 ("adding netlink to --protocol list
(#4605)", 2022-01-21).
See also commit 75073e0e4 ("man: mention that private-bin and
private-etc are cumulative", 2022-01-22) and issue #4078.
[1] https://github.com/netblue30/firejail/pull/5042/files#r825477891
=> man: mention that the protocol command accumulates

src/man/firejail-profile.txt, src/man/firejail.txt
And the workaround suggested by @smitsohu[1] and @rusty-snake[2].
Relates to #903 #5048.
[1] https://github.com/netblue30/firejail/issues/903#issuecomment-946673346
[2] https://github.com/netblue30/firejail/discussions/5048#discussioncomment-2360034
=> docs: mention inconsistent homedir bug involving --private=dir

etc/profile-m-z/ping-hardened.inc.profile, etc/profile-m-z/ping.profile
This started out as a simple typo fix. By sheer coincidence I noticed there were some comments in the profile that seemed odd to me and I started experimenting. Turns out quite a lot of hardening could be done. I've been running for a while with all of these added options without hiccups.
Makes me wonder if there are any distro differences out there that could explain the former comments. I've left them untouched, because I don't know where they stem from.
=> ping: (extra) hardening  

etc/profile-m-z/megaglest.profile
It would not start otherwise. It reports:
```
megaglest: error while loading shared libraries: liblua5.1.so.5.1: cannot open shared object file: Permission denied
```
This also fixes a tiny bit of whitespace in the same file. `megaglest_editor` does not appear to be affected so I did not have to modify it. There is also a new binary, `megaglest_g3dviewer`, which does not have a profile yet.
=> megaglest.profile: Add allow-lua.inc

etc/inc/disable-common.inc, etc/inc/disable-programs.inc
This directory is monitored by both appimaged[1] and
AppImageLauncher[2].  Also, when opening an AppImage with
AppImageLauncher, it may prompt the user to move the AppImage to
~/Applications.
Note that even when blacklisting a directory, it is possible to execute
an AppImage from it.  For example, the following works:
firejail --noprofile --blacklist='${HOME}/Applications' --appimage \
~/Applications/foo.AppImage
While the resulting process does not appear to have access to the
blacklisted directory.
[1] https://github.com/AppImage/appimaged/blob/2323f1825ed6abe19f2d3791d81307449692be03/README.md#monitored-directories
[2] https://github.com/TheAssassin/AppImageLauncher/wiki/Configuration
=> appimage: blacklist and make ~/Applications dir read-only 

etc/inc/disable-common.inc
It looks like it allows arbitrary command execution.  From
pkcs11.conf(5):
>     remote:
>         Instead of loading the PKCS#11 module locally, run the module
>         remotely.
>
>         Specify a command to run, prefixed with | a pipe. The command
>         must speak the p11-kit remoting protocol on its standard in
>         and standard out. For example:
>
>             remote: |ssh user@remote p11-kit remote /path/to/module.so
>
>         Other forms of remoting will appear in later p11-kit releases.
Environment: p11-kit 0.24.1-1 on Artix Linux.
Currently this entry only exists on whitelist-common.inc, added on
commit f74cfd07c ("add p11-kit support - #1646").
With this commit applied, all read-only entries on whitelist-commons.inc
are also part of disable-common.inc.
See also …
=> disable-common.inc: make ~/.config/pkcs11 read-only

src/man/firejail-profile.txt, src/man/firejail.txt
As hinted by @rusty-snake[1].
[1] https://github.com/netblue30/firejail/discussions/5064#discussioncomment-2417395
=> docs: mention capabilities(7) on --caps

etc/profile-m-z/teams.profile
First time I looked at teams.profile in reference to #5086. The double `ignore novideo` is reduced to a single occurence now.
=> teams: drop doubled option

etc/profile-m-z/vlc.profile
`apparmor` doesn't disable D-Bus anymore, so add it back to the profile. Remove `memory-deny-write-execute` comment, as this also breaks JIT compiled QtQuick nowadays.
=> harden vlc

etc/apparmor/firejail-default
Without this change here is what I see in syslog when running for example `firejail --profile=ssh /usr/bin/ssh test.local`:
```
Apr  2 14:59:29 kek kernel: [  177.596180] audit: type=1400 audit(1648900769.222:29): apparmor="DENIED" operation="connect" profile="firejail-default" name="/run/avahi-daemon/socket" pid=2562 comm="ssh" requested_mask="w" denied_mask="w" fsuid=1000 ouid=0
```
So it can't access the socket hence can't resolve the name.
=> Allow resolution of .local names with avahi-daemon in the apparmor profile.

src/firejail/util.c
When nogroups is used, the following warning may be issued (potentially
multiple times, as drop_privs may be called more than once):
Warning: cleaning all supplementary groups
But the warning is being shown even when it seems that all supplementary
groups can be safely dropped (and are thus dropped), which is likely a
common scenario.  This commit prevents the warning from being printed in
that case, making it so that it is only shown in the non-happy paths (as
was the case on firejail 0.9.66).
Misc: The added code was copied from drop_privs.
This amends commit 7abce0b4c ("Fix keeping certain groups with
nogroups", 2021-11-30) / PR #4732.
Kind of relates to #4930.
=> Stop warning on safe supplementary group clean

etc/inc/disable-programs.inc, etc/profile-a-l/atom.profile, etc/profile-a-l/code.profile, etc/profile-a-l/electron.profile, etc/profile-a-l/github-desktop.profile, etc/profile-m-z/notable.profile
Different versions of electron load flags from different files.
=> Whitelist electron-flags.conf for all versions of electron

src/fnettrace/hostnames.c
Partial error log when building firejail-git (afee8603f) with
--enable-fatal-warnings:
hostnames.c: In function ‘retrieve_hostname’:
hostnames.c:53:17: error: ‘fclose’ called on pointer returned from a mismatched allocation function [-Werror=mismatched-dealloc]
53 |                 fclose(fp);
|                 ^~~~~~~~~~
hostnames.c:38:20: note: returned from ‘popen’
38 |         FILE *fp = popen(cmd, "r");
|                    ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:7: hostnames.o] Error 1
Environment: gcc 11.2.0-4 on Artix Linux.
Added on commit 500a56efd ("more on nettrace", 2022-01-07).
=> hostnames.c: fix mismatched dealloc (fclose -> pclose)

etc/inc/whitelist-run-common.inc
Fixes downstream issue on NixOS https://github.com/NixOS/nixpkgs/issues/55191
Firefox or similar browsers are unable to render WebGL unless directory `/run/opengl-driver` is whitelisted.
=> NixOS fix OpenGL app support

etc/inc/whitelist-common.inc
This PR fixes an issue on NixOS where you cannot use firejail like this:
```
firejail chromium
```
it fails with `Error: no suitable chromium executable found`.
This is because `chromium` is usually a symlink in `~/.nix-profile` to the binary in the NixOS store. After whitelisting `~/.nix-profile` running 
```
firejail chromium
```
works :)
Solves downstream issue https://github.com/NixOS/nixpkgs/issues/170784
=> Whitelist for NixOS to resolve binary paths in user environment

src/fzenity/main.c
As caught by the Clang Static Analyzer:
$ make clean && NO_EXTRA_CFLAGS="yes" scan-build --status-bugs make -C src/fzenity
[...]
main.c:77:10: warning: Value stored to 'ptr' is never read [deadcode.DeadStores]
return ptr++;
^~~~~
1 warning generated.
[...]
scan-build: Analysis run complete.
scan-build: 1 bug found.
The above increment is a no-op, as it is equivalent to
`return ptr; ptr++;`.
For it to make any difference, the prefix increment operator would have
to be used in place of the postfix one:
return ++ptr;
Which would be equivalent to `++ptr; return ptr;`.
But in order to fix the warning (and CI) while avoiding to change the
current behavior, just remove the operator instead.
Added on commit 1cdfa6f95 ("more on firecfg --guide: fzenity",
2022-04-25).
=> fzenity: fix dead store

etc/profile-a-l/google-chrome-beta.profile, etc/profile-a-l/google-chrome-unstable.profile, etc/profile-a-l/google-chrome.profile
Without whitelist-usr-share-common, /usr/share becomes empty.
Adding whitelist-runuser-common didn't break google chrome.
Whitelisting /usr/share/mozilla/extensions and /usr/share/webext shouldn't break google chrome, either.
I tested google-chrome.profile only, but I think later versions should not be different.
It fixes https://github.com/netblue30/firejail/issues/5125
=> Prevent empty /usr/share in google-chrome profiles

src/firejail/checkcfg.c, src/firejail/firejail.h, src/firejail/main.c
Currently, when running on CI, `firejail --version` only prints the
following line:
firejail version 0.9.69
Add a new print_version() function that always prints both the above and
the compile-time options (like it is done outside of CI) and call it in
both of the places that handle --version on main.c.
Misc: The printing of compile-time features was added on commit
48dd1fbec ("apparmor", 2016-08-02).
=> ci: fix --version not printing compile-time features

.github/workflows/build-extra.yml, .github/workflows/build.yml, .gitlab-ci.yml
The "build_apparmor" job was added on commit 342e71cd8 ("Add
deb-apparmor build to Gitlab CI", 2019-01-26).  It would call
`./mkdeb-apparmor.sh`, which would run `./configure --enable-apparmor`
directly, adding `-lapparmor` to `EXTRA_LDFLAGS` and thus passing it to
the linker.
Later, commit 87e7b3139 ("Configure Debian package with AA and SELinux
options", 2020-05-13) / PR #3414 merged mkdeb.sh and mkdeb-apparmor.sh
into mkdeb.sh.in, which does not always pass `--enable-apparmor` to
./configure directly.  Instead, it adds `--enable-apparmor` depending on
whether the `$HAVE_APPARMOR` environment variable is set, which would be
done by a previous run of ./configure with `--enable-apparmor`.  Since
on "build_apparmor" ./configure is not run the first time with
`--enable-apparmor`, neither is …
=> ci: print version after install & fix apparmor support on build_apparmor

Makefile.in
distclean erases user-made modifications to the files generated by the
configure script; it is not obvious that a non-"clean" target would ever
run it.
That is, instead of:
./configure --enable-foo && make distclean && make dist
It would probably be safer (and more maintainable) to do:
make distclean && ./configure --enable-foo && make dist
So drop the distclean call and the file-moving hacks around it.
Added on commit 137985136 ("Baseline firejail 0.9.28", 2015-08-08).
Relates to commit 684919100 ("bug: preserve config.status during make
dist", 2016-09-19) and commit 31dc1218a ("fixups", 2020-07-19).
=> Makefile.in: stop running distclean on dist

etc/inc/disable-common.inc, etc/inc/disable-programs.inc, etc/profile-m-z/nvim.profile
Default paths as of neovim 0.7.0:
* backupdir:  $XDG_DATA_HOME/nvim/backup//
* directory:  $XDG_DATA_HOME/nvim/swap//
* undodir:    $XDG_DATA_HOME/nvim/undo//
* viewdir:    $XDG_DATA_HOME/nvim/view//
* shada file: $XDG_DATA_HOME/nvim/shada/main.shada
* log dir:    $XDG_CACHE_HOME/nvim/log
Default paths as of [1]:
* backupdir:  $XDG_STATE_HOME/nvim/backup//
* directory:  $XDG_STATE_HOME/nvim/swap//
* undodir:    $XDG_STATE_HOME/nvim/undo//
* viewdir:    $XDG_STATE_HOME/nvim/view//
* shada file: $XDG_STATE_HOME/nvim/shada/main.shada
* log dir:    $XDG_STATE_HOME/nvim/log
[1] https://github.com/neovim/neovim/pull/15583
=> nvim: add XDG_STATE_HOME path

etc/profile-a-l/kate.profile
Reduce restrictions, so that Kate can be used as intended by the developers:
- allow usage of Git
- permit Bash completion in built-in Konsole
- permit the requested access to kwinrc configuration
=> Kate fixes

etc/ids.config, etc/inc/disable-shell.inc
Since /etc/profile is present, add the other shell-related paths in /etc
that are listed on ids.config.
Suggestion by @rusty-snake[1].
Relates to #5167 #5170.
[1] https://github.com/netblue30/firejail/pull/5167#pullrequestreview-989621852
=> disable-shell.inc: add global shell paths from ids.config

README, mkdeb.sh.in
Since `make deb-apparmor` already exists, use that for now instead of
changing what `make deb` does.
This fixes CI.
Added on commit 494b26d50 ("adding --enable-apparmor by default for make
deb - most Debian-based distros have apparmor enabled by default",
2022-06-03).
Kind of relates to #5154.
=> mkdeb.sh.in: stop enabling apparmor

RELNOTES
RELNOTES: add missing new profiles
Profiles: opera-developer, node-gyp, npx, semver, ping-hardened.
Commands used to find the profiles:
$ git log --pretty= --graph --name-only \
--diff-filter=AC 0.9.68..HEAD -- etc
$ tig --diff-filter=AC 0.9.68..HEAD -- etc
Relates to #5001 #5058 #5061.
---
RELNOTES: add removed nvm profile
Commands used to find the profile:
$ git log --pretty= --graph --name-only \
--diff-filter=DBX 0.9.68..HEAD -- etc
$ tig --diff-filter=DXB 0.9.68..HEAD -- etc
Relates to #5058.
=> RELNOTES: add new and removed profiles

etc/profile-m-z/transmission-common.profile, etc/profile-m-z/transmission-qt.profile, etc/profile-m-z/transmission-remote-gtk.profile
Too many issues with private-lib in Transmission. See #5211 for discussion and rationale for removing private-lib from relevant profiles as suggested by @reinerh.
=> Transmission fixes: drop private-lib

test/fs/fs.sh
Before running test/fs/private-lib.exp.
Inspired by the configuration changes that are done on
test/root/checkcfg.exp.
Reason: Since commit 9741d0b60 ("fix disabled private-lib in
/etc/firejail/firejail.config", 2022-06-23), the "build_and_test" job
fails with the following error[1]:
TESTING: private-lib (test/fs/private-lib.exp)
spawn /bin/bash
firejail --private-lib --private-bin=sh,bash,dash,ps,grep,ls,find,echo,stty
runner@fv-az489-993:~/work/firejail/firejail/test/fs$
<private-bin=sh,bash,dash,ps,grep,ls,find,echo,stty
Error: private-lib feature is disabled in Firejail configuration file
runner@fv-az489-993:~/work/firejail/firejail/test/fs$ TESTING ERROR 1
This fixes CI.
Fixes #5214.
Relates to #5190.
[1] https://github.com/netblue30/firejail/runs/7030862406
=> test/fs: enable private-lib in firejail.config

etc/inc/disable-programs.inc, etc/profile-m-z/steam.profile
As [discussed](https://github.com/netblue30/firejail/pull/5187#issuecomment-1164782747) for #5187, this allows the Paradox Launcher to properly work within Steam games.
=> add Paradox Launcher to Steam profile

etc/profile-a-l/aria2c.profile
Otherwise winetricks fails to download packages.
=> aria2c.profile: allow access to ~/.cache/winetricks

src/firejail/fs.c
Instead of simply erroring out, just warn the user that a filesystem was
unable to be remounted due to EIO. This is helpful for FUSE filesystems
which might be buggy or having issues.
Directly addresses #5240.
=> Warn when encountering EIO during remount

RELNOTES
The following leverages the fact that when using a normal merge (as
opposed to "rebase and merge" or "squash and merge") on GitHub, the pull
request number is put in the commit message title and the title of the
PR is added to the commit message body.
Commands used to find and print the items for the RELNOTES:
$ git log --grep='^build:' --merges --reverse --pretty='%s %b' 0.9.70.. |
sed -E -n 's/Merge pull request (#[0-9]+) from [^ ]+ (.*)/  * \2 (\1)/p'
* build: deduplicate configure-time vars into new config files (#5140)
* build: fix file mode of shell scripts (644 -> 755) (#5206)
* build: reduce autoconf input files from 32 to 2 (#5219)
Commands used to generate the message below:
$ git log --grep='^build:' --merges --reverse --pretty='%s %b' 0.9.70.. |
sed -E -n 's/Merge pull request …
=> RELNOTES: add build items (plus commands)

etc/profile-m-z/remmina.profile
Remmina failed to work after some update with this:
```
Reading profile /etc/firejail/remmina.profile
Reading profile /etc/firejail/allow-ssh.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 373392, child pid 373393
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 243.40 ms
remmina-Message: 20:38:05.572: Remmina does not log all output …
```
=> remmina.profile: allow python3

etc/profile-m-z/viewnior.profile
Wanted to crop an image in viewnior, noticed it did not work, checked stdout and sure enough it was missing a whitelisted path.
=> viewnior.profile: allow accessing /usr/share/viewnior

.gitignore
Ignore it only on the repository root path, as a directory that matches
`firejail-*` could eventually be added.
Note that the dist archive is already ignored since commit da6b131c3
("chore(.gitignore) ignore built packages", 2018-01-15) / PR #1733.
Example paths:
* build dir: firejail-0.9.71/
* archive:   firejail-0.9.71.tar.xz
See `$(NAME)-$(VERSION)` and `$(NAME)-$(VERSION).tar.xz` in the "dist"
target on the root Makefile.
=> build: add dist build directory to .gitignore

.github/workflows/build-extra.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml
Add the following paths to the ignore lists:
- .git-blame-ignore-revs
- .gitignore
- COPYING
To avoid running CI unnecessarily.
Commands used to show only the root files:
$ git ls-files | grep -v /
Misc: I noticed the missing paths on #5248.
=> ci: ignore git-related paths and the project license

config.mk.in, config.sh.in
To note on the output files that they are generated and to clarify how
they are generated.
From the manual of GNU Autoconf (version 2.69):
>  -- Variable: configure_input
>      A comment saying that the file was generated automatically by
>      'configure' and giving the name of the input file.  'AC_OUTPUT'
>      adds a comment line containing this variable to the top of every
>      makefile it creates.  For other files, you should reference this
>      variable in a comment at the top of each input file.  For
>      example, an input shell script should begin like this:
>
>           #!/bin/sh
>           # @configure_input@
>
>      The presence of that line also reminds people editing the file
>      that it needs to be processed by 'configure' in order to be used.
Resulting output …
=> build: add autoconf auto-generation comment to input files

src/firejail/join.c, src/firejail/main.c, src/firejail/sandbox.c
=> improve force-nonewprivs security guarantees

etc/profile-m-z/makepkg.profile
=> makepkg: add description

etc/profile-a-l/audacity.profile
removed `private-bin` line from audacity profile as it appears to block
access to shared libraries needed to start audacity on some
distributions.
Relates to github issue #5281
=> fix(audacity): !5281 sharedlib bug on Arch/Fedora

Makefile
There were a couple of files leftover after `make uninstall`. This
patch fixes that.
=> build: Add files `make uninstall` forgot to remove

etc/profile-m-z/vmware.profile
This patch avoid the following error:
Error: One of the parameters supplied is invalid
Tested with VMware Workstation 16.2.4
=> vmware.profile: snapshot requires /etc/mtab

src/man/firejail.txt
On the introduction of firejail(1), mention the main risk of SUID
binaries and that by default, only trusted users should be allowed to
run firejail (and how to accomplish that).
Note: The added comment line is completely discarded (so there is no
extraneous blank line); see groff_man(7) for details.
Suggested by @emerajid on #5288.
Relates to #4601.
=> docs: mention risk of SUID binaries and also firejail-users(5)

src/man/firecfg.txt, src/man/firejail-login.txt, src/man/firejail-profile.txt, src/man/firejail-users.txt, src/man/firejail.txt
Since the man pages in src/man use a ".txt" file extension (rather than
".1" or ".5"), their filetype is detected by (neo)vim as "text".
So at the bottom of every man page, add a vim modeline in a comment and
set the filetype to "groff", to enable syntax highlighting.
Note: All of the generated ".man", ".1" and ".5" files are currently
being detected as "nroff".
Note2: Set the filetype to "groff" rather than "nroff" because at least
.UR and .UE are groff extensions.  These macros look the same with
either filetype, but there may be more extensions being used and the
nroff.vim syntax file (which is included by groff.vim) does things
differently based on which filetype is used.
Based on the following example from (neo)vim's filetype.txt:
or add this modeline to the file:
/* vim: set …
=> docs: set vim filetype on man pages for syntax highlighting

etc/inc/disable-programs.inc, etc/profile-m-z/microsoft-edge-beta.profile, etc/profile-m-z/microsoft-edge-dev.profile, etc/profile-m-z/microsoft-edge.profile
I did rewrite microsoft-edge.profile from dev/beta for stable channel that is using only this name as executable binary unlike the other two.
About what we were discussing in #5307, I did replace private-opt by whitelist for stable, beta and dev profiles.
Tell me if this is not the way you would like it to be and I will follow your recommendations..
=> microsoft-edge.profile rewritten for stable channel and moved microsoft-edge{,-beta,-dev} from private-opt to whitelist

etc/profile-m-z/makedeb.profile
makedeb is a makepkg fork for debian.
I didn't add it in firecfg because makepkg isn't there either.
=> makedeb profile creation

etc/apparmor/firejail-default
Hello everyone!
Recently, a [pull request](https://github.com/netblue30/firejail/pull/5274) was merged that added support for custom AppArmor profiles. However, there was a use-case I haven't tested -- a case where an application confined by a default profile uses ptrace or sends signals. In the original profile, it was allowed only for apps with the same security label. However, I've missed that, while **firejail-default//&unconfined** and **firejail-default** have equal AppArmor permissions, ptrace reading and sending signals were previously allowed for peers only with the latter security label. I've fixed it in this PR by allowing both.
Fixes #5316
=> Fix an AppArmor profile denial issue with ptrace reading and signals

etc/profile-m-z/steam.profile
As reported by @rsramkis on #5185, upgrading from Proton-7.2-GE-2[1]
(released on 2022-02-14) to GE-Proton7-18[2] (released on 2022-05-19)
breaks logging in on World of Tanks Blitz unless the `process_vm_ready`
32-bit syscall is allowed[3], so allow it.
Fixes #5185.
[1] https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/7.2-GE-2
[2] https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton7-18
[3] https://github.com/netblue30/firejail/issues/5185#issuecomment-1152350336
=> steam.profile: fix breakage with newer Proton-GE (process_vm_readv)

src/man/firejail.txt
Make it more explicit that they do and add an example for each command.
Relates to #5338.
Cc: @birdie-github @rusty-snake (from #5338)
=> docs: note that blacklist/whitelist follow symlinks

etc/inc/allow-ssh.inc
Currently ssh client cant see anything under `/etc/ssh/ssh_config.d`. It is evidently a bug.
=> Make /etc/ssh/ssh_config.d visible for ssh

Makefile
This PR ensures ids.config only gets installed when --enable-ids is set during configure. Fixes #5356.
=> build: only install ids.config when --enable-ids is set

etc/profile-a-l/chafa.profile, src/firecfg/firecfg.config
chafa is a terminal image viewer.
As far as I know, there is no configuration file for chafa.
=> Add profile for chafa

etc/inc/disable-programs.inc, etc/profile-a-l/firefox.profile
code change: `whitelist ${RUNUSER}/psd/*firefox*`
fixes: #4568
=> Fix Firefox 'Profile not found' for psd (v6.45)

README.md, RELNOTES
```console
* README.md: remove items duplicated from RELNOTES
* RELNOTES: reword modif items for clarity
* RELNOTES: sort items by category then date added
* RELNOTES: add docs
```
=> RELNOTES: dedup/reword/sort/add

.git-blame-ignore-revs
Put the committer date ("%cd") and commit message subject ("%s") as a
comment right after the commit hash ("%H").  The pipe ("|") is intended
to improve readability.
This format looks more similar to the output of `git log --oneline` and
should make it easier to visually parse long lists.  It also allows more
hashes to fit into the same amount of lines (at the cost of longer
lines).
Use committer date ("%cd") instead of author date ("%ad") as the former
tells when a commit actually landed on master.  This usually matches the
topological order, which should make it easier to verify that all of the
relevant commits are listed (and that there are no extraneous commits).
Use --date + "%cd" instead of just "%ci" because the former can be used
to ensure that the date is always printed in the …
=> .git-blame-ignore-revs: change format and add Landlock v1

etc/profile-a-l/arduino.profile
As mentioned in its description, this profile is intended for an IDE, so
allow paths used for development and stop including the following
profiles:
* disable-devel.inc
* disable-exec.inc
* disable-interpreters.inc
Fixes #5292.
=> arduino.profile: allow devel paths

etc/profile-a-l/darktable.profile, etc/profile-a-l/digikam.profile, etc/profile-a-l/geeqie.profile, etc/profile-a-l/hugin.profile
Programs that seem to support exiftool:
$ LC_ALL=C pacman -Sii perl-image-exiftool |
grep -e '^Version' -e '^Required' -e '^Optional For' | head -n 3
Version         : 12.42-1
Required By     : digikam  geotag  gitlab-workhorse  mat2  rapid-photo-downloader
Optional For    : darktable  geeqie  gpsprune  hugin  jpeg-archive  ranger  recoll  shutter
Environment: Artix Linux.
Note for hugin.profile: Does not currently work with private-bin on
Arch/Artix; see the private-bin comment on
etc/profile-a-l/exiftool.profile.
Relates to #5365.
=> profiles: allow perl/exiftool on the relevant profiles

etc/profile-m-z/mpv.profile
This is an mpv plugin for MPRIS integration.
See: https://github.com/hoyon/mpv-mpris
=> mpv: whitelist mpv-mpris

.github/ISSUE_TEMPLATE/bug_report.md
We had some comments saying that the output exceeds the allowed length of a github comment (65534 characters IIRC).
This commit adds a comment to instruct users to create a secret gist in that case.
=> docs: Add gist note to bug_report.md

etc/profile-m-z/mpv.profile
This reverts commit 393c5beff2686d7732221dadb6730917f24835a0.
Which broke mpv:
$ mpv --version
Cannot start application: No such file or directory
Probably because mpv itself uses many libraries and it has plugins that
may depend on files in /usr/lib as well:
$ pacman -Qlq mpv | grep /lib/ | grep -v '/$'
/usr/lib/libmpv.so
/usr/lib/libmpv.so.1
/usr/lib/libmpv.so.1.109.0
/usr/lib/pkgconfig/mpv.pc
$ strings /usr/bin/mpv | grep '^lib.*\.so' | sort -u | wc -l
53
$ pacman -Qlq yt-dlp | grep /lib/ | grep -v '/$' |
cut -f -4 -d / | sort -u
/usr/lib/python3.10
$ pacman -Q mpv yt-dlp
mpv 1:0.34.1-5
yt-dlp 2022.09.01-1
Environment: Artix Linux.
Also, private-lib is disabled by default in firejail.config (see #5190)
and mpv.profile does not use private-lib, so there should be no need to
whitelist …
=> Revert "mpv: whitelist mpv-mpris (#5386)"

src/man/firejail.txt
`--appimage` option is mentioned twice in the man page: first with a short description, next with usage examples. The short description is:
```
firejail [OPTIONS] --appimage [appimage-file and arguments]
```
While the examples are of form `firejail --appimage <some extra options> someapp.appimage`.
Even though the option parser recognizes such order, it is better to keep it the same way in both places in the man page.
=> docs: Make appimage examples consistent with --appimage option short description

src/fnettrace/main.c, src/libtrace/libtrace.c, src/libtracelog/libtracelog.c
Fixes two warnings when building firejail with musl libc.
Should fix #5421.
=> Fix musl warnings

src/man/firejail-profile.txt, src/man/firejail.txt
And fix the argument order in the examples to reflect that.
Background: The order in which these options appeared in the
documentation was inconsistent.  src/man/firejail.txt used --appimage
before --profile and src/man/firejail-profile.txt used --profile before
--appimage.  Then commit 44fefcac0 ("Make appimage examples consistent
with --appimage option short description", 2022-10-05) / PR #5402 was
made, which standardized on --profile before --appimage in both places.
But as mentioned by @rusty-snake[1], --appimage has be specified before
--profile in order for any `?HAS_APPIMAGE` conditionals inside of the
profile to evaluate to true.
So change the documentation to use and recommend the latter form.
Also, add --quiet to one example to make it clear that --appimage does
not have to be …
=> docs: clarify that --appimage should appear before --profile

.github/workflows/build-extra.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/profile-checks.yml
Commits:
```console
* ci: sort items on paths-ignore lists
* ci: ignore github markdown templates in all workflows
* ci: ignore dependabot and gitlab-ci in all workflows
* ci: ignore codeql workflow file in other workflows
* ci: ignore firecfg.config in the codeql workflow
* ci: ignore man/vim paths in build-extra/codeql workflows
```
Sort the paths and then ignore unnecessary files (mainly ignore workflow files
in other workflows).
Relates to #5249.
Kind of relates to #5289 #5296.
=> ci: sort and ignore more paths

etc/profile-a-l/ktorrent.profile
firejail fails to create the following files:
* ~/.kde/share/config/ktorrentrc
* ~/.kde4/share/config/ktorrentrc
Because it does not create the preceding directories beforehand:
* ~/.kde/share/config
* ~/.kde4/share/config
Relates to #5414.
=> ktorrent.profile: fix mkfile without mkdir & comment legacy paths

etc/profile-a-l/firefox-common.profile
We already added profile-sync-daemon (psd) support in firefox.profile with:
noblacklist ${RUNUSER}/psd/*firefox*
whitelist ${RUNUSER}/psd/*firefox*
This PR fixes DRM usage when using psd by ignoring noexec ${RUNUSER}.
=> firefox-common.profile: Add DRM support when using psd

configure, configure.ac
Commits:
```console
* configure*: fix typo of "been"
* configure*: fix trailing comma in HAVE_CONTRIB_INSTALL
* configure*: fix indentation
* configure*: remove extraneous blank lines
* configure*: remove extraneous blank lines (warning)
* configure*: wrap long shell command output lines
* configure*: wrap long AS_HELP_STRING line (sanitizer)
* configure*: fix quotes/parens alignment (sanitizer)
* configure*: quote and line-wrap AC_CHECK_HEADER line
```
Relates to #4712.
=> build: fix formatting and misc in configure

.github/workflows/build-extra.yml, .github/workflows/codeql-analysis.yml, CONTRIBUTING.md, Makefile, contrib/gtksourceview-5/language-specs/firejail-profile.lang
Tested with org.gnome.TextEditor.
The gtksourceview language-spec hasn't changed between gtksourceview 3, 4 and 5 AFAIK so it should also work on older systems if you copy/link the file in the right places.
=> Add basic gtksourceview language-spec

etc/profile-a-l/kcalc.profile
kcalc.profile: fix mkfile without mkdir
firejail may fail to create the following files:
* ~/.kde/share/config/kcalcrc
* ~/.kde4/share/config/kcalcrc
Because it does not create the preceding directories beforehand:
* ~/.kde/share/config
* ~/.kde4/share/config
---
kcalc.profile: stop creating legacy KDE paths
Leave them commented.
With this commit, there are no more profiles creating paths in ~/.kde
nor in ~/.kde4:
$ git grep -e '^mkdir .*\.kde' -e '^mkfile .*\.kde' -- etc
$
Relates to #5415.
=> kcalc.profile: fix mkfile without mkdir & comment legacy paths

etc/profile-a-l/cantata.profile, etc/profile-a-l/librecad.profile, etc/profile-m-z/ping.profile, etc/profile-m-z/rpcs3.profile
CI does checks on `private-etc` to always have 'alternatives' for Debian and derivatives. This PR ensures it's there, even in comments.
=> private-etc: always reference 'alternatives'

etc/inc/whitelist-usr-share-common.inc, etc/profile-m-z/qbittorrent.profile
For now it looks as if only [qbittorrent](https://archlinux.org/packages/community/x86_64/qbittorrent/) uses Qt6 (on Arch Linux). I've checked and cantata, otter-browser and qutebrowser still use Qt5 so those profiles are fine as they are.
=> Add support for Qt6

etc/inc/disable-programs.inc, etc/profile-a-l/avidemux.profile, etc/profile-a-l/avidemux3_cli.profile, etc/profile-a-l/avidemux3_jobs_qt5.profile, etc/profile-a-l/avidemux3_qt5.profile, src/firecfg/firecfg.config
A profile already exists for Avidemux, but when running the GUI avidemux3_qt5, the GUI job processor avidemux3_jobs_qt5 or the command line interface avidemux3_cli, only the default profile is used (on openSUSE Tumbleweed with avidemux3 installed from the Packman repository). Add profiles for each of the tools.
The Avidemux builds from Packman are also patched to store settings in directory ~/.avidemux3 instead of ~/.avidemux6.
=> Avidemux tools support

Makefile
This reverts commit 82299440533f54bd45bd5ec69136233c04028c15.
The idea is to later enable building the .deb package with AppArmor by
default with `make deb` and to then remove `make deb-apparmor` (though
note that some ci changes might also be needed in tandem[1]).  This
could potentially allow building a .deb package for all firejail
versions (including past and future ones) with just `make deb`.
Also, note that other options can be added/removed to the default `deb`
target (besides AppArmor-related ones), so ideally there would be only a
single `deb` target with all the desired options applied.
So instead of releasing a version without `make deb` and then
potentially adding it back and removing `make deb-apparmor`, just leave
the targets as is (considering the current release, 0.9.70) …
=> Revert "remove make deb and use make deb-apparmor to build packages"

etc/profile-m-z/spectre-meltdown-checker.profile
(Offtopic)
There's a typo in the latest release of the script that causes a leftover file (/devnull) being present in the filesystem. I've [opened a PR](https://github.com/speed47/spectre-meltdown-checker/pull/442) upstream to fix that. Out-of-scope for Firejail, although in theory we could use `private` to prevent it. But with a script that creates such a long and detailed output I opted not to do that.
=> spectre-meltdown-checker: fixes

etc/profile-a-l/awesome.profile, etc/profile-a-l/blackbox.profile, etc/profile-a-l/fluxbox.profile, etc/profile-a-l/i3.profile, etc/profile-m-z/openbox.profile
Assuming that users expect a working browser on their desktops.
Fix browsers and electron apps running inside a window manager sandbox, most of the time.
=> window manager profiles: fix browser/electron internal sandboxes

etc/templates/profile.template
Updates the link to the "Restrict DBus" wiki page in the profile template, it currently links to https://github.com/netblue30/firejail/wiki/Restrict-D-Bus, but it seems like the title got changed to https://github.com/netblue30/firejail/wiki/Restrict-DBus.
=> Update DBus wiki link

etc/inc/disable-programs.inc
[google-drive-ocamlfuse](https://github.com/astrada/google-drive-ocamlfuse) is a _FUSE filesystem over Google Drive_. Its config stores sensitive access tokens, much like rclone's config. The latter is blacklisted in firejail by default, so let it be the same for the former.
According to the [docs](https://github.com/astrada/google-drive-ocamlfuse/blob/beta/doc/Configuration.md) there are two default pathes for the config: either `~/.gdfuse` or `~/.config/gdfuse`
=> Blacklist  google-drive-ocamlfuse config

etc/profile-a-l/firefox-common.profile, src/firejail/firejail.h, src/firejail/main.c, src/firejail/profile.c, src/firejail/sandbox.c
A temporary workaround to #5462
=> A temporary fix to the bug caused by apparmor profiles stacking.

etc/profile-a-l/balsa.profile, etc/profile-a-l/claws-mail.profile, etc/profile-a-l/email-common.profile, etc/profile-m-z/sylpheed.profile
Started work for https://github.com/netblue30/firejail/pull/5305. For now only balsa.profile is fully refactored for email-common.profile. claws-mail and sylpheed already were so those needed just some reshuffling.
=> email-common refactoring

etc/profile-a-l/email-common.profile
claws-mail vcalendar-plugin uses libical to get current timezone. Libical needs access to file `/etc/timezone` to work properly.
See (already closed but not yet completely solved) bug report: https://github.com/netblue30/firejail/issues/5448
=> add timezone access to make libical functional

src/firejail/sandbox.c
Currently, if double-dash ("--") is passed to firejail, it is forwarded
to the user shell:
$ firejail --debug --noprofile -- echo test 2>&1 |
grep -e execvp -e test
Building quoted command line: 'echo' 'test'
Building quoted command line: 'echo' 'test'
Running 'echo' 'test'  command through /bin/bash
execvp argument 0: /bin/bash
execvp argument 1: -c
execvp argument 2: --
execvp argument 3: 'echo' 'test'
test
This causes issues when the user shell does not accept "--" / is not
POSIX-compatible:
$ /bin/bash -c -- 'echo test'
test
$ /bin/fish -c -- 'echo test'
fish: Unknown command: --
fish:
--
^
Fixes #5599.
Relates to #3434.
Reported-by: @iltep64
Reported-by: @ferreum
=> modif: Stop forwarding own double-dash to the shell

etc/profile-a-l/amarok.profile, etc/profile-a-l/arm.profile, etc/profile-a-l/gmpc.profile, etc/profile-a-l/gnome-clocks.profile, etc/profile-m-z/mpDris2.profile, etc/profile-m-z/netactview.profile, etc/profile-m-z/pavucontrol.profile, etc/profile-m-z/qnapi.profile, etc/profile-m-z/sqlitebrowser.profile, etc/profile-m-z/transgui.profile, etc/profile-m-z/wireshark.profile
Fixes for #5608. Relates to #5607.
=> private-etc rework fixes

etc/inc/disable-programs.inc, etc/profile-m-z/zoom.profile
With Zoom version 5.12.6 Zoom changed how they handle encrypting the local database. This change resulted in the new file zoom.conf being used. As it was not allowed by the default profile this could lead to users losing their chat history if they cannot be retrieved from the cloud (e.g. when e2e encryption is used).
=> zoom.profile: whitelist ~/.config/zoom.conf

etc/profile-m-z/qutebrowser.profile
Without those files in private-etc, qutebrowser cannot launch terminal emulators.
I personally think we shouldn't add individual files to private-etc. There should be file groups that we give to private-etc.
Like
```
private-etc @common,@3d,@audio,@dbus,@gui,@gtk,@kde,@networking,@qt
```
=> qutebrowser.profile: Add more files to private-etc

src/firejail/main.c, src/firejail/profile.c, src/man/firejail.txt
If I use only numbers for a name,`firejail --ls=numbers /` fails. Is this an actual bug? If you forbid only numbers in jails, I will close this PR. I can rework it to delete the `if`'s around the lines I added. This commit seems to me like the fix that touches the fewest lines of code. I gave priority to `extract_pid` which should better find the jail if it exists, is it correct?
=> modif: Prevent sandbox name from containing only digits

etc/inc/disable-common.inc, etc/profile-a-l/elinks.profile, etc/profile-m-z/mutt.profile, etc/profile-m-z/nano.profile, etc/profile-m-z/neomutt.profile, etc/profile-m-z/w3m.profile
Move some paths from mutt.profile and neomutt.profile.
Added on commit 6b9bfad ("Fix python; add read-only to editors/cli
browsers;re-add cache directory", 2020-12-29) / PR #3849.
And also make ~/.config/nano read-only.
Misc: This is a follow-up to #5626.
=> disable-common.inc: add more ro editor/browser paths

Makefile
To improve clarity and to prevent unnecessary filesystem lookups.
Overall, this appears to reduce the amount of implicit rule searches by
~4% for the default build and by ~12% for the "man" target (as an
example):
$ git checkout master >/dev/null 2>&1
$ git show --pretty='%h %ai %s' -s
b55cb6a80 2023-01-31 18:56:42 -0500 testing
$ ./configure >/dev/null
$ make clean >/dev/null && make --debug=i -j 4     | grep -F 'Trying implicit' | wc -l
7101
$ make clean >/dev/null && make --debug=i -j 4 man | grep -F 'Trying implicit' | wc -l
1239
$ make clean >/dev/null && make --debug=i -j 4     | grep -F 'Trying implicit' | wc -l
6793
$ make clean >/dev/null && make --debug=i -j 4 man | grep -F 'Trying implicit' | wc -l
1085
Environment: GNU make 4.4-1 on Artix Linux.
Note: The amount lines printed …
=> build: mark most phony targets as such

etc/profile-a-l/aria2c.profile, etc/profile-a-l/discord-common.profile, etc/profile-a-l/email-common.profile, etc/profile-a-l/ghostwriter.profile, etc/profile-m-z/marker.profile, etc/profile-m-z/whois.profile, etc/profile-m-z/xiphos.profile
The private-etc rework is really showing its value in https://github.com/netblue30/firejail/commit/5d0822c52c9a5e631676899e9642911d9143dba8. Easier to spot `oddities` now, like prior typos that stayed undetected.
Relates to #5610.
=> private-etc fixes

etc/profile-a-l/ephemeral.profile
Only changed the syntax to adhere to the @groups work and kept private-etc disabled.
Relates to #5610.
See the [commit comment](https://github.com/netblue30/firejail/commit/0f996ea4de584dc061faf21853d61a600da1a1d8#commitcomment-99461328).
=> ephemeral: use newly introduced private-etc @groups syntax

etc/profile-m-z/whois.profile
Thanks @rusty-snake for [pointing out](https://github.com/netblue30/firejail/pull/5641#discussion_r1097637201) jwhois actually is a thing.
=> whois: re-fix private-etc

Makefile, mkdeb.sh
Instead of using the first argument as the `EXTRA_VERSION` variable.
This should make the usage of mkdeb.sh less confusing, especially when
one is not trying to set the variable.
As for using `EXTRA_VERSION` (which is still optional with this commit),
make sure that it is set as an environment variable before caling
mkdeb.sh.  Example:
env EXTRA_VERSION=-apparmor ./mkdeb.sh --enable-apparmor
See also commit 9a0fbbd71 ("mkdeb.sh.in: pass remaining arguments to
./configure", 2022-05-13) / PR #5154.
=> build: mkdeb.sh: pass all arguments to ./configure

src/include/common.h, src/lib/common.c, src/lib/pid.c
Names and commands can contain control characters:
```
firejail --name="$(echo -e '\e[31mRed\n\b\b\bText\e[0m')" sleep 10s
```
results in "Text" printed in red.
Prevent commands like `--tree` to control the terminal.
I've tested some control characters and I can't do worse than making jails disappear from `--tree` (by controlling the cursor) and possibly output anything to console (hijacking a console output). Reading various documentations and forums, I didn't find interesting control characters like "writing to file" or "execute command", that resulted in CVEs in the past.
* Which other functions should be fixed? `print_elem` is the one used in `--tree`.
* Which other control characters should be escaped?
* In `if (iscntrl(*c)) {`, if the `*c`character is not one in the `switch`, the …
=> modif: Escape control characters of the command line

etc/inc/whitelist-usr-share-common.inc, etc/profile-a-l/com.github.johnfactotum.Foliate.profile
We already allow spelling-checkers. Hyphenation is also part of language usage toolkits.
=> wusc: allow hyphenation

.github/workflows/build.yml, .gitlab-ci.yml, Makefile, README, contrib/update_deb.sh, mkdeb.sh
The official .deb package is always built with apparmor support, so use
`--enable-apparmor` in mkdeb.sh and remove the "deb-apparmor" target in
order to reduce redundancy.
Note that custom configure options may be specified by calling
./mkdeb.sh directly.
For example, to build the .deb package without apparmor support, instead
of running `make deb`, the following commands can be used:
make dist
./mkdeb.sh --disable-apparmor
Also, change the `build_apparmor` GitLab CI job into
`build_no_apparmor`, which is intended to check that building without
apparmor still works.
Note: This commit makes the resulting .deb package not have an
"-apparmor" suffix (see `EXTRA_VERSION` in mkdeb.sh), to avoid
redundancy (as having apparmor support becomes the default).
Misc: This is a follow-up to #5654. …
=> build: deb: enable apparmor by default & remove deb-apparmor

src/firejail/selinux.c
selinux.c: Split Copyright notice in two
This makes firejail's Copyright notice match the ones in basically
every other file, which simplifies updating the Copyright years.
selinux.c was added on commit 1ad2d54c0 ("Add support for SELinux
labeling", 2020-02-18) and it claims to be "from systemd
selinux-util.c".
As for systemd's Copyright notice, the current version of that file on
the systemd project does not have any[1].
The first commit in the systemd repository is from 2009[2] and the file
was copied in 2020 (and does not seem to have been synced since), so set
the years in its Copyright notice to 2009-2020.
Since there is no Copyright notice (and no author) in the upstream file,
list "The systemd Authors" in the Copyright notice.
See also systemd commit 0c69794138 ("tree-wide: remove …
=> docs: selinux.c: Split Copyright notice & use same license as upstream

etc/inc/disable-common.inc
Arch Linux got [systemd v253](https://github.com/archlinux/svntogit-packages/commit/05d0aedb2b83a2e1ba07cab47205772f82cb4814). It adds a few new files we should blacklist in `disable-common.inc`:
- /etc/credstore
- /etc/credstore.encrypted
- /run/credentials/systemd-sysctl.service
- /run/credentials/systemd-sysusers.service
- /run/credentials/systemd-tmpfiles-setup.service
- /run/credentials/systemd-tmpfiles-setup-dev.service
=> disable-common.inc: add systemd v253 blacklists

etc/profile-a-l/apostrophe.profile
/usr/share/perl5 is already present in the included whitelist-usr-share-common.inc
=> apostrophe: drop whitelist covered by wusc

RELNOTES, etc/profile-a-l/fix-qdf.profile, etc/profile-m-z/qpdf.profile, etc/profile-m-z/zlib-flate.profile, src/firecfg/firecfg.config
qpdf (CLI) provides PDF metadata cleaning.
See [privacy-handbuch.de](https://www.privacy-handbuch.de/handbuch_43a.htm) for details. The site offers [pdf-meta-clean.sh](https://www.privacy-handbuch.de/download/pdf-meta-clean.sh), which works very well with firejailed qpdf.
=> New profiles: qpdf and redirects

src/firejail/main.c
Also, s/arguments/argument/ since the message refers to one specific
argument.
Relates to commit 0d06369a8 ("Make env/arg sanity check failure messages
more useful", 2021-11-10) / PR #4676.
Relates to #5676.
Cc: @hlein (from #4676)
=> Print the argument when failing with "too long arguments"

etc/inc/disable-programs.inc, etc/profile-m-z/parsecd.profile
Upstream website: https://parsec.app
It is partly open source, see https://github.com/chrisd1100/libmatoya
Directives that wont work:
- private-dev - it needs that for the passthrough of input devices
- noinput, novideo, noaudio, no3d - because it needs all that
- netfilter - would need custom rules because it connects to STUN stuff
- private-cache - because it does not need any cache and having just ~/.parsec is enough
- the no-exec include - it has executable .so stuff in ~/.parsec for whatever reason and not just in /usr/share/parsec
Did not try seccomp because I am not in the mood to debug segfaults due to missing syscalls, but it otherwise works perfectly with the given profile. The profile is probably missing comments, too.
=> New profile: parsecd

etc/profile-m-z/rsync-download_only.profile
Streamline .local override name. No functional changes.
=> rsync-download_only: fix local override name

src/firejail/main.c, src/firejail/output.c
Forbid control characters in names and filenames. https://github.com/netblue30/firejail/pull/5613.
Syntax for hostnames from https://en.wikipedia.org/wiki/Hostname#Syntax
=> Forbid control chars in names

etc/inc/disable-programs.inc, etc/profile-a-l/lobster.profile, src/firecfg/firecfg.config
it's a shell script for streaming
=> add lobster.profile

etc/inc/disable-programs.inc, etc/profile-a-l/ani-cli.profile, src/firecfg/firecfg.config
shell script for streaming anime
=> add ani-cli.profile

etc/profile-m-z/mpv.profile
~~Although mpv.profile includes `allow-lua.inc`, lua support was effectively broken due to not being referenced in `private-bin`. This PR fixes this.~~
Lua support is working despite of not being referenced in private-bin. Edit comments to clarify things accordingly.
=> mpv: improve and clarify comments

etc/profile-a-l/agetpkg.profile, etc/profile-a-l/archiver-common.profile, etc/profile-a-l/file.profile, etc/profile-a-l/galculator.profile, etc/profile-a-l/geekbench.profile, etc/profile-m-z/mdr.profile, etc/profile-m-z/qpdf.profile, etc/profile-m-z/tesseract.profile, etc/profile-m-z/unf.profile, etc/profile-m-z/uudeview.profile, etc/profile-m-z/whois.profile
Now we have randomized [UTS namespaces support](https://github.com/netblue30/firejail/discussions/5597#discussioncomment-4996357) by default for every sandbox there's no longer a need to set hostname to a fixed value. This PR removes such fixed hostname entrees from all profiles that had it.
=> Drop hostname option from all profiles

.github/workflows/build-extra.yml
This should fix installing packages on build-extra.yml.
Note that this is already done on build.yml and on gitlab-ci.yml.
From the GitHub Actions documentation[1] [2]:
> Note: Always run `sudo apt-get update` before installing a package. In
> case the `apt` index is stale, this command fetches and re-indexes any
> available packages, which helps prevent package installation failures.
[1] https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners
[2] https://github.com/actions/runner-images/issues/2924
=> ci: always update the package db before installing packages

etc/profile-a-l/keepassxc.profile
KeePassXC can offer a Secret Service (see https://specifications.freedesktop.org/secret-service/latest/) to store secrets for other programs
=> keepassxc: Allow offering the Secret Service

src/firejail/firejail.h, src/firejail/util.c
The "invalid_name" function claims to "allow strict ASCII letters and
numbers".
However, it uses isalnum(3) and isdigit(3), which may take the current
locale into account and thus return 1 for non-ASCII characters.
So add the following functions:
* ascii_isalnum
* ascii_isalpha
* ascii_isdigit
* ascii_islower
* ascii_isupper
* ascii_isxdigit
And use the applicable ones in "invalid_name" so that it actually uses
strictly ASCII in its comparisons.
Added on commit b4ffaa207 ("merges; more on cleaning up esc chars",
2023-02-14).
Relates to #5578.
Kind of relates to #5708.
=> util.c: add and use ascii-only char functions

etc/profile-m-z/mov-cli.profile, src/firecfg/firecfg.config
browse and watch movies/shows in the terminal in python.
https://github.com/mov-cli/mov-cli
=> add mov-cli.profile

etc/inc/disable-common.inc, etc/inc/disable-programs.inc, etc/inc/whitelist-common.inc, etc/profile-a-l/ani-cli.profile, etc/profile-a-l/awesome.profile, etc/profile-a-l/cower.profile, etc/profile-a-l/electron-mail.profile, etc/profile-a-l/email-common.profile, etc/profile-a-l/firefox.profile, etc/profile-a-l/geary.profile, etc/profile-a-l/kube.profile, etc/profile-a-l/linuxqq.profile, etc/profile-a-l/lobster.profile, etc/profile-m-z/makepkg.profile, etc/profile-m-z/mov-cli.profile, etc/profile-m-z/openbox.profile, etc/profile-m-z/signal-desktop.profile, etc/profile-m-z/steam.profile, etc/profile-m-z/thunderbird.profile, etc/profile-m-z/trojita.profile, etc/profile-m-z/tutanota-desktop.profile, etc/profile-m-z/youtube-viewers-common.profile, etc/profile-m-z/zeal.profile, etc/templates/profile.template
This should reduce duplication and increase hardening a bit.
Relates to #1642 #5706 #5707 #5710.
Cc: @pirate486743186 (from #5706 #5707 #5710)
=> profiles: move read-only config entries to disable-common.inc

.github/workflows/codeql-analysis.yml
Due to step-security/harden-runner blocking access to
objects.githubusercontent.com.
Log from a recent run of CodeQL[1] [2]:
##[group]Setup CodeQL tools
Did not find CodeQL tools version 2.12.6 in the toolcache.
Downloading CodeQL tools from https://github.com/github/codeql-action/releases/download/codeql-bundle-20230403/codeql-bundle-linux64.tar.gz. This may take a while.
connect ECONNREFUSED 54.185.253.63:443
Waiting 13 seconds before trying again
connect ECONNREFUSED 54.185.253.63:443
Waiting 12 seconds before trying again
##[error]connect ECONNREFUSED 54.185.253.63:443
##[error]Unable to download and extract CodeQL CLI
Post job cleanup.
[...]
Mon, 10 Apr 2023 07:20:18 GMT:endpoint called ip address:port 140.82.112.4:443, domain: github.com.
Mon, 10 Apr 2023 07:20:20 GMT:endpoint …
=> ci: fix codeql unable to download its own bundle

etc/profile-m-z/softmaker-common.profile
When using `private-etc`, app "forgets" it's product key and
asks for license activation, despite it has already been done.
Allow access to "/etc/fstab" to avoid it & related GUI error:
The application cannot create a unique identifier.
Please make sure the application has sufficient permissions.
Fixes #5773.
=> softmaker-common.profile: add fstab to private-etc

.gitlab-ci.yml
Split them into separate steps to make it clearer in the logs which
command causes a job to fail when it does.
Note that they are already spli in the GitHub workflows:
* .github/workflows/build.yml
* .github/workflows/build-extra.yml
=> ci: split configure/build/install commands on gitlab

etc/profile-a-l/gtk-lbry-viewer.profile, etc/profile-a-l/gtk-pipe-viewer.profile, etc/profile-a-l/gtk-straw-viewer.profile, etc/profile-a-l/gtk-youtube-viewer.profile, etc/profile-a-l/gtk-youtube-viewers-common.profile, etc/profile-a-l/gtk2-youtube-viewer.profile, etc/profile-a-l/gtk3-youtube-viewer.profile, etc/profile-a-l/lbry-viewer.profile, etc/profile-m-z/pipe-viewer.profile, etc/profile-m-z/straw-viewer.profile, etc/profile-m-z/youtube-viewer.profile, etc/profile-m-z/youtube-viewers-common.profile
created gtk-youtube-viewers-common.profile moved some stuff to it
some clean up
They will be easier to manage.
=> youtube-viewers: refactor and add gtk-youtube-viewers-common

etc/profile-a-l/apostrophe.profile, etc/profile-a-l/bluefish.profile, etc/profile-a-l/celluloid.profile, etc/profile-a-l/claws-mail.profile, etc/profile-a-l/clipit.profile, etc/profile-a-l/com.github.bleakgrey.tootle.profile, etc/profile-a-l/corebird.profile, etc/profile-a-l/deadbeef.profile, etc/profile-a-l/dino-im.profile, etc/profile-a-l/dino.profile, etc/profile-a-l/gajim.profile, etc/profile-a-l/geeqie.profile, etc/profile-a-l/gtk-lbry-viewer.profile, etc/profile-a-l/gtk-pipe-viewer.profile, etc/profile-a-l/gtk-straw-viewer.profile, etc/profile-a-l/gtk-youtube-viewer.profile, etc/profile-a-l/gtk2-youtube-viewer.profile, etc/profile-a-l/gtk3-youtube-viewer.profile, etc/profile-a-l/guvcview.profile, etc/profile-a-l/handbrake.profile, etc/profile-a-l/leafpad.profile, etc/profile-m-z/marker.profile, etc/profile-m-z/mp3splt-gtk.profile, etc/profile-m-z/remmina.profile, etc/profile-m-z/sylpheed.profile
For consistency and to reduce confusion.
The toolkit has been renamed from "GTK+" to just "GTK" in 2019[1].
Note: This also fixes some adjacent typos.
Commands used to search and replace:
$ git grep -lz 'G[Tt][Kk]' -- etc | xargs -0 -I '{}' sh -c \
"printf '%s\n' \"\$(sed -E \
-e 's/G[Tt][Kk]\+?/GTK/g' \
-e 's/GTK-.\.0/GTK/g' \
-e 's/GTK base/GTK-base/g' \
-e 's/GTK-base /GTK-based /g' \
-e 's/Light weight/Lightweight/g' \
-e 's/client with GTK/client made with GTK/g' '{}')\" >'{}'"
Misc: I noticed this on #5722.
[1] https://mail.gnome.org/archives/gtk-devel-list/2019-February/msg00000.html
Cc: @pirate486743186 (from #5722)
=> profiles: standardize on just "GTK" on comments

.gitlab-ci.yml
Currently, the author name is used as the author email in git and vice
versa.
Changes:
* Split the commands to make them easier to read
* Put the name command first to match the usual git usage
* Fix swapped name/email arguments
* Use the DEBFULLNAME / DEBEMAIL environment variables instead of
GitLab-specific ones
Added on commit 4cf51b591 ("extend gitlab-ci configuration to run Debian
CI tests", 2019-06-21).
=> ci: fix swapped name/email arguments in debian_ci

.github/workflows/build-extra.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/profile-checks.yml, .gitlab-ci.yml, Makefile, ci/printenv.sh
Commits:
```console
* ci: fix commented sort.py code in alpine job
* ci: ignore build workflows on more workflows
* ci: simplify test steps in build.yml
* ci: line-wrap and split/join some commands
* ci: use one command per line instead of chaining them
* ci: improve quotes in gitlab ci
* ci: print some program versions
* ci: print env-related settings in each job
```
The changes are mostly about making the workflows easier to read and debug.
This is a follow-up to #5795.
Relates to #5481.
=> ci: formatting and misc improvements

src/firejail/arp.c
Log from build_and_test[1]:
TESTING: network scan (net_scan.exp)
[...]
firejail /bin/bash
Child process initialized in 1704.83 ms
spawn /bin/bash
firejail --net=br0 --ip=10.10.20.60
runner@fv-az576-472:~/work/firejail/firejail/test/network$
<l/test/network$ firejail --net=br0 --ip=10.10.20.60
Reading profile /etc/firejail/default.profile
** Note: you can use --noprofile to disable default.profile **
Error select: arp.c:202 arp_check: Invalid argument
runner@fv-az576-472:~/work/firejail/firejail/test/network$ TESTING ERROR 4
This "Invalid argument" error does not always happen, so I assume that
it may be due to a negative integer value in `ts` when calling select.
Misc: Found in #5805.
[1] …
=> arp.c: ensure positive timeout on select(2)

.github/workflows/build-extra.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/profile-checks.yml
Having CI always run on WIP branches without having to open a PR
beforehand makes it easier to debug CI issues.
GitHub currently does not have any apparent limit for CI runs and there
are no project-specific secrets as far as I know, so it should be safe
to remove these restrictions.
=> ci: run for every branch instead of just master

README.md
Clarify how to remove the symlinks created by firecfg.
Reported by @MikeNavy in #5098.
=> docs: add uninstall instructions to README.md

etc/profile-a-l/email-common.profile
Fixes #5809.
Additionally added bsfilter whitelisting (similar to bogofilter).
=> email-common: fix bogofilter/bsfilter support

src/etc-cleanup/main.c, src/fbuilder/main.c, src/fcopy/main.c, src/fids/main.c, src/firecfg/main.c, src/firejail/checkcfg.c, src/firejail/firejail.h, src/firejail/main.c, src/firejail/usage.c, src/firemon/firemon.c, src/firemon/firemon.h, src/firemon/usage.c, src/fldd/main.c, src/fnet/main.c, src/fnetfilter/main.c, src/fnettrace-dns/main.c, src/fnettrace-icmp/main.c, src/fnettrace-sni/main.c, src/fnettrace/main.c, src/fsec-optimize/main.c, src/fsec-print/main.c, src/fseccomp/main.c, src/ftee/main.c, src/jailcheck/main.c, src/profstats/main.c
It is not too uncommon for the firejail version to be missing when issues are
reported; this PR makes it more likely that any posted logs will contain the
program version.
Do so just for firejail and firecfg for now because they are the most common
user-facing programs.
Kind of relates to #5275.
=> modif: Improve --version/--help & print version on startup

configure, configure.ac, src/prog.mk, src/so.mk
Enable -Wall by default and add -Wextra.
=> build: enable compiler warnings by default

etc/profile-a-l/firefox.profile
We enable private-etc in firefox-common.profile. The comment in firefox.profile about private-etc no longer makes sense and we can add 'firefox' to it there.
=> firefox: fix private-etc firefox

contrib/vim/ftdetect/firejail.vim
Currently it only sets the appropriate filetype for files in
`/etc/firejail` and `~/.config/firejail`.
With this commit, the firejail filetype should also be set when opening
`etc/inc/*.inc`, for example, as long as there is a "firejail" directory
somewhere before that (such as in `/foo/firejail/bar/etc/inc/*.inc`).
Note: At least `*/firejail/*.inc` needs to force the match (by using
`set filetype` rather than `setfiletype`), or else the default vim
checks take precedence (and the filetype for all files in
`etc/inc/*.inc` gets set to `pov`).
Fixes #4319.
Relates to #2679.
Cc: @laomaiweng @reinerh @rusty-snake (from #2679 #4319)
=> contrib/vim: match profile files more broadly

.github/workflows/build-extra.yml, .github/workflows/build.yml, .gitlab-ci.yml
General changes:
* Use a single -q on update, as the output is not too long
* Use a single -q on install, to show all packages at once
GitLab-specific changes:
* Use `DEBIAN_FRONTEND=noninteractive` to reduce noise
* Use --no-install-recommends to avoid installing unnecessary packages
* Filter out uninteresting lines on install
Note: `DEBIAN_FRONTEND` does not appear to be needed in the default
GitHub runner container and not many packages are currently being
downloaded/installed in them, so do the above changes only jobs that use
custom Docker images.
=> ci: standardize apt-get update/install & misc improvements

src/firejail/main.c, src/firejail/profile.c, src/firejail/util.c, src/man/firejail.txt
Main changes:
* Unify name and hostname checks
* Use only `invalid_name` to check the name and hostname instead of
ad-hoc checks
* Standardize empty/invalid error messages for name/hostname
* Add missing name/hostname checks
* docs: document NAME VALIDATION in firejail.txt
Note: This makes the hostname validation less strict, though it still
forbids control characters and only numbers.
Relates to #5578 #5708.
See also commit b4ffaa2 ("merges; more on cleaning up esc chars",
2023-02-14).
Cc: @layderv @netblue30
=> modif: Standardize and add missing name/hostname checks

Makefile, src/bash_completion/Makefile, src/etc-cleanup/Makefile, src/fbuilder/Makefile, src/fcopy/Makefile, src/fids/Makefile, src/firecfg/Makefile, src/firejail/Makefile, src/firemon/Makefile, src/fldd/Makefile, src/fnet/Makefile, src/fnetfilter/Makefile, src/fnettrace-dns/Makefile, src/fnettrace-icmp/Makefile, src/fnettrace-sni/Makefile, src/fnettrace/Makefile, src/fsec-optimize/Makefile, src/fsec-print/Makefile, src/fseccomp/Makefile, src/ftee/Makefile, src/fzenity/Makefile, src/jailcheck/Makefile, src/lib/Makefile, src/libpostexecseccomp/Makefile, src/libtrace/Makefile, src/libtracelog/Makefile, src/man/Makefile, src/profstats/Makefile, src/zsh_completion/Makefile, test/Makefile
To reduce unnecessary filesystem lookups.
Overall, this appears to reduce the amount of implicit rule searches by ~97.5%
for the default build and by ~99.3% for the "man" target (as an example):
$ git show --pretty='%h %ai %s' -s
a8f01a383 2023-06-20 05:26:23 +0000 Merge pull request #5859 from kmk3/build-remove-retpoline
$ ./configure >/dev/null
$ make clean >/dev/null && make --debug=i -j 4     | grep -F 'Trying implicit' | wc -l
6798
$ make clean >/dev/null && make --debug=i -j 4 man | grep -F 'Trying implicit' | wc -l
1085
$ make clean >/dev/null && make --debug=i -j 4     | grep -F 'Trying implicit' | wc -l
2535
$ make clean >/dev/null && make --debug=i -j 4 man | grep -F 'Trying implicit' | wc -l
42
$ make clean >/dev/null && make --debug=i -j 4     | grep -F 'Trying implicit' | wc …
=> build: disable all built-in implicit make rules

etc/profile-m-z/vmplayer.profile, etc/profile-m-z/vmware-player.profile, etc/profile-m-z/vmware-view.profile, etc/profile-m-z/vmware-workstation.profile, etc/profile-m-z/vmware.profile, src/firecfg/firecfg.config
Add vmplayer.profile as a redirect to vmware.profile.
This is apparently the filename for the "VMWare Workstation Player" on
Linux Mint 20.3 (based on Ubuntu 20.04)[1].
Relates to #3526 #5861.
[1] https://github.com/netblue30/firejail/issues/5861#issuecomment-1598132860
Reported-by: @MikeNavy
=> profiles: vmware improvements and new redirect

etc/inc/disable-programs.inc, etc/profile-a-l/lobster.profile
lobster went through a major rewrite.
ueberzugpp is a ueberzug alternative in C++, it's more like a library
.local/share/applications/lobster is just a symlink to /tmp, it doesn't need to be persistent. If it already exist it will be used.
=> update lobster profile

etc/profile-a-l/lobster.profile
it needs to write in `.local/share/applications` on first run.
It has to be at the end of the profile to take effect.
=> fix lobster.profile

Makefile, etc/ids.config, etc/inc/disable-common.inc, src/jailcheck/main.c
Commands used to find the relevant paths in /etc:
$ pacman -Qo /etc/* 2>/dev/null | grep sudo | LC_ALL=C sort
/etc/pam.d/ is owned by sudo 1.9.14.p1-1
/etc/sudo.conf is owned by sudo 1.9.14.p1-1
/etc/sudo_logsrvd.conf is owned by sudo 1.9.14.p1-1
/etc/sudoers is owned by sudo 1.9.14.p1-1
/etc/sudoers.d/ is owned by sudo 1.9.14.p1-1
Environment: Artix Linux.
Also, add missing paths sudo/doas to etc/ids.config and jailcheck.
See also commit dbebd71db ("disable-common.inc: blacklist doas binary",
2022-10-05).
Relates to #5385.
Reported-by: Dieter Plaetinck <dieter@plaetinck.be>
=> disable-common.inc: blacklist sudo/doas paths in /etc

etc/profile-a-l/beaker.profile, etc/profile-a-l/default.profile, etc/profile-a-l/fdns.profile, etc/profile-a-l/gnome-nettool.profile, etc/profile-a-l/jitsi-meet-desktop.profile, etc/profile-m-z/pidgin.profile, etc/profile-m-z/rocketchat.profile, etc/profile-m-z/server.profile, etc/templates/profile.template, src/bash_completion/firejail.bash_completion.in, src/fbuilder/build_profile.c, src/firejail/main.c, src/firejail/profile.c, src/man/firejail-profile.5.in, src/zsh_completion/_firejail.in, test/environment/shell-none.profile, test/profiles/ignore.exp, test/profiles/ignore.profile, test/profiles/ignore2.profile, test/profiles/ignore3.profile, test/utils/build.exp
The `shell` option has been removed. Remove stale references.
This does NOT remove `shell none`-related code comments in:
- [src/firejail/fs_lib.c](https://github.com/netblue30/firejail/blob/1d5fff9034796d69f287abbcfedff0342990fb7c/src/firejail/fs_lib.c#L433-L441)
- [src/firejail/join.c](https://github.com/netblue30/firejail/blob/1d5fff9034796d69f287abbcfedff0342990fb7c/src/firejail/join.c#L415-L417)
Relates to #5196.
Suggested by #5891.
=> modif: drop deprecated 'shell' option references

etc/inc/disable-programs.inc, etc/profile-m-z/sqlitebrowser.profile
Sqlitebrowser supports editing remote databases. By default it clones such DB's and installs the needed CA certificates under `${HOME}/.local/share/sqlitebrowser`, which this PR makes accessible in the sandbox.
=> sqlitebrowser remote support

etc/profile-a-l/firefox-common-addons.profile, etc/profile-m-z/mpv.profile, etc/profile-m-z/smplayer.profile
No need for whitelisting /usr/share/vulkan twice in profiles that include wusc. We already do it there:
https://github.com/netblue30/firejail/blob/9863f982ca148f687a56690e2aeed10014d05e59/etc/inc/whitelist-usr-share-common.inc#L70
=> profiles: remove /usr/share/vulkan already whitelisted by wusc

etc/apparmor/firejail-local, etc/inc/disable-programs.inc, etc/profile-m-z/mullvad-browser.profile, src/firecfg/firecfg.config
Add new profile for [mullvad-browser](https://mullvad.net/en/download/browser/linux). Requested [here](https://github.com/netblue30/firejail/issues/1139#issuecomment-1500052260) and suggested [here](https://github.com/netblue30/firejail/issues/1139#issuecomment-1500125403).
=> New profile: mullvad-browser

Makefile, src/bash_completion/Makefile, src/prog.mk, src/so.mk, src/zsh_completion/Makefile, test/Makefile
This also fixes the duplicate execution of the "clean" targets.
=> build: fix hardcoded make & remove unnecessary distclean targets

Makefile, mkasc.sh, platform/rpm/mkrpm.sh, test/compile/compile.sh
This removes the need to manually pass variables such as `$(TARNAME)`
and `$(VERSION)` to shell scripts in the root Makefile.
Relates to #5140.
=> build: fix some shellcheck issues & use config.sh in more scripts

etc/profile-m-z/thunderbird.profile
The `Enigmail` add-on was replaced with built-in support for OpenPGP in Thunderbird 78. Development has [stopped](https://enigmail.net/index.php/en/home/news/70-2019-10-08-future-openpgp-support-in-thunderbird) in 2019. IMO it's time to drop allowing full access to the user and system bus and introduce selective filtering.
=> thunderbird: D-Bus hardening

etc/inc/disable-programs.inc, etc/profile-a-l/chatterino.profile, etc/profile-a-l/firefox-common-addons.profile, etc/profile-m-z/QMediathekView.profile, etc/profile-m-z/mediathekview.profile, etc/profile-m-z/mpsyt.profile, etc/profile-m-z/mpv.profile, etc/profile-m-z/rtv-addons.profile, etc/profile-m-z/smtube.profile, etc/profile-m-z/youtube-viewers-common.profile
mpv v0.36.0 uses ~/.cache/mpv[1] [2]:
Relates to #2838 #5936.
[1] https://github.com/mpv-player/mpv/releases/tag/v0.36.0
[2] https://github.com/mpv-player/mpv/pull/10838
=> mpv.profile: add XDG_CACHE_HOME & missing paths

ci/check/profiles/sort-firecfg.config.sh, src/firecfg/firecfg.config
Remove the space after `#` for commented code and use `#` instead of `-`
for comments at the end of the line.
Currently the CI check does not consider certain special characters
(such as `-`) when sorting due to `sort -d`.
So remove `-d`, sort firecfg using `LC_ALL=C` and enforce that order.
Also add `sort -u` to check for duplicates.
This also allows the CI check to ignore normal comments (lines starting
with `# `) anywhere in the file.
Relates to #4643.
=> build: firecfg.config sorting improvements

etc/profile-a-l/0ad.profile
Se [this issue](https://github.com/netblue30/firejail/issues/5938#issue-1833607321) that describes it all.
=> 0ad.profile: fix libmozjs error on OpenSUSE Tumbleweed

etc/profile-a-l/daisy.profile, etc/profile-a-l/dbus-send.profile, etc/profile-a-l/drill.profile, etc/profile-a-l/gapplication.profile, etc/profile-a-l/gnome-calendar.profile, etc/profile-a-l/gnubik.profile, etc/profile-a-l/gravity-beams-and-evaporating-stars.profile, etc/profile-a-l/ipcalc.profile, etc/profile-m-z/Xephyr.profile, etc/profile-m-z/Xvfb.profile, etc/profile-m-z/mirrormagic.profile, etc/profile-m-z/notify-send.profile, etc/profile-m-z/ping.profile, etc/profile-m-z/reader.profile, etc/profile-m-z/seahorse-adventures.profile, etc/profile-m-z/wordwarvi.profile, etc/profile-m-z/xbill.profile
As I was [recently](https://github.com/netblue30/firejail/pull/5943#pullrequestreview-1564187005) reminded by @kmk3 to #903 I checked existing profiles for similar issues. This PR fixes whitelisting in ${HOME} and streamlines the reference to #903.
=> profiles: improvements to profiles using private

.github/workflows/build-extra.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/profile-checks.yml
This PR does two things:
1. Updates `step-security/harden-runner` from 2.5.0 to 2.5.1 in the GitHub Actions workflows.
GitHub Actions recently started making outbound calls to a few endpoints not in the default allowed list.   This causes the build to get stuck when using a `block` policy with `harden-runner`. This update to harden-runner (version v2.5.1), adds these new endpoints to the default allowed list. 
I noticed that some of the workflows in this repository are getting stuck, so creating a PR to bump up the version to the latest. 
Release notes for the latest version are here:
https://github.com/step-security/harden-runner/releases/tag/v2.5.1
2. I also noticed while testing the workflows that some endpoints that should be allowed were not in the allowed list, and were getting …
=> build(deps): Update step-security/harden-runner and update allowed endpoints

etc/profile-a-l/gmpc.profile, etc/profile-m-z/mpDris2.profile, etc/profile-m-z/mpd.profile
mpDris2 brings MPRIS2 support to MPD:
https://github.com/eonpatapon/mpDris2
Let's use our dbus-filtering options for some hardening.
=> mpd: allow MPRIS2

.github/workflows/build-extra.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/codespell.yml, Makefile, RELNOTES, contrib/jail_prober.py, etc/profile-a-l/kwin_x11.profile, etc/profile-m-z/tvbrowser.profile, etc/profile-m-z/twitch.profile, etc/profile-m-z/youtube.profile, etc/profile-m-z/youtubemusic-nativefier.profile
Changes:
```console
* build: fix codespell errors in more files
* build: codespell: remove dependency on "clean"
* ci: move codespell job into its own workflow
* ci: run ./configure in codespell
* build: run codespell on almost all files
```
Homepage: <https://github.com/codespell-project/codespell>
Added on commit d78fc96ee ("codespell github action", 2023-03-05).
=> build: codespell improvements

Makefile, contrib/syntax/lists/profile_commands_arg0.list
Make the non-phony targets that are defined in the root Makefile depend
on it, to ensure that they get re-generated if their recipes change.
Note that these targets are generated nearly instantly, so this should
not noticeably affect rebuild times.
Relates to #5627.
=> build: add missing makefile dep & syntax improvements

etc/inc/disable-common.inc, etc/inc/disable-devel.inc
As of https://github.com/netblue30/firejail/commit/96beb3358c430a5e470ce02fd64ffc3f7fc23706 `fakeroot` is blacklisted in disable-common.inc. Without that, makepkg will break, cfr. https://github.com/netblue30/firejail/commit/96beb3358c430a5e470ce02fd64ffc3f7fc23706#r125237349.
=> profiles: move fakeroot blacklisting to disable-devel.inc

etc/inc/allow-common-devel.inc, etc/inc/disable-devel.inc, etc/inc/disable-programs.inc
Which also blacklists ~/.cargo.
Note that ~/.rustup is the only `${HOME}` entry in disable-devel.inc.
Added on commit 8d9b12d1c ("New profiles + fixes + hardening",
2020-09-14).
=> profiles: move ~/.rustup blacklist to disable-programs.inc

etc/profile-a-l/ani-cli.profile, etc/profile-a-l/lobster.profile, etc/profile-m-z/patch.profile
Commit 3077b2d1f blacklists `${PATH}/patch` in disable-devel.inc[1]. We
need to noblacklist it in the profiles that need it.
[1] https://github.com/netblue30/firejail/commit/3077b2d1ff6c6e26a83487ae460985157b5c61fd
=> profiles: patch fixes

etc/profile-m-z/neochat.profile
The latest Neochat package on Arch (23.08.0-2, with libquotient 0.8.1.1-1) crashes otherwise.
=> neochat: Allow netlink

etc/inc/disable-programs.inc, etc/profile-m-z/telegram.profile
New TelegramWebApps uses another directory for saving local storage.
=> telegram.profile: allow ~/.local/share/telegram-desktop

RELNOTES, src/firejail/main.c, src/firejail/util.c
This group is apparently used on Gentoo[1].
Currently only the "audio" supplementary group is kept.
Fixes #5992.
See also commit f32938669 ("Keep vglusers group unless no3d is used
(virtualgl)", 2022-01-07) / PR #4851.
[1] https://wiki.gentoo.org/wiki/PipeWire
Reported-by: @amano-kenji
=> modif: keep pipewire group unless nosound is used

etc/profile-a-l/gnome-logs.profile, etc/profile-a-l/gnome-system-log.profile, etc/profile-a-l/journal-viewer.profile, etc/profile-m-z/profile-m-z/profile-m-z/system-log-common.profile
Introduces a common profile for existing GUI log viewer applications.
=> profiles: refactor log viewers

etc/profile-a-l/file-roller.profile, etc/profile-a-l/freemind.profile
The two profiles with dpkg in private-bin didn't override `blacklist ${PATH}/dpkg*` from disable-common.inc. Let's fix that.
=> profiles: dpkg fix

etc/inc/disable-programs.inc, etc/profile-a-l/lettura.profile, src/firecfg/firecfg.config
Another free and open-source feed reader
https://zhanglun.github.io/lettura/
https://github.com/zhanglun/lettura
=> New profile: lettura

.github/workflows/build-extra.yml, .github/workflows/build.yml, .github/workflows/check-c.yml, .github/workflows/check-profiles.yml, .github/workflows/check-python.yml, .github/workflows/codespell.yml, .github/workflows/test.yml
Add `on.workflow_dispatch`.
See:
* https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatch
* https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
=> ci: allow running workflows manually

etc/profile-m-z/tidal-hifi.profile, src/firecfg/firecfg.config
modified src/firecfg/firecfg.config to add tidal-hifi
created etc/profile-m-z/tidal-hifi.profile
closes: #6008
=> New profile: tidal-hifi

etc/profile-m-z/nicotine.profile
From https://github.com/netblue30/firejail/issues/6034. Nicotine+ needs `dbus-user.own org.nicotine_plus.Nicotine` or it will crash if started with options for Fcitx. And `dbus-user.talk ca.desrt.dconf` is to support dconf as stated [here]( https://github.com/netblue30/firejail/issues/6034#issuecomment-1750542403).
=> nicotine: support Fcitx and dconf via dbus-user filter

etc/profile-m-z/wireshark.profile
Grant access to ${PATH}/dumpcap (blacklisted in disable-common.inc).
Came up [here](https://github.com/netblue30/firejail/issues/4241#issuecomment-1750809663).
=> wireshark: fix access to dumpcap

etc/profile-m-z/pavucontrol-qt.profile
=> pavucontrol-qt: fix broken whitelisting in ${HOME}

etc/profile-a-l/bitwarden.profile, etc/profile-a-l/discord-canary.profile, etc/profile-a-l/discord-ptb.profile, etc/profile-a-l/discord.profile, etc/profile-a-l/electron-mail.profile, etc/profile-a-l/element-desktop.profile, etc/profile-a-l/gitter.profile, etc/profile-a-l/google-earth.profile, etc/profile-a-l/linuxqq.profile, etc/profile-m-z/microsoft-edge-beta.profile, etc/profile-m-z/mullvad-browser.profile, etc/profile-m-z/notable.profile, etc/profile-m-z/nuclear.profile, etc/profile-m-z/ocenaudio.profile, etc/profile-m-z/palemoon.profile, etc/profile-m-z/spotify.profile, etc/profile-m-z/thunderbird-beta.profile, etc/profile-m-z/torbrowser-launcher.profile, etc/profile-m-z/tutanota-desktop.profile, etc/profile-m-z/twitch.profile, etc/profile-m-z/xmr-stak.profile, etc/profile-m-z/youtube.profile, etc/profile-m-z/youtubemusic-nativefier.profile, etc/templates/profile.template, src/man/firejail.1.in
private-opt breaks file-copy-limit, use a whitelist instead of draining RAM
cfr. https://github.com/netblue30/firejail/discussions/5307
This PR streamlines the comment and does the relevant whitelisting in /opt.
=> profiles: exchange private-opt with a whitelist

contrib/syntax/files/firejail-profile.lang.in
PR to fix https://github.com/netblue30/firejail/issues/6057
=> contrib/syntax: remove 'text/plain' from firejail-profile.lang.in

etc/inc/disable-common.inc, etc/inc/disable-programs.inc, etc/profile-m-z/mutt.profile, etc/profile-m-z/neomutt.profile
Since version 1.8.6 msmtp supports per-user configuration at either
~/.msmtprc (already supported by firejail) or
`$XDG_CONFIG_HOME/msmtp/config`. System-wide support can be placed at
/etc/msmtprc.
This adds the missing paths to the relevant .inc and .profile files.
Note that `blacklist ${HOME}/.msmtprc` is present on both
disable-common.inc and disable-programs.inc, so the new paths are added
to both files.
References:
https://wiki.archlinux.org/title/Msmtp#Basic_setup
https://marlam.de/msmtp/msmtp.html#Configuration-files
=> profiles: support more msmtp configuration paths

etc/inc/disable-common.inc, etc/inc/disable-programs.inc
They are already present in disable-common.inc.
Added in the following commits:
* 6bf6d5ed5 ("updated program files", 2016-12-02) / PR #951
* 49280197c ("various hardening (#3394)", 2020-05-02)
* 2e2c2327f ("profiles: support more msmtp configuration paths (#6060)",
2023-10-22)
Misc: This was noticed on PR #6060.
=> disable-programs.inc: remove duplicated entries

etc/profile-a-l/discord.profile
[discord_arch_electron](https://aur.archlinux.org/packages/discord_arch_electron) stores its files in /usr/share/discord, rather than the usual /opt/discord. this commit simply adds that directory to the whitelist.
=> discord.profile: allow /usr/share/discord

etc/inc/disable-programs.inc, etc/profile-m-z/tiny-rdm.profile, src/firecfg/firecfg.config
A Modern Redis GUI Client
https://redis.tinycraft.cc/
https://github.com/tiny-craft/tiny-rdm
=> New profile: tiny-rdm

src/firejail/ls.c
The most generic way is to use `intmax_t`
because we dont't know what is the "parent" type of `off_t`.
This fixes https://github.com/netblue30/firejail/issues/5982 .
=> Fix displaying of large file sizes.

src/fcopy/main.c
When copying directories use lstat when reading info about source files.
Closes #5378.
=> fcopy: Use lstat when copy directory.

etc/profile-m-z/steam.profile
EA Origin (game launcher) won't launch without this.
See https://github.com/netblue30/firejail/issues/5185#issuecomment-1776516159
=> steam.profile: allow process_vm_readv syscall

etc/profile-a-l/lutris.profile
Need to whitelist `ptrace` and `clone3` for Ubisoft Connect to work.
journalctl did list `process_vm_readv` when a game was running, but it
didn't crash the game; see
https://github.com/netblue30/firejail/issues/6035#issuecomment-1776513877
Fixes #6035.
=> lutris.profile: allow more syscalls

contrib/sort.py, etc/profile-a-l/ani-cli.profile, etc/profile-a-l/discord-canary.profile, etc/profile-a-l/discord-ptb.profile, etc/profile-a-l/discord.profile, etc/profile-a-l/display.profile, etc/profile-a-l/enpass.profile, etc/profile-a-l/fbreader.profile, etc/profile-a-l/fluffychat.profile, etc/profile-a-l/hugin.profile, etc/profile-a-l/lobster.profile, etc/profile-m-z/QMediathekView.profile, etc/profile-m-z/QOwnNotes.profile, etc/profile-m-z/Viber.profile, etc/profile-m-z/XMind.profile, etc/profile-m-z/mov-cli.profile, etc/profile-m-z/mutt.profile, etc/profile-m-z/natron.profile, etc/profile-m-z/neomutt.profile, etc/profile-m-z/postman.profile, etc/profile-m-z/ppsspp.profile, etc/profile-m-z/softmaker-common.profile, etc/profile-m-z/telegram.profile, etc/profile-m-z/transgui.profile
To match how things are sorted elsewhere, such as with `noblacklist` /
`whitelist` lines (vertically) in profiles and in
ci/check/profiles/sort-disable-programs.sh and src/etc-cleanup/main.c.
This makes the order in `private-etc` always be groups (`@group`), then
uppercase paths, then lowercase paths.  Example from
etc/profile-m-z/softmaker-common.profile:
private-etc @tls-ca,SoftMaker,fstab
Note that this does not affect a significant amount of profiles; most
changes are in `private-bin` / `private-lib` lines and in `private-etc`
lines for newer profiles that do not use groups.  This is partly due to
commit 5d0822c52 ("private-etc: big profile changes", 2023-02-05)
replacing `X11` with `@x11` in `private-etc` lines and then commit
0f996ea4d ("private-etc: groups modified", 2023-02-05) …
=> build: sort.py: use case-sensitive sorting

src/firejail/fs_lib2.c, src/firejail/x11.c
Don't use hardcoded `/usr/bin/xauth`,
iterate over directories inside PATH instead.
This fixes https://github.com/netblue30/firejail/issues/6006
=> Lookup xauth in PATH.

src/firecfg/firecfg.config
Geary uses bubblewrap now.
Fixes #6103.
=> firecfg.config: drop geary

etc/inc/disable-programs.inc, etc/profile-a-l/curl.profile
curl supports several locations for rc file according to its man page:
[...]
When curl is invoked, it (unless -q, --disable is used) checks for a default config file and uses it if found, even when -K, --config is used. The default config file is checked for in the following places in this order:
1) "$CURL_HOME/.curlrc"
2) "$XDG_CONFIG_HOME/curlrc" (Added in 7.73.0)
3) "$HOME/.curlrc"
[...]
This PR adds support for ~/.config/curlrc.
=> curl: add support for ~/.config/curlrc

etc/profile-m-z/obs.profile
Some plugins may require it[1]:
error: os_dlopen([...]): libluajit-5.1.so.2: [...]: Permission denied
warning: Module '/usr//lib/obs-plugins/frontend-tools.so' not loaded
[1] https://github.com/netblue30/firejail/issues/6130#issue-2040800338
=> obs.profile: allow lua

etc/profile-m-z/minecraft-launcher.profile
It turns out it is using it to save logins and will error out with just a generic "something went wrong, so we can not save your login".
I copied the directives from email-common.inc. Unsure which specific dbus topic thingy is actually used here but it works and I think it is fine to leave all 3.
Dear maintainers, if the ordering of the directives, my arch nemesis, is wrong, please apply your suggestion or edit without asking.
=> minecraft-launcher.profile: allow keyring access

contrib/syntax/lists/profile_commands_arg0.list, contrib/syntax/lists/profile_commands_arg1.list, etc/inc/landlock-common.inc, etc/profile-a-l/default.profile, etc/templates/profile.template, src/bash_completion/firejail.bash_completion.in, src/firejail/firejail.h, src/firejail/landlock.c, src/firejail/main.c, src/firejail/profile.c, src/firejail/sandbox.c, src/firejail/usage.c, src/man/firejail-profile.5.in, src/man/firejail.1.in, src/zsh_completion/_firejail.in
Changes:
* Move commands from --landlock and --landlock.proc= into
etc/inc/landlock-common.inc
* Remove --landlock and --landlock.proc=
* Add --landlock.enforce
Instead of hard-coding the default commands (and having a separate
command just for /proc), move them into a dedicated profile to make it
easier for users to interact with the entries (view, copy, add ignore
entries, etc).
Only enforce the Landlock commands if --landlock.enforce is supplied.
This allows safely adding Landlock commands to (upstream) profiles while
keeping their enforcement opt-in.  It also makes it simpler to
effectively disable all Landlock commands, by using
`--ignore=landlock.enforce`.
=> landlock: move commands into profile and add landlock.enforce

platform/rpm/mkrpm.sh
For consistency with mkdeb.sh.
Note: The default arguments and support for argument overriding was
added to to mkrpm.sh on commit 3d97332fd ("Add configure options when
building rpm (#3422)", 2020-05-19).
The support for appending arguments was added to mkdeb.sh on commit
9a0fbbd71 ("mkdeb.sh.in: pass remaining arguments to ./configure",
2022-05-13) / PR #5154.
Cc: @rusty-snake @sfc-gh-hyu (from #3422)
=> build: mkrpm.sh: append instead of override configure args

etc/profile-a-l/chatterino.profile, etc/profile-a-l/firefox-common-addons.profile, etc/profile-m-z/QMediathekView.profile, etc/profile-m-z/mpv.profile
use case, you install scripts in  `/usr/share/mpv` but they remain inactive. You then symlnk them to `/etc/mpv` to activate them if you want.
Question, isn't `whitelist /usr/share/lua` redundant because of `whitelist /usr/share/lua*` ?
=> mpv: whitelist /usr/share/mpv

src/firejail/fs_lib2.c, src/firejail/x11.c
This reverts commit 407c05ebefe23e725f858b6170b3e52659e044a2.
If --private-lib is used (and firejail is configured with
--enable-private-lib), the following error occurs:
$ firejail --quiet --noprofile --private-lib true
firejail: fs_lib.c:56: find_in_path: Assertion `geteuid() != 0' failed.
Error: proc 10000 cannot sync with peer: unexpected EOF
Peer 10001 unexpectedly killed (Segmentation fault)
Given that it causes an uid assertion failure, the logic appears to not
be correct and the current behavior may be unsafe, so for now revert
that commit until the issue is properly addressed.
Relates to #6006 #6087.
Fixes #6113.
Cc: @chestnykh @hashelq
=> Revert "Lookup xauth in PATH."

etc/inc/allow-lua.inc, etc/profile-a-l/firefox-common-addons.profile, etc/profile-m-z/mpv.profile, etc/profile-m-z/rhythmbox.profile
To ensure that it includes luajit paths as well:
* /usr/share/lua
* /usr/share/luajit-2.1
And remove all entries of the same path without the wildcard, to avoid
redundancy.
Misc: The wildcard entries were added on commit 56b60dfd0 ("additional
Lua blacklisting (#3246)", 2020-02-24) and the entries without the
wildcard were partially removed on commit 721a984a5 ("Fix Lua in
disable-interpreters.inc", 2020-02-24).
This is a follow-up to #6128.
Reported-by: @pirate486743186
=> profiles: use only /usr/share/lua*

src/firecfg/desktop_files.c, src/firecfg/firecfg.h, src/firecfg/main.c, src/man/firecfg.1.in
Currently it is only used when parsing the configuration files:
* /etc/firecfg.d/*.conf
* /etc/firecfg.config
Use it when searching for .profile and .desktop files as well:
* ~/.config/firejail/*.profile
* /usr/share/applications/*.desktop
Closes #5245.
Relates to #5876.
=> firecfg: use ignorelist also for .profile/.desktop files

config.mk.in, src/etc-cleanup/Makefile, src/fbuilder/Makefile, src/fcopy/Makefile, src/fids/Makefile, src/firecfg/Makefile, src/firejail/Makefile, src/firemon/Makefile, src/fldd/Makefile, src/fnet/Makefile, src/fnetfilter/Makefile, src/fnetlock/Makefile, src/fnettrace-dns/Makefile, src/fnettrace-icmp/Makefile, src/fnettrace-sni/Makefile, src/fnettrace/Makefile, src/fsec-optimize/Makefile, src/fsec-print/Makefile, src/fseccomp/Makefile, src/ftee/Makefile, src/fzenity/Makefile, src/include/common.h, src/jailcheck/Makefile, src/lib/Makefile, src/libpostexecseccomp/Makefile, src/libtrace/Makefile, src/libtracelog/Makefile, src/profstats/Makefile, src/prog.mk, src/so.mk
This makes the compile commands clearer when building in parallel (with
`make -j`) and ensures that `__FILE__` includes the full build-time path
(relative to the root of the repository) whenever it is referenced, such
as in failed assert() messages (currently the full path is only shown in
errExit() messages).  Example:
Before:
firejail: main.c:100: main: Assertion `1 == 2' failed.
Error src/firecfg/main.c:100: main: malloc: Cannot allocate memory
After:
firejail: ../../src/firejail/main.c:100: main: Assertion `1 == 2' failed.
Error ../../src/firecfg/main.c:100: main: malloc: Cannot allocate memory
Commands used to search and replace:
$ git grep -Ilz '^MOD_DIR =' -- '*Makefile' | xargs -0 -I '{}' \
sh -c "printf '%s\n' \"\$(sed -E \
-e 's|^MOD_DIR = src/(.*)|MOD = \\1\\nMOD_DIR = …
=> build: use full paths on compile/link targets

etc/profile-m-z/tesseract.profile
Tesseract is a CLI program and its output may be parsed by other
programs (such as `ocrmypdf`).  Including messages from firejail in the
output may break the parsing, so remove them.
Fixes #6171.
Reported-by: @kmille
=> tesseract.profile: add quiet

etc/profile-a-l/crawl.profile
Add common Lua include to crawl.profile (Dungeon Crawl Stone Soup) to allow Lua libraries, as both the ncurses and tiles executables are dynamically linked to Lua.
=> crawl.profile: allow lua

etc/profile-a-l/geeqie.profile
Recent versions of [geeqie](https://www.geeqie.org/) use a LUA interpreter, like the one in Arch Linux (2.2).
Without this fix it fails with:
```
/usr/bin/geeqie: error while loading shared libraries: liblua.so.5.4: cannot open shared object file: Permission denied
```
=> geeqie.profile: allow lua interpreter

.github/workflows/build-extra.yml, .github/workflows/build.yml, .github/workflows/check-c.yml, .github/workflows/check-profiles.yml, .github/workflows/check-python.yml, .github/workflows/codespell.yml, .github/workflows/test.yml, .gitlab-ci.yml
So that they fail early instead of letting them run indefinitely when
there are problems with the CI infrastructure.
Use 5 minutes for the jobs that usually complete in under a minute
(check-profiles and codespell) and 10 minutes for the rest (most jobs
usually take 1-3 minutes).
=> ci: add timeout limits

src/firejail/restrict_users.c
Fix the following CodeQL warning (CWE-253)[1]:
> Rule ID: cpp/incorrectly-checked-scanf
> The result of scanf is only checked against 0, but it can also return
> EOF.
> Functions in the scanf family return either EOF (a negative value) in
> case of IO failure, or the number of items successfully read from the
> input.  Consequently, a simple check that the return value is nonzero
> is not enough.
>
> Recommendation
>
> Ensure that all uses of scanf check the return value against the
> expected number of arguments rather than just against zero.
Note: The affected code portions attempt to read values from /etc/passwd
and /etc/group, so invalid input seems unlikely to be the case.  Either
way, the changes make the checks in question more consistent with
similar sscanf return value checks in …
=> security: fix sscanf rv checks (CodeQL)

.gitignore, Makefile, src/fnettrace/Makefile, test/Makefile
Organize the main clean target and remove more paths on clean.
=> build: improve main clean target

contrib/syntax/lists/profile_commands_arg1.list, etc/inc/landlock-common.inc, etc/templates/profile.template, src/bash_completion/firejail.bash_completion.in, src/firejail/firejail.h, src/firejail/landlock.c, src/firejail/main.c, src/firejail/profile.c, src/firejail/usage.c, src/man/firejail-profile.5.in, src/man/firejail.1.in, src/zsh_completion/_firejail.in
As discussed with @topimiettinen[1], it is unlikely that an unprivileged
process would need to directly create block or character devices.  Also,
`landlock.special` is not very descriptive of what it allows.
So split `landlock.special` into:
* `landlock.makeipc`: allow creating named pipes and sockets (which are
usually used for inter-process communication)
* `landlock.makedev`: allow creating block and character devices
Misc: The `makedev` name is based on `nodev` from mount(8), which makes
mount not interpret block and character devices.  `ipc` was suggested by
@rusty-snake[2].
[1] https://github.com/netblue30/firejail/pull/6078#pullrequestreview-1740569786
[2] https://github.com/netblue30/firejail/pull/6187#issuecomment-1924107294
=> landlock: split .special into .makeipc and .makedev

src/firejail/landlock.c
Recently (as of Landlock ABI 4), the `handled_access_net` field was
added to the `landlock_ruleset_attr` struct in the Linux kernel (in
linux/landlock.h).  In src/firejail/landlock.c, that field is not being
set in the struct (as we currently do not use it) before passing it to
the `landlock_create_full_ruleset` syscall, so it is likely to contain
random garbage when used, resulting in the syscall returning EINVAL:
$ firejail --debug --profile=/etc/firejail/landlock-common.inc \
--landlock.enforce true
[...]
ll_is_supported: Detected Landlock ABI version 4
ll_restrict: Starting Landlock restrict
ll_create_full_ruleset: Creating Landlock ruleset (abi=4 fs=1fff)
Error: ll_create_full_ruleset: failed to create Landlock ruleset (abi=4 fs=1fff): Invalid argument
ll_read: Adding Landlock rule …
=> landlock: fix struct initialization

.gitlab-ci.yml, platform/rpm/mkrpm.sh
This is a follow-up to #6126.
Relates to #297.
=> build: mkrpm.sh improvements

etc/profile-a-l/enchant-lsmod-2.profile
Keep our include logic intact by redirecting to enchant-2.profile.
=> enchant-lsmod-2: redirect to enchant-2

etc/profile-a-l/gnome-keyring-daemon.profile, etc/profile-a-l/gnome-keyring.profile, src/firecfg/firecfg.config
We were missing a profile for gnome-keyring-daemon. Let's bring that in.
Also slightly hardened gnome-keyring.profile.
=> gnome-keyring: harden and add gnome-keyring-daemon.profile

etc/profile-m-z/nextcloud.profile
Relates to https://github.com/netblue30/firejail/discussions/6209.
Additional context:
- created wiki entree on [how to create local D-Bus overrides](https://github.com/netblue30/firejail/wiki/Frequently-Asked-Questions#how-do-i-sandbox-systemd-started-applications)
- edited the [firecfg FAQ](https://github.com/netblue30/firejail/wiki/Frequently-Asked-Questions#how-do-i-undo-firecfg) to make it clear there's native support via firecfg.d now
=> nextcloud: D-Bus filtering changes

src/include/common.h
Move most of the `errExit` macro into a new `_errExit` inline function
and use the former just to forward arguments to the latter.
This reduces the noise in the build output when using `-fanalyzer`, as
it causes the `errExit` macro to stop being expanded.
For example, the complete output of the following warning in
src/firejail/dbus.c is reduced from 243 lines to 141 lines (a ~41%
reduction):
$ pacman -Q gcc
gcc 13.2.1-5
$ ./configure --enable-apparmor --enable-analyzer >/dev/null &&
make clean >/dev/null && make >/dev/null
[...]
../../src/firejail/dbus.c: In function ‘dbus_proxy_start’:
../../src/firejail/dbus.c:311:36: warning: leak of file descriptor ‘dup2(output_fd, 1)’ [CWE-775] [-Wanalyzer-fd-leak]
311 |                                 if (dup2(output_fd, STDOUT_FILENO) != …
=> build: move errExit macro into inline function

etc/profile-a-l/alacarte.profile, etc/profile-a-l/apostrophe.profile, etc/profile-a-l/equalx.profile, etc/profile-a-l/ghostwriter.profile, etc/profile-a-l/gnome-latex.profile, etc/profile-a-l/impressive.profile, etc/profile-a-l/lyx.profile, etc/profile-m-z/menulibre.profile, etc/profile-m-z/okular.profile
Detected a few profiles that include wusc yet still reference paths that are present in that file. This PR drops the 'double' whitelisting from the relevant profiles.
=> profiles: drop paths already in wusc

.github/workflows/check-c.yml, Makefile, config.mk.in, configure, configure.ac, src/bash_completion/Makefile, src/man/Makefile, src/zsh_completion/Makefile
Allow overriding the following tools at configure-time and build-time:
* codespell
* cppcheck
* gawk
* scan-build
For example, instead of hardcoding `gawk`, enable overriding it at
configure-time with:
./configure GAWK=/path/to/gawk
To override it for a single `make` invocation:
make GAWK=/path/to/gawk
Also, add default values for the programs that are not found (rather
than leaving the variables empty), to make error messages clearer when
trying to run them:
$ make CPPCHECK= cppcheck-old
[...]
force --error-exitcode=1 --enable=warning,performance .
make: force: No such file or directory
$ make CPPCHECK=cppcheck cppcheck-old
[...]
cppcheck --force --error-exitcode=1 --enable=warning,performance .
make: cppcheck: No such file or directory
=> build: allow overriding certain tools & sync targets with CI

etc/profile-m-z/multimc5.profile
When starting an instance, in the logs, a failed attempt to load the lwjgl library is shown and the game doesn't run.
The library is in the /tmp directory. The reason for this appears to be, in the lwjgl source code, the shared library loading function, extracts in the temporary directory and continues from there. This is fixed by whitelisting.
The reason for adding "ignore noexec /tmp" as well, is that without it, the game can't run, even if the directory is whitelisted. It seems the library needs to be loaded from /tmp.
A second error for a failed attempt to access /home/user/.cache/JNA is also shown in the logs. This is also fixed by whitelisting.
The errors which inspired the commit:
```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: …
```
=> multimc: instances not running, because of missing permissions

contrib/syntax/lists/profile_commands_arg1.list, etc/inc/landlock-common.inc, etc/templates/profile.template, src/bash_completion/firejail.bash_completion.in, src/firejail/firejail.h, src/firejail/landlock.c, src/firejail/main.c, src/firejail/profile.c, src/firejail/usage.c, src/man/firejail-profile.5.in, src/man/firejail.1.in, src/zsh_completion/_firejail.in
Since Landlock ABI v4 it is possible to restrict actions related to the
network and potentially more areas will be added in the future.
So use `landlock.fs.` as the prefix in the current filesystem-related
commands (and later `landlock.net.` for the network-related commands) to
keep them organized and to match what is used in the kernel.
Examples of filesystem and network access flags:
* `LANDLOCK_ACCESS_FS_EXECUTE`: Execute a file.
* `LANDLOCK_ACCESS_FS_READ_DIR`: Open a directory or list its content.
* `LANDLOCK_ACCESS_NET_BIND_TCP`: Bind a TCP socket to a local port.
* `LANDLOCK_ACCESS_NET_CONNECT_TCP`: Connect an active TCP socket to a
remote port.
=> landlock: use "landlock.fs." prefix in filesystem commands

etc/profile-a-l/ledger-live-desktop.profile
This is a profile for the [Ledger Live wallet](https://www.ledger.com/ledger-live).
I based it off the profile offered in #3595, but it needed several tweaks for it to work.
I tested the binary installation in /opt (I use the [ledger-live-bin package in AUR](https://aur.archlinux.org/packages/ledger-live-bin)). Ledger Live is also offered as an AppImage, but I didn't test that case.
I own a Ledger USB wallet and this profile is working for me.
=> Profile for Ledger Live desktop app

.github/workflows/build-extra.yml, .github/workflows/build.yml, .github/workflows/check-c.yml, .github/workflows/test.yml, .gitlab-ci.yml, Makefile, contrib/update_deb.sh, gcov.sh, mkdeb.sh, platform/rpm/mkrpm.sh, src/tools/mkcoverit.sh, test/compile/compile.sh
Main changes:
* build: reduce TARNAME hardcoding
* build: standardize parallel make arguments
* build: standardize ./configure arguments
Relates to #5148 #5960 #6224.
This is a follow-up to #6222.
=> build: reduce hardcoding and inconsistencies

etc/profile-a-l/gnome-boxes.profile
Restrict access to /usr/libexec.
=> gnome-boxes: deny access to /usr/libexec

etc/profile-a-l/atool.profile, etc/profile-a-l/bsdtar.profile, etc/profile-m-z/tar.profile, etc/profile-m-z/unrar.profile, etc/profile-m-z/unzip.profile
Commit https://github.com/netblue30/firejail/commit/29da82d08aab5120262f42032fed6dc7807e5b0d added `private-etc` to `archiver-common.profile`. To avoid doubled options this PR removes it from archiver profiles which already had it.
Relates to #5610.
=> archivers: drop private-etc now that it's in archiver-common

etc/profile-a-l/archiver-common.profile
[mkinitcpio](https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio) (used to generate initramfs images) supports [several compression formats](https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/blob/master/mkinitcpio.conf#L54-L64). On Arch Linux (based distributions) at least this implies the supported archivers to have access to mkinitcpio-related files under /etc.
This was no problem before https://github.com/netblue30/firejail/commit/29da82d08aab5120262f42032fed6dc7807e5b0d added `private-etc` to `archivers-common.profile`. This PR adds the now needed extra private-etc items to mkinitcpio's supported compressors.
Relates to #5610.
Side-note: mkinitcpio also supports `lz4` compression. I was a bit surprised to notice we don't have a profile for that yet. I'll add one …
=> archiver-common: add mkinitcpio support to private-etc

etc/profile-m-z/ssh.profile
Since gnome-keyring 1.46 the ssh-agent functionality has been removed and gcr-ssh-agent is the recommended alternative.
Source:
- https://gitlab.gnome.org/GNOME/gcr/-/merge_requests/67
- https://wiki.archlinux.org/title/GNOME/Keyring#SSH_keys
NOTE: @glitsj16 suggested to put the whitelist statement inside `whitelist-runuser-common.inc`, but since `whitelist-runuser-common.inc` is in this file, I think it makes more sense to leave it right after it.
=> ssh: whitelist gcr-ssh-agent unix socket

etc/inc/disable-programs.inc, etc/profile-m-z/qt5ct.profile, etc/profile-m-z/qt6ct.profile
Blacklisting qt5ct/qt6ct configuration and data paths breaks styling in all apps that use them. This was working as expected before #6249 and #6250, let's restore this for both apps.
=> profiles: remove blacklisting of qt5ct/qt6ct paths

src/firecfg/firecfg.config
Floorp Browser is already having a profile (floorp.profile) but the firecfg.config doesn't have a entry for floorp. As a result `sudo firecfg` was not creating firejail symlinks for floorp.
=> firecfg.config: add floorp

contrib/sort.py, etc/profile-a-l/dnscrypt-proxy.profile
Note: This seems to already be done for `protocol` lines.
Before:
$ ./contrib/sort.py test.profile
sort.py: checking 1 profile(s)...
test.profile:1:-private-etc ,,bar,,foo,,bar,,,
test.profile:1:+private-etc ,,,,,,,bar,bar,foo
test.profile:2:-protocol ,,unix,,bluetooth,,unix,,inet,,,
test.profile:2:+protocol unix,inet,bluetooth
[ Fixed ] test.profile
After:
$ ./contrib/sort.py test.profile
sort.py: checking 1 profile(s)...
test.profile:1:-private-etc ,,bar,,foo,,bar,,,
test.profile:1:+private-etc bar,foo
test.profile:2:-protocol ,,unix,,bluetooth,,unix,,inet,,,
test.profile:2:+protocol unix,inet,bluetooth
[ Fixed ] test.profile
=> build: sort.py: filter empty and duplicate items

etc/apparmor/firejail-local, etc/profile-m-z/torbrowser-launcher.profile
Apparently Tor Browser 13.0.11 (based on Mozilla Firefox 115.8.0esr)
changed a few things. The former versions installed under
`${HOME}/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser`
and now under
`${HOME}/.local/share/torbrowser/tbb/x86_64/tor-browser/Browser`.
All of our tor-browser-foo.profile profiles redirect to
torbrowser-launcher.profile and are covered by the fixes.
torbrowser.profile was not tested. It redirects to
firefox-common.profile and seems to be Gentoo-specific.
Fixes #6269.
=> torbrowser-launcher fixes

etc/profile-m-z/qt6ct.profile
Add support for qt6ct packages that use XDG desktop portal.
https://github.com/MikeWalrus/qt6ct#branch=colorscheme-portal
https://aur.archlinux.org/packages/qt6ct-xdg-colorscheme-git
=> qt6ct: add dbus-filtering rules

src/man/firecfg.1.in
Based on the discussion at #5063.
Misc: The `\&` is used to escape the dot in `.desktop` (see roff(7)).
This amends commit a9c851ee4 ("firecfg: use ignorelist also for .desktop
files", 2024-01-08) / PR #6153.
=> docs: firecfg: note different .desktop naming schemes

etc/profile-a-l/editorconfiger.profile, src/firecfg/firecfg.config
editorconfiger
Description: Plain tool to validate and compare .editorconfig files.
https://github.com/aegoroff/editorconfiger
https://aur.archlinux.org/packages/editorconfiger
https://aur.archlinux.org/packages/editorconfiger-bin
=> New profile: editorconfiger

etc/profile-m-z/mimetype.profile
mimetype
Description: Determines the file type.
https://metacpan.org/release/File-MimeInfo
https://archlinux.org/packages/extra/any/perl-file-mimeinfo/
=> New profile: mimetype

etc/profile-a-l/k3b.profile
@hedgehog29 commented[1]:
> It prevents k3b from detecting all dvd drives, incudling USB ones, and
> it seems that also SATA.
Fixes #6279.
[1] https://github.com/netblue30/firejail/issues/6279#issue-2191392448
=> k3b.profile: fix dvd drive detection (private-dev)

etc/profile-m-z/tqemu.profile, src/firecfg/firecfg.config
tqemu
Description: QEMU frontend without libvirt.
https://github.com/thanoulis/tqemu
=> New profile: tqemu

etc/profile-a-l/dropbox.profile, etc/profile-a-l/gitter.profile, etc/profile-m-z/meteo-qt.profile
The files in this directory are intended to be automatically executed
when the user logs in.
In which case, granting write access to this directory allows the
program to easily escape the sandbox (by autostarting itself outside of
firejail, for example).
Misc: This was noticed on #6244.
=> profiles: deny access to ~/.config/autostart

etc/profile-a-l/firefox.profile
Turning this into a PR as per <https://github.com/netblue30/firejail/issues/1139#issuecomment-2014916426>.
I recently set up KDE connect and plasma-browser-integration for firefox (Linux Mint 21.2) and needed this line in addition to the ones mentioned in the profile. Found it via running `firejail --profile=/etc/firejail/firefox.profile --dbus-user.log firefox`, trying to send links to device, and seeing what events get logged.
(I also needed `ignore dbus-user none` in `firefox-common.local`, which is mentioned in a comment already. I'm not using `private-bin` for firefox.)
Ideally I'd want someone to test this and confirm they also require this line for plasma-browser-integration to work; possibly it's platform- or version-specific.
=> firefox: Add org.kde.kdeconnect to plasma integration comment

etc/profile-m-z/qemu-common.profile, etc/profile-m-z/qemu-launcher.profile, etc/profile-m-z/qemu-system-x86_64.profile, etc/profile-m-z/tqemu.profile
Add a common profile to deduplicate entries and make qemu-related
profiles redirect to it.
Relates to #6255.
=> New profile: qemu-common.profile

contrib/sort.py
Similarly to `sed -i` and `perl -i`.
This allows checking if sort.py correctly sorts the relevant lines in a
profile without having to overwrite it, which makes debugging and
testing easier (for example, in #6261).
Note: If it finds items that are not sorted, it still sorts them, prints
the diff and returns an error.
=> build: sort.py: add and require -i to edit in-place

etc/profile-a-l/bpftop.profile, etc/profile-a-l/cloneit.profile, etc/profile-a-l/deadlink.profile, etc/profile-a-l/dexios.profile, etc/profile-a-l/editorconfiger.profile, etc/profile-a-l/kdiff3.profile, etc/profile-m-z/makepkg.profile, etc/profile-m-z/statusof.profile, etc/profile-m-z/textroom.profile, etc/profile-m-z/torbrowser.profile, etc/profile-m-z/tvnamer.profile
See etc/templates/profile.template.
This is a follow-up to #6286.
=> profiles: sort blacklist sections

etc/profile-m-z/rssguard.profile, etc/templates/profile.template
To make it consistent with the other include profiles.
See etc/templates/profile.template.
Relates to #3866 #5881.
=> profiles: add allow-nodejs.inc to profile.template

etc/templates/profile.template
To make it consistent with the other include profiles.
See etc/templates/profile.template.
Note: It is not currently included in any profile.
Added on commit 89f30f1f2 ("Create allow-php.inc", 2020-01-25).
This is a follow-up to #6298.
=> profiles: add allow-php.inc to profile.template

src/firejail/firejail.h, src/firejail/landlock.c, src/firejail/profile.c
Changes:
* Always declare public landlock functions, regardless of
`HAVE_LANDLOCK`
* Make the other public landlock functions (besides `ll_add_profile`)
also be empty when `HAVE_LANDLOCK` is not defined
* Clarify related comments
This amends commit 8259f66e1 ("landlock fix for old kernel versions",
2024-04-06).
For clarity, landlock-common.inc is included by default.profile and the
issue that the aforementioned commit fixes is that if profile.c is built
without the part that parses landlock commands (that is, when
`HAVE_LANDLOCK` is not defined), using default.profile would cause
firejail to abort due to "invalid lines".
Note that the issue would only occur when firejail is built with an
older kernel (or with --disable-landlock), not when simply running on an
older kernel.
See also commit …
=> landlock: amend empty functions and comments

src/man/firejail-profile.5.in, src/man/firejail.1.in
=> docs: warn about limitations of landlock

etc/inc/allow-ssh.inc
=> profiles: allow-ssh: allow /etc/ssh/ssh_revoked_hosts

etc/profile-a-l/audacity.profile
Newly release audacity 3.5 supports cloud-saving and remote backup features:
- https://www.audacityteam.org/blog/audacity-3-5/
- https://support.audacityteam.org/additional-resources/changelog/audacity-3.5#cloud-project-saving
=> profiles: audacity: allow networking by default

etc/profile-a-l/loupe.profile, src/firecfg/firecfg.config
works but can be improved
loupe opens each image in its own sandbox using bwrap if available
largely copy/pasted from eo-common
=> profiles: add loupe

etc/profile-a-l/d-spy.profile, src/firecfg/firecfg.config
d-spy
D-Bus debugger for GNOME
https://gitlab.gnome.org/GNOME/d-spy
https://wiki.gnome.org/Apps/DFeet
D-Feet is no longer maintained. Please use d-spy
=> New profile: d-spy

etc/profile-a-l/loupe.profile
The profile currently does not include disable-common nor makes
`${HOME}` read-only, so the program can simply write to ~/.bashrc
directly[1].
disable-common.inc was commented due to it apparently breaking bwrap.
As discovered by @glitsj16, it seems that allowing the bwrap binary is
enough to make it work (and that apparmor breaks loupe)[2].
So disable apparmor, allow bwrap and include disable-common.inc, plus
other hardening by @glitsj16.
This amends commit 9a0db13e1 ("profiles: add loupe", 2024-04-30) /
PR #6327.
[1] https://github.com/netblue30/firejail/pull/6327#pullrequestreview-2033860865
[2] https://github.com/netblue30/firejail/pull/6333#issuecomment-2099805480
=> profiles: loupe: harden and disable apparmor

etc/profile-m-z/steam.profile
Update comment to account for camera-based motion trackers.
Fixes an issue with https://github.com/markx86/opentrack-launcher, where
video input devices won't show up unless novideo is removed.
=> profiles: steam: update novideo comment for webcam motion trackers

etc/inc/disable-programs.inc, etc/profile-m-z/nhex.profile, src/firecfg/firecfg.config
nhex
Description: Tauri-based IRC client inspired by HexChat.
https://nhexirc.com/
https://github.com/nhexirc/nhex
=> New profile: nhex

.github/dependabot.yml
It is currently only used for GitHub Actions.  The ones used in this
project rarely ever contain notable changes in their changelogs (in a
way that would cause a noticeable difference in our CI).
Also, there are weeks when most/all of the PR/commit activity is from
dependabot PRs being opened/merged.  For example, see the output of the
following command:
git log --no-decorate --oneline 9a0db13e12..bef085035
So change the checks from weekly to monthly to reduce the noise.
Additionally, bump `open-pull-requests-limit` to 4, as it seems that we
only have 4 dependencies:
$ git grep 'uses:' -- .github/ | sed -E 's/.*(uses: .*)@.*/\1/' |
LC_ALL=C sort -u
uses: actions/checkout
uses: github/codeql-action/analyze
uses: github/codeql-action/init
uses: step-security/harden-runner
This should ensure …
=> ci: make dependabot updates monthly and bump PR limit

contrib/sort.py
Overwrite in-place by default (`-i`) and add `-n` to override it.
This restores the previous default behavior (from 0.9.72), for the sake
of being consistent with all previous versions and because it's more
likely to be the desired behavior in most cases.
This amends commit aa08aa132 ("build: sort.py: add and require -i to
edit in-place (#6290)", 2024-03-25).
* build: sort.py: support "--" and fail on unknown option
Support "--" to end options and fail if an unknown option is given.
=> build: sort.py: use -i by default and add -n

Makefile
* build: add a standalone strip target
Move the strip invocation into its own target to allow stripping
binaries without having to run the "realinstall" target.
* build: remove redundant realinstall target
Leave just the "install" and "install-strip" targets.
See commit 099925e18 ("added install-strip, make install now without
strip.", 2015-09-10) / PR #60 and commit 0215cbc02 ("make install, make
install-strip", 2015-09-11).
=> build: add strip target and simplify install targets

Makefile
Cleaning does not appear to make a difference; the same amount of files
is checked with/without cleaning.
Environment: cppcheck 2.12.0-3 on Artix Linux.
Added on commit 4e22add64 ("llvm scan", 2015-11-29).
This is a follow-up to #6222.
=> build: remove clean dependency from cppcheck targets

etc/profile-a-l/electron-mail.profile, etc/profile-a-l/email-common.profile, etc/profile-a-l/fluffychat.profile, etc/profile-a-l/geary.profile, etc/profile-a-l/gtk-youtube-viewers-common.profile, etc/profile-a-l/kube.profile, etc/profile-a-l/lettura.profile, etc/profile-a-l/linuxqq.profile, etc/profile-m-z/signal-desktop.profile, etc/profile-m-z/thunderbird.profile, etc/profile-m-z/trojita.profile, etc/profile-m-z/tutanota-desktop.profile, etc/profile-m-z/zeal.profile
Changes:
* Improve Firefox D-Bus comment
* Add missing/standardize related comments
* Include allow-bin-sh.inc in relevant profiles
* Use Firefox URL open section in relevant profiles
=> profiles: streamline Firefox URL opening support

etc/profile-a-l/libreoffice.profile
Based on the entries in etc/profile-m-z/makepkg.profile.
This fixes #6352.
=> profiles: libreoffice: support signing documents with GPG

src/fids/main.c, src/firecfg/desktop_files.c, src/firejail/bandwidth.c, src/firejail/fs_home.c, src/firejail/ids.c, src/firejail/run_files.c, src/firejail/util.c, src/firemon/netstats.c, src/jailcheck/access.c, src/jailcheck/noexec.c, src/jailcheck/virtual.c
Fix memory and descriptor leaks.
=> bugfix: fix various resource leaks

etc/inc/disable-programs.inc, etc/profile-a-l/armcord.profile, src/firecfg/firecfg.config
ArmCord
Standalone Discord client
https://armcord.app/
https://github.com/NextWork123/ArmCord
Requested in https://github.com/netblue30/firejail/issues/1139#issuecomment-2140174880.
=> New profile: armcord

etc/inc/disable-common.inc, etc/inc/disable-programs.inc, etc/profile-a-l/i3.profile
This closes the escape route discussed in https://github.com/netblue30/firejail/discussions/6357.
It's left open for i3's own profile, so that people who run i3 itself sandboxed still have the option to use IPC with it at all.
Reference for file paths: https://i3wm.org/docs/userguide.html#_interprocess_communication
=> profiles: blacklist i3 IPC socket & dir except for i3 itself

src/man/firejail.1.in
This should resolve or at least begin to resolve issues mentioned in #6358.
Fixes #6358.
=> docs: add precedence info to manpage & fix noblacklist example

Makefile
For increased consistency and readability.
See also commit dae3933 ("rework make realinstall and uninstall
(#3435)", 2020-06-04).
Relates to #3435 #4628.
Cc: @rusty-snake @smitsohu
=> build: standardize install commands

.github/ISSUE_TEMPLATE/bug_report.md
We still see lots of issue reports where the user runs `firejail foo` and ends up running foo's sandbox twice (due to firecfg's symlink precedence). Try to improve the situation by explicitly using absolute paths in the 'steps to reproduce' section.
=> docs: bug_report.md: use absolute path in 'steps to reproduce'

etc/profile-a-l/claws-mail.profile
=> profiles: claws-mail: note no3d issue with "fancy" plugin

src/firejail/fs_dev.c
Apparently hashcat needs access to this device for hardware acceleration
on AMD gpus and `private-dev` currently breaks that (see #6364).
It seems to be used by the "amdgpu" and "amdkfd" Linux kernel drivers
and as with /dev/dri/renderD128, this file is owned by the "render"
group.
Relevant udev rules from /usr/lib/udev/rules.d/50-udev-default.rules:
SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="render", MODE="0666"
SUBSYSTEM=="kfd", GROUP="render", MODE="0666"
SUBSYSTEM=="accel", GROUP="render", MODE="0666"
Environment: udev 255.6-1 on Artix Linux.
Reported-by: @schrotthaufen
=> modif: private-dev: keep /dev/kfd unless no3d is used

etc/profile-m-z/noprofile.profile, src/firejail/fs.c
It has been reported in #6372 that after upgrading the nvidia
proprietary driver from version 550.78 to 550.90.07, programs using
hardware acceleration fail unless paths in `/sys/module/nvidia*` are
accessible.  Example:
$ firejail --noprofile prime-run /bin/glxdemo
[...]
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  150 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  22
Current serial number in output stream:  23
[...]
Meanwhile, the AMD proprietary driver (AMDGPU Pro) seems to depend on
`/sys/module/amdgpu` for OpenCL (though it is unclear how to detect that
driver).  See commit 95c8e284d ("Allow accessing /sys/module directory", …
=> modif: keep /sys/module/nvidia* if prop driver and no no3d

etc/inc/disable-programs.inc, etc/profile-a-l/claws-mail.profile
It is apparently used by the (widely used) "Fancy" plugin, which
"Renders HTML e-mail using the WebKit library".
https://www.claws-mail.org/plugins.php
Relates to #6377.
Note: etc/profile-a-l/email-common.profile contains `private-cache`.
=> profiles: claws-mail: add ~/.cache/claws-mail 

etc/inc/disable-programs.inc, etc/profile-a-l/fractal.profile
I'm on Arch using Fractal 7 and firejail 0.9.72. Even after fixing #6119, using Fractal with firejail would either not work (without Internet access) or show me "Crypto identity incomplete" when using it with, as it stores (encrypted) messages and key material in ~/.local/share/fractal.
This patch fixes that issue for me. Let me know if you'd like me to open an issue first to discuss the problem there before accepting a pull request, or if you have any advice or improvements.
=> profiles: fractal: add ~/.local/share/fractal

src/man/firejail-profile.5.in, src/man/firejail.1.in
Format and sort items in the private-bin, private-dev and private-etc
sections.
=> docs: man: format and sort some private- items

contrib/syntax/lists/profile_commands_arg0.list, etc/profile-a-l/default.profile, etc/templates/profile.template, src/fbuilder/build_profile.c, src/firejail/firejail.h, src/firejail/fs_dev.c, src/firejail/main.c, src/firejail/profile.c, src/firejail/sandbox.c, src/firejail/usage.c, src/man/firejail-profile.5.in, src/man/firejail.1.in, src/zsh_completion/_firejail.in
An ssh private key may be stored in a Trusted Platform Module (TPM)
device and `private-dev` in ssh.profile currently breaks this use-case,
as it does not keep tpm devices (see #6379).
So add a new `notpm` command and keep tpm devices in /dev by default
with `private-dev` unless `notpm` is used.
Tested locally with:
```
❯ /usr/local/bin/firejail --private-dev --noprofile stat /dev/tpm0
firejail version 0.9.73
Parent pid 34059, child pid 34060
Base filesystem installed in 0.03 ms
Child process initialized in 13.23 ms
File: /dev/tpm0
Size: 0         	Blocks: 0          IO Block: 4096   character special file
Device: 0,6	Inode: 150         Links: 1     Device type: 10,224
Access: (0600/crw-------)  Uid: (  973/     tss)   Gid: (  973/     tss)
Access: 2024-06-22 11:20:44.017230197 +0200 …
```
=> feature: add notpm command & keep tpm devices in private-dev

src/firejail/usage.c, src/zsh_completion/_firejail.in
This command is deprecated and may be confused for a hardening option.
This amends commit 5a612029b ("rename noautopulse to keep-config-pulse",
2021-05-13) / PR #4278.
This is a follow-up to #6390.
=> modif: remove --noautopulse from --help and zsh comp

src/man/mkman.sh
Changes:
* Use the exact same source date string for all `date` invocations
* Use `-d` instead of `--date=`
* Fallback to `-r` and then to no argument
Some `date` implementations only support BSD `-r` instead of GNU `-d` /
`--date=` and others may not support any of them since neither option is
in POSIX.
For example, if zoneinfo is installed by chromebrew on ChromeOS, it
provides a date program that only supports `-r` and overrides the system
one (which supports `-d`) [1]:
./mkman.sh 0.9.72 src/man/firejail.man firejail.1
date: invalid option -- '-'
date: usage: date [-u] [-c] [-r seconds] [+format]
make: *** [Makefile:42: firejail.1] Error 1
Environment: zoneinfo 2024a on ChromeOS M125.
Note: The changes are based on what is suggested by
reproducible-builds.org [2].
Relates to #193. …
=> build: improve reliability/portability of date command usage

src/firemon/procevent.c
The coredump-related code fails to build on Linux kernel version 3.8 as
apparently it only exists on Linux since version 3.10:
docker run --platform linux/386 --rm -it satmandu/crewbuild:386
[...]
./configure && make
[...]
gcc -ggdb -O2 -DVERSION='"0.9.73"' [...] -march=i686  -c ../../src/firemon/procevent.c -o ../../src/firemon/procevent.o
../../src/firemon/procevent.c: In function ‘procevent_monitor’:
../../src/firemon/procevent.c:399:38: error: ‘PROC_EVENT_COREDUMP’ undeclared (first use in this function); did you mean ‘PROC_EVENT_COMM’?
399 |                                 case PROC_EVENT_COREDUMP:
|                                      ^~~~~~~~~~~~~~~~~~~
|                                      PROC_EVENT_COMM
../../src/firemon/procevent.c:399:38: note: each undeclared identifier is …
=> bugfix: firemon: skip coredump if unsupported

src/firecfg/firecfg.config
There are various reports in #5127 that the current profile is broken on
wayland (and at least one report that it is broken on xorg as well).
Relates to #6268.
=> profiles: firecfg.config: disable spectacle

etc/profile-a-l/bijiben.profile, src/firecfg/firecfg.config
The current `bijiben.profile` sets an environment variable to disable
its internal webkit/bubblewrap sandbox but now a different variable
needs to be set[1]:
WEBKIT_FORCE_SANDBOX no longer allows disabling the sandbox. Use WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1 instead.
This may be needed to make the profile work, but disabling the sandbox
affects the security in webkit[2], so update the variable and disable
bijiben by default in firecfg.config.
Note: Upstream replaced bijiben by gnome-notes[3] [4].
Relates to #2995.
[1] https://github.com/WebKit/WebKit/blob/0678a98c864ee36f0114ea4e7d303fd07788a822/Source/WebKit/UIProcess/Launcher/glib/ProcessLauncherGLib.cpp#L117
[2] https://github.com/netblue30/firejail/issues/2995
[3] https://archlinux.org/packages/extra/x86_64/gnome-notes/
[4] …
=> profiles: bijiben: update webkit var and disable in firecfg

etc/profile-a-l/d-feet.profile, etc/profile-a-l/d-spy.profile, etc/profile-a-l/dbus-debug-common.profile
There are a lot of common options in the `d-feet` and `d-spy` profiles.
Create a new common include file and refactor the existing profiles as
redirects.
Relates to #2492 #6328.
=> profiles: refactor dbus debugger profiles

etc/profile-a-l/element-desktop.profile
This path is apparently needed on openSUSE Tumbleweed[1]:
$ LC_ALL=C firejail /usr/bin/element-desktop
[...]
Error launching app
Unable to find Electron app at /usr/share/element/app
Cannot find module '/usr/share/element/app'
Parent is shutting down, bye...
Fixes #6421.
[1] https://software.opensuse.org/package/element-desktop
Reported-by: @leukimi
=> profiles: element-desktop: allow /usr/share/element

etc/inc/disable-common.inc, etc/profile-m-z/sway.profile
Much like the i3 IPC socket (#6361), the sway IPC socket also allows arbitrary code execution via the `exec` subcommand (i.e. `swaymsg exec 'echo test > ~/test'`) . Access should only be permitted to sway itself by default.
The location of the IPC socket is set in [sway/ipc-server.c](https://github.com/swaywm/sway/blob/7e74a4914261cf32c45017521960adf7ff6dac8f/sway/ipc-server.c#L126):
```
const char *dir = getenv("XDG_RUNTIME_DIR");
if (!dir) {
dir = "/tmp";
}
if (path_size <= snprintf(ipc_sockaddr->sun_path, path_size,
"%s/sway-ipc.%u.%i.sock", dir, getuid(), getpid())) {
sway_abort("Socket path won't fit into ipc_sockaddr->sun_path");
}
```
=> profiles: blacklist sway IPC socket

etc/profile-m-z/ssh.profile
If a custom GPG homedir is used, a hash of its path is used in the path
of the gpg agent socket[1].
For example, when running:
gpgconf --list-dirs agent-ssh-socket
With a custom homedir it returns:
/run/user/1000/gnupg/<hashed homedir>/S.gpg-agent.ssh
Environment: gnupg 2.4.5-4 on Arch Linux.
[1] https://github.com/gpg/gnupg/blob/91532dc3f40599b74fff489cb021c0cd3344ae60/common/homedir.c#L1342
=> profiles: ssh: allow gpgagent socket for custom homedir

etc/profile-a-l/abrowser.profile, etc/profile-a-l/basilisk.profile, etc/profile-a-l/cachy-browser.profile, etc/profile-a-l/cliqz.profile, etc/profile-a-l/cyberfox.profile, etc/profile-a-l/firefox-common-addons.profile, etc/profile-a-l/icecat.profile, etc/profile-a-l/iceweasel.profile, etc/profile-a-l/librewolf.profile, etc/profile-m-z/palemoon.profile, etc/profile-m-z/waterfox.profile
It was enabled in firefox-common.inc on commit 34d004892 ("private-etc:
corss-distro test for curl, gimp, inkscape, firefox, warzone2100",
2023-01-28), but not in the profiles that include it.
Enable it in the including profiles as well.
Note: This was already done for firefox.profile on commit 76249284f
("firefox: fix private-etc firefox", 2023-06-02) / PR #5844.
Relates to #6400.
=> profiles: firefox-common: fix private-etc in includers

etc/profile-a-l/bitwarden-desktop.profile, etc/profile-a-l/bitwarden.profile, src/firecfg/firecfg.config
Changes:
- Allow shell access (bitwarden-desktop may be a shell script)
- Enable whitelist-usr-share-common.inc
- Introduce a new redirect for bitwarden-desktop
- Add the new redirect to firecfg
Relates to #6442.
=> profiles: bitwarden: improvements and new bitwarden-desktop redirect

src/man/firejail-profile.5.in, src/man/firejail.1.in
Sort commands in firejail.1.in and sync the result with
firejail-profile.5.in.
* Commands: `--dbus-system.*`, `--dbus-user.*`, `--icmptrace`,
`--ip=none`, `memory-deny-write-execute`, `--noinput`
Relates to #3190 #3406 #4209.
=> docs: man: sort commands (firejail.1)

src/man/firejail-profile.5.in, src/man/firejail.1.in
Reset the bold right after each command/argument.
Command used to check for issues:
git grep -E ' \\fR' -- src/man/*.in
* e91b9ff0f ("Deprecate --nodbus option", 2020-04-07) /
PR #3265
* 5a612029b ("rename noautopulse to keep-config-pulse", 2021-05-13) /
PR #4278
* d79547ca9 ("docs: warn about limitations of landlock", 2024-03-31) /
PR #6302
This is a follow-up to #6451.
=> docs: man: fix bold in command TPs

src/man/firejail-profile.5.in, src/man/firejail.1.in
Remove extranous escape characters and fix bold escaping.
Command used to check for unusual escape sequences:
$ git grep -E -e '\\f[^BR]' -e '\\[^ "\f-]' -- src/man/*.in
With this, the only escape sequences used are:
$ git grep -E -ho -e '\\-' -e '\\[^-][^ ]?' -- src/man/*.in |
LC_ALL=C sort | uniq -c
9 \"
1 \&.
1194 \-
23 \\
507 \fB
127 \fR
* 137985136 ("Baseline firejail 0.9.28", 2015-08-08)
* 1684c9ea7 ("Fixes for man firejail (#2628)", 2019-03-29)
* 73525015e ("Clarify that file globbing occurs only at start",
2020-04-11) / PR #3347
* f54ee53b1 ("man text for --include command", 2021-03-05).
This is a follow-up to #6472.
Kind of relates to #5903.
=> docs: man: fix wrong escapes

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/build_issue.md, .github/ISSUE_TEMPLATE/feature_request.md
Changes:
* Sync bug_report.md with build_issue.md (reword items and add Linux
kernel item)
* Add a colon to the end of every item (to clarify where to add the
information)
* Add the Environment section to feature_request.md
The last item is intended as a basic sanity check, as users using an
outdated version of firejail may request something that was already
implemented (for example, see #6461).
Relates to #4515 #6423.
=> docs: github: streamline environment in issue templates

etc/inc/disable-programs.inc, etc/profile-a-l/ffmpeg.profile, etc/profile-a-l/handbrake.profile, etc/profile-m-z/mplayer.profile, etc/profile-m-z/mpv.profile, etc/profile-m-z/smplayer.profile, etc/profile-m-z/totem.profile, etc/profile-m-z/vlc.profile
It's used by libdvdcss (which is used to play copy-restricted dvds).
It seems to be just a cache directory, so just allow without mkdir.
Relates to #5391.
Suggested-by: @reinerh
=> profiles: video: add ~/.dvdcss

etc/inc/disable-programs.inc, etc/profile-a-l/evolution.profile
These paths are apparently used for attachments.
Disable private-tmp to make it easier to open attachments with external
programs.
Relates to #5101.
Reported-by: @githlp
Suggested-by: @rusty-snake
=> profiles: evolution: add /tmp/evolution-* & disable private-tmp

etc/profile-a-l/librewolf.profile
It appears that LibreWolf 129 uses `io.gitlab.firefox.*` as the dbus
name.
Commands used to check the dbus name:
$ busctl --user --no-legend | grep -v '^:' | grep librewolf |
sed -E 's/(^[^ ]+\.)[^. ]+ .*/\1/'
io.gitlab.firefox.
Commands used to test dbus communication:
$ firejail --name=lwtest --ignore=name --ignore='dbus-user none' \
--dbus-user=filter --dbus-user.own='io.gitlab.firefox.*' \
--private --net=none --ignore=net /usr/bin/librewolf
$ firejail --join=lwtest /usr/bin/librewolf --new-tab about:blank
* c3f299620 ("Let programs outside librewolf sandbox open new tabs in
librewolf (#4546)", 2021-09-19)
* a8ad9cad1 ("Update librewolf.profile: use new message bus",
2022-02-03) / PR #4897
* 4211ee323 ("merges", 2022-02-04)
Fixes #6413.
Misc: This was noticed on …
=> profiles: librewolf: add new dbus name (io.gitlab.firefox)

etc/profile-m-z/wesnoth.profile
Fixes the following error:
$ LC_ALL=C firejail /usr/bin/wesnoth
[...]
/usr/bin/wesnoth: error while loading shared libraries: liblua++.so.5.4: cannot open shared object file: Permission denied
Environment: lua 5.4.7-1, wesnoth 1:1.18.2-2 on Arch Linux.
Fixes #6475.
Reported-by: @marek22k
=> profiles: wesnoth: allow lua

etc/profile-m-z/QOwnNotes.profile, etc/profile-m-z/nextcloud.profile
* 7c481eb43 ("Add QOwnNotes profile", 2018-10-20)
* 49a381c70 ("Add nextcloud-desktop", 2021-02-20) / PR #3997
Fixes #5877.
Reported-by: @Sadoon-AlBader
=> profiles: nextcloud: fix access to ~/Nextcloud

etc/profile-m-z/ssh.profile
Based on the report by @Saren-Arterius[1]:
Since GNOME gvfs 1.53+, the ssh client options `ControlMaster=auto` and
`ControlPath=/run/user/$UID/gvfsd-sftp/%C` are used to mount sftp.
Since `/run/user/$UID/gvfsd-sftp` is not whitelisted, gvfs sftp mount
with nautilus will fail with a meaningless error message shown in the
UI.
Steps to reproduce[1]:
Prepare ssh server or localhost, then run:
ssh -o"ForwardX11 no" -o"ForwardAgent no" \
-o"PermitLocalCommand no" -o"ClearAllForwardings yes" \
-o"NoHostAuthenticationForLocalhost yes" \
-o"ControlMaster auto" \
-o"ControlPath=/run/user/${UID}/gvfsd-sftp/test" \
-s {SSH_HOST} sftp
stderr shows:
unix_listener: cannot bind to path /run/user/$UID/gvfsd-sftp/test.{RANDOM_STRING}: No such file or directory
And ssh exits with error code 255.
Fixes …
=> profiles: ssh: add ${RUNUSER}/gvfsd-sftp

src/firecfg/firecfg.config
Disable common general-purpose text editors.
They are likely to be the default OS text editor and users may want to
use them for editing most/all files, which could include common
sensitive files such as ~/.bashrc and profiles in ~/.config/firejail.
Fixes #6002.
Relates to #924 #941 #1154.
Reported-by: @ilikenwf
=> profiles: firecfg: disable text editors

etc/profile-a-l/cachy-browser.profile, etc/profile-a-l/chromium-common.profile, etc/profile-a-l/firefox-common-addons.profile, etc/profile-a-l/firefox-common.profile, etc/profile-a-l/firefox.profile, etc/profile-a-l/floorp.profile, etc/profile-a-l/librewolf.profile
Relates to:
* #3014
* #3326
* #3984
* #6285
* #6391
* #6444
=> profiles: browsers: centralize/sync/improve comments

etc/profile-a-l/chromium-common.profile, etc/profile-a-l/firefox-common-addons.profile, etc/profile-a-l/firefox-common.profile, etc/profile-a-l/keepassxc.profile
KeePassXC browser extension look for KeePassXC socket in the /run/user/app directory (https://github.com/keepassxreboot/keepassxc/blob/6b1ab1a5edd66ac10706a2fb5af34ec9458a901d/src/browser/BrowserShared.cpp#L41).
Unfortunately, /run/user/app seems to be blacklisted in disable-common.inc under the flatpak section (https://github.com/netblue30/firejail/blob/b89ec818926b4bcd3a58bb4e2a67b68a8090ba1c/etc/inc/disable-common.inc#L667), as a result, KeePassXC extension cannot find a socket.
Fixes #5447.
Relates to:
* #3952
* #3984
* #4213
=> profiles: keepassxc: add new socket location

etc/profile-m-z/signal-desktop.profile
Signal recently started storing a local key in the freedesktop.org secret API so allow access in the profile
Also see https://github.com/signalapp/Signal-Desktop/issues/6970
=> profiles: signal-desktop - Add access to D-Bus freedesktop.org secret API

etc/profile-a-l/firefox-common.profile
This fixes drag and drop for at least Dolphin.
Fixes #6444.
Reported-by: @Utini2000
Suggested-by: @rusty-snake
=> profiles: firefox-common: allow org.freedesktop.portal.Documents

etc/profile-m-z/thunderbird.profile
This fixes access to Thunderbird system policies, which can be set
system-wide via `/etc/thunderbird/policies/policies.json`.
Users can also use this directory to set different default preferences.
Relates to #6400 #6435.
=> profiles: thunderbird: allow /etc/thunderbird

etc/profile-a-l/firefox-esr.profile
This path is apparently used on Debian.
Relates to #5518 #6400 #6435.
Reported-by: @Boruch-Baum
=> profiles: firefox-esr: allow /etc/firefox-esr

README, README.md
Make the introduction friendlier for non-kernel geeks and clarify the
build section.
Relates to #4049.
=> docs: clarify intro and build section in README

etc/profile-a-l/keepassxc.profile
Fixes #3314.
Relates to #6529.
=> keepassxc: allow access to ssh-agent socket

src/firecfg/firecfg.config
There are multiple reports in #6121 that dnsmasq does not work when
called by libvirt:
$ sudo virsh net-start default
error: Failed to start network default
error: internal error: Child process (VIR_BRIDGE_NAME=virbr0 /usr/local/bin/dnsmasq [...]) unexpected exit status 1: Error: PATH environment variable not set
Also, note that this is a server program, so it might be better to
disable it by default anyway.
Reported-by: @marek22k
=> profiles: firecfg.config: disable dnsmasq

etc/profile-a-l/lutris.profile, etc/profile-m-z/steam.profile
While gamepads apparently work fine in the Steam client itself, `nou2f`
appears to make gamepads unresponsive inside certain games while using
"Steam Input" (possibly due to `nou2f` blocking access to `/dev/hidraw*`
devices).
This issue reportedly affects at least the following games on Steam:
"Undertale", "Persona 4 Golden" and "Persona 5 Royal".
Disable nou2f to ensure that gamepads can be used.
Relates to #6523.
Reported-by: @opqriu
=> profiles: game-launchers: disable nou2f

etc/profile-a-l/anki.profile, src/firecfg/firecfg.config
Anki relies on mpv and mplayer for playing audio and video files.
If mpv is present in the system but not allowed in firejail then Anki fails to start because mpv permissions won't allow for execution.
Fixes #6544.
=> profiles: anki: fix opening, allow media & add to firecfg

etc/profile-m-z/wget.profile, etc/profile-m-z/wget2.profile
wget appears to require access to this directory for HSTS & HPKP.
Without access to this directory, I get the following error when running wget:
```sh
Failed to read HSTS data
Failed to read HPKP data
Failed to write HSTS file
```
This fixes it.
=> profiles: wget: allow ~/.local/share/wget

etc/profile-m-z/wget.profile, etc/profile-m-z/wget2.profile
According to @rusty-snake[1]:
> Distributions started to replace wget with wget2 (I.e. `wget` and
> `wget2` are the same binary where one of them is a symlink to the
> other).
So move all custom entries (other than `private-bin`) from wget2.profile
into wget.profile and turn wget2.profile into more of a redirect to
wget.profile.
[1] https://github.com/netblue30/firejail/pull/6542#pullrequestreview-2426287045
=> profiles: wget: unify wget2 into wget profile

etc/profile-m-z/tesseract.profile
As reported by @kmille[1]:
The current `tesseract` profile breaks `ocrmypdf`:
kmille@linbox:scans ocrmypdf C.pdf del.pdf
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
1  Error, could not create hOCR output file: No such file or directory                             tesseract.py:253
1  Error, could not create TXT output file: No such file or directory                              tesseract.py:253
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/1 -:--:--
An exception occurred while executing the pipeline                                                       _common.py:294
Traceback (most recent call last):
File "/usr/lib/python3.12/site-packages/ocrmypdf/_pipelines/_common.py", line 259, in
cli_exception_handler
return fn(options, …
=> profiles: tesseract: disable private-tmp to fix ocrmypdf

etc/profile-a-l/firefox-common-addons.profile, etc/profile-m-z/QMediathekView.profile, etc/profile-m-z/mediathekview.profile, etc/profile-m-z/rtv-addons.profile, etc/profile-m-z/smtube.profile
mpv crashes if luajit is blocked:
$ firejail --quiet --noprofile \
--include=/etc/firejail/disable-interpreters.inc /usr/bin/mpv
/usr/bin/mpv: error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: Permission denied
So make sure that allow-lua.inc is always included when mpv paths (such
as ~/.config/mpv) are allowed.
Environment: luajit 2.1.1727870382-1, mpv 1:0.39.0-3 on Artix Linux.
* db2bdaadd ("add lua support for mpv (#3243)", 2020-02-24) /
PR #3243
* d6a6fb905 ("Allow Lua for mpv in dolphin.profile", 2020-04-18) /
issue #3363
* f3585e539 ("fixes, closes, enhances, improvements, and so on",
2020-11-09) /
issue #3686
* 3ec523f11 ("profiles: anki: allow lua", 2024-11-14) /
PR #6545
=> profiles: ensure allow-lua where mpv is allowed

contrib/sort.py
Print the usage if `-h` is given.
Kind of relates to #6290.
=> build: sort.py: add -h option for help

contrib/sort.py
build: sort.py: strip trailing whitespace in all lines
Currently the output is mangled if the last item on the line contains
trailing whitespace and is moved when sorting.
So remove trailing whitespace in all lines (that is, not just in lines
containing supported commands).
Leave leading whitespace as is for now since it could potentially be
used for indentation.
Before:
$ printf '# hello world  \nprivate-bin a,b  \nprivate-bin b,a  \nprivate-bin  a,b\n' \
>foo.profile
$ ./contrib/sort.py -n foo.profile | tr ' ' .
sort.py:.checking.1.profile(s)...
foo.profile:3:-private-bin.b,a..
foo.profile:3:+private-bin.a..,b
After:
$ printf '# hello world  \nprivate-bin a,b  \nprivate-bin b,a  \n' \
>foo.profile
$ ./contrib/sort.py -n foo.profile | tr ' ' .
sort.py:.checking.1.profile(s)... …
=> build: sort.py: strip whitespace in profiles

etc/profile-a-l/chatterino.profile, etc/profile-m-z/QMediathekView.profile, etc/profile-m-z/smtube.profile, etc/profile-m-z/youtube-viewers-common.profile
Add missing paths for:
* lua (for mpv)
* mplayer
* mpv
* smplayer
* vlc
Apparently mpv plugins may break without the lua path; see commit
ccff014de ("fix Lua in mpv.profile", 2020-07-28) / issue #3554.
Command used to search for relevant profiles:
$ git grep -IE -l '/\.?(s?mplayer|mpv|vlc)' -- etc
This is a follow-up to commit e4ebbfafe ("profiles: ensure allow-lua
where mpv is allowed (#6555)", 2024-11-29).
=> profiles: video-players: add missing /usr/share paths

etc/inc/disable-programs.inc, etc/profile-a-l/clamav.profile, etc/profile-a-l/email-common.profile
See also commit 2453f0ecf ("email-common.profile: allow clamav plugin
for claws-mail", 2023-03-07) / PR #5719.
=> profiles: clamav: add /etc/clamav

etc/inc/disable-programs.inc, etc/profile-a-l/singularity.profile, src/firecfg/firecfg.config
Tested it myself of course. This is a small, python-based game which needs no network access and is generally quite frugal in terms of resources.
I would deem it fine if this is added to firecfg, as there are little to no configurable options and will work out of the box.
=> New profile: singularity (Endgame: Singularity)

etc/profile-m-z/prismlauncher.profile, src/firecfg/firecfg.config
Created a firejail profile for prismlauncher, I've attempted to limit it as much as possible while allowing Minecraft to run.
As for Downloads, PrismLauncher can get files from Downloads, I'm not sure for what so I have set it to read-only.
If anyone has any ideas on improvement let me know.
=> New profile: prismlauncher

etc/profile-m-z/syncthing.profile, src/firecfg/firecfg.config
https://docs.syncthing.net/
tested with v1.28.0
=> New profile: syncthing

src/firejail/main.c
The `arg_debug` flag is set after some functions check for it.
https://github.com/netblue30/firejail/blob/f27775c5a810729b7dc8f144f522c5e79ec4ee55/src/firejail/main.c#L1347
An example of a function in this situation is `check_kernel_procs()`.
https://github.com/netblue30/firejail/blob/f27775c5a810729b7dc8f144f522c5e79ec4ee55/src/firejail/main.c#L1129
https://github.com/netblue30/firejail/blob/f27775c5a810729b7dc8f144f522c5e79ec4ee55/src/firejail/no_sandbox.c#L102
=> bugfix: parse --debug before using it

.github/workflows/check-profiles.yml, contrib/sort.py, etc/profile-a-l/devhelp.profile, etc/profile-a-l/display-im6.q16.profile, etc/profile-a-l/empathy.profile, etc/profile-a-l/gnome-font-viewer.profile, etc/profile-a-l/gnome-recipes.profile, etc/profile-a-l/godot.profile, etc/profile-m-z/quassel.profile, etc/profile-m-z/rtorrent.profile, etc/profile-m-z/silentarmy.profile
Changes:
* Strip whitespace at the beginning
* Strip whitespace at the end
* Ensure exactly one newline at the end
* Strip extraneous newlines
Also, for clarity print the git diff in the sort.py ci job, since the
specific lines changed are not printed by the sort.py script in this
case (as whitespace is fixed in the entire profile at once).
Command used to search and replace:
./contrib/sort.py etc/inc/*.inc etc/profile*/*.profile
This is a follow-up to #6556.
=> build: sort.py: fix whitespace in entire profile

contrib/sort.py
To make it clearer when only whitespace was fixed on a given line.
Before:
$ printf 'private-bin a,b \n' >foo.profile
$ ./contrib/sort.py -n foo.profile
sort.py: checking 1 profile(s)...
foo.profile:1:-private-bin a,b
foo.profile:1:+private-bin a,b
After:
$ printf 'private-bin a,b \n' >foo.profile
$ ./contrib/sort.py -n foo.profile
sort.py: checking 1 profile(s)...
foo.profile:1:-'private-bin a,b '
foo.profile:1:+'private-bin a,b'
See commit 53ff8e0ad ("build: sort.py: strip trailing whitespace in all
lines", 2024-11-26) / PR #6556.
=> build: sort.py: quote diff lines

src/firejail/fs_home.c
The pointer returned by ```asprintf()``` should be passed to free() to release the allocated storage when it is no longer needed.
There was one exit point without previous freeing ```src```.
=> bugfix: fix possible memory leak in fs_home.c

etc/profile-a-l/com.github.johnfactotum.Foliate.profile, etc/profile-a-l/foliate.profile, src/firecfg/firecfg.config
=> profiles: refactor com.github.johnfactotum.Foliate into foliate.profile

etc/profile-m-z/tremc.profile
https://github.com/tremc/tremc
=> New profile: tremc

etc/profile-a-l/aria2p.profile
aria2p is a command-line tool, so these should not be needed (and it's
unclear how/why they would be used by the program).
See also:
https://github.com/netblue30/firejail/pull/6583#discussion_r1912891807
Added on commit c869f11d5 ("New profile: aria2p/aria2rpc", 2024-12-27) /
PR #6583.
Cc: @amano-kenji
=> profiles: aria2p: disable x11 and clipboard managers

etc/profile-a-l/anki.profile
=> profiles: anki: fix dark mode detection & misc changes

.github/workflows/build-extra.yml, .github/workflows/build.yml, .github/workflows/test.yml, .gitlab-ci.yml, Makefile, gcov.sh
To make it consistent with the standard GNU make targets.
From the manual of GNU Make (version 4.4.1-2):
> 'installcheck'
>      Perform installation tests (if any).  The user must build and
>      install the program before running the tests.  You should not
>      assume that '$(bindir)' is in the search path.
Commands used to search and replace:
$ git grep -Ilz print-version |
xargs -0 -I '{}' sh -c "printf '%s\n' \"\$(sed \
's/print-version/installcheck/g' '{}')\" >'{}'"
$ git grep -Ilz 'print version' .github/workflows |
xargs -0 -I '{}' sh -c "printf '%s\n' \"\$(sed \
's/print version/make installcheck/g' '{}')\" >'{}'"
Added on commit c9531d95e ("build: add print-version target and use in
CI", 2024-02-22) / #6230.
=> build: rename print-version target to installcheck

.github/workflows/check-c.yml
This considerably speeds up the execution of the relevant steps, most
noticeably on scan-build:
* scan-build:  121s to 55s (-54.5%)
* cppcheck:     51s to 30s (-41.2%)
* cppcheck-old: 21s to 11s (-47.6%)
Note: The above uses the average time of 3 runs on master (commit
bd946e359 ("Merge pull request #6624 from
powerjungle/chore/update-security-md", 2025-01-21)) [1] [2] [3] and 3
runs on this commit[4] [5] [6].
Note: This considers only the steps themselves, as the total time of
each job varies a lot between runs, mostly due to the apt-get
update/install steps.  For example, the same `apt-get install` command
took 3 seconds on one scan-build job run[7] and 132 seconds on another
scan-build job run[8].
* 500d8f2d6 ("ci: run make in parallel where applicable", 2023-08-14) / …
=> ci: check-c: run all checks in parallel mode

etc/profile-a-l/device-flasher.linux.profile
The CalyxOS CLI device flasher.
=> New profile: device-flasher.linux (CalyxOS)

etc/profile-m-z/tor.profile
Add `memory-deny-write-execute` to tor profile. (Tested by running tor for more than 7 hour with continuous traffic.)
Note: not tested as relay. If it is expected that tor touches on this only as a relay, then it would benefit to await a second opinion.
Update: tor ran (as client) for 7+ hours continuously without issue.
=> profiles: tor: add memory-deny-write-execute

etc/inc/disable-programs.inc, etc/profile-a-l/hledger-ui.profile, etc/profile-a-l/hledger.profile
=> New profile: hledger/hledger-ui

etc/inc/disable-common.inc, etc/inc/disable-programs.inc, etc/profile-m-z/ncmpcpp.profile
https://github.com/ncmpcpp/ncmpcpp
=> New profile: ncmpcpp

etc/inc/disable-programs.inc, etc/profile-m-z/pyradio.profile
https://github.com/coderholic/pyradio
=> New profile: pyradio

etc/inc/disable-common.inc, etc/inc/disable-programs.inc
Added the path to tor-browser as used by torbrowser-launcher: `~/.local/share/torbrowser`.
Actualy, this original entry for `${HOME}/opt/torbrowser` seems to be oddly placed. There is an occurrence in `disable-programs.profile` for `${HOME}/.local/share/torbrowser` already. Should the old entry be removed (or moved) instead? Did you guys start using `disable-programs.profile` at a later time?
=> profiles: torbrowser-launcher: move path from dc to dp

etc/inc/disable-common.inc, etc/inc/disable-programs.inc, etc/profile-m-z/nsxiv.profile, src/firecfg/firecfg.config
=> New profile: nsxiv

etc/profile-m-z/youtube-music-desktop-app.profile, etc/profile-m-z/ytmdesktop.profile, src/firecfg/firecfg.config
Apparently the main binary has been renamed from `ytmdesktop` to
`youtube-music-desktop-app`[1]:
$ pacman -Qlq ytmdesktop
[...]
/opt/ytmdesktop/youtube-music-desktop-app
/usr/bin/youtube-music-desktop-app
/usr/share/applications/ytmdesktop.desktop
So add a redirect for it.
Fixes #6662.
[1] https://github.com/netblue30/firejail/issues/6662#issuecomment-2681532969
Reported-by: @Dieterbe
---
ytmdesktop: whitelist /opt/ytmdesktop
See also commit 175905530 ("profiles: exchange private-opt with a
whitelist (#6021)", 2023-10-18).
=> profiles: ytmdesktop: add redirect & whitelist /opt/ytmdesktop 

etc/profile-m-z/remmina-file-wrapper.profile, src/firecfg/firecfg.config
Remmina may install this wrapper binary on some distributions.
On Void Linux, this is the default binary launched via application
launchers (e.g. rofi):
$ grep "Exec" /usr/share/applications/org.remmina.Remmina.desktop
TryExec=remmina-file-wrapper
Exec=remmina-file-wrapper %U
[...]
=> New profile: remmina-file-wrapper

src/firecfg/desktop_files.c
Currently, firecfg only checks the last word in .desktop files when
trying to match them to an existing profile.  For example:
* `org.gnome.gedit.desktop` -> `gedit.desktop`
* `org.gnome.seahorse.Application.desktop` -> `Application.desktop`
This works in the former case where there is an exact match of the last
word on each side (`gedit.desktop` and `gedit.profile`), but not in the
latter case (`Application.desktop` and `seahorse.profile`).
So make firecfg also check the full filename of the .desktop file, to
make it easier to create redirect profiles that match the full name of
the .desktop files.  For example:
* `org.gnome.seahorse.Application.desktop` ->
`org.gnome.seahorse.Application.profile` (which itself then redirects
to `seahorse.profile`)
* a6341b904 ("disable …
=> bugfix: firecfg: check full filename in check_profile()

etc/profile-m-z/org.gnome.seahorse.Application.profile, src/firecfg/firecfg.config
Apparently the .desktop file for `seahorse` is located in the following
path:
* `/usr/share/applications/org.gnome.seahorse.Application.desktop`
Which ends in `Application.desktop` instead of `seahorse.desktop`,
leading to it not being automatically detected by firecfg.
So add a redirect profile and an entry in firecfg.config.
See also commit 8f69e9841 ("bugfix: firecfg: check full filename in
check_profile() (#6674)", 2025-03-04).
Fixes #6658.
Reported-by: @ginto37
Reported-by: @rusty-snake
=> profiles: seahorse: add redirect org.gnome.seahorse.Application

contrib/syntax/lists/profile_commands_arg0.list, etc/profile-a-l/lutris.profile, etc/profile-m-z/noprofile.profile, etc/profile-m-z/steam.profile, etc/profile-m-z/wine.profile, etc/templates/profile.template, src/firejail/firejail.h, src/firejail/fs_dev.c, src/firejail/main.c, src/firejail/profile.c, src/firejail/sandbox.c, src/firejail/usage.c, src/man/firejail-profile.5.in, src/man/firejail.1.in, src/zsh_completion/_firejail.in
Changes:
* Block access to /dev/ntsync by default
* Add the `keep-dev-ntsync` command to allow access to /dev/ntsync (even
if `private-dev` is used)
* Add `keep-dev-ntsync` to wine.profile and similar profiles
Closes #6655.
=> feature: block /dev/ntsync & add keep-dev-ntsync command

.github/workflows/check-c.yml, Makefile
To avoid CI failures.
From the first run of `cppcheck_old` on commit 8f69e9841 ("bugfix:
firecfg: check full filename in check_profile() (#6674)", 2025-03-04)
[1]:
> This is a scheduled Ubuntu 20.04 brownout. Ubuntu 20.04 LTS runner
> will be removed on 2025-04-01. For more details, see
> https://github.com/actions/runner-images/issues/11101
The target depends on the cppcheck version from Ubuntu 20.04 in order to
work properly and this distribution will become EOL next month (April
2025), so just remove the target.
Added on commit 53f0b3950 ("CI: keep old cppcheck job and ignore two
files in new job that take too long to check", 2022-07-26).
[1] https://github.com/netblue30/firejail/actions/runs/13658953453/job/38185280665
=> build: remove cppcheck-old target/job

RELNOTES, src/firejail/main.c, src/firejail/util.c, test/seccomp-extra/noroot.exp
To make hardware tokens available for ordinary users, some distributions include a udev rule to make the corresponding entry in /dev/... available for users belonging to a specific group.
The options `noroot` and `nogroups` currently break this behavior.
This PR implements a fix that checks whether `browser-disable-u2f` is set to `no`  in order to disable these two options.
=> modif: keep plugdev group unless nou2f is used

etc/profile-a-l/godot.profile
I had weird errors when working on a godot project:
addons/godot-sqlite/bin/libgdsqlite.linux.template_debug.x86_64.so: failed to map segment from shared object.
ERROR: Can't open GDExtension dynamic library: 'res://addons/godot-sqlite/gdsqlite.gdextension'.
These addons are executable files. Addons like these are common enough
and `noexec` breaks them. I confirmed that the change fixes this error
and allows loading addons.
=> profiles: godot: ignore noexec in home to fix addons

etc/inc/disable-programs.inc, etc/profile-a-l/floorp.profile
Fix typo.
Denying read-write access to ${HOME}/.local/share/applications prevents Floorp from creating shortcuts to the application launcher, which breaks the (experimental) PWA feature on Linux.
Additionally i whitelisted the directories `${RUNUSER}/*floorp* `and
whitelist `${RUNUSER}/psd/*floorp* `to enable profile-sync-daemon support.
Since this is my first time doing a PR, I may have missed something, feel free to edit if needed.
=> profiles: floorp: add profile sync daemon paths

etc/profile-a-l/firefox-common-addons.profile
This is used by at least floorp and FirefoxPWA.
This is a follow-up to #6683.
=> profiles: firefox: add comment about creating PWA shortcuts

src/firejail/fs_dev.c
Certain devices appear in numbered paths in /dev (such as `/dev/hidraw0`
or `/dev/hidraw1`) when they are plugged in.  When private-dev is used,
it attempts to include a hardcoded list of /dev paths in the sandbox.
Since the hardcoded paths only go up to a specific number (mostly from 0
to 9), devices that appear at higher numbered paths (such as
`/dev/hidraw10` or `/dev/hidraw20`) do not show up in /dev when
private-dev is enabled.
This issue also affects options that attempt to disable numbered paths
(such as --no3d and --nou2f), independently of whether private-dev is
used.
Fix this by using glob patterns (such as `/dev/hidraw[0-9]*`) to ensure
that all relevant numbered paths are matched regardless of number.
The globbing is similar to the one from commit 2993298aa ("firecfg:
parse …
=> feature: use globbing in hardcoded numbered /dev paths

src/man/firecfg.1.in, src/man/firejail-login.5.in, src/man/firejail-profile.5.in, src/man/firejail-users.5.in, src/man/firejail.1.in, src/man/firemon.1.in, src/man/jailcheck.1.in
Changes:
* Add missing punctuation after URLs
* Wrap more URLs with .UR/.UE macros
* Format surrounding text in some cases
Kind of relates to commit 03550e94c ("Man pages: were missing info about
.profile .local resolution (#3440)", 2020-06-04).
=> docs: improve URL formatting in man pages

etc/inc/disable-common.inc, etc/inc/disable-x11.inc, etc/inc/whitelist-common.inc
Add the following files, which may be used to configure X clients:
* `~/.Xdefaults`
* `~/.Xdefaults-*` (`~/.Xdefaults-$(hostname)`)
* `~/.Xresources`
And block the following paths, which are intended for the X server:
* `~/.local/share/xorg` (rootless Xorg log directory)
* `/etc/X11/xinit`
* `/etc/X11/xorg.conf.d`
* `/var/log/Xorg.*` (default Xorg log path)
Note: ~/.Xdefaults is read directly by each application when it starts,
while ~/.Xresources is loaded once into the X root window with xrdb(1)
when starting the session, such as by a DE or directly in ~/.xinitrc.
Both use the same format and it appears that users are encouraged to use
~/.Xresources instead of ~/.Xdefaults but applications still try to read
~/.Xdefaults if it exists.
From xrdb(1):
> FILES
>        Xrdb does not load any …
=> profiles: add more xorg paths

src/firejail/preproc.c
Print them to stdout, for consistency with the rest of the debug
messages.
This amends commit 53bc65897 ("modif: improve flock handling",
2024-04-17) / #6307.
=> bugfix: fix flock debug messages going to stderr

src/firejail/mountinfo.c
Currently when a line from /proc/self/mountinfo is too long, firejail
exits with an unclear error message:
Error: cannot read /proc/self/mountinfo
So reword it and include the maximum line length and the offending line:
Error: /proc/self/mountinfo line is too long and may be truncated (4095 >= 4095): [...]
Improve other error messages in mountinfo.c as well.
Relates to #6450.
=> modif: improve error messages in mountinfo.c

config.mk.in
=> build: use TARNAME in SYSCONFDIR/VARDIR

config.mk.in
By default autoconf expands `@localstatedir@` to `/var`.
`VARDIR` was first added on commit a627071b3 ("intrusion detection
system", 2021-07-28) and is only used in src/firejail/ids.c.
This is a follow-up to commit 5b4524a74 ("build: use TARNAME in
SYSCONFDIR/VARDIR (#6713)", 2025-04-19).
=> build: add localstatedir and use in VARDIR

etc/profile-a-l/godot.profile
As you might know, Godot is a game engine. For this reason, they support the very commonly used gamepads and other potentially exotic input devices. `noinput` is incompatible with that and interferes with normal operation.
=> profiles: godot: remove noinput so gamepads work

src/firejail/main.c, src/firejail/util.c
This group is apparently used by tpm2-tss for accessing TPM devices.
udev rules from tpm2-tss 4.1.3[1]:
KERNEL=="tpm[0-9]*", TAG+="systemd", MODE="0660", OWNER="tss"
KERNEL=="tpmrm[0-9]*", TAG+="systemd", MODE="0660", GROUP="tss"
Misc: This was noticed on #6700.
Relates to #6390.
[1] https://github.com/tpm2-software/tpm2-tss/blob/4.1.3/dist/tpm-udev.rules
=> modif: keep tss group if keep-dev-tpm is used

src/firejail/fs_dev.c, src/man/firejail-profile.5.in, src/man/firejail.1.in
Treat them like `/dev/tpm[0-9]*` devices.
It seems that `/dev/tpm[0-9]*` allows direct access to the TPM device
while `/dev/tpmrm[0-9]*` mediates access through a "resource manager"
inside of the kernel (for example, to facilitate concurrent access).
Alternatively, it looks like the resource management can be done in
userspace through tpm2-abrmd, the "TPM2 Access Broker & Resource
Management Daemon", which also supports older kernels (Linux 3.x vs
4.12) [1] [2] [3].
udev rules from tpm2-tss 4.1.3[4]:
KERNEL=="tpm[0-9]*", TAG+="systemd", MODE="0660", OWNER="tss"
KERNEL=="tpmrm[0-9]*", TAG+="systemd", MODE="0660", GROUP="tss"
This is a follow-up to #6718.
Misc: This was noticed on #6700.
Relates to #6390.
[1] https://github.com/tpm2-software/tpm2-abrmd
[2] …
=> modif: keep /dev/tpmrm devices if keep-dev-tpm is used

src/firejail/fs_dev.c, src/man/firejail-profile.5.in, src/man/firejail.1.in
Paths:
* `/dev/tcm[0-9]*`
* `/dev/tcmrm[0-9]*`
Apparently Trusted Cryptography Module (TCM) is a standard from China
that is an alternative to the TCG Trusted Compute Module (TPM)
standard[1].
udev rules from tpm2-tss master[2]:
KERNEL=="tpm[0-9]*", TAG+="systemd", MODE="0660", OWNER="tss"
KERNEL=="tpmrm[0-9]*", TAG+="systemd", MODE="0660", GROUP="tss"
KERNEL=="tcm[0-9]*", TAG+="systemd", MODE="0660", OWNER="tss"
KERNEL=="tcmrm[0-9]*", TAG+="systemd", MODE="0660", GROUP="tss"
This is a follow-up to #6719.
Relates to #6390.
Misc: This was noticed on #6700.
=> modif: keep tcm/tcmrm devices if keep-dev-tpm is used

etc/profile-a-l/chromium-common.profile, etc/profile-a-l/ephemeral.profile, etc/profile-a-l/ferdi.profile, etc/profile-a-l/firefox-common.profile, etc/profile-a-l/franz.profile, etc/profile-m-z/midori.profile, etc/profile-m-z/otter-browser.profile, etc/profile-m-z/rambox.profile, etc/profile-m-z/seamonkey.profile
To reduce clutter in the user home.
This appears to be a legacy path and the relevant profiles already
create an XDG path as well:
mkdir ${HOME}/.local/share/pki
From nss 3.111[1]:
/**
* Return the path to user's NSS database.
* We search in the following dirs in order:
* (1) $HOME/.pki/nssdb;
* (2) $XDG_DATA_HOME/pki/nssdb if XDG_DATA_HOME is set;
* (3) $HOME/.local/share/pki/nssdb (default XDG_DATA_HOME value).
* If (1) does not exist, then the returned dir will be set to either
* (2) or (3), depending if XDG_DATA_HOME is set.
*/
The XDG path has apparently been supported since nss 3.42, which was
released on 2019-01-25[2] [3] [4].
Misc: The original path was first added on commit 3a71eb2af ("added
mkdir in all whitelisted profiles", 2016-02-18) and the XDG path was
first added on …
=> profiles: remove mkdir ~/.pki

etc/profile-m-z/mpv.profile
To reduce clutter in the user home.
This file is apparently intended to specify login information for remote
systems, such as username and password for ftp/http connections
(similarly to using ~/.ssh/config for ssh connections).
From inetutils.info of GNU inetutils 2.6, which provides ftp and telnet
binaries (among others):
> 11.7 The ‘.netrc’ file
> The ‘.netrc’ file contains login and initialization information used
> by the auto-login process.  It generally resides in the user's home
> directory, but a location outside of the home directory can be set
> using the environment variable ‘NETRC’.  Both locations are overridden
> by the command line option ‘-N’.  The selected file must be a regular
> file, or access will be denied.
It seems that the file is intended to be created manually …
=> profiles: mpv: remove mkfile ~/.netrc

etc/profile-a-l/curl.profile
From curl(1):
> -n, --netrc
>        Make curl scan the .netrc file in the user's home directory for
>        login name and password. This is typically used for FTP on
>        Unix.  If used with HTTP, curl enables user authentication. See
>        netrc(5) and ftp(1) for details on the file format. curl does
>        not complain if that file does not have the right permissions
>        (it should be neither world- nor group-readable). The
>        environment variable "HOME" is used to find the home directory.
Environment: curl 8.13.0-2 on Artix Linux.
This is a follow-up to #6735.
=> profiles: curl: allow ~/.netrc

etc/profile-a-l/discord-common.profile
The discord wrapper script in gentoo runs `#!/usr/bin/env bash`.
See https://github.com/gentoo/gentoo/blob/master/net-im/discord/files/launcher.sh
=> profiles: discord-common: add env to private-bin

src/firejail/fs_dev.c
Some objects are created in fs_dev but not labeled.  This patch ensures that those objects are properly labeled.
As an aside: I am locally running a fully confined SELinux setup using firejail (this is in fact posted from a fully SELinux contained Firefox instance running within a firejail).  This involves a custom SELinux module for firejail (and other programs).  So, this patch isn't "abstract" in any way---it's actually essential for me.
=> bugfix: add missing selinux relabeling for /dev paths

src/firecfg/firecfg.config
As reported by @hlein[1]:
> A number of packages can't compile on Gentoo when various `*sum` tools
> are firejailed; they'll die like:
>
>     ...
>     -- Installing: /var/tmp/portage/dev-libs/protobuf-30.2/image/usr/lib64/cmake/protobuf/protobuf-options.cmake
>     Error: too many arguments: argc (166) >= MAX_ARGS (128)
>      * ERROR: dev-libs/protobuf-30.2::gentoo failed (install phase):
>     ...
>      * The specific snippet of code:
>      *       cksum=$(_multilib_header_cksum) || die;
>
> Same for various others.
>
> `_multilib_header_cksum` is defined in `eclass/multilib-build.eclass`
> and it does a `find ... -exec chksum {} +` - behaves similar to `xargs`.
> `chksum` is wrapped by `firecfg` by default.
>
> So this points out anything that uses `find ... -exec ... {} +` or
> …
=> profiles: firecfg: disable checksum programs

etc/profile-m-z/rssguard.profile
Error log[1]:
$ firejail rssguard
Reading profile /etc/firejail/rssguard.profile
[...]
rssguard: error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: Permission denied
Fixes #6758.
[1] https://github.com/netblue30/firejail/issues/6758#issue-3088510624
Reported-by: @1eof
=> profiles: rssguard: allow lua

etc/profile-m-z/wine.profile
As reported by @kolAflash[1]:
> ### Description
>
> If `~/.cache/gstreamer-1.0/` is empty, `/usr/lib/python3*` is needed
> to initialize it.
>
> Wine needs gstreamer for example in the case of
> EpicGamesLauncherInstaller.msi[2] (2025-05-29).
>
> ### Steps to Reproduce
>
> 1. Copy `EpicInstaller-18.5.0.msi` to `~/.wine/drive_c/`.
> 2. Run:
>
>     firejail --profile=wine --whitelist="${HOME}"/.wine \
>       wine msiexec /i 'C:\\EpicInstaller-18.5.0.msi' /q
>
>     firejail --profile=wine --whitelist="${HOME}"/.wine \
>       wine 'C:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win32\\EpicGamesLauncher.exe'
>
> ### Expected behavior
>
> Epic Games Launcher login screen should show up.
>
> ### Actual behavior
>
> Epic Games Launcher is stuck loading the login screen.
>
> …
=> profiles: wine: allow python to fix Epic Games Launcher

etc/inc/whitelist-usr-share-common.inc
With xkeyboard-config 2.45, many programs fail to start, such as:
Firefox, Thunderbird, Gajim, KeepassXC, GoldenDict, and Zathura.
Example[1]:
Reading profile /etc/firejail/zathura.profile
[...]
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
firejail version 0.9.75
[...]
Child process initialized in 197.83 ms
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
Parent is shutting down, bye...
It seems that in xkeyboard-config 2.45 the path was changed from:
* /usr/share/X11/xkb
To:
* /usr/share/xkeyboard-config-2
With the former now being a symlink to the latter and with the goal of
using a versioning scheme for the directories, in …
=> profiles: wusc: add /usr/share/xkeyboard-config-2

etc/profile-a-l/chafa.profile
When using chafa as an image viewer for other apps, it litters the
output with firejail (debug/output) messages.
Use `quiet` so that the image is displayed cleanly.
=> profiles: chafa: quiet output

etc/profile-m-z/ripperx.profile, etc/profile-m-z/sound-juicer.profile
They are currently named as "mpv".
This amends commit 5dbdf657b ("new profiles: ripperx, sound-juicer",
2020-03-19).
Misc: This was noticed on #6779.
=> profiles: ripperx/sound-juicer: fix profile name typos

etc/profile-a-l/basilisk.profile, etc/profile-a-l/enpass.profile, etc/profile-m-z/mate-dictionary.profile, etc/profile-m-z/microsoft-edge-dev.profile, etc/profile-m-z/microsoft-edge.profile, etc/profile-m-z/minecraft-launcher.profile, etc/profile-m-z/postman.profile, etc/profile-m-z/ppsspp.profile, etc/profile-m-z/tidal-hifi.profile, etc/templates/profile.template
Changes:
* Convert all private-opt entries (other than `private-opt none`) to
whitelist entries
* Remove remaining commented private-opt entries and related comments
(for profiles that also have a corresponding whitelist entry)
* Enable `whitelist /opt/basilisk` in basilisk.profile (similarly to
mullvad-browser.profile and palemoon.profile)
* Update private-opt comment in etc/templates/profile.template
Most private-opt entries were converted into whitelist entries on commit
175905530 ("profiles: exchange private-opt with a whitelist (#6021)",
2023-10-18), while some of them were left alone due to the program size
being deemed small enough as not to break file-copy-limit in
firejail.config.
For the sake of simplicity and clarity (and to avoid potential issues
with program install sizes …
=> profiles: finish converting private-opt to whitelist

src/fcopy/main.c
Apparently /etc/resolv.conf may be a regular file (instead of a symlink
to /run/systemd/resolve/resolv.conf) and owned by the "systemd-resolve"
user at the same time.
This is a follow-up to #6804.
Fixes #4545.
Relates to #1531.
=> bugfix: fcopy: allow /etc/resolv.conf owned by systemd-resolve

src/firejail/sandbox.c
Even when Landlock is in fact being enforced.
Also, mention the `landlock.enforce` command in the message.
This amends commit 760f50f78 ("landlock: move commands into profile and
add landlock.enforce", 2023-11-17) / PR #6125.
Relates to #6078 #6796.
Reported-by: @osevan
=> bugfix: fix "Not enforcing Landlock" message always being printed

src/firejail/util.c
Clarify that `--net` should be used to create a new network namespace
before using a firejail command that needs to be executed inside a
(firejail) network namespace.
Example:
$ firejail --netfilter.print=10000
Switching to pid 10001, the first child process inside the sandbox
Error: the sandbox doesn't use a new network namespace (see --net)
Reported-by: @osevan
Relates to #6820.
=> modif: improve new network namespace error message

etc/profile-a-l/keepassxc.profile
It is a GUI program and without it the program does not start due to a
dbus error[1]:
$ firejail keepassxc
Reading profile /etc/firejail/keepassxc.profile
[...]
firejail version 0.9.74
[...]
Child process initialized in 698.63 ms
dbus[23]: D-Bus library appears to be incorrectly set up: see the manual page for dbus-uuidgen to correct this issue. (Failed to open "/var/lib/dbus/machine-id": No such file or directory; Failed to open "/etc/machine-id": No such file or directory)
D-Bus not built with -rdynamic so unable to print a backtrace
Parent is shutting down, bye...
This issue is also mentioned in src/include/etc_groups.h:
// @x11
static char *etc_group_x11[] = {
// [...]
"machine-id", // QT dbus lib is crashing without it!
// [...]
NULL
};
This amends commit 5d0822c52 ("private-etc: big …
=> profiles: keepassxc: add x11 group to private-etc

.gitlab-ci.yml
Instead of Debian 10, use Debian 11 in `build_debian_package`.
It currently fails to update the package index[1]:
Executing "step_script" stage of the job script 00:01
Using effective pull policy of [always] for container debian:buster
Using docker image sha256:69530eaa9e7e18d0aad40c38b75a22b40c6ebdc374c059bd5f2eb07042caa50a for debian:buster with digest debian@sha256:58ce6f1271ae1c8a2006ff7d3e54e9874d839f573d8009c20154ad0f2fb0a225 ...
$ apt-get update -qy
Ign:1 http://deb.debian.org/debian buster InRelease
Ign:2 http://deb.debian.org/debian-security buster/updates InRelease
Ign:3 http://deb.debian.org/debian buster-updates InRelease
Err:4 http://deb.debian.org/debian buster Release
404  Not Found [IP: 151.101.2.132 80]
Err:5 http://deb.debian.org/debian-security buster/updates Release …
=> ci: upgrade debian:buster to debian:bullseye

.github/workflows/check-c.yml, .github/workflows/check-python.yml
The `codeql-cpp` CI job for #6844 is failing[1]:
##[group]Setup CodeQL tools
[...]
Did not find CodeQL tools version 2.22.2 in the toolcache.
Using CodeQL CLI version 2.22.2 sourced from https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.22.2/codeql-bundle-linux64.tar.zst .
Downloading CodeQL tools from https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.22.2/codeql-bundle-linux64.tar.zst . This may take a while.
Streaming the extraction of the CodeQL bundle.
node:events:502
throw er; // Unhandled 'error' event
^
Error: connect ECONNREFUSED 54.185.253.63:443
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
[...]
errno: -111,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '54.185.253.63',
port: 443
}
Node.js v20.19.3
Post …
=> ci: allow new github domain for codeql download

src/man/firejail.1.in
Changes:
* Use `strace --trace=%file` instead of `| grep open`, so that more
path-related syscalls are traced (rather than just `open*`)
* Always use `strace -f` to ensure that child processes are also traced
* Add an example using firejail + strace for `--private-etc`
* Improve formatting/grammar
* Add references between commands related to strace
Added on commit 9774ab8a3 ("private-etc rework: new man page",
2023-01-25) / issue #6400.
Misc: This was noticed on #6843.
=> docs: man: improve strace usage and add refs

src/firemon/procevent.c
All other debug messages in procevent.c use the `%s: %d, ` format.
Note that by default this line is not actually compiled (unless
`DEBUG_PRCTL` is defined).
Added on commit d72a43af0 ("firemon fixes", 2016-02-29).
Kind of relates to #6792.
=> bugfix: firemon: fix inconsistent debug message format

src/firejail/checkcfg.c
It looks like it could happen if a line in /etc/firejail/firejail.config
starts with `netfilter-default ` and there is a space or tab right after
that.
$ pacman -Q gcc14 glibc
gcc14 14.3.1+r25+g42e99e057bd7-1
glibc 2.42+r3+gbc13db739377-1
$ ./configure --enable-analyzer CC=gcc-14 >/dev/null &&
make clean >/dev/null && make >/dev/null
[...]
../../src/firejail/checkcfg.c: In function ‘checkcfg’:
../../src/firejail/checkcfg.c:137:40: warning: infinite loop [CWE-835] [-Wanalyzer-infinite-loop]
137 |                                 while (*fname == ' ' || *fname == '\t')
|                                        ^~~~~~
‘checkcfg’: events 1-5
|
|  137 |                                 while (*fname == ' ' || *fname == '\t')
|      | …
=> bugfix: fix potential infinite loop in checkcfg (-fanalyzer)

.github/workflows/check-c.yml
For consistency and simplicity, name the `apt-get install` step just
"install dependencies" in all jobs.
Affected jobs:
* check-c.yml: scan-build
* check-c.yml: cppcheck
* 94e2ce275 ("Create build.yml (#3651)", 2020-10-01)
* 0fa11826b ("build: test build with apparmor and selinux in CI",
2020-10-01)
=> ci: standardize "apt-get install" step name

.github/workflows/codespell.yml
Relevant software changes:
* codespell 2.1.0 -> 2.2.6
See also [1] and [2].
[1] https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
[2] https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
=> ci: codespell: upgrade ubuntu-22.04 to ubuntu-24.04

src/firemon/procevent.c
Simplify the deallocation of `cmd` to make it easier to understand,
which looks like it would fix a potential memory leak of `cmd`:
if (!cmd) {
cmd = pid_proc_cmdline(pid); // alloc
}
if (add_new) {
// ...                       // no dealloc
}
else if (proc_ev->what == PROC_EVENT_EXIT && pids[pid].level == 1) {
// ...                       // no dealloc
}
else {
// ...
else {
sprintf(lineptr, " %s\n", cmd);
if (cmd != pids[pid].option.event.cmd) {
free(cmd);           // dealloc
}
}
// ...
}
This is a follow-up to commit 5ec00f70c ("fix: avoid cmd double-free in
procevent_monitor", 2025-07-31) / PR #6846.
Relates to #6792.
=> bugfix: firemon: fix potential memory leak in procevent_monitor

etc/profile-a-l/ephemeral.profile, etc/profile-a-l/falkon.profile, etc/profile-a-l/firefox-common.profile, etc/profile-a-l/geary.profile, etc/profile-m-z/Viber.profile, etc/profile-m-z/mutt.profile, etc/profile-m-z/neomutt.profile, etc/profile-m-z/otter-browser.profile, etc/profile-m-z/seamonkey.profile, etc/profile-m-z/w3m.profile
Allow `~/.mailcap` for the profiles that have `mailcap` in `private-etc`
and vice-versa.
Fixes #6883.
Reported-by: @vinc17fr
Suggested-by: @vinc17fr
=> profiles: add missing mailcap entries

src/firejail/main.c, src/firejail/profile.c, src/firejail/util.c, src/man/firejail.1.in, test/environment/rlimit-bad-profile.exp, test/environment/rlimit-bad.exp
The proper suffixes (KiB, MiB and GiB) are uppercase.
This is a follow-up to #6890.
Relates to #4315.
=> modif: rlimit: use uppercase suffixes in the code/docs

src/firejail/main.c, src/firejail/profile.c, src/firejail/util.c, test/environment/rlimit-bad-profile.exp, test/environment/rlimit-bad.exp
Changes:
* Remove unrelated `strerror` output from some error messages
* Remove periods from some error messages
* Ensure that the invalid value is in the error message
* Ensure that the full command name is in the error message (instead of
just `rlimit` in some cases)
* Standardize output
* tests: Expect the full command name (and argument in some cases)
Examples:
Before:
$ firejail --quiet --noprofile --rlimit-cpu=-1 /bin/true
Error: invalid rlimit -1
$ firejail --quiet --noprofile --rlimit-nproc=-1 /bin/true
Error: invalid rlimit -1
$ firejail --quiet --noprofile --rlimit-as=-1 /bin/true
Error: invalid rlimit-as. Only use positive numbers and K, M or G suffix.: No such file or directory
After:
$ firejail --quiet --noprofile --rlimit-cpu=-1 /bin/true
Error: invalid rlimit-cpu: -1
$ …
=> modif: rlimit: improve error messages

etc/inc/whitelist-usr-share-common.inc
This directory is part of the gtk4 package (version 1:4.20.1-1) on Artix
Linux.
Add it just in case, as wusc already contains the same analogous paths
for gtk2 and gtk3.
This is a follow-up to #6907.
=> profiles: wusc: add /usr/share/gtk-4.0
